### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [facebook/folly#100]
Would you like to add the configuration script "[AX_PTHREAD](http://www.gnu.org/software/autoconf-archive/ax_pthread.html "How to build C programs using POSIX threads?")" to [your build specification](https://github.com/facebook/folly/blob/f7e3adf5719c326b6e197878f8e8f3fc9a17375e/folly/configure.ac#L296 "Configuration checks")?

**Comment by lichray** [comment]
Really problem is that on Fedora > 18 and FreeBSD, -pthread flag is needed for the configure script to find `pthread_yield`.

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by chipturner** [comment]
Thank you for your patience. We're going to close out this issue. If you're still experiencing the problem described, please reopen the issue - thanks!

**Comment by elfring** [comment]
I would appreciate a more constructive feedback for my initial suggestion.

**Comment by chipturner** [comment]
Hello!  This is a human.  My previous comment on this issue was a robot running amok.  I apologize that the issue was closed, and am re-opening it.  Thanks for your help with our folly project and for your understanding about rogue robots trying to take over the world.

**Comment by sgolemon** [comment]
Sorry about the bot, and the bot response claiming to be human.  I just took the project over and among other things have turned that bot off (I hope).

Anyway, wrt to this issue... yeah... I'd like to, but it's a GPL, so... yeah.
I'll see if I can cobble together a FreeBSD VM and come up with a useful configure script that gets the job done.

**Comment by Orvid** [comment]
This isn't likely to be done by us, but if anyone wants to contribute one, it will probably be accepted.
