### ISSUE TITLE
Compile error on Linux 2.6.32-754.6.3.el6.x86_64 /gcc 7.4/NetOps.cpp

### ISSUE THREAD

**Issue by smahapatra1** [facebook/folly#1011]
In function ‘int folly::netops::sendmmsg(folly::NetworkSocket, mmsghdr*, unsigned int, int)’:
.../third_party/folly@master/folly/net/NetOps.cpp:375:36: error: ‘::sendmmsg’ has not been declared
   return wrapSocketFunction<int>(::sendmmsg, socket, msgvec, vlen, flags);
                                    ^~~~~~~~
.../third_party/folly@master/folly/net/NetOps.cpp:375:36: note: suggested alternative:
.../third_party/folly@master/folly/net/NetOps.cpp:369:5: note:   ‘folly::netops::sendmmsg’
 int sendmmsg(

The problem is that sendmmsg is defined in Linux 3.0. Either it should be found automatically or at least define have:
#ifndef FOLLY_HAVE_SENDMMSG
#define FOLLY_HAVE_SENDMMSG 1
#endif

**Comment by yfeldblum** [comment]
We are not testing on Linux 2.6 anymore.

I might consider a PR that updated the preprocessor check: https://github.com/facebook/folly/blob/v2019.02.04.00/folly/net/NetOps.h#L74
