### ISSUE TITLE
folly link error to build surround360_render

### ISSUE THREAD

**Issue by bluelikemilk** [facebook/folly#1015]
Hi,

I have already fixed the problem on folly && double-conversion #263
But then I got another error **undefined reference to `cplus_demangle_v3_callback'**
I have rebuilt folly several times but nothing changes. Is there any way to fix this problem?

[ 45%] Linking CXX executable bin/TestVignettingCalibration
//usr/local/lib/libfolly.a(Demangle.cpp.o): In function `folly::detail::cplus_demangle_v3_callback_wrapper(char const*, void (*)(char const*, unsigned long, void*), void*)': /home/chufan/folly/folly/detail/Demangle.cpp:38: undefined reference to `cplus_demangle_v3_callback'
collect2: error: ld returned 1 exit status
CMakeFiles/TestVignettingCalibration.dir/build.make:133: recipe for target 'bin/TestVignettingCalibration' failed
make[2]: *** [bin/TestVignettingCalibration] Error 1
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/TestVignettingCalibration.dir/all' failed
make[1]: *** [CMakeFiles/TestVignettingCalibration.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Thanks for your help!

**Comment by yfeldblum** [comment]
Is libiberty being linked in?

**Comment by bluelikemilk** [comment]
> Is libiberty being linked in?

I have installed libiberty-dev package and do I need to do anything else to link libiberty? I am new to Linux and thank you very much for your help!

**Comment by bluelikemilk** [comment]
> > Is libiberty being linked in?
> 
> I have installed libiberty-dev package and do I need to do anything else to link libiberty? I am new to Linux and thank you very much for your help!

I tried to recompile folly and got a new error:

undefined reference to `folly::f14::detail::F14LinkCheck<(folly::f14::detail::F14IntrinsicsMode)2>::check()'

**Comment by yfeldblum** [comment]
The F14 question is in #1027.
