### ISSUE TITLE
Baton try_wait_for issue

### ISSUE THREAD

**Issue by kreuzerkrieg** [facebook/folly#1052]
Folly v2019.01.28.00, but I see the same code in the master
I'm running the following code
```
TEST(Baton, RepititiveWait)
{
	folly::fibers::Baton baton;
	thread t([&baton]() {
		this_thread::sleep_for(100ms);
		baton.post();
	});
	baton.try_wait_for(20ms);
	this_thread::sleep_for(50ms);
	//t.join();
	baton.wait();
	t.join();
}
```
The second `wait` fails with 

> Other thread is already waiting on this baton

. Of course there is no other thread waiting on `Baton`. Apparently, the state of `Baton` after `try_wait_for` is `THREAD_WAITING`, which, to me, looks wrong, it is more likely have to be `TIMEOUT`. But the way it is written in `Baton::timedWaitThread` `TIMEOUT` is not acceptable state when `Baton` enters the function. So I guess, it is by design. But why? Why it is not allowed to `wait` or `wait_for` again on `Baton` that expired once?

**Comment by yfeldblum** [comment]
As documented, `Baton` allows a single wait attempt. If this does not work for you, then `Baton` may not be the primitive that you are looking for.
