### ISSUE TITLE
Failing to Compile on FreeBSD

### ISSUE THREAD

**Issue by chaitanyav** [facebook/folly#106]
I get this error, any ideas on how to resolve this on BSD 

    --- IPAddressV4.lo ---
    In file included from IPAddressV4.cpp:17:
    In file included from ./../folly/IPAddressV4.h:26:
    /../folly/detail/IPAddress.h:282:70: error: no member named 's6_addr16' in 'in6_addr'
     const uint16_t* bytes = reinterpret_cast<const uint16_t*>(&in6Addr.s6_addr16);
                                                             ~~~~~~~ ^

**Comment by lichray** [comment]
Suggest the following fix:

``` diff
diff --git a/folly/detail/IPAddress.h b/folly/detail/IPAddress.h
index f255229..f6db412 100644
--- a/folly/detail/IPAddress.h
+++ b/folly/detail/IPAddress.h
@@ -46,7 +46,8 @@ extern "C" {
 #include <folly/Conv.h>
 #include <folly/Format.h>

-#if defined(__APPLE__) && !defined(s6_addr16)
+#if defined(__FreeBSD__) || defined(__NetBSD__) || defined(__OpenBSD__) || \
+    defined(__APPLE__)
 # define s6_addr16 __u6_addr.__u6_addr16
 #endif

```

**Comment by zauguin** [comment]
Does anything speaks against this?

```diff
diff --git a/folly/detail/IPAddress.h b/folly/detail/IPAddress.h
index f255229..f6db412 100644
--- a/folly/detail/IPAddress.h
+++ b/folly/detail/IPAddress.h
@@ -46,7 +46,8 @@ extern "C" {
 #include <folly/Conv.h>
 #include <folly/Format.h>

-#if defined(__APPLE__) && !defined(s6_addr16)
+#if !defined(s6_addr16)
 # define s6_addr16 __u6_addr.__u6_addr16
 #endif
```

**Comment by lichray** [comment]
I'm always conservative, but I don't mind.

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by chipturner** [comment]
Thank you for your patience. We're going to close out this issue. If you're still experiencing the problem described, please reopen the issue - thanks!

**Comment by chipturner** [comment]
Hello!  This is a human.  My previous comment on this issue was a robot running amok.  I apologize that the issue was closed, and am re-opening it.  Thanks for your help with our folly project and for your understanding about rogue robots trying to take over the world.

**Comment by samupl** [comment]
This error still occurs with the latest sources on FreeBSD 10.1-RELEASE-p10

**Comment by sgolemon** [comment]
Diff up for review internally: D2182912
