### ISSUE TITLE
Interest in deduction guides for containers

### ISSUE THREAD

**Issue by JoeLoser** [facebook/folly#1064]
How does the team feel about implementing deduction guides for the various containers? It would be guarded by the `__cpp_deduction_guides` feature test macro to not break any existing code. This would help those using C++17 or C++20 to use additional language facilities with the existing containers.

There is existing prior art in defining deduction guides for some `pushmi` types as added by @kirkshoop

**Comment by yfeldblum** [comment]
I like it.

**Comment by yfeldblum** [comment]
I would definitely take PRs with deduction guides.

**Comment by JoeLoser** [comment]
[Here](https://github.com/facebook/folly/pull/1090) is a PR for `fbvector` deduction guide. If we're all on the same page with the level of testing/approach, then I'm happy to continue with other containers, beginning in the level of popularity by use.
