### ISSUE TITLE
failed compilation on debian 

### ISSUE THREAD

**Issue by cparfon** [facebook/folly#107]
Trying to compile latest version and I get this:

In file included from io/async/AsyncTimeout.cpp:22:0:
./../folly/io/async/EventBase.h:130:3: error: looser throw specifier for 'virtual folly::EventBase::~EventBase()'
In file included from ./../folly/io/async/EventBase.h:22:0,
from io/async/AsyncTimeout.cpp:22:
./../folly/wangle/Executor.h:29:13: error: overriding 'virtual folly::wangle::Executor::~Executor() noexcept (true)'
make[2]: [io/async/AsyncTimeout.lo] Error 1
make[2]: Leaving directory `/home/ciprian/folly-master/folly-master/folly'
make[1]: [all-recursive] Error 1
make[1]: Leaving directory `/home/ciprian/folly-master/folly-master/folly'
make: * [all] Error 2

Any thoughts?

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by chipturner** [comment]
Thank you for your patience. We're going to close out this issue. If you're still experiencing the problem described, please reopen the issue - thanks!

**Comment by chipturner** [comment]
Hello!  This is a human.  My previous comment on this issue was a robot running amok.  I apologize that the issue was closed, and am re-opening it.  Thanks for your help with our folly project and for your understanding about rogue robots trying to take over the world.

**Comment by sgolemon** [comment]
Actually, this stuff has been moved and refactored quite a bit since then.

I'm going to close the issue in the hopes that it got fixed along the way, but if you're still experiencing build issues, please reopen it with an updated error output.  Thanks.
