### ISSUE TITLE
apply_tuple_test.ForwardTuple.Basic fails with Clang and libc++

### ISSUE THREAD

**Issue by JoeLoser** [facebook/folly#1078]
The `apply_tuple_test.ForwardTuple.Basic` fails for [forwarding tuple](https://github.com/facebook/folly/blob/master/folly/functional/test/ApplyTupleTest.cpp#L578)

In particular, with Clang 7.0.1 and `libc++`, we get back `std::tuple<const int&&, const double&&>` instead of a tuple of lvalue references.

**Comment by yfeldblum** [comment]
I have a diff up for review internally to fix this test.

**Comment by JoeLoser** [comment]
Nice. Thanks for the update.
