### ISSUE TITLE
Allow selection of SSL Context based on target IP in addition to SNI

### ISSUE THREAD

**Issue by smunaut** [facebook/folly#108]
Basically I want to be able to select a context based on the IP the client connected to when it provided no SNI information.

The setup is as follow:
- The server is configured with several loopbacks interface in several range.
- The network gear will route any packet  for those range to the main server IP.
- This basically allows the server to easily have 100's of IPs without having to configure a distinct interface for each.

If the client sends SNI info, then of course we use that. Unfortunately, there is still quite a bit of clients that don't especially in enterprise environment or when using client libraries (like python only added SNI _very_ recently), so to still support those, we assign a distinct IP to each of our customer that has a custom domain and we use the target IP as a fallback.

Unfortunately, in folly (and proxygen which is what I'd like to use) all of this is kind of hidden away in the Acceptor SSLContextManager, it evens extract the domains name directly from the certs.

The least intrusive way I can see to support this would be to add a mapping from IP -> DN in the SSL Context Manager where a user can manually fill a map and then in the ServerNameCallbackResult, if there is no SNI, then lookup if the is a IP -> DN mapping and use that.

If I write such a thing, would it be admissible for merging or is this something you just don't want ?

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by chipturner** [comment]
Thank you for your patience. We're going to close out this issue. If you're still experiencing the problem described, please reopen the issue - thanks!

**Comment by afrind** [comment]
I think this was closed in error.  An engineer has been assigned to implement this feature.  We'll update shortly.

**Comment by chipturner** [comment]
Hello!  This is a human.  My previous comment on this issue was a robot running amok.  I apologize that the issue was closed.  Thanks for your help with our folly project and for your understanding about rogue robots trying to take over the world.

**Comment by Orvid** [comment]
Hello non-bots @afrind and @chipturner. Did this ever happen?

**Comment by smunaut** [comment]
Closing 6 year old issue ... no idea if this was ever implemented but if it wasn't, it will obviously never be.
