### ISSUE TITLE
Any plan to support async results in subprocess?

### ISSUE THREAD

**Issue by prehistoric-penguin** [facebook/folly#1091]
For boost process, we can combine async io with process, like this:
https://www.boost.org/doc/libs/1_65_1/doc/html/boost_process/tutorial.html#boost_process.tutorial.async_io

Is there any plan to support this?

**Comment by yfeldblum** [comment]
I don't know that anyone is currently working on this. But I would be willing to review an implementation if one is contributed. 😃 

Closing the issue, because the question *as asked* has been answered.
