### ISSUE TITLE
CMake fails with LOCATION property

### ISSUE THREAD

**Issue by deryck1031** [facebook/folly#1100]
CMake Error at  build/fbcode_builder/CMake/FindLibEvent.cmake:39 (get_target_property):
  INTERFACE_LIBRARY targets may only have whitelisted properties.  The
  property "LOCATION" is not allowed.

We are running with cmake version of 3.13.2.  According to others:
                   CMake removed the ability to use the LOCATION property around 3.6

Below workaround seems to be working:
-  get_target_property(LIBEVENT_LIB event LOCATION)
+  get_target_property(LIBEVENT_LIB event INTERFACE_LINK_LIBRARIES)

**Comment by wez** [comment]
Hmm, the change that introduced that ran through CI running a mixture of cmake versions that includes at least 3.6 and 3.14.  I suspect that this is related more to your version of libevent; can you share more details about your build environment?  The contents of the `<PREFIX>/lib/cmake/libevent/*.cmake` files would be most useful to see to understand exactly what we're dealing with.

Can you share the "Found libevent ..." line from the cmake output when you make the switch to `INTERFACE_LINK_LIBRARIES`?  I'm curious to see what it is returning to you.

**Comment by deryck1031** [comment]
We are basically creating a project that includes latest code from folly, libevent, abseil, etc.  We are including them as sub projects.  We are running Linux 2.6 with gcc 7.4.  
Since we always use latest libevent source from github, I think you can find all the cmake files from below:
          https://github.com/libevent/libevent/tree/master/cmake

Below is the output using INTERFACE_LINK_LIBRARIES:
             **Found libevent from package config include=/home/zkn8etz/source/third_party/libevent@master/include;/data/local/local0/_zkn8etz_cmake_build/gmts/debug/_deps/libevent-build/include lib=event_static**

Please let me know if there are anything else you want me to provide.

**Comment by wez** [comment]
I think it would be helpful to see the installed `lib/cmake/libevent/*.cmake` files; those are generated by your local cmake and bake in the details from your installation.

Regarding the output you shared; thanks for that!  Unfortunately, it shows that it wouldn't solve the problem that led to the use of `LOCATION`, which is that the bare `event_static` bleeds into downstream packages rather than the actual library that it resolves to.

**Comment by deryck1031** [comment]
Below is for LibeventTargets.cmake:

# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget event_core_static event_extra_static event_openssl_static event_pthreads_static event_static)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target event_core_static
add_library(event_core_static STATIC IMPORTED)

# Create imported target event_extra_static
add_library(event_extra_static STATIC IMPORTED)

# Create imported target event_openssl_static
add_library(event_openssl_static STATIC IMPORTED)

# Create imported target event_pthreads_static
add_library(event_pthreads_static STATIC IMPORTED)

# Create imported target event_static
add_library(event_static STATIC IMPORTED)

# Import target "event_core_static" for configuration "Debug"
set_property(TARGET event_core_static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(event_core_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "/data/local/local0/_zkn8etz_cmake_build/gmts/debug/_deps/libevent-build/lib/libevent_core.a"
  )

# Import target "event_extra_static" for configuration "Debug"
set_property(TARGET event_extra_static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(event_extra_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "/data/local/local0/_zkn8etz_cmake_build/gmts/debug/_deps/libevent-build/lib/libevent_extra.a"
  )

# Import target "event_openssl_static" for configuration "Debug"
set_property(TARGET event_openssl_static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(event_openssl_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "/data/local/local0/_zkn8etz_cmake_build/gmts/debug/_deps/libevent-build/lib/libevent_openssl.a"
  )

# Import target "event_pthreads_static" for configuration "Debug"
set_property(TARGET event_pthreads_static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(event_pthreads_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "/data/local/local0/_zkn8etz_cmake_build/gmts/debug/_deps/libevent-build/lib/libevent_pthreads.a"
  )

# Import target "event_static" for configuration "Debug"
set_property(TARGET event_static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(event_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "/data/local/local0/_zkn8etz_cmake_build/gmts/debug/_deps/libevent-build/lib/libevent.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
~

**Comment by deryck1031** [comment]
Below is LibeventConfig.cmake:

###### # - Config file for the Libevent package
###### # It defines the following variables
###### #  LIBEVENT_INCLUDE_DIRS - include directories for FooBar
###### #  LIBEVENT_LIBRARIES    - libraries to link against

###### # Get the path of the current file.
get_filename_component(LIBEVENT_CMAKE_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)

###### # Set the include directories.
set(LIBEVENT_INCLUDE_DIRS "/home/zkn8etz/source/third_party/libevent@master/include;/data/local/local0/_zkn8etz_cmake_build/gmts/debug/_deps/libevent-build/include")

###### # Include the project Targets file, this contains definitions for IMPORTED targets.
include(${LIBEVENT_CMAKE_DIR}/LibeventTargets.cmake)

###### # IMPORTED targets from LibeventTargets.cmake
set(LIBEVENT_LIBRARIES event event_core event_extra)

**Comment by deryck1031** [comment]
Below is LibeventConfigVersion.cmake:

set(PACKAGE_VERSION "2.2.0")

###### # Check whether the requested PACKAGE_FIND_VERSION is compatible
if("${PACKAGE_VERSION}" VERSION_LESS "${PACKAGE_FIND_VERSION}")
  set(PACKAGE_VERSION_COMPATIBLE FALSE)
else()
  set(PACKAGE_VERSION_COMPATIBLE TRUE)
  if ("${PACKAGE_VERSION}" VERSION_EQUAL "${PACKAGE_FIND_VERSION}")
    set(PACKAGE_VERSION_EXACT TRUE)
  endif()
endif()

**Comment by deryck1031** [comment]
With the latest checkout, I am still getting the same error msg:

```
CMake Deprecation Warning at /home/zkn8etz/source/third_party/folly@master/build/fbcode_builder/CMake/FindLibEvent.cmake:42 (cmake_policy):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
Call Stack (most recent call first):
  /home/zkn8etz/work/gmts/CMakeLists.txt:26 (_find_package)
  /home/zkn8etz/source/third_party/folly@master/CMake/folly-deps.cmake:39 (find_package)
  /home/zkn8etz/source/third_party/folly@master/CMakeLists.txt:96 (include)


CMake Error at /home/zkn8etz/source/third_party/folly@master/build/fbcode_builder/CMake/FindLibEvent.cmake:44 (get_target_property):
  INTERFACE_LIBRARY targets may only have whitelisted properties.  The
  property "LOCATION" is not allowed.

```

**Comment by deryck1031** [comment]
Maybe the issue is caused by below where event lib is added as an INTERFACE library?

https://github.com/libevent/libevent/blob/master/cmake/AddEventLibrary.cmake <= line #121

**Comment by Frostfox24** [comment]
###### #Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
###### #----------------------------------------------------------------
###### # Generated CMake target import file.
###### #----------------------------------------------------------------

###### # Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

###### # Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget event_core_static event_extra_static event_openssl_static event_pthreads_static event_static)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


###### # Create imported target event_core_static
add_library(event_core_static STATIC IMPORTED)

###### # Create imported target event_extra_static
add_library(event_extra_static STATIC IMPORTED)

###### # Create imported target event_openssl_static
add_library(event_openssl_static STATIC IMPORTED)

###### # Create imported target event_pthreads_static
add_library(event_pthreads_static STATIC IMPORTED)

###### # Create imported target event_static
add_library(event_static STATIC IMPORTED)

###### # Import target "event_core_static" for configuration "Debug"
set_property(TARGET event_core_static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(event_core_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "/data/local/local0/_zkn8etz_cmake_build/gmts/debug/_deps/libevent-build/lib/libevent_core.a"
  )

###### # Import target "event_extra_static" for configuration "Debug"
set_property(TARGET event_extra_static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(event_extra_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "/data/local/local0/_zkn8etz_cmake_build/gmts/debug/_deps/libevent-build/lib/libevent_extra.a"
  )

###### # Import target "event_openssl_static" for configuration "Debug"
set_property(TARGET event_openssl_static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(event_openssl_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "/data/local/local0/_zkn8etz_cmake_build/gmts/debug/_deps/libevent-build/lib/libevent_openssl.a"
  )

###### # Import target "event_pthreads_static" for configuration "Debug"
set_property(TARGET event_pthreads_static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(event_pthreads_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "/data/local/local0/_zkn8etz_cmake_build/gmts/debug/_deps/libevent-build/lib/libevent_pthreads.a"
  )

###### # Import target "event_static" for configuration "Debug"
set_property(TARGET event_static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(event_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "/data/local/local0/_zkn8etz_cmake_build/gmts/debug/_deps/libevent-build/lib/libevent.a"
  )

###### # This file does not depend on other imported targets which have
###### # been exported from the same project but in a separate export set.

###### # Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)

**Comment by Frostfox24** [comment]
add_library (event_static STATIC IMPORTED)

# Kommandoer ud over dette punkt behøver ikke at kende versionen.

Eller hvad ?
