### ISSUE TITLE
Compile failures with char8_t by MSVC under /std:c++latest mode

### ISSUE THREAD

**Issue by QuellaZhang** [facebook/folly#1102]
We've stumbled across some build failures in Folly after implementing support for char8_t under /std:c++latest in the development version of Visual C++. Could you help look at this? Thanks in advance! Noted that this issue only found when compiles with unreleased vctoolset, that next release of MSVC will have this behavior. 

**Repro steps:**

1. open X64 native tools command prompt for VS2017
2. git clone https://github.com/Microsoft/vcpkg D:\VCPKG\src
3. cd D:\VCPKG\src
4. devenv /upgrade .\toolsrc\vcpkg.sln
5. set CL=/D_SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING
6. msbuild /p:Configuration=Release /p:Platform=x86 /p:WindowsTargetPlatformVersion=10.0.17134.0 toolsrc\vcpkg.sln /t:Rebuild
7. set CL=
8. set path=%cd%\toolsrc\msbuild.x86.release;%path%
9. vcpkg install folly:x64-windows --head

**Failures:**
json.cpp
```
D:\Folly\vcpkg\src\buildtrees\folly\src\head\master-9d61a4af1a\folly/lang/Pretty.h(82): warning C4686: 'folly::detail::pretty_carray_from': possible change in behavior, change in UDT return calling convention
D:\Folly\vcpkg\src\buildtrees\folly\src\head\master-9d61a4af1a\folly\json.cpp(770): **error C2664**: 'std::basic_string<char,std::char_traits<char>,std::allocator<char>> &std::basic_string<char,std::char_traits<char>,std::allocator<char>>::append(const std::basic_string<char,std::char_traits<char>,std::allocator<char>> &)': cannot convert argument 1 from 'const char8_t [4]' to 'std::initializer_list<_Elem>'
        with
        [
            _Elem=char
        ]
D:\Folly\vcpkg\src\buildtrees\folly\src\head\master-9d61a4af1a\folly\json.cpp(770): note: No constructor could take the source type, or constructor overload resolution was ambiguous
D:\Folly\vcpkg\src\buildtrees\folly\src\head\master-9d61a4af1a\folly\json.cpp(851): note: see reference to function template instantiation 'void folly::json::escapeStringImpl<true>(folly::StringPiece,std::string &,const folly::json::serialization_opts &)' being compiled
D:\Folly\vcpkg\src\buildtrees\folly\src\head\master-9d61a4af1a\folly/Range.h(1361): note: see reference to class template instantiation 'folly::Range<const char *>' being compiled
```

**Comment by yfeldblum** [comment]
The code in question looks like:

```
std::string& out = /*...*/; // context
out.append(u8"\ufffd"); // <--- error
```

Is there something wrong with this code?

**Comment by Orvid** [comment]
@yfeldblum Yep, the issue is that you can't pass a `char8_t*` (aka a utf-8 string literal) to a function accepting a `char*`. I'm working on a fix, just haven't put it up yet :) The current version of MSVC & GCC/Clang both treat the expression as a `char*` IIRC.

**Comment by QuellaZhang** [comment]
@yfeldblum @Orvid Thank you very much. Folly works well under /std:c++latest mode on MSVC
 now.
