### ISSUE TITLE
folly::fibers and boost::fiber_specific_ptr

### ISSUE THREAD

**Issue by kreuzerkrieg** [facebook/folly#1103]
Since folly uses boost's `context` is it safe to assume boost::fiber_specific_ptr would work and work properly?

**Comment by yfeldblum** [comment]
It is not safe to assume that. Folly fibers does reuse some of Boost's internal machinery, but it is not safe to assume that anything about Folly fibers is interoperable with anything about Boost fibers.

**Comment by kreuzerkrieg** [comment]
Thanks. 
Looks like it is not working anyway
