### ISSUE TITLE
Internal compiler error with GCC 5.3.

### ISSUE THREAD

**Issue by vchrn** [facebook/folly#1105]
Hey guys,

I've tried to build the latest version of folly with GCC 5.3 (it's the default production compiler for our Red Hat version) and it fails with an internal compiler error. It's very easy to reproduce: https://godbolt.org/z/tSMGWC

I don't know if this GCC version is considered supported, but it would be nice to have a workaround, if possible.

**Comment by Orvid** [comment]
@yfeldblum Since you're already poking the pretty name stuff, do you want to look at this as well? It still reproduces with the newer version of the code as well: https://godbolt.org/z/_Ie8Gn

**Comment by vchrn** [comment]
I think I've found a workaround which, albeit stupid, does not cause the segmentation fault any longer. It's enough to wrap `pretty_raw<T>()` in its own constexpr function.

```cpp
template <typename T>
struct pretty_name_zarray {
  static constexpr auto raw_() {
    constexpr auto raw = pretty_raw<T>();
    return raw;
  }

  static constexpr auto raw = raw_();
  static constexpr auto info = pretty_parse(raw.data);
  static constexpr auto size = info.e - info.b;

  static constexpr auto zarray_() {
    pretty_carray<size + 1> data{};
    for (std::size_t i = 0; i < size; ++i) {
      data.data[i] = raw.data[info.b + i];
    }
    data.data[size] = 0;
    return data;
  }

  static constexpr pretty_carray<size + 1> zarray = zarray_();
};
```

Please note that the local variable is important, a simple `return pretty_raw<T>();` still crashes.

**Comment by yfeldblum** [comment]
Does #1106 work?

**Comment by vchrn** [comment]
Yes, it's fine, thanks for a quick fix!
