### ISSUE TITLE
folly::makeExpected dangerous behavior with explicitly constructible error type

### ISSUE THREAD

**Issue by drsam94** [facebook/folly#1111]
There is an inconsistency in the constructors of folly::Expected which makes it somewhat easy to write compiling code with folly::makeExpected which is pretty much guaranteed to crash a program. The following is a minimal example:

```
#include <folly/Expected.h>

struct A {
    explicit A(int) {};
};

int main(int argc, char** argv) {
    folly::Expected<int, A> a = folly::makeExpected<int>(argc);
    return a.value();
}
```

folly::makeExpected will return an Expected<int, int>, so this call will attempt to call the following constructor of folly::Expected<int, A>:
```
  template <
      class V,
      class E FOLLY_REQUIRES_TRAILING(
          !std::is_same<Expected<V, E>, Expected>::value &&
          std::is_constructible<Value, V&&>::value &&
          std::is_constructible<Error, E&&>::value)>
  Expected(Expected<V, E> that) : Base{expected_detail::EmptyTag{}} {
    *this = std::move(that);
  }
```

Now, if int were **convertible** to A, then this assignment operator would call the following assignment operator:
```
  template <
      class V,
      class E FOLLY_REQUIRES_TRAILING(
          !std::is_same<Expected<V, E>, Expected>::value &&
          expected_detail::IsConvertible<V&&, Value>::value &&
          expected_detail::IsConvertible<E&&, Error>::value)>
  Expected& operator=(Expected<V, E> that) {
    this->assign(std::move(that));
    return *this;
  }
```

And all would be fine, however, as the Error type we are trying to construct to is merely constructible, and not convertible, from the supplied error type, we end up instead matching none of the explicit assignment operators, and instead call the defaulted move assignment operator, which ends up recursively calling the same copy constructor again, and again, and again, in an infinite loop that will surely crash the program.

If such code is not supposed to work (as the IsConvertible check on the assignment operator leads me to believe), then this should at least fail to compile rather than generating an infinite loop.

**Comment by terrelln** [comment]
CC @ericniebler

**Comment by terrelln** [comment]
Your example should compile and work as expected now.
