### ISSUE TITLE
Unable to build on Debian 9.8 Stretch

### ISSUE THREAD

**Issue by pcampr** [facebook/folly#1121]
cmake wrongly fails with:

```
-- Performing Test FOLLY_CPP_ATOMIC_BUILTIN
-- Performing Test FOLLY_CPP_ATOMIC_BUILTIN - Failed
-- Performing Test FOLLY_CPP_ATOMIC_WITH_LIBATOMIC
-- Performing Test FOLLY_CPP_ATOMIC_WITH_LIBATOMIC - Failed
CMake Error at CMake/folly-deps.cmake:152 (message):
  unable to link C++ std::atomic code: you may need to install GNU libatomic
```

Cmake uses `check_cxx_source_compiles` in `CMake/folly-deps.cmake:152`, but the result is falsely negative (`FOLLY_CPP_ATOMIC_BUILTIN` is false, but should be true). 

---

When I extracted the same check to standalone CMakeLists.txt, the result was correct:

```
cmake_minimum_required(VERSION 3.0.2 FATAL_ERROR)
include(CheckCXXSourceCompiles)
check_cxx_source_compiles("
  #include <atomic>
  int main(int argc, char** argv) {
	struct Test { int val; };
	std::atomic<Test> s;
	return static_cast<int>(s.is_lock_free());
  }"
  FOLLY_CPP_ATOMIC_BUILTIN
)
message(STATUS "FOLLY_CPP_ATOMIC_BUILTIN=" ${FOLLY_CPP_ATOMIC_BUILTIN})
```

here, the result was correct: `FOLLY_CPP_ATOMIC_BUILTIN=1`

Some other capabilities are detected wrongly too, e.g. `FOLLY_HAVE_MEMRCHR`, `FOLLY_HAVE_RECVMMSG`, `FOLLY_HAVE_CLOCK_GETTIME`.

Tested on fresh Debian 9.8 Stretch, with:
```
$ sudo apt -y install cmake g++ libboost-all-dev libevent-dev libdouble-conversion-dev libgoogle-glog-dev libgflags-dev libiberty-dev liblz4-dev liblzma-dev libsnappy-dev zlib1g-dev binutils-dev libjemalloc-dev libssl-dev
$ cmake --version
cmake version 3.7.2
$ g++ --version
g++ (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
```

---

I tried to force set these options:
```
# added to the top of main CMakeLists.txt:
set(FOLLY_CPP_ATOMIC_BUILTIN 1)
set(FOLLY_HAVE_MEMRCHR 1)
set(FOLLY_HAVE_RECVMMSG 1)
set(FOLLY_HAVE_CLOCK_GETTIME 1)
```
With this I am able to build Folly, but I am not sure if all capabilities are enabled.

---

(All worked on Ubuntu 19.04 correctly.)

**Comment by junhochoi** [comment]
In additional to above, I also needed the following to CMakeLists.txt:
```
set(FOLLY_HAVE_WEAK_SYMBOLS 1)
```

**Comment by pcampr** [comment]
@junhochoi you are right. I had to add this one too, I just missed to paste it here. With this one I can run cmake & compile.

**Comment by pcampr** [comment]
I narrowed it down to problem with `gflags`.

Using `cmake ../folly-2019.04.29.00/ --debug-trycompile` and going through logs I found this error:

```
make[2]: Entering directory '/home/pavel/folly/build/CMakeFiles/CMakeTmp'
make[2]: *** No rule to make target 'gflags', needed by 'cmTC_f2204'.  Stop.
```

That's the reason why `check_cxx_source_compiles` fails.

---

Not sure what's wrong, but **compiling own gflags 2.2.2 helped** (it's the latest version). Folly compiles smoothly then.
Compiling own gflags 2.1.2 (the same version shipped with Debian 9.8) from the source didn't help.

**Comment by jmccl** [comment]
Same issue on debian 9.9, fwiw.

**Comment by jmccl** [comment]
The problem is that with the move to cmake, folly only handles gflags when installed in 'module mode', but not when installed in 'config mode'. I'll put in a PR.

**Comment by goudan-er** [comment]
> The problem is that with the move to cmake, folly only handles gflags when installed in 'module mode', but not when installed in 'config mode'. I'll put in a PR.

Same issue in CentOS 7.6. This PR fix the issue.

**Comment by pcampr** [comment]
closing, Debian 9 = too old to talk about
