### ISSUE TITLE
CHECK failed in SingletonThreadLocal.h in gcc 7.4.0 and 8.3.0 because of gcc bug

### ISSUE THREAD

**Issue by tudor** [facebook/folly#1135]
As 7.4.0 is the default version that ships with Ubuntu 18.04, this might be worth working around.

Tried with both gcc 7.4.0 and 8.3.0 on Ubuntu 18.04 LTS, x86_64.

https://github.com/facebook/folly/commit/d6dd4b4767bd1763c48fe96b3a01607667f2336a assumes that `thread_local` objects inside of `inline` functions have the same address, as they should, but that's not true across shared-library boundaries in gcc, see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90562

cc: @yfeldblum @djwatson @igorcanadi

**Comment by tudor** [comment]
```
    CHECK_EQ(check, &cache) << "inline function static thread_local merging";
    @ 00007fe1f5358998 google::LogMessageFatal::~LogMessageFatal()
    @ 00007fe1f6e86a3e folly::SingletonThreadLocal<folly::hazptr_tc<std::atomic>, void, folly::detail::DefaultMake<folly::hazptr_tc<std::atomic> >, void>::getSlow(folly::SingletonThreadLocal<folly::hazptr_tc<std::atomic>, void, folly::detail::DefaultMake<folly::hazptr_tc<std::atomic> >, void>::Wrapper*&)
                       /usr/local/include/folly/SingletonThreadLocal.h:168
                       -> /opt/rockset/rs/src/cpp/util/executor.cc
    @ 00007fe1f6e86ee7 folly::UnboundedBlockingQueue<folly::CPUThreadPoolExecutor::CPUTask>::add(folly::CPUThreadPoolExecutor::CPUTask)
                       /usr/local/include/folly/SingletonThreadLocal.h:179
                       -> /opt/rockset/rs/src/cpp/util/executor.cc
    @ 00007fe1f595b6bd folly::CPUThreadPoolExecutor::add(folly::Function<void ()>, std::chrono::duration<long, std::ratio<1l, 1000l> >, folly::Function<void ()>)
                       /tmp/folly/folly/executors/CPUThreadPoolExecutor.cpp:114
```

**Comment by yfeldblum** [comment]
And of course this is how it would turn out!

For context, the reason for this complexity is to have very short inline paths (both a short inline fast path and a short inline slow path).

`SingletonRelaxedCounter` uses a more general strategy for the same effect and I am curious whether `SingletonRelaxedCounter` actually deals better with shared-library boundaries in practice, if in your setup you have some way to tell.

**Comment by tudor** [comment]
Well, the “short” inline fast path is probably dwarfed in the case of shared libraries by how expensive GD TLS lookup is...

**Comment by yfeldblum** [comment]
I don't work much with shared libraries so I'm not sure what is the best way to solve it. Would guarding the `thread_local`-cached path with something like `!(__GNUC__ && __PIC__)` help?

**Comment by tudor** [comment]
Actually @yfeldblum, I think that guarding on `__PIC__` in a header file is not the right fix. That violates ODR when different parts of the code are compiled differently. (Compiling folly as a shared library and compiling the main executable without PIC is perfectly rrasonable)

**Comment by yfeldblum** [comment]
Hmmm is there a better idea?

How harmful is the ODR violation? Since `get` is always-inline, the ODR violation here could only mean that some paths in the main executable will be uncached and some paths in the shared library will be cached, but AFAICT that should affect only performance and not correctness in practice (of course in theory every ODR violation is incorrect). Although this may still suffer from the bug in `thread_local` merging anyway.

The alternative is the `SingletonRelaxedCounter` approach which is fine, but it still has the same issue with the inline fast path being big and slow in shared libraries because of TLS lookup. (The fast path is there for statically-linked things.)

**Comment by tudor** [comment]
@yfeldblum Gate if a folly shared library is built (`-DBUILD_SHARED_LIBS` at `cmake` time) *and* building with gcc < 8.4.0.

**Comment by tudor** [comment]
(The bug is fixed in gcc 8.4 and gcc 9)

**Comment by tudor** [comment]
Actually, building folly as a shared library makes no difference. The problem occurs if code that includes this header file is built as a shared library, regardless of folly's own build flags. Sigh. I guess that disabling the optimization completely for basically all released versions of gcc (except 9) is a non-starter? :)

I guess the ODR violation isn't *too* terrible, even though it makes me feel gross. Maybe gate it on gcc version < 8.4.0.

**Comment by yfeldblum** [comment]
@tudor I don't have your setup. Can you check whether #1138 works?

**Comment by tudor** [comment]
@yfeldblum I'll try it today. It seems to be a rather heavyweight fix. I'd personally prefer something that avoids the bug in gcc rather than assume that it behaves in the currently-buggy way :)

**Comment by yfeldblum** [comment]
@tudor In some ways it's actually a lightweight approach if it works, since it has less per-instance TLS overhead in threads which do not participate in using that instance.

**Comment by tudor** [comment]
@yfeldblum The PR worked for us.

**Comment by yfeldblum** [comment]
@tudor Thanks for testing!
