### ISSUE TITLE
Problems with comments in F14Table

### ISSUE THREAD

**Issue by leventov** [facebook/folly#1144]
First is from here: https://github.com/facebook/folly/pull/1142#issuecomment-497577241

https://github.com/facebook/folly/blob/9feea214fb9e8d4a7a141155b68643a393193c2a/folly/container/detail/F14Table.h#L2021-L2022 doesn't seem that this function returns anything now

Second:

https://github.com/facebook/folly/blob/9feea214fb9e8d4a7a141155b68643a393193c2a/folly/container/detail/F14Table.h#L1788-L1802

I cannot make sense of the comment (why would growing by 2^1.5 ~= 2.8 be optimal, when the chunk array's size is always a power of two?), it might be a typo where `2^1.0` was actually intended, but not sure.

**Comment by yfeldblum** [comment]
@nbronson for the growth strategy.
