### ISSUE TITLE
folly not building with Python extensions on using build_openr_debian.sh

### ISSUE THREAD

**Issue by Vijayendra-Pretlist** [facebook/folly#1156]
In file included from /usr/local/src/folly/folly/FBString.h:59:0,
                 from /usr/local/src/folly/folly/Demangle.h:19,
                 from /usr/local/src/folly/folly/ExceptionWrapper.h:33,
                 from folly/executor.cpp:635:
/usr/local/src/folly/folly/hash/Hash.h:709:8: error: redefinition of ‘struct std::hash<__int128>’
 struct hash<__int128> : folly::detail::integral_hasher<__int128> {};
        ^~~~~~~~~~~~~~
In file included from /usr/include/c++/7/bits/basic_string.h:6587:0,
                 from /usr/include/c++/7/string:52,
                 from /usr/include/c++/7/bits/locale_classes.h:40,
                 from /usr/include/c++/7/bits/ios_base.h:41,
                 from /usr/include/c++/7/ios:42,
                 from folly/executor.cpp:630:
/usr/include/c++/7/bits/functional_hash.h:169:3: note: previous definition of ‘struct std::hash<__int128>’
   _Cxx_hashtable_define_trivial_hash(__GLIBCXX_TYPE_INT_N_0)
   ^
In file included from /usr/local/src/folly/folly/FBString.h:59:0,
                 from /usr/local/src/folly/folly/Demangle.h:19,
                 from /usr/local/src/folly/folly/ExceptionWrapper.h:33,
                 from folly/executor.cpp:635:
/usr/local/src/folly/folly/hash/Hash.h:712:8: error: redefinition of ‘struct std::hash<__int128 unsigned>’
 struct hash<unsigned __int128>
        ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/7/bits/basic_string.h:6587:0,
                 from /usr/include/c++/7/string:52,
                 from /usr/include/c++/7/bits/locale_classes.h:40,
                 from /usr/include/c++/7/bits/ios_base.h:41,
                 from /usr/include/c++/7/ios:42,
                 from folly/executor.cpp:630:
/usr/include/c++/7/bits/functional_hash.h:170:3: note: previous definition of ‘struct std::hash<__int128 unsigned>’
   _Cxx_hashtable_define_trivial_hash(__GLIBCXX_TYPE_INT_N_0 unsigned)
   ^
In file included from /usr/local/src/folly/folly/synchronization/Hazptr.h:19:0,
                 from /usr/local/src/folly/folly/concurrency/UnboundedQueue.h:30,
                 from /usr/local/src/folly/folly/executors/TimedDrivableExecutor.h:21,
                 from /usr/local/src/folly/folly/futures/Future.h:32,
                 from folly/executor.cpp:637:

**Comment by Orvid** [comment]
This should be filed against the openr repo, as that's where the script your running lives.
