### ISSUE TITLE
libfolly does not build on older ARM platforms

### ISSUE THREAD

**Issue by neheb** [facebook/folly#1159]
Sample output:

```
[  0%] Building CXX object CMakeFiles/folly_base.dir/folly/CancellationToken.cpp.o
{standard input}: Assembler messages:
{standard input}:170: Error: selected processor does not support `yield' in ARM mode
{standard input}:463: Error: selected processor does not support `yield' in ARM mode
{standard input}:881: Error: selected processor does not support `yield' in ARM mode
{standard input}:1098: Error: selected processor does not support `yield' in ARM mode
CMakeFiles/folly_base.dir/build.make:62: recipe for target 'CMakeFiles/folly_base.dir/folly/CancellationToken.cpp.o' failed
```

**Comment by Orvid** [comment]
Which architecture specifically is this showing on?

**Comment by neheb** [comment]
ARMv5. Maybe v6 too. See: 

https://downloads.openwrt.org/snapshots/faillogs/arm_arm926ej-s/packages/libfolly/compile.txt
https://downloads.openwrt.org/snapshots/faillogs/arm_fa526/packages/libfolly/compile.txt
https://downloads.openwrt.org/snapshots/faillogs/arm_xscale/packages/libfolly/compile.txt

**Comment by Orvid** [comment]
Looks like it's complaining about https://github.com/facebook/folly/blob/master/folly/portability/Asm.h#L42

What should older arm systems be using instead?

**Comment by neheb** [comment]
I don't think there's an equivalent for older ARM processors.

**Comment by benstadin** [comment]
Same error on Raspbian with a Raspberry Pi 4. 

Any updates on this? Can using dissassembly code be disabled, where a non-optimized implementation is also available?

**Comment by benstadin** [comment]
The dcheck and the yield patch from openwrt worked for me for Folly v2019.10.21. @neheb Could you do a merge request for those patches?

**Comment by neheb** [comment]
https://github.com/facebook/folly/pull/1176

Complain to someone to merge.

**Comment by yfeldblum** [comment]
#1176 is merged.
