### ISSUE TITLE
Fatal error: malloc.h: No such file or directory on Mac OS X

### ISSUE THREAD

**Issue by c9s** [facebook/folly#116]
```
[  9%] Building CXX object third-party/folly/CMakeFiles/folly.dir/folly/Bits.cpp.o
[ 10%] Building CXX object third-party/folly/CMakeFiles/folly.dir/folly/Checksum.cpp.o
[ 10%] Building CXX object third-party/folly/CMakeFiles/folly.dir/folly/Conv.cpp.o
In file included from /Volumes/ramdisk/hhvm/third-party/folly/folly/FBString.h:60:0,
                 from /Volumes/ramdisk/hhvm/third-party/folly/folly/Conv.h:27,
                 from /Volumes/ramdisk/hhvm/third-party/folly/folly/Conv.cpp:17:
/Volumes/ramdisk/hhvm/third-party/folly/folly/Malloc.h:91:20: fatal error: malloc.h: No such file or directory
```

However, the `malloc.h` file is located in `/usr/include/malloc/malloc.h`

**Comment by Gownta** [comment]
Can you run `g++ -dM -E [somefile.cpp] | grep __APPLE__`?

**Comment by spacek** [comment]
Same problem here:

Linking C static library libafdt.a
[  0%] Built target afdt
[  0%] Building C object third-party/timelib/CMakeFiles/timelib.dir/parse_tz.c.o
[  0%] Building C object third-party/timelib/CMakeFiles/timelib.dir/timelib.c.o
[  0%] Building C object third-party/timelib/CMakeFiles/timelib.dir/tm2unixtime.c.o
[  1%] Building C object third-party/timelib/CMakeFiles/timelib.dir/unixtime2tm.c.o
[  1%] [  2%] [  2%] Building CXX object third-party/folly/CMakeFiles/folly.dir/folly/Bits.cpp.o
Building CXX object third-party/folly/CMakeFiles/folly.dir/folly/Checksum.cpp.o
Building CXX object third-party/folly/CMakeFiles/folly.dir/folly/Conv.cpp.o
In file included from /Users/jirispacek/hhvm/third-party/folly/folly/FBString.h:60:0,
                 from /Users/jirispacek/hhvm/third-party/folly/folly/Conv.h:27,
                 from /Users/jirispacek/hhvm/third-party/folly/folly/Conv.cpp:17:
/Users/jirispacek/hhvm/third-party/folly/folly/Malloc.h:91:20: fatal error: malloc.h: No such file or directory
 #include <malloc.h>
                    ^
compilation terminated.
make[2]: *** [third-party/folly/CMakeFiles/folly.dir/folly/Conv.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [third-party/folly/CMakeFiles/folly.dir/all] Error 2

**Comment by MerelyAPseudonym** [comment]
@Gownta, I have the same problem, and running the command you provided results in the following output:

```none
$ g++ -dM -E Conv.cpp | grep __APPLE__
Conv.cpp:17:10: fatal error: 'folly/Conv.h' file not found
#include <folly/Conv.h>
         ^
1 error generated.
#define __APPLE__ 1
```

**Comment by Gownta** [comment]
@spacek: are you on a MAC? Is __APPLE__ defined on your system?

@MerelyAPseudonym: That is a different problem. It looks like you need to put folly in your include path. The problem that c9s has is that he is on a MAC (which doesn't have the malloc.h header), but folly/Malloc.h is trying to include it nonetheless.

**Comment by spacek** [comment]
@Gownta yes, I use Yosemite, I tried echo __APPLE__ but this returned the same string.

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by chipturner** [comment]
Thank you for your patience. We're going to close out this issue. If you're still experiencing the problem described, please reopen the issue - thanks!

**Comment by chipturner** [comment]
Hello!  This is a human.  My previous comment on this issue was a robot running amok.  I apologize that the issue was closed, and am re-opening it.  Thanks for your help with our folly project and for your understanding about rogue robots trying to take over the world.

**Comment by sgolemon** [comment]
Could you send me your config.log (to sgolemon@fb.com ) or at least paste relevant looking bits around mentions of malloc.h ?
A copy of your folly-config.h would be nice as well.

There is a check for malloc.h and there is an ifdef based on that check, so I'm not sure why you're getting this error.

**Comment by sgolemon** [comment]
No feedback for five months, closing.
