### ISSUE TITLE
Fiber deadlock when waiting on nested Futures

### ISSUE THREAD

**Issue by yuruiz** [facebook/folly#1160]
For the example code with nested future as below, the fiber would block on the future1.wait() forever. 
```
 folly::EventBase evb;
  FiberManager& manager = getFiberManager(evb);
  std::thread t1([&]() {
    evb.loopForever();
  });

  auto future = manager.addTaskRemoteFuture([&]() {
    folly::Future<bool> future1 = manager.addTaskRemoteFuture([&]() {
      std::cout << "1" << std::endl;
      std::cout << "2" << std::endl;
      std::cout << "3" << std::endl;
      return true;
    });

    future1.wait(); // blocking here forever
    evb.terminateLoopSoon();
  });
  future.wait();

  t1.join();

```

However, if I change the future1.wait() to baton.wait(), the fiber would be able to proceed with no problem. I am wondering is there anything wrong with waiting future in another fiber? How could I avoid the deadlock situation?

```
folly::EventBase evb;
  FiberManager& manager = getFiberManager(evb);
  std::thread t1([&]() {
    evb.loopForever();
  });

  auto future = manager.addTaskRemoteFuture([&]() {
    folly::Future<bool> future1 = manager.addTaskRemoteFuture([&]() {
      std::cout << "1" << std::endl;
      std::cout << "2" << std::endl;
      std::cout << "3" << std::endl;
      return true;
    });

    Baton baton;
    std::move(future1).thenValue([&](bool ret) {
      if (ret) {
        baton.post();
      }
    });
    baton.wait();  // proceed with no problem

    evb.terminateLoopSoon();
  });
  future.wait();

  t1.join();
```

**Comment by yfeldblum** [comment]
What platform is this on?

**Comment by yuruiz** [comment]
Currently this code is tested on MacOS Mojave. And I am using clang 7.0.1.

**Comment by yfeldblum** [comment]
Is it related to `FOLLY_FUTURE_USING_FIBER`?

https://github.com/facebook/folly/blob/v2019.06.03.00/folly/futures/Portability.h#L21-L22
https://github.com/facebook/folly/blob/v2019.06.03.00/folly/futures/Future-inl.h#L42-L43

**Comment by yuruiz** [comment]
You are right! By setting FOLLY_FUTURE_USING_FIBER to 1 the problem is solved! Thank you very much.
