### ISSUE TITLE
Imported target "Folly::folly" includes non-existent path

### ISSUE THREAD

**Issue by condy0919** [facebook/folly#1175]
Folly git master installed.

When compiling [fizz](https://github.com/facebookincubator/fizz), it prompts
```
CMake Error in CMakeLists.txt:
  Imported target "Folly::folly" includes non-existent path

    "//include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

The "//include" path appears in `folly-targets.cmake`#L64, which is generated by CMake.
> 63 set_target_properties(Folly::folly_deps PROPERTIES
> 64   INTERFACE_INCLUDE_DIRECTORIES "/usr/include;//include;/usr/include/libiberty"

Fizz compiles by removing the weird "//include".
I can't figure out which cmake file references the **weird** "//include" directory.

**Comment by RBlafford** [comment]
@condy0919 I found this issue as well when compiling in a fresh fedora:30 docker image. Apparently creating /include fixed the issue for me.

**Comment by condy0919** [comment]
> @condy0919 I found this issue as well when compiling in a fresh fedora:30 docker image. Apparently creating /include fixed the issue for me.

It enforces us to pollute a `include` directory in `/`
