### ISSUE TITLE
App security test reports Insecure API for React Native iOS App - Binary Analysis (IPA)

### ISSUE THREAD

**Issue by kamalyzl** [facebook/folly#1181]
Currently the project contains variables not recommended by apple, which generates vulnerabilities when compiling an ipa.
for example:

https://developer.apple.com/library/archive/documentation/Security/Conceptual/SecureCodingGuide/Articles/BufferOverflows.html#//apple_ref/doc/uid/TP40002577-SW1

Don’t use these functions | Use these instead
-- | --
strcat | strlcat
strcpy | strlcpy
strncat | strlcat
strncpy | strlcpy
sprintf | snprintf (see note) or asprintf
vsprintf | vsnprintf (see note) or vasprintf
gets | fgets (see note) or use Core Foundation or Foundation API

I would like to know if it is possible to correct them since it is giving problems in the projects created with native react

**Comment by Orvid** [comment]
The only places using any of these things should not be present in any build other than for linux (the elf symbolizer appears to make use of `strncat`) and Windows (where one of the time portability functions we have a stub for has no ability to use anything safer than `strcpy` :( ). Could you point to which functions you're seeing issues with?

**Comment by kamalyzl** [comment]
Hello! The inconvenience is given when using it with native react, when a static analysis or analysis of ethical hacking is done to the ipa made with
 react native.
Certain vulnerabilities appear, such as:
_strcpy, _strncat, _strlen, _alloca, _printf, _sscanf, _stat, _memcpy, _fopen, _vsnprintf, _gets.

Hello! The inconvenience is given when using it with native react, when a static analysis or analysis of ethical hacking is done to the ipa made with
 react native.
Certain vulnerabilities appear, such as:


as well as the method random()
