### ISSUE TITLE
Concurrent hashmap update issue

### ISSUE THREAD

**Issue by mtmd** [facebook/folly#1185]
According to the documentation, holding an iterator should be sufficient for concurrent update of a key in folly ConcurrentHashMap. However, when I try to do so using the following code snippet the results are no correct. In this code, many threads are trying to insert elements in a hashmap. In case that the key already exist, they update the value only if it is larger than the old value.

``` 
 folly::ConcurrentHashMap<KeyType, ValType> follyMap;
    do {
      auto found = follyMap.find(key);
      if (found != follyMap.end()) {
        if (found->second < val) {
          auto res = follyMap.assign_if_equal(key, found->second, val);
          cont = !res;
        }
        break;
      } else {
        auto res = follyMap.insert(key, val);
        cont = !res.second;
      }
    } while (cont);
```
Thank you.

**Comment by suspend0** [comment]
```
 * A: Yes, this is safe.  However, the iterating thread is not
 * garanteed to see (or not see) concurrent insertions and erasures.
```
I think that means `found->second` could change between when you test `found->second < val` and when you pass it to `assign_if_equal`.

**Comment by mtmd** [comment]
Thank you @suspend0. I have tried it by saving a copy of `found->second` and still the result is wrong. Here is the snippet:
```
 auto found = follyMap.find(key);
      if (found != follyMap.end()) {
        ValType oldVal = found->second;
        if (oldVal < val) {
          auto res = follyMap.assign_if_equal(key, oldVal, val);
          cont = !res;
        }
        break;
      } else {
        auto res = follyMap.insert(key, val);
        cont = !res.second;
      }
      cnt++;
    } while (cont);
```
The problem is that many threads call `assign_if_equal` concurrently and they overwrite each others' work.

**Comment by yfeldblum** [comment]
> According to the documentation, holding an iterator should be sufficient for concurrent update of a key in folly ConcurrentHashMap.

This is a mistaken reading of the documentation. `ConcurrentHashMap` provides *no synchronization* over the mapped values. It provides synchronization *only* over the map structure itself. For example, it permits concurrent access to a value in one thread while another thread erases that value.

To do the algorithm in your question, you must add your own synchronization. This can take the form of a mutex for the whole map or of a per-value mutex or of atomic max operations implemented via compare-exchange loops.
