### ISSUE TITLE
Possible undefined behavior in `folly/json.cpp`

### ISSUE THREAD

**Issue by SuperV1234** [facebook/folly#1190]
Hello, [`folly/json.cpp` L126-133](https://github.com/facebook/folly/blob/master/folly/json.cpp#L126-L133) has the following code:

```cpp
using SortByRef = FunctionRef<bool(dynamic const&, dynamic const&)>;
auto const& sort_keys_by = opts_.sort_keys_by
    ? SortByRef(opts_.sort_keys_by)
    : SortByRef(std::less<dynamic>());
std::sort(refs.begin(), refs.end(), [&](ref a, ref b) {
    // Only compare keys.  No ordering among identical keys.
    return sort_keys_by(a.get().first, b.get().first);
});
```

Isn't `SortByRef(std::less<dynamic>())` creating a dangling `FunctionRef` pointing to a dead `std::less<dynamic>()` temporary, or am I missing something?

Thanks.

**Comment by suspend0** [comment]
is this const reference lifetime extension?

**Comment by SuperV1234** [comment]
I am not referring to the lifetime of the FunctionRef, but to the lifetime of what it refers to.

On 17 Jul 2019 17:57, Darren Gilroy <notifications@github.com> wrote:

is this const reference lifetime extension?

**Comment by SuperV1234** [comment]
Unless I am missing something, in 

```cpp
auto const& sort_keys_by = opts_.sort_keys_by
    ? SortByRef(opts_.sort_keys_by)
    : SortByRef(std::less<dynamic>());
```

the temporary created by `std::less<dynamic>()` lives only for the duration of the full expression. Therefore when `sort_keys_by` is used in 

```cpp
std::sort(refs.begin(), refs.end(), [&](ref a, ref b) {
    // Only compare keys.  No ordering among identical keys.
    return sort_keys_by(a.get().first, b.get().first);
});
```

the pointer inside the `FunctionRef` that was supposed to point to the `std::less<dynamic>()` temporary is actually pointing to a dead object.

**Comment by SuperV1234** [comment]
Any news on this?

**Comment by yfeldblum** [comment]
Thanks, this looks like a bug. I have an internal change up for code review.
