### ISSUE TITLE
Waiting for any baton to be posted

### ISSUE THREAD

**Issue by GauthamBanasandra** [facebook/folly#1196]
Let's say we have 2 batons `baton1` and `baton2`. Is there any construct that allows me to wait until *any* of them is posted?
For example,
```
folly::fibers::Baton baton1;
folly::fibers::Baton baton1;

fiber_mgr_.addTask([this]() {
    baton1.post();
});

fiber_mgr_.addTask([this]() {
    baton2.post();
});

// I want to wait until at least one of them has be posted and take some action.
// I'm thinking of something like this -
BatonWaiter({baton1, []() { /* baton1 has been posted */},
    {baton2, []() {/* baton2 has been posted */}).WaitAny();
```

**Comment by yfeldblum** [comment]
No, that is not directly supported by `Baton`, but you could write something on top of it.

```
folly::fibers::Baton baton1;
folly::fibers::Baton baton2;
std::atomic<bool> claimed{false};
int which{0};
folly::fibers::Baton batonAny;

fiber_mgr_.addTask([this]() { baton1.post(); });
fiber_mgr_.addTask([this]() { baton2.post(); });

auto waitAny = [this](auto& baton, int id) {
  return [this, baton = &baton]() {
    baton->wait();
    if (!claimed.exchange(true, std::memory_order_relaxed)) {
      which = id;
      batonAny.post();
    }
  };
};

fiber_mgr_.addTask(waitAny(baton1, 1));
fiber_mgr_.addTask(waitAny(baton2, 2));

fiber_mgr_.addTask([this]() {
  batonAny.wait();
  switch (which) {
    case 1: // ...
    case 2: // ...
  }
});
```

**Comment by GauthamBanasandra** [comment]
Thanks @yfeldblum . Is a PR welcome for `BatonWaiter` ?

**Comment by yfeldblum** [comment]
Possibly, though I would question why you need it, and would first try to see if alternatives are possible (e.g., `collectN`).

The high-level reason is that `Baton` is intended to be a primitive used to build higher-level libraries for general use, rather than being one of those libraries.

**Comment by GauthamBanasandra** [comment]
I wouldn't place `BatonWaiter` as part of `Baton`. It would be, as you said, built on top of `Baton`.
I'm just thinking that `BatonWaiter` would be more elegant and easy to accomplish scenarios like these. We could add more functionality to `BatonWaiter` -
1. `WaitAll()` Waits till all the batons have been posted.
2. `WaitN()` Waits till any N of batons have been posted.
It wouldn't be so straightforward for moderate users to implement them on their own (at least for me).

**Comment by yfeldblum** [comment]
True. But regarding moderate users, the normal expectation is that they will use futures with `collectN` rather than using batons.
