### ISSUE TITLE
cmake targets error

### ISSUE THREAD

**Issue by zwkno1** [facebook/folly#1205]
build project depend on folly will cause error:

CMake Error in CMakeLists.txt:
Imported target "Folly::folly" includes non-existent path

"//include"
in its INTERFACE_INCLUDE_DIRECTORIES. Possible reasons include:

The path was deleted, renamed, or moved to another location.

An install or uninstall procedure did not complete successfully.

The installation package was faulty and references files it does not
provide.

CMake Error in CMakeLists.txt:
Imported target "Folly::folly" includes non-existent path

"//include"
in its INTERFACE_INCLUDE_DIRECTORIES. Possible reasons include:

The path was deleted, renamed, or moved to another location.

An install or uninstall procedure did not complete successfully.

The installation package was faulty and references files it does not
provide.

-- Generating done
CMake Generate step failed. Build files cannot be regenerated correctly.

i build folly(last release) and install in /usr.
i think /usr/lib/cmake/folly/folly-targets.cmake is errror. 

i edit it,then compliler succed.

**Comment by jklappenbach** [comment]
Thank you.  That was some horrid autogeneration.

**Comment by pramodsatya** [comment]
Thanks, this fixed it for me.
