### ISSUE TITLE
poly not working with msvc c++14 .

### ISSUE THREAD

**Issue by Prashanth-BC** [facebook/folly#1206]
folly.poly is not working with msvc c++14, On compilation I am seeing the below error. There is no compilation error with c++17 though!
```
1>C:\workspace\cpp_projs\type_erasure_test2\include\folly\Poly.h(1131): error C2510:  'apply': left of '::' must be a class/struct/union
1>C:\workspace\cpp_projs\type_erasure_test2\include\folly\Poly.h(1133): message :  see reference to class template instantiation 'folly::Poly<I>' being compiled
1>type_erasure_test2.cpp
1>C:\workspace\cpp_projs\type_erasure_test2\include\folly\Poly.h(1132): error C2510:  'apply': left of '::' must be a class/struct/union
1>C:\workspace\cpp_projs\type_erasure_test2\include\folly\Poly.h(1131): error C2510:  'apply': left of '::' must be a class/struct/union
1>C:\workspace\cpp_projs\type_erasure_test2\include\folly\Poly.h(1133): message :  see reference to class template instantiation 'folly::Poly<I>' being compiled
1>C:\workspace\cpp_projs\type_erasure_test2\include\folly\Poly.h(1132): error C2510:  'apply': left of '::' must be a class/struct/union
```
```
This is the part of the code where the error is referred to.
template <class I>
struct Poly final : detail::PolyValOrRef<I> {
  friend detail::PolyAccess;
  Poly() = default;
  using detail::PolyValOrRef<I>::PolyValOrRef;
  using detail::PolyValOrRef<I>::operator=;
};
```

**Comment by Prashanth-BC** [comment]
When compiled on linux with c++14 it works. I the problem is only in msvc with c++14.

**Comment by Orvid** [comment]
Poly is known to be non-functional on Windows, which is why it isn't built by default: https://github.com/facebook/folly/blob/master/CMakeLists.txt#L237

Which version of MSVC are you building with?

**Comment by yfeldblum** [comment]
@Orvid More broadly, do we intend to support MSVC with C++14 or only with C++17?

**Comment by Orvid** [comment]
@yfeldblum C++17 and C++latest

**Comment by Prashanth-BC** [comment]
The version of the MSVC is 19.22.27905.0. with c++17 it works without any problem. But it doesn't work with c++14. Hence we cant use in the older projects. But it works even with c++14 on Linux.

**Comment by yfeldblum** [comment]
Thank you for the report, but we do not plan to make Poly work with MSVC in C++14 mode. Older versions of MSVC and MSVC in older modes have too much divergent behavior.
