### ISSUE TITLE
Arena wants to be movable but isn't

### ISSUE THREAD

**Issue by ckamm** [facebook/folly#121]
It looks like folly::Arena wants to be movable. It says
```
  // movable
  Arena(Arena&&) = default;
  Arena& operator=(Arena&&) = default;
```
But it doesn't help because it's inside a private: section. If Arena really can be moved safely, these functions should be made public.

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by 0xae** [comment]
fb bot, i hate you

**Comment by chipturner** [comment]
Thank you for your patience. We're going to close out this issue. If you're still experiencing the problem described, please reopen the issue - thanks!

**Comment by chipturner** [comment]
Hello!  This is a human.  My previous comment on this issue was a robot running amok.  I apologize that the issue was closed.  Thanks for your help with our folly project and for your understanding about rogue robots trying to take over the world.

**Comment by sgolemon** [comment]
Diff up for internal review: D2184131
