### ISSUE TITLE
Folly failed to build due to error C2668 on MSVC

### ISSUE THREAD

**Issue by QuellaZhang** [facebook/folly#1222]
Hi All,

Folly failed to build due to error C2668 on MSVC. We verified this issue started with https://github.com/facebook/folly/commit/2ccb83e210451d42cb6b85bd63c056ffe8153c93#diff-adc9887ed7cec42eefa64676de690bc8. Could you please help take a look at this? Thanks in advance!

Environment
VCPKG(latest revision from github) + VS 2017 + Windows Server 2016

**Repro steps:**

1. open X64 native tools command prompt for VS2017
2. git clone https://github.com/Microsoft/vcpkg D:\VCPKG\src
3. cd d:\vcpkg\src
4. devenv /upgrade .\toolsrc\vcpkg.sln
5. set CL=/D_SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING
6. msbuild /p:Configuration=Release /p:Platform=x86 /p:WindowsTargetPlatformVersion 10.0.16299.0 toolsrc\vcpkg.sln /t:Rebuild
7. set CL=
8. set path=%cd%\toolsrc\Release;%path%
9. vcpkg install folly:x64-windows –head

Actual result:
TimekeeperScheduledExecutor.i
D:\Folly\vcpkg\src\buildtrees\folly\src\head\master-64d3e55ef1\folly/futures/detail/Core.h(690): error C2668: 'folly::atomic_compare_exchange_strong_explicit': ambiguous call to overloaded function
D:\Folly\vcpkg\src\buildtrees\folly\src\head\master-64d3e55ef1\folly/synchronization/AtomicUtil-inl.h(78): note: could be 'bool folly::atomic_compare_exchange_strong_explicit<folly::futures::detail::State>(std::atomic<folly::futures::detail::State> *,folly::futures::detail::State *,folly::futures::detail::State,std::memory_order,std::memory_order)'
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\atomic(1718): note: or       'bool std::atomic_compare_exchange_strong_explicit<folly::futures::detail::State>(std::atomic<folly::futures::detail::State> *const ,folly::futures::detail::State *const ,const folly::futures::detail::State,const std::memory_order,const std::memory_order) noexcept' [found using argument-dependent lookup]
D:\Folly\vcpkg\src\buildtrees\folly\src\head\master-64d3e55ef1\folly/futures/detail/Core.h(695): note: while trying to match the argument list '(std::atomic<folly::futures::detail::State> *, _Ty *, folly::futures::detail::State, std::memory_order, std::memory_order)'
        with
        [
            _Ty=folly::futures::detail::State
        ]
D:\Folly\vcpkg\src\buildtrees\folly\src\head\master-64d3e55ef1\folly/futures/detail/Core.h(682): note: while compiling class template member function 'void folly::futures::detail::Core<T>::setResult(folly::Executor::KeepAlive<folly::Executor> &&,folly::Try<T> &&)'
        with
        [
            T=folly::Unit
        ]

**Comment by yfeldblum** [comment]
Should be fixed by b1233937ae794b6f2a9102d81e3c737906851c23.
