### ISSUE TITLE
DelayedDestructionBase.h asserts that unsigned integral is greater than zero

### ISSUE THREAD

**Issue by suspend0** [facebook/folly#1224]
This is a super silly thing that probably doesn't warrant this issue, but here goes:

```
    explicit DestructorGuard(DelayedDestructionBase* dd) : dd_(dd) {
      if (dd_ != nullptr) {
        ++dd_->guardCount_;
        assert(dd_->guardCount_ > 0); // check for wrapping
      }
    }
```

this `assert` is offering a false sense of security since `guardCount_` is defined as a `uint32_t`

**Comment by yfeldblum** [comment]
The assertion is there to check for overflow. E.g. if `guardCount_` starts off as `uint32_t(-1)` (the largest positive integer value representable as `uint32_t`), then `++guardCount_` increments it around to `0` and then the assertion fails.
