### ISSUE TITLE
Does using a ticket improve performance for MPMC Queue

### ISSUE THREAD

**Issue by benstadin** [facebook/folly#1225]
Title says all. Does using a ticket affect the read / write performance of MPMC Queue? I'm asking because I'm curious whether the ticket has any performance meaning at all, and if it is a comparable optimization to the Token of a Moodycamel ConcurrentQueue, for example.

**Comment by yfeldblum** [comment]
@magedm

**Comment by magedm** [comment]
@nbronson created MPMCQueue

**Comment by nbronson** [comment]
The ticket helps the contended case a lot. The intuition is that the contention is on an operation that always succeeds (atomic_add), and that must only be done once per enqueue or dequeue. Once the ticket has been dispensed then writers and their paired readers are spread across a range of cache lines (see the stride_ variable).

At least on x86, if lots of threads perform atomic increment they will all succeed. Contention on a compare_and_set algorithm, however, usually means that N-1 of the threads fail and have to try again, further increasing traffic on that cache line. Once the ticket has been dispensed then we can use a less contention-tolerant but more complex algorithm on the individual slot. This design isn't as effective on CPUs that have to implement std::atomic::fetch_add with a loop, namely ARM.

**Comment by benstadin** [comment]
Thank you for this info. How would I use a ticket using the blocking API? I only see a these two in MPMCQueue.h:

blockingWrite()
blockingReadWithTicket()

There seems to be no blockingWriteWithTicket() and I couldn't find how to use the ticket API. 

It would be really interesting how using a ticket compares to the benchmarks provided as comments at the end of the file in DynamicBoundedQueueTest.cpp. The benchmarks there do not seem to use tickets either.

**Comment by nbronson** [comment]
The tickets are supposed to be an internal implementation detail. They are already used for every read and write (blocking or not), but it isn't intended that you manage them directly. blockingReadWithTicket should probably be private or protected; I'm surprised it is public.

**Comment by benstadin** [comment]
Thank you for clarifying. I'll close this ticket.
