### ISSUE TITLE
Folly does not build in PowerPC64

### ISSUE THREAD

**Issue by gustavotemple** [facebook/folly#123]
This issue will be use to keep track of PowerPC64 related pull requests / issues in the Folly

**Comment by gustavotemple** [comment]
https://github.com/facebook/folly/pull/122

**Comment by gustavotemple** [comment]
https://github.com/facebook/folly/pull/127

**Comment by facebook-github-bot-7** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by chipturner** [comment]
Thank you for your patience. We're going to close out this issue. If you're still experiencing the problem described, please reopen the issue - thanks!

**Comment by chipturner** [comment]
Hello!  This is a human.  My previous comment on this issue was a robot running amok.  I apologize that the issue was closed.  Thanks for your help with our folly project and for your understanding about rogue robots trying to take over the world.

**Comment by sgolemon** [comment]
With the application of #127, does the build still fail? Reopen with details if so.
