### ISSUE TITLE
Job steal in executors

### ISSUE THREAD

**Issue by asierguti** [facebook/folly#1236]
Does folly support job stealing in threadpoolexecutor or iothreadpoolexecutor? If not, could it be feasible to do it? I don't know if a thread can look into other threads even loop and remove a task from there. I would be glad to work in such feature and submit a PR

**Comment by yfeldblum** [comment]
`CPUThreadPoolExecutor` has a single queue shared among all threads.

`IOThreadPoolExecutor` has a queue per thread and does not do work-stealing. But code should almost never be using it directly, and should generally be using it only for the underlying async IO and not, in general, for any associated CPU work like compression/decompression or serialization/deserialization.
