### ISSUE TITLE
should FOLLY_HAVE_PTHREAD_ATFORK should be defined for linux by default?

### ISSUE THREAD

**Issue by senior7515** [facebook/folly#124]
Folly version 23 (i just download this today)

/usr/local/include/folly/detail/ThreadLocalDetail.h:221:6: error: pthread_atfork unavailable [-Werror,-W#warnings]

```
  StaticMeta() : nextId_(1) {
    head_.next = head_.prev = &head_;
    int ret = pthread_key_create(&pthreadKey_, &onThreadExit);
    checkPosixError(ret, "pthread_key_create failed");
 
#if FOLLY_HAVE_PTHREAD_ATFORK
    ret = pthread_atfork(/*prepare*/ &StaticMeta::preFork,
                         /*parent*/ &StaticMeta::onForkParent,
                         /*child*/ &StaticMeta::onForkChild);
    checkPosixError(ret, "pthread_atfork failed");
#elif !__ANDROID__
    // pthread_atfork is not part of the Android NDK at least as of n9d. If
    // something is trying to call native fork() directly at all with Android's
    // process management model, this is probably the least of the problems.
    //
    // But otherwise, this is a problem.
    #warning pthread_atfork unavailable
#endif
  }

```

Here  is the man pages for the default linux pthread installation. 

https://gist.github.com/senior7515/88c40a7c007595603531

maybe i'm missing something?

**Comment by djwatson** [comment]
Yea, something seems wrong with the configure script that tries to detect this

**Comment by marcinpe** [comment]
i can confirm it. Happens also on latest arch linux (as a result make check fails on ThreadLocalTest). Seems that the presence of pthread_at_fork is tested without linking in pthread.

**Comment by 0mok** [comment]
I already fixed configure script for this issue.
Please check my pull request.
https://github.com/facebook/folly/pull/125

**Comment by marcinpe** [comment]
pull request #125  has been merged. I verified it work with latest Arch Linux (it used to fail before).
