### ISSUE TITLE
Dependeny on fmt not mentioned in installation instructions

### ISSUE THREAD

**Issue by SashaNullptr** [facebook/folly#1262]
# fmt not mentioned as dependency

Folly depends on the [fmt](https://github.com/fmtlib/fmt) library in order to build, as seen in [folly-deps.cmake](https://github.com/facebook/folly/blob/547f5abfb80f37bd09f3cd4ffde82e8796c2b624/CMake/folly-deps.cmake#L214) as of da41ae504804260fa371595daed100d03440670e . This  isn't mentioned in the installation instructions. For example if one is naively following the Ubuntu 16.04 LTS install instructions CMake will fail to find `fmt` and error out.

On Ubuntu 18.04 LTS installing `libfmt-dev` doesn't fix things, at least not with CMake running without any flags (i.e. `cmake ..`). It seems that fmt needs to be installed from source as described in the [fmt usage guide](https://fmt.dev/latest/usage.html#building-the-library).

**Comment by SashaNullptr** [comment]
In particular, if `libfmt-dev` from Ubuntu 18,04 is installed ( version 4.0.0+ds-2 ) the following error occurs:

```shell
In file included from /folly/folly/logging/LogStreamProcessor.cpp:17:0:
/folly/folly/logging/LogStreamProcessor.h:19:10: fatal error: fmt/core.h: No such file or directory
```

**Comment by yfeldblum** [comment]
@vitaut

**Comment by vitaut** [comment]
I'll update the instructions.

**Comment by vitaut** [comment]
Oh, I see it's already done in #1263. Thanks, @SashaNullptr.
