### ISSUE TITLE
Is fbvector itself IsRelocatable and IsZeroInitializable?

### ISSUE THREAD

**Issue by hadrielk** [facebook/folly#1270]
This is more of a question than an issue, but I assume `fbvector` itself is trivially-relocatable and zero-initializable?

In other words, no matter what type-T an `fbvector` holds, an `fbvector<T>` should be relocatable and zero-initializable, correct?

It looks like it should be, but I don't see those traits being set for `fbvector` itself, and it fails `static_assert` checks for it - though admittedly I'm using an older version of folly.

**Comment by hadrielk** [comment]
I have the same question about `small_vector`, which I believe should be IsRelocatable as well, and possibly IsZeroInitializable.

**Comment by Quuxplusone** [comment]
Short answer is "your intuition is correct." There are merely some caveats for `fbvector<T, A>`.

`fbvector<T, A>` is trivially relocatable iff `A` and `A::pointer` are both trivially relocatable _and_ `A`'s POCMA/POCCA/POCS are all `true_type`. The former are true for `std::allocator<T>`, but false for e.g. `boost::interprocess::allocator<T, boost::interprocess::managed_shared_memory::segment_manager>`. The latter are true for `std::allocator<T>`, but false for e.g. `std::pmr::polymorphic_allocator<T>`. I have no idea whether `fbvector` would actually be bug-free, or even compile, with either of those allocators; I'm just giving the Platonic ideal.

`fbvector<T, A>` is zero-initializable (i.e. trivially value-initializable) iff `A` and `A::pointer` are both zero-initializable.

`small_vector<T, N>` is trivially relocatable iff `T` is trivially relocatable, and zero-initializable iff `T` is zero-initializable. (Under the reasonable assumption that `size_t` is always both trivially relocatable and zero-initializable.)

So, should `folly::IsRelocatable` be specialized for `fbvector<T, std::allocator<T>>`? IMHO maybe; I have no strong opinion personally.
Should it be specialized for `fbvector<T, A>`? Probably not worth the maintenance burden.
The ideal situation would be to just convince your friendly neighborhood compiler vendor to support full-on `__is_trivially_relocatable(T)` and `[[fncv::trivially_relocatable]]` and then Folly could opt in to using the builtin/attribute on that compiler. ;)
