### ISSUE TITLE
bootstrap for Centos

### ISSUE THREAD

**Issue by mallochine** [facebook/folly#128]
It would greatly ease compilation and installation. My experience with "folly" thus far has been extremely unsatisfactory.

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by chipturner** [comment]
Thank you for your patience. We're going to close out this issue. If you're still experiencing the problem described, please reopen the issue - thanks!

**Comment by mallochine** [comment]
Please reopen it for me. I don't see a description of how the issue was resolved. It's near impossible to build 'folly' on a CentOS machine.

I actually decided to quit using folly for this reason.

**Comment by chipturner** [comment]
Hello!  This is a human.  My previous comment on this issue was a robot running amok.  I apologize that the issue was closed.  Thanks for your help with our folly project and for your understanding about rogue robots trying to take over the world.

**Comment by sgolemon** [comment]
Could you clarify what you want bootstrapped?  "bootstrap for CentOS" doesn't really describe an issue...

**Comment by mallochine** [comment]
Yeah. There seems to be a shell script for Mac OS that will install all the libraries you need to compile. I had a very hard time getting the libraries myself:

```
  cd folly
  ./bootstrap-osx-homebrew.sh
  make
  make check
```

**Comment by sgolemon** [comment]
Ah, I see what you mean.

I'm going to be cleaning up the build system soon and can address this at that point (since I'm going to want to test the changes on a few distros).  Watch this space. :)

**Comment by renoust** [comment]
Hi there,

I see no updates has been made for a year here.
I'm trying to install fblualib on CentOS.
I managed to compile double-conversion as indicated in your README, however I can't seem to be able to manage autoconf generate the configure script (in folly/). Maybe a dependency issue:

"configure.ac:20: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:32: error: possibly undefined macro: AM_PROG_LIBTOOL
configure.ac:39: error: possibly undefined macro: AC_CXX_COMPILE_STDCXX_0X
configure.ac:57: error: possibly undefined macro: AC_MSG_ERROR
configure.ac:120: error: possibly undefined macro: AM_PATH_PYTHON
configure.ac:515: error: possibly undefined macro: AM_CONDITIONAL"

Any idea? or document to walk me through centos compilation?

Cheers,

**Comment by renoust** [comment]
Hi!

I managed to solve my issues. I leave this message for other users who would face trouble compiling folly on CentOS.

First a quick note, I found that a _double-conversion_ package exists for CentOS but I haven't tried compiling with it. _double-conversion_ was locally compiled following the instructions given by README.md. And I linked as suggested after building (in `double-conversion/`) :
`ln -s src double-conversion`

My issue reported up there came from an incomplete _autotools_ suit, so be sure to install all the packages:
`yum install automake autoconf autogen libtool make scons`
However here is the trick, you also need 
`yum install perl-Thread-Queue`

You should then follow the package suit given in the README.md (don't forget the devel).
`yum install boost boost-devel gflags gflags-devel glog glog-devel libevent libevent-devel epel-release lz4 lz4-devel lzma lzma-devel snappy snappy-devel zlib zlib-devel`

Ok, from that point on, you need to set a few local variables:
`export DOUBLE_CONVERSION_HOME=/your/path/to/double-conversion`

This will be necessary at compilation time:
`export LD_LIBRARY_PATH=$DOUBLE_CONVERSION_HOME`

I had a few issues with _gfalgs_, so I had to set the following, plus specify the use of _pthead_ later:
```
export GFLAGS_INCLUDE=/usr/local/include/gflags/
export GFLAGS_LIB=/usr/local/lib/
```

Now you can go to your `folly/folly/` folder, and in the configure, the `-lpthread` will save you some trouble:
```
autoreconf -ivf
./configure LDFLAGS="-L$DOUBLE_CONVERSION_HOME/ -L$GFLAGS_LIB -lpthread" CPPFLAGS="-I$DOUBLE_CONVERSION_HOME/ -I$GFLAGS_INCLUDE" --prefix=/path/to/your/local/installation/
make
make install
```

Cheers,

**Comment by snarkmaster** [comment]
@renoust, thanks for the very helpful message! I'm going to close out this issue so that it doesn't get repurposed for new reports. It's better to keep these things separate.

**Comment by joaorossi** [comment]
I have some doubts if this will actually work.
Shouldn't Boost be build with at least gcc 4.9+ with C++14 support?
I couldn't find anywhere evidence that CentOS Boost pkgs meet those demands.
At the moment I'm very frustrated trying to build folly reliably on CentOS, and the only solution seems to be using Ubuntu :/

**Comment by daniel-lucio** [comment]
For CentOS, check #929
