### ISSUE TITLE
Question regarding concurrent hash map

### ISSUE THREAD

**Issue by Milerius** [facebook/folly#1282]
Hello i have the following declaration:

```cpp
using t_coins_registry      = folly::ConcurrentHashMap<std::string, coin_config>;
using t_balance_registry    = folly::ConcurrentHashMap<std::string, ::mm2::api::balance_answer>;
using t_my_orders           = folly::ConcurrentHashMap<std::string, ::mm2::api::my_orders_answer>;
using t_tx_history_registry = folly::ConcurrentHashMap<std::string, std::vector<tx_infos>>;
using t_orderbook_registry  = folly::ConcurrentHashMap<std::string, ::mm2::api::orderbook_answer>;
```

@magedm 

I looked at the allocator of ConcurrentHashMap this is a `std::allocator<std::uint8_t>`

`ubsan` blame me because I have misaligned call and construction regarding the map.

There is another allocator that I can use to quickly solve my problem ?

(All my data structure are much more than 1byte aligned I guess)

Thank's a lot !

**Comment by yfeldblum** [comment]
It is possible to use `folly::AlignedSysAllocator` or `boost::memory::aligned_allocator`.

**Comment by Milerius** [comment]
hey @yfeldblum 

i tried:

```cpp
template <typename Key, typename Value>
using t_concurrent_reg = folly::ConcurrentHashMap<Key, Value, std::hash<Key>, 
std::equal_to<>, 
boost::alignment::aligned_allocator<uint8_t>>;

using t_balance_registry    = t_concurrent_reg<std::string, ::mm2::api::balance_answer>;
using t_my_orders           = t_concurrent_reg<std::string, ::mm2::api::my_orders_answer>;
using t_tx_history_registry = t_concurrent_reg<std::string, std::vector<tx_infos>>;
using t_orderbook_registry  = t_concurrent_reg<std::string, ::mm2::api::orderbook_answer>;
```

Same error:

`Constructor call on misaligned address 0x7fe4e2de3b20 for type 'folly::ConcurrentHashMap<std::__1::basic_string<char>, std::__1::vector<atomic_dex::tx_infos, std::__1::allocator<atomic_dex::tx_infos> >, std::__1::hash<std::__1::basic_string<char> >, std::__1::equal_to<void>, boost::alignment::aligned_allocator<unsigned char, 1>, '\x08', std::atomic, std::__1::mutex, detail::concurrenthashmap::bucket::BucketTable>::SegmentT' (aka 'ConcurrentHashMapSegment<std::__1::basic_string<char>, std::__1::vector<atomic_dex::tx_infos, std::__1::allocator<atomic_dex::tx_infos> >, '\b', std::__1::hash<std::__1::basic_string<char> >, std::__1::equal_to<void>, boost::alignment::aligned_allocator<unsigned char, 1>, atomic, std::__1::mutex, BucketTable>'), which requires 64 byte alignment`

If I try to use an allocator aligned on 64 byte I got this error:

fatal error: cannot initialize a parameter of type 'boost::alignment::aligned_allocator<unsigned long long, 1>::pointer' (aka 'unsigned long long *') with an rvalue of type 'uint8_t *' (aka 'unsigned char *')
        Allocator().deallocate((uint8_t*)seg, sizeof(SegmentT));

**Comment by Milerius** [comment]
I think that we can use `Allocator::pointer` for casting, everyone will be happy.
