### ISSUE TITLE
Subprocess.h, /bin/bash -c does not propragate kill signal. template should be /bin/bash -c 'exec ' + command

### ISSUE THREAD

**Issue by senior7515** [facebook/folly#129]
# This is more of a discussion / request for comment / possible improvement

## Issue: 

When building a subprocess to run in /bin/bash, the kill signal is not propagated

## Example
```
      folly::Subprocess::Options procopts;
      procopts.parentDeathSignal(9);
      client_ = std::make_shared<folly::Subprocess>(command, procopts, &env);
      LOG(INFO) << "Client process running with proc id: " << client_->pid();
      auto retcode = client_->returnCode();
      if(retcode.exited() || retcode.killed()) {
        LOG(FATAL) << "Could not start the process: " << retcode.str();
      }

      auto proc = client_;
      std::thread([proc](){
          auto retcode = proc->wait();
          if(retcode.exited() || retcode.killed()) {
            LOG(FATAL) << "Error detected with running process: "
                       << proc->pid() << ", details: " << retcode.str();
          }
        }).detach(); // monitoring thread;
    });
```

The issue w/  running a command inside a /bin/bash -c (what folly does) is that when the parent dies, the shell *does* in fact propagate the signal to the child process (/bin/bash) but that in turn **does not** propagate it to it's child process. 

# Proposed solution / Comment

1. write a template for folly similar to the following: 

```
#!/bin/bash

trap 'kill -TERM $PID' TERM INT
$JAVA_EXECUTABLE $JAVA_ARGS &
PID=$!
wait $PID
trap - TERM INT
wait $PID
EXIT_STATUS=$?

```

2. Add an exec (bash command) to the string that gets concatenated so that the /bin/bash runs the process in the foreground

```
/bin/bash -c 'exec ' + command
```

Technically I think folly is correct, but is certainly not the expected usecase. Happy to send in a PR for this if interested. 

Thank you!

**Comment by facebook-github-bot-0** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by chipturner** [comment]
Thank you for your patience. We're going to close out this issue. If you're still experiencing the problem described, please reopen the issue - thanks!

**Comment by chipturner** [comment]
Hello!  This is a human.  My previous comment on this issue was a robot running amok.  I apologize that the issue was closed.  Thanks for your help with our folly project and for your understanding about rogue robots trying to take over the world.

**Comment by Orvid** [comment]
PRs are always welcome, but for now, I'll close this.

**Comment by senior7515** [comment]
@Orvid I am happy to send in the PR that adds the `exec` to the string that process uses. The question I was trying to get here is if it would be accepted. the PR is so simple that I was just trying to get feedback. Happy to push if you still want it. The work around is that now my forked processes always use the 'exec' at the begining of the string. Again, happy to push the PR if the library wants to behave that way.

**Comment by Orvid** [comment]
After reading through the issue a bit closer, I think it's probably better to keep the existing API functioning as it is currently. If you want to add an extra option onto the existing API though, that would probably be accepted.

**Comment by yfeldblum** [comment]
Prefixing with `exec ` will break, e.g., `true && echo "hello world"` by turning it into `exec true && echo "hello world"`.

I would generally recommend using the `Subprocess` ctor that takes the command to run as `const vector<string>&`.
