### ISSUE TITLE
try_emplace for AtomicHashMap?

### ISSUE THREAD

**Issue by michaeleisel** [facebook/folly#1314]
For the single-threaded case, I have the following:
```
folly::AtomicHashMap<const char *, uint32_t> map(N);
auto iter = map.find(key);
if (iter != map.end()) {
  return iter->second;
} else {
  id++;
  map.insert(key, id);
  return id;
}
```
However, for the multi-threaded case, `.find` and `.insert` are insufficient because this code will have a race condition (two threads might enter the `else` block for the same key at the same time). So, I need an atomic operation, i.e. `try_emplace`, that will do this. `recToIdx` is undocumented but public, and the `mayInsert` parameter for it suggests that it could do what I need. Is that true? If not, is there any other way to do this, or should I just use a `ConcurrentHashMap`?

**Comment by suspend0** [comment]
> Insert returns false if there is a key collision

I think that means you can do
```
auto ret = map.insert(key, id);
if(ret.second) // key was inserted
```
I might not have a good grasp on your use case, but does that help?

**Comment by michaeleisel** [comment]
Yes, thanks!
