### ISSUE TITLE
was this operation thread-safe?

### ISSUE THREAD

**Issue by monadbobo** [facebook/folly#1315]
Are the following operations thread-safe?

``` c
// Thread A
auto promise = std::make_shared<folly::Promise<folly::Unit>>();
auto f = p.getFuture();

// Thread B
promise->setValue(folly::unit);

//Thread A
f.get()
```

**Comment by yfeldblum** [comment]
Yes.

The promise object is not thread-safe. The future object is not thread-safe.

But there is just enough internal synchronization between the promise and the future such that it is safe to use the promise from one thread and the future from another thread.
