### ISSUE TITLE
boost 1.70 and Windows build

### ISSUE THREAD

**Issue by ayermolo** [facebook/folly#1320]
Hello
Looks like vcpkg is applying some patches to get folly to work with boost 1.7.0
https://github.com/microsoft/vcpkg/tree/master/ports/folly

Are there any plans to port them to folly master?

Thanks

**Comment by Orvid** [comment]
We've already fixed this in https://github.com/facebook/folly/commit/52dcff2e82700a3a2c77c24983447c3c2c5b22b7
