### ISSUE TITLE
ThreadCachedInt race condition

### ISSUE THREAD

**Issue by sriramsankar** [facebook/folly#133]
When a thread dies, the destructor of the IntCache object is called to pass on its val_ value to the parent's target_ variable.  During the time the destructor is running, if readFull() is called, this thread is left out by accessAllThreads() in ThreadLocalPtr.  And if the destructor has not yet called flush() (see code below), the val_ of the IntCache object is left out of the total.

So, for example, if the correct value to be returned by readFull() is 1000, and the value of val_ of the dying thread is 100, readFull() ends up returning 900 in this situation.

Would appreciate a fix/solution if anyone has one.  Thanks.

    ~IntCache() {
      if (parent_) {
        flush();
      }
    }

**Comment by sriramsankar** [comment]
Suggestion for fix:  ThreadLocalPtr should not allow destruction of thread local state and calls to accessAllThreads() to happen simultaneously.

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by chipturner** [comment]
Thank you for your patience. We're going to close out this issue. If you're still experiencing the problem described, please reopen the issue - thanks!

**Comment by sriramsankar** [comment]
The issue is still around.  Attached is a unit test.

Sriram.

On Thu, Jun 4, 2015 at 11:56 AM, Chip Turner <notifications@github.com>
wrote:

> Thank you for your patience. We're going to close out this issue. If
> you're still experiencing the problem described, please reopen the issue -
> thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/folly/issues/133#issuecomment-109009259>.
>

#include "folly/ThreadCachedInt.h"

#include <atomic>
#include <memory>
#include <stdint.h>
#include <thread>
#include <vector>
#include <gtest/gtest.h>

using std::unique_ptr;
using std::vector;

namespace folly {

typedef ThreadCachedInt<int64_t> Counter;

class ThreadCachedIntTest : public testing::Test {
 public:
  uint32_t GetDeadThreadsTotal(const Counter& counter) {
    return counter.readFast();
  }
};

// Multithreaded tests.  Creates a specified number of threads each of
// which iterates a different amount and dies.

namespace {
// Set cacheSize to be large so cached data moves to target_ only when
// thread dies.
Counter g_counter_for_mt_slow(0, UINT32_MAX);
Counter g_counter_for_mt_fast(0, UINT32_MAX);

// Used to sync between threads.  The value of this variable is the
// maximum iteration index upto which Runner() is allowed to go.
std::atomic<uint32_t> g_sync_for_mt(0);

std::chrono::milliseconds one_milli(1);

// Performs the specified number of iterations.  Within each
// iteration, it increments counter 10 times.  At the beginning of
// each iteration it checks g_sync_for_mt to see if it can proceed,
// otherwise goes into a loop sleeping and rechecking.
void Runner(Counter* counter, uint32_t iterations) {
  for (uint32_t i = 0; i < iterations; ++i) {
    while (i >= g_sync_for_mt) {
      // Iteration i blocked at this point, so we wait.
      std::this_thread::sleep_for(one_milli);
    }
    for (uint32_t j = 0; j < 10; ++j) {
      counter->increment(1);
    }
  }
}
} // namespace

// Slow test with fewer threads where there are more busy waits and
// many calls to readFull().  This attempts to test as many of the
// code paths in Counter as possible to ensure that counter values are
// properly passed from thread local state, both at calls to
// readFull() and at thread death.
TEST_F(ThreadCachedIntTest, MultithreadedSlow) {
  static constexpr uint32_t kNumThreads = 20;
  g_sync_for_mt = 0;
  vector<unique_ptr<std::thread>> threads(kNumThreads);
  // Creates kNumThreads threads.  Each thread performs a different
  // number of iterations in Runner() - threads[0] performs 1
  // iteration, threads[1] performs 2 iterations, threads[2] performs
  // 3 iterations, and so on.
  for (uint32_t i = 0; i < kNumThreads; ++i) {
    threads[i].reset(new std::thread(Runner, &g_counter_for_mt_slow, i + 1));
  }
  // Variable to grab current counter value.
  int32_t counter_value;
  // The expected value of the counter.
  int32_t total = 0;
  // The expected value of GetDeadThreadsTotal().
  int32_t dead_total = 0;
  // Each iteration of the following thread allows one additional
  // iteration of the threads.  Given that the threads perform
  // different number of iterations from 1 through kNumThreads, one
  // thread will complete in each of the iterations of the loop below.
  for (uint32_t i = 0; i < kNumThreads; ++i) {
    // Allow upto iteration i on all threads.
    g_sync_for_mt = i + 1;
    total += (kNumThreads - i) * 10;
    // Loop until the counter reaches its expected value.
    do {
      counter_value = g_counter_for_mt_slow.readFull();
    } while (counter_value < total);
    // All threads have done what they can until iteration i, now make
    // sure they don't go further by checking 10 more times in the
    // following loop.
    for (uint32_t j = 0; j < 10; ++j) {
      counter_value = g_counter_for_mt_slow.readFull();
      EXPECT_EQ(total, counter_value);
    }
    dead_total += (i + 1) * 10;
    EXPECT_GE(dead_total, GetDeadThreadsTotal(g_counter_for_mt_slow));
  }
  // All threads are done.
  for (uint32_t i = 0; i < kNumThreads; ++i) {
    threads[i]->join();
  }
  counter_value = g_counter_for_mt_slow.readFull();
  EXPECT_EQ(total, counter_value);
  EXPECT_EQ(total, dead_total);
  EXPECT_EQ(dead_total, GetDeadThreadsTotal(g_counter_for_mt_slow));
}

// Fast test with lots of threads and only one call to readFull()
// at the end.
TEST_F(ThreadCachedIntTest, MultithreadedFast) {
  static constexpr uint32_t kNumThreads = 1000;
  g_sync_for_mt = 0;
  vector<unique_ptr<std::thread>> threads(kNumThreads);
  // Creates kNumThreads threads.  Each thread performs a different
  // number of iterations in Runner() - threads[0] performs 1
  // iteration, threads[1] performs 2 iterations, threads[2] performs
  // 3 iterations, and so on.
  for (uint32_t i = 0; i < kNumThreads; ++i) {
    threads[i].reset(new std::thread(Runner, &g_counter_for_mt_fast, i + 1));
  }
  // Let the threads run to completion.
  g_sync_for_mt = kNumThreads;
  // The expected value of the counter.
  uint32_t total = 0;
  for (uint32_t i = 0; i < kNumThreads; ++i) {
    total += (kNumThreads - i) * 10;
  }
  // Wait for all threads to complete.
  for (uint32_t i = 0; i < kNumThreads; ++i) {
    threads[i]->join();
  }
  int32_t counter_value = g_counter_for_mt_fast.readFull();
  EXPECT_EQ(total, counter_value);
  EXPECT_EQ(total, GetDeadThreadsTotal(g_counter_for_mt_fast));
}

} // namespace folly

**Comment by sriramsankar** [comment]
Here's a fix that is required - the red part has been moved into the scope
of the lock, and the comment in blue is no longer valid.  This fix is
required for users of ThreadLocal (such as ThreadCachedInt) because it
should not be possible to see an intermediate state between when a thread
starts to die and when the data of that thread has been fully cleaned up.

Sriram.


  static void onThreadExit(void* ptr) {
    auto & meta = instance();
#if !__APPLE__
    ThreadEntry* threadEntry = getThreadEntry();

    DCHECK_EQ(ptr, &meta);
    DCHECK_GT(threadEntry->elementsCapacity, 0);
#else
    ThreadEntry* threadEntry = static_cast<ThreadEntry*>(ptr);
#endif
    {
      std::lock_guard<std::mutex> g(meta.lock_);
      meta.erase(threadEntry);

*      // No need to hold the lock any longer; the ThreadEntry is private
to this*
*      // thread now that it's been removed from meta.*

*    FOR_EACH_RANGE(i, 0, threadEntry->elementsCapacity) {*
*      threadEntry->elements[i].dispose(TLPDestructionMode::THIS_THREAD);*
*    }*


    }
    free(threadEntry->elements);
    threadEntry->elements = nullptr;
    pthread_setspecific(meta.pthreadKey_, nullptr);

#if __APPLE__
    // Allocated in getThreadEntry(); free it
    delete threadEntry;
#endif
  }

**Comment by chipturner** [comment]
Hello!  This is a human.  My previous comment on this issue was a robot running amok.  I apologize that the issue was closed.  Thanks for your help with our folly project and for your understanding about rogue robots trying to take over the world.

**Comment by Orvid** [comment]
I see no colors in that.
If the problem still exists, could you open a PR with the changes?
