### ISSUE TITLE
Folly failed to build due to ’error C2039: 'bit_cast': is not a member of 'std'‘ on MSVC

### ISSUE THREAD

**Issue by QuellaZhang** [facebook/folly#1333]
Hi All,

Folly failed to build due to error C2039 on MSVC. Could you please help take a look at this? Thanks in advance!

**Environment**
VCPKG(latest revision from github) + VS 2019 + Windows Server 2016

**Repro steps:**

1. open X64 native tools command prompt for VS2019
2. git clone https://github.com/Microsoft/vcpkg D:\VCPKG\src
3. cd d:\vcpkg\src
4. devenv /upgrade .\toolsrc\vcpkg.sln
5. set CL=/D_SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING
6. msbuild /p:Configuration=Release /p:Platform=x86 /p:WindowsTargetPlatformVersion 10.0.18362.0 toolsrc\vcpkg.sln /t:Rebuild
7. set CL=
8. set path=%cd%\toolsrc\Release;%path%
9. vcpkg install folly:x64-windows –head

**Actual result:**
F:\gitP\microsoft\vcpkg\buildtrees\folly\src\head\master-71ebdf935b\folly/lang/Bits.h(71): error C2039: 'bit_cast': is not a member of 'std'
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cinttypes(22): note: see declaration of 'std'
F:\gitP\microsoft\vcpkg\buildtrees\folly\src\head\master-71ebdf935b\folly/lang/Bits.h(71): error C2873: 'bit_cast': symbol cannot be used in a using-declaration

**Comment by CaseyCarter** [comment]
It looks like Bits.h is detecting support for `std::bit_cast` with `__cpp_lib_bit_cast`, which is fine, but using it without including `<bit>` first, which is not fine.
