### ISSUE TITLE
MPMCQueue does not seem to handle 64-bit data items

### ISSUE THREAD

**Issue by staffantj** [facebook/folly#1336]
The unit tests for MPMCQueue seem to be only checking for the validity of the values of passed data when dealing with 32-bit data (ints). Type safety is checked for eg pointers, however.

When passing 64-bit values through the queue, it appears that approx the top 3 bytes are trimmed, at least when using MSVC 2019 16.4 in 64-bit mode. 

This is illustrated by the following test
```C++
namespace
{
   constexpr size_t queue_capacity{ 100 };
   std::set< uint64_t > const results{ 0x0badf00d, 0xa5a5a5a5a5a5a5a5, 0x5a5a5a5a5a5a5a5a, 0xa5a5a5a5a5a5a5a6, 0x5a5a5a5a5a5a5a5b, 0xa5a5a5a5a5a5a5a7, 0x5a5a5a5a5a5a5a5c, 0xa5a5a5a5a5a5a5a8, 0x5a5a5a5a5a5a5a5d, 0xa5a5a5a5a5a5a5a9 };
}

TEST( folly_mpmc, simple_use )
{
   folly::MPMCQueue< uint64_t > test_instance{ queue_capacity };
   for( uint64_t a : results )
   {
      test_instance.write( a );
   }

   EXPECT_EQ( 10, test_instance.writeCount() );
   EXPECT_EQ( 0, test_instance.readCount() );

   for( uint64_t b : results )
   {
      uint64_t c{};
      test_instance.read( c );
      EXPECT_EQ( b, c );
   }
}
```
This results in test errors like the following:

> error: Expected equality of these values:
>   b
>     Which is: 6510615555426900570
>   c
>     Which is: 383767960154

It's easier to see in Hex, where we get
0x5a5a5a5a 5a5a5a5a
vs
0x59 5a5a5a5a

This may share some characteristicss with eg #914

**Comment by suspend0** [comment]
> at least when using MSVC 2019 16.4 in 64-bit mode
For what it's worth, this test passes on GCC 7.4.0 (Ubuntu)

**Comment by staffantj** [comment]
I pulled a latest vcpkg version of folly, and with that the test passes - must have been something I caused in the version I pulled.
