### ISSUE TITLE
Allow user code to create an invalid future

### ISSUE THREAD

**Issue by lichray** [facebook/folly#134]
Like to have a public ctor

```
Future(std::nullptr_t);
```

Otherwise when a user needs to define a future and to use it right after the definition, the future always needs to be initialized to a value or an exception.

**Comment by facebook-github-bot-5** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by chipturner** [comment]
Thank you for your patience. We're going to close out this issue. If you're still experiencing the problem described, please reopen the issue - thanks!

**Comment by chipturner** [comment]
Hello!  This is a human.  My previous comment on this issue was a robot running amok.  I apologize that the issue was closed.  Thanks for your help with our folly project and for your understanding about rogue robots trying to take over the world.

**Comment by fugalh** [comment]
I don't understand what legitimate operations you would perform on a future constructed with a null core. What are you trying to accomplish?

**Comment by lichray** [comment]
Put a future as a data member in a class, where you don't have an appropriate way to initialize it, but you can make it valid later.

**Comment by fugalh** [comment]
I see. We'll take it into consideration. A workaround would be to put it on the heap (shared_ptr), or use a folly::Optional. 

We have traditionally avoided exposing invalid-state future objects, however there is a leak in the boat anyway (you can potentially get one as the result of a move operation), so we may lower that vigilance. However, the void specialization makes it difficult to do the way we'd want (we'd want to just use the default constructor, but that is different for void). We are looking to do away with Future<void> in favor of Future<Unit> which might make it easier.

**Comment by leolchat** [comment]
Isn't `makeEmpty` filling that gap now?

**Comment by lichray** [comment]
@leolchat It is.
