### ISSUE TITLE
Add Windows CI support

### ISSUE THREAD

**Issue by uilianries** [facebook/folly#1341]
Hi!

It would be great having Folly built on Windows (Visual Studio) to validate any new change. For now, we have good free options:

- Appveyor 
- Azure

I can submit a PR with Appveyor, but some admin needs to activate the integration between CI service and this repository.

**Comment by Orvid** [comment]
We already have a build validating windows changes for pull requests.

**Comment by uilianries** [comment]
Great! I'll follow it. Thanks!
