### ISSUE TITLE
folly:x64-windows failed with: BUILD_FAILED on vs2015

### ISSUE THREAD

**Issue by fengshaoxia** [facebook/folly#1366]
use command : vcpkg install folly:x64-windows
vs version : vs2015
Vcpkg version: 2020.02.04

info:
Starting package 1/1: folly:x64-windows
Building package folly[core,zlib]:x64-windows...
-- Note: folly only supports static library linkage. Building static library.
-- Using cached F:/Github/vcpkg/downloads/facebook-folly-8874256376d2f8a32867f17c9472a446d6707604.tar.gz
-- Extracting source F:/Github/vcpkg/downloads/facebook-folly-8874256376d2f8a32867f17c9472a446d6707604.tar.gz
-- Applying patch missing-include-atomic.patch
-- Applying patch reorder-glog-gflags.patch
-- Applying patch disable-non-underscore-posix-names.patch
-- Applying patch boost-1.70.patch
-- Using source at F:/Github/vcpkg/buildtrees/folly/src/46d6707604-d64234cbb5
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: "D:/Program Files (x86)/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v
    Working Directory: F:/Github/vcpkg/buildtrees/folly/x64-windows-dbg
    See logs for more information:
      F:\Github\vcpkg\buildtrees\folly\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/folly/portfile.cmake:70 (vcpkg_install_cmake)
  scripts/ports.cmake:90 (include)

Error: Building package folly:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: folly:x64-windows
  Vcpkg version: 2020.02.04

**Comment by Orvid** [comment]
Folly doesn't support building with VS2015 due to the lack of support for many modern C++ features.
