### ISSUE TITLE
Broken on FreeBSD: Undefined symbol "_r_debug"

### ISSUE THREAD

**Issue by yurivict** [facebook/folly#1373]
```libfolly.so``` is missing this symbol.

```
$ ./test
ld-elf.so.1: /usr/local/lib/libfolly.so: Undefined symbol "_r_debug"
```

Version: 2020.05.25.00
OS: FreeBSD 12.1

**Comment by yuxuanchen1997** [comment]
I also stumbled upon this when checking if we can port the exception tracer, which depends on the symbolizer to display names for frames, to FreeBSD. 

The symbolizer code [tries to link to `_r_debug` global variable](https://github.com/facebook/folly/blob/main/folly/debugging/symbolizer/detail/Debug.cpp#L73), which holds the pointer to `struct r_debug`. However, such variable is dependent on the implementation detail of `ld.so` on Linux. 

The `struct r_debug` [does exist on FreeBSD](https://github.com/freebsd/freebsd-src/blob/a1a067b7131ef9122800f16dbc154dd390dc74a6/sys/sys/link_elf.h#L66), although it's not available as a global variable. Now it looks the proper way of finding the pointer to the `r_debug` struct should look like [this one in lldb](https://github.com/llvm/llvm-project/blob/0252d338fa9f4f2f1262b5f7d8158e3f5857fcaf/lldb/source/Plugins/DynamicLoader/POSIX-DYLD/DYLDRendezvous.cpp#L93-L95). I haven't checked how much work is necessary to port this to folly. 

cc: @yfeldblum
