### ISSUE TITLE
Detect that Future is detached from producer side?

### ISSUE THREAD

**Issue by tudor** [facebook/folly#1390]
Is there a way for the producer side of a promise contract to detect that the Future (consumer side) is detached?

Use case: I have a separate thread that needs to periodically check if some external event happened. I want to provide an interface like `Future<Unit> whenThingHappened()`, which is fine, except that the caller may stop caring about this event -- in which case I'd like to detect this and stop the polling thread.

Right now the interface returns a `Handle` (well, `shared_ptr<Handle>`, with appropriate wrangling of `shared_from_this`), and the `Handle` has a `getFuture()` method; you indicate that you lost interest by destroying the `Handle`, but that's not ideal -- I'd prefer to avoid having this intermediate public object.

**Comment by tudor** [comment]
An alternative is to abstract this as `pair<shared_ptr<void>, Future<Unit>>`, but it's still not as nice as I'd like.

**Comment by mpark** [comment]
I don't think that detecting `detach` is supported by `Future`. But would you interpret `whenThingHappened().thenValue(...);` to mean that the caller no longer cares about the event? To me, dropping of the `Future` by itself doesn't seem sufficient to conclude that the caller doesn't care. I would probably force the caller to explicitly call `future.cancel()` and detect this from the `Promise` side via `promise.setInterruptHandler(f)`.

**Comment by tudor** [comment]
That's a good point. I'd like to say that yes, if you have a callback set, you care about the completion, but then there's not really a good way to give up and clean resources in that case. I'll stick to my handle solution.

Relying on cancellation has its own set of problems, notably https://github.com/facebook/folly/issues/1237
