### ISSUE TITLE
[QUESTION] For F14 Hash Map with std::string key, does it store the key as a string ?

### ISSUE THREAD

**Issue by PrabhakarTayenjam** [facebook/folly#1392]
If a value is inserted to `F14FastMap<string, int>`, does it store the key as a string or in some other form like hash of the key?

**Comment by nbronson** [comment]
The entries will be stored internally as `std::pair<std::string const, int>`. Even though we might be able to be more efficient managing the string contents directly, if we used a different type internally we wouldn't be able to return a reference to the `std::pair` from the iterator's `operator*`. That would mean F14 couldn't be dropped into existing code that uses `std::unordered_map`.

Although the key is stored as a string inside the map, F14 allows you to use other string-like types when you call its methods. For example, if you pass a `std::string_view` or `folly::StringPiece` as the key to `insert_or_assign`, a `std::string` form of the key won't be constructed in the assign case.
