### ISSUE TITLE
folly seems not be able to match then call

### ISSUE THREAD

**Issue by lexuscrossover** [facebook/folly#1394]
Hi Guys, 

I tried to compile the following:

```
int main(int argc, char* argv[]) {
    folly::init(&argc, &argv);

    folly::Promise<int> promise;
    promise.getFuture()
    .then([](int value) { 
      cout << "I am in then" << endl;
    });
...
}
```
And got the compilation error below.  I built folly master a couple of days ago on ubuntu 20.04.

Thank you advance for your help!

futures_1.cpp: In function ‘int main(int, char**)’:
futures_1.cpp:13:10: error: no matching function for call to ‘folly::Future<int>::then(main(int, char**)::<lambda(int)>)’
   13 |         });
      |          ^
In file included from futures_1.cpp:2:
/usr/local/include/folly/futures/Future.h:1219:73: note: candidate: ‘template<class F> folly::Future<typename folly::futures::detail::tryCallableResult<T, F>::value_type> folly::Future<T>::then(F&&) && [with F = F; T = int]’
 1219 |   Future<typename futures::detail::tryCallableResult<T, F>::value_type> then(
      |                                                                         ^~~~
/usr/local/include/folly/futures/Future.h:1219:73: note:   template argument deduction/substitution failed:
/usr/local/include/folly/futures/Future.h: In substitution of ‘template<class F> folly::Future<typename folly::futures::detail::tryCallableResult<int, F, typename std::enable_if<is_invocable_v<F, folly::Try<int>&&>, void>::type>::value_type> folly::Future<int>::then<F>(F&&) && [with F = main(int, char**)::<lambda(int)>]’:
futures_1.cpp:13:10:   required from here
/usr/local/include/folly/futures/Future.h:1219:73: error: no type named ‘type’ in ‘struct std::enable_if<false, void>’
/usr/local/include/folly/futures/Future.h:1250:39: note: candidate: ‘template<class R, class Caller, class ... Args> folly::Future<typename folly::isFuture<F>::Inner> folly::Future<T>::then(R (Caller::*)(Args ...), Caller*) && [with R = R; Caller = Caller; Args = {Args ...}; T = int]’
 1250 |   Future<typename isFuture<R>::Inner> then(
      |                                       ^~~~
/usr/local/include/folly/futures/Future.h:1250:39: note:   template argument deduction/substitution failed:
futures_1.cpp:13:10: note:   mismatched types ‘R (Caller::*)(Args ...)’ and ‘main(int, char**)::<lambda(int)>’
   13 |         });
      |          ^
In file included from futures_1.cpp:2:
/usr/local/include/folly/futures/Future.h:1277:8: note: candidate: ‘template<class Arg> auto folly::Future<T>::then(folly::Executor::KeepAlive<>, Arg&&) && [with Arg = Arg; T = int]’ <deleted>
 1277 |   auto then(Executor::KeepAlive<> x, Arg&& arg) && = delete;
      |        ^~~~
/usr/local/include/folly/futures/Future.h:1277:8: note:   template argument deduction/substitution failed:
futures_1.cpp:13:10: note:   candidate expects 2 arguments, 1 provided
   13 |         });
      |          ^
In file included from /usr/local/include/folly/futures/Future.h:2667,
                 from futures_1.cpp:2:
/usr/local/include/folly/futures/Future-inl.h:1218:14: note: candidate: ‘folly::Future<folly::Unit> folly::Future<T>::then() && [with T = int]’
 1218 | Future<Unit> Future<T>::then() && {
      |              ^~~~~~~~~
/usr/local/include/folly/futures/Future-inl.h:1218:14: note:   candidate expects 0 arguments, 1 provided
make: *** [Makefile:5: futures_1] Error 1

**Comment by yfeldblum** [comment]
Try replacing the `.then` with `.thenValue`.

**Comment by lexuscrossover** [comment]
@yfeldblum thank you!  changing to .thenValue() works.  However, instead of doing promise.getFuture().thenValue(), I changed to the following:

```
    folly::Future<int> future = promise.getFuture();

    future.thenValue([](int value){
        cout << value;
    });
```

I then got this error: error: no matching member function for call to 'thenValue'

If I could do promise.getFuture().thenValue(),  shouldn't I be able to do future.thenValue()? 

Thank you very much for your help in advance!

**Comment by lexuscrossover** [comment]
to answer my own question, instead of using future.thenValue, one would use std::move(future) to get a rvalue, thenValue() would work.  My firm actually uses the folly library from 2018.  future.then() works.  Not sure if the most recent folly library would break code written against a previous version of folly ...
