### ISSUE TITLE
Folly build failed with error C3861

### ISSUE THREAD

**Issue by LilyWangL** [facebook/folly#1412]
I am a member of Microsoft VCPKG team. In an internal version of Visual Studio, folly build failed with error C3861:
```
buildtrees\folly\src\46d6707604-9be5d31935.clean\folly/GroupVarint.h(265): error C3861: '__builtin_clz': identifier not found
buildtrees\folly\src\46d6707604-9be5d31935.clean\folly/GroupVarint.h(301): warning C5054: operator '+': deprecated between enumerations of different types
buildtrees\folly\src\46d6707604-9be5d31935.clean\folly/GroupVarint.h(364): warning C5054: operator '+': deprecated between enumerations of different types
buildtrees\folly\src\46d6707604-9be5d31935.clean\folly/GroupVarint.h(453): error C3861: '__builtin_clzll': identifier not found
```
This issue due to an internal change in compiler. For fixing this issue, we need to remove `#if !defined(_MSC_VER) || (_MSC_VER < 1923)` of `Builtins.h`.
I have added a patch to solve this problem temporarily on VCPKG, the related PR https://github.com/microsoft/vcpkg/pull/12419. I submit this issue and want to fix this error on upstream.

**Comment by Orvid** [comment]
These builtins were previously disabled in https://github.com/facebook/folly/commit/6e58e89bf1a23f37c29ca8e4d1ef42b4e54408b0 due to the being implemented in a newer version of the compiler. Did the version where they were supposed to be enabled change?

**Comment by QuellaZhang** [comment]
Yes, Folly enabled use of these intrinsics after we(the MSVC team) added them, but in the latest MSVC version, we've ripped them out, we also encountered this issue when testing internally Folly at MSVC.
