### ISSUE TITLE
build folly on ubuntu14.04 using gcc5 meet error

### ISSUE THREAD

**Issue by minicaptain** [facebook/folly#1413]
hi, when i build the folly on ubuntu 14.04 using gcc5 meet the following error:
/usr/include/c++/5/bits/basic_string.tcc: In instantiation of 'static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&, std::forward_iterator_tag) [with _FwdIterator = const char*; _CharT = char; _Traits = std::char_traits<char>; _Alloc = folly::reentrant_allocator<char>]':
/usr/include/c++/5/bits/basic_string.h:4235:30:   required from 'static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct_aux(_InIterator, _InIterator, const _Alloc&, std::__false_type) [with _InIterator = const char*; _CharT = char; _Traits = std::char_traits<char>; _Alloc = folly::reentrant_allocator<char>]'
/usr/include/c++/5/bits/basic_string.h:4256:27:   required from 'static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&) [with _InIterator = const char*; _CharT = char; _Traits = std::char_traits<char>; _Alloc = folly::reentrant_allocator<char>]'
/usr/include/c++/5/bits/basic_string.tcc:647:31:   required from 'std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = folly::reentrant_allocator<char>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]'
/home/sdev/ddx/algo/folly/folly/experimental/symbolizer/ElfCache.h:62:52:   required from here
/usr/include/c++/5/bits/basic_string.tcc:568:28: error: no matching function for call to 'folly::reentrant_allocator<char>::reentrant_allocator()'
  if (__beg == __end && __a == _Alloc())

pls help me.

**Comment by minicaptain** [comment]
I suppose this error is caused by gcc version? but i tried the gcc8、gcc9 all met the same error.

**Comment by oerdnj** [comment]
I see that reading is still the hardest discipline of them all: https://github.com/facebook/folly#build-notes

> folly requires a version of boost compiled with C++14 support.

Also Ubuntu 14.04 LTS reached end-of-life more than year ago, you should upgrade instead.

**Comment by yfeldblum** [comment]
This is caused by using the legacy ABI with libstdc++. Switching to the current ABI ought to address this issue.

https://developers.redhat.com/blog/2015/02/05/gcc5-and-the-c11-abi/

This is because one place in folly uses `folly::reentrant_allocator`, which is not default-constructible, as the allocator for `std::basic_string` - and the legacy libstdc++ ABI implementation of `std::basic_string` is broken here.
