### ISSUE TITLE
Read data from an IOBuf

### ISSUE THREAD

**Issue by GitAntoinee** [facebook/folly#1417]
Hello,

I am new with folly and I need to read an unsigned short from an `IOBuf` but I cannot find anything.

Do I need to create a function to read an unsigned short from any `IOBuf` or it already exists?

**Comment by afrind** [comment]
Create a Cursor (https://github.com/facebook/folly/blob/master/folly/io/Cursor.h) around the IOBuf, and then use readBE<uint16_t>().
