### ISSUE TITLE
Folly built failed with boost 1.58

### ISSUE THREAD

**Issue by Lunkeqing** [facebook/folly#1419]
It shows that the build process need boost file "fcontext.hpp" from  boost::context::detail. Somehow i found the file in my station is under "boost/context/". Is it necessary to upgrade boost? or have any other way to solve this problem?

In file included from /home/lunke/software/folly/folly/fibers/Fiber.h:28:0,
                 from /home/lunke/software/folly/folly/fibers/Baton-inl.h:17,
                 from /home/lunke/software/folly/folly/fibers/Baton.h:304,
                 from /home/lunke/software/folly/folly/futures/Future-inl.h:37,
                 from /home/lunke/software/folly/folly/futures/Future.h:2653,
                 from /home/lunke/software/folly/folly/executors/TimekeeperScheduledExecutor.h:23,
                 from /home/lunke/software/folly/folly/executors/TimekeeperScheduledExecutor.cpp:17:
/home/lunke/software/folly/folly/fibers/BoostContextCompatibility.h:19:45: fatal error: boost/context/detail/fcontext.hpp: No such file or directory
compilation terminated.
CMakeFiles/folly_base.dir/build.make:963: recipe for target 'CMakeFiles/folly_base.dir/folly/executors/TimekeeperScheduledExecutor.cpp.o' failed
make[2]: *** [CMakeFiles/folly_base.dir/folly/executors/TimekeeperScheduledExecutor.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....

**Comment by yfeldblum** [comment]
What version of boost-context have you got? Folly as of recently requires >= 1.61.

**Comment by Lunkeqing** [comment]
> What version of boost-context have you got? Folly as of recently requires >= 1.61.

Thanks for your answer, I had later installed an old version of folly, and it is all fine for me.
