### ISSUE TITLE
Document reliance of Folly on /Zc:__cplusplus in MSVC

### ISSUE THREAD

**Issue by asklar** [facebook/folly#1453]
MSVC doesn't provide an accurate value for __cplusplus by default (see blog https://devblogs.microsoft.com/cppblog/msvc-now-correctly-reports-__cplusplus/).

Portability.h uses __cplusplus values to determine e,g, whether to define `FOLLY_HAS_STRING_VIEW`
So in order for MSVC to take advantage of this you have to add the following to your vcxproj:
```xml
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalOptions>/Zc:__cplusplus %(AdditionalOptions)</AdditionalOptions>
    </ClCompile>
  </ItemDefinitionGroup>
```

**Comment by yfeldblum** [comment]
Folly uses `_MSVC_LANG` under MSVC nowadays.

See: https://github.com/facebook/folly/blob/v2024.06.17.00/folly/Portability.h#L24-L28, https://github.com/facebook/folly/commit/fe3cce9b63bd94c19adb20b353fc34856b9f1996.
