### ISSUE TITLE
Folly CI is broken

### ISSUE THREAD

**Issue by asklar** [facebook/folly#1456]
Looks like the CI loops have been broken for a while on all platforms:
- tests are failing
- it doesn't build on mac, maybe other platforms either?
- it isn't clear what it's using to build in windows but it isn't how windows devs would consume it (which is via a Visual Studio project)
- tests aren't covering important cases like making sure builtins.h can build (see #1450  and my naïve attempt in #1451 )

**Comment by asklar** [comment]
CC @Orvid

**Comment by Orvid** [comment]
The test failures are known, and I need to build out a system to allow disabling certain tests for open source (we have a mechanism to disable individual tests internally, but only have the ability to disable at the file level in open source right now). The vast majority of these failures are the result of tests being dependent on timing. These tests are 

The mac build error is known and we're working on a fix.

Windows builds use CMake, just as every other platform. The CMake build was actually originally written for Windows, with the rest added on top of it. We use a different build system (Buck) internally, and also run the CMake build to ensure we don't break it.

Tests cover most things, but the portability headers are one of the largest places lacking distinct tests, as the portability headers were only implementing things used in other parts of Folly, so were already being indirectly tested and I didn't really want to write a bunch of tests for `strcasecmp`, `open`, and a bunch of other libc functions. Over time parts of Folly have been refactored and written against more standard C++ functions, reducing the need for various parts of the portability headers, and also reducing coverage as a result.

**Comment by asklar** [comment]
thanks @Orvid . 
- re: portability tests - do you have any thoughts on just including builtins.h to the portability test to catch issues like missing `__builtin_clz` etc. / is there more that should be done ?
- re: build system, would you be open to me adding a vsbuild action in github to validate that a simple project continues to build as folly evolves? This would have caught the break introduced by the removal of the version guards in builtins.h

**Comment by Orvid** [comment]
In reality we should probably just write the tests properly, but adding the include is fine for now.

We're already building against MSVC 2017 albeit with ninja, we should probably add a build for MSVC 2019 and, if possible the 2019 preview as well.

**Comment by chenrui333** [comment]
yeah, on mac side, it is broken with the most two recent releases. 
https://github.com/Homebrew/homebrew-core/pull/61132
https://github.com/Homebrew/homebrew-core/pull/61476

**Comment by Orvid** [comment]
https://github.com/facebook/folly/commit/802e8f7a0c345ce8743ec06c8197d125875349d1 should have been the fix for the Mac failures, but it looks like some changes to the stack trace infrastructure has landed in the meantime to cause other issues :(
