### ISSUE TITLE
Installation Err on RedHat Linux 6.5

### ISSUE THREAD

**Issue by puffCN** [facebook/folly#147]
I'm installing folly on RedHat Enterprise Linux 6.5

While installing I got the following ERROR, Can anyone kindly help me out ? Did I miss some of  the dependencies ?

relocation R_X86_64_32S against '.rodata' can not be used when making a shared object; recompile with -fPIC /usr/local/lib/../lib64/libiberty.a: could not read symbols: Bad Value

![2015-03-12_093112](https://cloud.githubusercontent.com/assets/4182430/6610461/95000bac-c89a-11e4-8b5e-2f5f20bac2e4.png)

**Comment by djwatson** [comment]
libiberty on your system appears to not be compiled with PIC support?  We're happy to take a patch to fix it if you have one, but we only have cycles to verify that ubuntu works out of the box.
