### ISSUE TITLE
Is it possible to use folly fibers with thread pool

### ISSUE THREAD

**Issue by dmitryikh** [facebook/folly#1473]
Is it possible to use folly fibers with thread pool?

So called M:N scheduling (M fibers to N OS threads). Could you please provide a short example.

Thanks!

**Comment by orrorcol** [comment]
The same question

**Comment by yfeldblum** [comment]
Fibers are N:1 with `EventBase`, and each `EventBase` is driven by 1 thread. Fibers do not migrate from one `EventBase` (and thread) to another.
