### ISSUE TITLE
Build Failure if liburing is Installed

### ISSUE THREAD

**Issue by jmccl** [facebook/folly#1486]
I’ve included a patch at the end of this issue that fixes things. If you want I’ll put in a pull request, but there are a number of ways to deal with this and my approach may not be your preferred path.

The first error is this.

> /folly/folly/experimental/io/IoUringBackend.cpp:28:1: error: C++ requires a type specifier for all declarations
> DEFINE_int64(

(Note that *IoUringBackend.cpp* only builds if [liburing](https://github.com/axboe/liburing) is installed; see CMakeLists.txt.)

The problem is that *DEFINE_int64* isn’t defined. I believe this relatively recent change caused this: https://github.com/facebook/folly/commit/d6ed060efe7f9ea291fc78362d7f83c1c197f219. Including an appropriate header fixes things

The second problem is this.

> /folly/folly/experimental/io/SimpleAsyncIO.cpp:29:2: error: #error "Cannot build without at least one of AsyncIO.h and IoUring.h"
>  29 | #error "Cannot build without at least one of AsyncIO.h and IoUring.h"

SimpleAsyncIO.cpp also doesn’t build unless liburing is installed for the same reasons. This one is just a typo in this relatively recently introduced file.

---

```
index bfe752d8d..db8345e6a 100644
--- a/folly/experimental/io/IoUringBackend.cpp
+++ b/folly/experimental/io/IoUringBackend.cpp
@@ -15,6 +15,7 @@
  */
 
 #include <folly/experimental/io/IoUringBackend.h>
+#include <folly/portability/GFlags.h>
 #include <folly/Likely.h>
 #include <folly/String.h>
 #include <folly/container/F14Map.h>
diff --git a/folly/experimental/io/SimpleAsyncIO.cpp b/folly/experimental/io/SimpleAsyncIO.cpp
index 8d8f22af9..2baef6eac 100644
--- a/folly/experimental/io/SimpleAsyncIO.cpp
+++ b/folly/experimental/io/SimpleAsyncIO.cpp
@@ -25,7 +25,7 @@
 #include <folly/experimental/io/IoUring.h>
 #endif
 
-#if !defined(AIO_SUPPORTED) && !defined(IOURING_SUPORTED)
+#if !defined(AIO_SUPPORTED) && !defined(IOURING_SUPPORTED)
 #error "Cannot build without at least one of AsyncIO.h and IoUring.h"
 #endif
 
```

**Comment by yfeldblum** [comment]
Would you care to turn this into a PR?
