### ISSUE TITLE
build with boost1.70 No suitable boost_context variant has been identified

### ISSUE THREAD

**Issue by leaout** [facebook/folly#1491]
OS centos 7.5
boost 1.70

step 
mkdir _build && cd _build && cmake ..

error :

-- Found Boost 1.70.0 at /usr/local/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET REQUIRED COMPONENTS context;filesystem;program_options;regex;system;thread
-- Found boost_headers 1.70.0 at /usr/local/lib/cmake/boost_headers-1.70.0
-- Found boost_context 1.70.0 at /usr/local/lib/cmake/boost_context-1.70.0
-- No suitable boost_context variant has been identified!
--   libboost_context.so.1.70.0 (shared, BUILD_SHARED_LIBS not ON, set Boost_USE_STATIC_LIBS=OFF to override)
--   libboost_context.a (static, Boost_USE_STATIC_LIBS=OFF)
CMake Error at /usr/local/lib/cmake/Boost-1.70.0/BoostConfig.cmake:95 (find_package):
  Found package configuration file:

    /usr/local/lib/cmake/boost_context-1.70.0/boost_context-config.cmake

  but it set boost_context_FOUND to FALSE so package "boost_context" is
  considered to be NOT FOUND.  Reason given by package:

  No suitable build variant has been found.

Call Stack (most recent call first):
  /usr/local/lib/cmake/Boost-1.70.0/BoostConfig.cmake:124 (boost_find_dependency)
  /usr/local/share/cmake-3.16/Modules/FindBoost.cmake:443 (find_package)
  CMake/folly-deps.cmake:38 (find_package)
  CMakeLists.txt:118 (include)

-- Configuring incomplete, errors occurred!
See also "/root/pro/folly-2020.11.16.00/_build/CMakeFiles/CMakeOutput.log".
See also "/root/pro/folly-2020.11.16.00/_build/CMakeFiles/CMakeError.log".
localhost:/root/pro/folly-2020.11.16.00/_build

**Comment by jtcheng** [comment]
Reference to issue: https://github.com/Microsoft/vcpkg/issues/5936
I fix this as below:
```
diff --git a/CMake/folly-deps.cmake b/CMake/folly-deps.cmake
index e0e02c0..7751887 100644
--- a/CMake/folly-deps.cmake
+++ b/CMake/folly-deps.cmake
@@ -35,6 +35,7 @@ else()
 endif()
 set(Boost_USE_STATIC_LIBS "${FOLLY_BOOST_LINK_STATIC}")

+set(Boost_NO_BOOST_CMAKE ON)
 find_package(Boost 1.51.0 MODULE
   COMPONENTS
     context
```

**Comment by leaout** [comment]
@jtcheng thanks bro!  it works now.

**Comment by xiedeacc** [comment]
meet same problem, but failed use above solution

**Comment by xiedeacc** [comment]
fixed by set(Boost_COMPILER vc143)
