### ISSUE TITLE
Runtime error with hazptr: linked both statically and dynamically into this executable

### ISSUE THREAD

**Issue by huyi** [facebook/folly#1495]
I use "cmake -G Ninja .. -DCMAKE_BUILD_TYPE=Debug" for config folly libs, ninja -j 9 for building, and then use in my app as static lib, but it crash, and message is

ERROR: something wrong with flag 'folly_hazptr_use_executor' in file '..\folly\synchronization\Hazptr.cpp'.  One possibility: file '..\folly\synchronization\Hazptr.cpp' is being linked both statically and dynamically into this executable.

I noticed that when linking, the linker says
LINK : warning LNK4217:符号“?FLAGS_folly_hazptr_use_executor@fLB@@3_NA (bool fLB::FLAGS_folly_hazptr_use_executor)”(在“ folly.lib(Hazptr.cpp.obj)”中定义)已由“folly.lib(Request.cpp.obj)”(函数“"private: void __cdecl folly::hazptr_domain<struct std::atomic>::check_threshold_and_reclaim(void)" (?check_threshold_and_reclaim@?$hazptr_domain@Uatomic@std@@@folly@@AEAAXXZ)”中)导入

It sound like something was multi imported, btw, I use vcpkg to install depended gflags lib as dll, (folly was complied as static) 

Please help me to fix this crash?

**Comment by huyi** [comment]
I fixed, gflags should also install as statics, vcpkg should fix this issue.

**Comment by Ruwen14** [comment]
Hey @huyi, 

how did you manage to fix linking to gflags statically, as I’m experiencing the same issue?
