### ISSUE TITLE
After installation Flipper-Folly, due to dual OpenSSL lib application crash on iOS platform. 

### ISSUE THREAD

**Issue by gavaliswapnil** [facebook/folly#1498]
I have written my own node module. its contain a static library. This static library contains OpenSSL lib. I have installed flipper with my node module in the application. After running the application is crashing in OpenSSL code written in your library. 
My OpenSLL lib version is 1.1.0f and yours is 1.0.2u. 
Kindly update your OpenSSL version to  1.1.0 series to remove conflicts.

**Comment by Orvid** [comment]
Folly does not build openssl, and we don't maintain flipper-folly. Please file this issue directly against flipper's folly build.
