### ISSUE TITLE
Linking problem with UninitializedMemoryHacks.h

### ISSUE THREAD

**Issue by alexander-nadel** [facebook/folly#1502]
Hi,

I've written the following very simple program for resizing an std::vector<int> without initialization using UninitializedMemoryHacks.h:

-------------------------
    #include <vector>
    #include "UninitializedMemoryHacks.h"
    
    int main(int argc, char** argv)
    {
	    std::vector<int> v;
	    
	    folly::resizeWithoutInitialization(v, 10000);
			    
	    return 0;
    }
    
    FOLLY_DECLARE_VECTOR_RESIZE_WITHOUT_INIT_IMPL(int)
-------------------------

Unfortunately, I'm getting a linking error with gcc 10.1 (I've also tried older gcc's):

-------------------------
g++ aux.cpp

.../gcc/10.1.0/.bin/../lib/gcc/x86_64-pc-linux-gnu/10.1.0/../../../../x86_64-pc-linux-gnu/bin/ld: .../gcc_10.1/tmp/ccWJVcJE.o: in function `void folly::detail::unsafeVectorSetLargerSize<int>(std::vector<int, std::allocator<int> >&, unsigned long)':
aux.cpp:(.text._ZN5folly6detail25unsafeVectorSetLargerSizeIiEEvRSt6vectorIT_SaIS3_EEm[_ZN5folly6detail25unsafeVectorSetLargerSizeIiEEvRSt6vectorIT_SaIS3_EEm]+0x1f): undefined reference to `folly::detail::unsafeVectorSetLargerSizeImpl(std::vector<int, std::allocator<int> >&, unsigned long)'
collect2: error: ld returned 1 exit status
-------------------------

What am I missing?

Thanks,
  Alex.

**Comment by nbronson** [comment]
It should be `FOLLY_DECLARE_VECTOR_RESIZE_WITHOUT_INIT(int)` (no `_IMPL`)

**Comment by alexander-nadel** [comment]
Many thanks!
