### ISSUE TITLE
Update OpenSSL-Universal  to latest version 1.1.180

### ISSUE THREAD

**Issue by ghasemikasra39** [facebook/folly#1506]
You're using `OpenSSL-Universal 1.0.2.20` which causes this [issue](https://github.com/krzyzanowskim/OpenSSL/issues/103#issuecomment-751509834). This version of `OpenSSL-Universal` is outdated. I tried to update this package but it rejects as `OpenSSL-Universal` is a dependency of your package. Your package is automatically installed when creating any new React Native project. Currently the only solution is to delete your package completely to solve this issue. 

environment
```
System:
    OS: macOS 11.0.1
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 117.21 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.3 - ~/.nvm/versions/node/v14.15.3/bin/node
    Yarn: 1.22.4 - ~/Documents/youpendo/youpendo-app-bareworkflow/node_modules/.bin/yarn
    npm: 6.14.9 - ~/.nvm/versions/node/v14.15.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_275 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: ^4.8.0 => 4.13.0
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
```

**Comment by atulmy** [comment]
@ghasemikasra39 is there a work around?

I'm getting following issue with React Native iOS build:

/app/ios/Pods/OpenSSL-Universal/ios/lib/libcrypto.a(cryptlib.o), building for iOS Simulator, but linking in object file built for iOS, file '/app/ios/Pods/OpenSSL-Universal/ios/lib/libcrypto.a' for architecture arm64

**Comment by lsale** [comment]
Same for me. I'm unable to compile my react native project for the iOS Simulator because of this. Is anyone able to look into this issue, please? 

It seems the `OpenSSL-Universal` version fixing this is `>= 1.1.180`

**Comment by Orvid** [comment]
The Folly devs do not maintain any podspecs for folly, please file this issue against whatever repo you got the podspec from, in this case likely react native.

**Comment by ghasemikasra39** [comment]
Dear @Orvid 
Can you please explain, what do you mean by `The Folly devs do not maintain any podspecs for folly` ? What do you mean by `podspecs` ?

**Comment by Orvid** [comment]
If I'm understanding correctly, you're trying to build folly via cocoapods, which we don't directly support. The folly devs only directly support building with CMake.
