### ISSUE TITLE
folly 2020.12.{21,28}.00 build failure

### ISSUE THREAD

**Issue by chenrui333** [facebook/folly#1507]
Looks like after [this commit](https://github.com/facebook/folly/commit/e6955f4dc06d6c77922ca1c7005819313aed8d71), folly failed to build.

```
  "___asan_region_is_poisoned", referenced from:
      folly::detail::asan_region_is_poisoned_(void*, unsigned long) in SanitizeAddress.cpp.o
ld: symbol(s) not found for architecture x86_64
```

full build log in here, https://github.com/Homebrew/homebrew-core/runs/1618875877
relates to https://github.com/Homebrew/homebrew-core/pull/67424

**Comment by dtrodrigues** [comment]
It's failing on the 2021.01.18 tag as well: https://github.com/Homebrew/homebrew-core/pull/69391
```
/tmp/folly-20210120-79940-1hxar6w/folly-2021.01.18.00/folly/support/tests/main.cpp:98:20: error: invalid token in expression
  __asm__ volatile("int $3"); // Auto breakpoint in gdb.
                   ^
<inline asm>:1:6: note: instantiated into assembly here
        int $3
            ^
/tmp/folly-20210120-79940-1hxar6w/folly-2021.01.18.00/folly/support/tests/main.cpp:98:20: error: invalid operand
  __asm__ volatile("int $3"); // Auto breakpoint in gdb.
                   ^
<inline asm>:1:6: note: instantiated into assembly here
        int $3
            ^
2 errors generated.
```

**Comment by Orvid** [comment]
We have a diff up internally to fix the inline asm. A test accidentally got included in the main library :(

We had a fix up to try to fix the primary error but that doesn't seem to be panning out so I'm just going to give up on doing anything smart and just `#ifdef` it to unbreak things.

**Comment by Orvid** [comment]
Asm issue should be fixed by 3fa09cb1c576bad42ce57c7380d78935f4c0dcec

asan issue should hopefully be fixed by 5b44809e44bbae14b309ef203dd2581321a4191f

**Comment by dtrodrigues** [comment]
I don't believe https://github.com/facebook/folly/commit/3fa09cb1c576bad42ce57c7380d78935f4c0dcec resolves the asm issue on Apple Silicon since ` __asm__ volatile("int $3");` is not valid on ARM.

**Comment by dtrodrigues** [comment]
Log from the build after the patch was applied: https://github.com/Homebrew/homebrew-core/pull/69391/checks?check_run_id=1746019815#step:7:681

**Comment by Orvid** [comment]
The secondary effect of 3fa09cb should be that the file is no longer compiled in open source as a result of being in a `test` directory rather than `tests`. (we auto-exclude files in `/test/` from the main library glob) That run does not appear to have 3fa09cb in it, as it's still referring to `tests`.

I've also just created the v2021.01.18.01 release with the pair of patches.

**Comment by dtrodrigues** [comment]
You're right, I'm not sure why the patch didn't apply during that run.

I tested the new release locally and it built and the homebrew test succeeded too, so I've submitted https://github.com/Homebrew/homebrew-core/pull/69502. Thanks!

**Comment by dtrodrigues** [comment]
The macOS build is passing now in homebrew. This issue can be closed.

**Comment by chenrui333** [comment]
Closing the issue, thanks all!!
