### ISSUE TITLE
A question about resizeWithoutInitialization(v,s) in UninitializedMemoryHacks.h: does it allocate precisely s entries?

### ISSUE THREAD

**Issue by alexander-nadel** [facebook/folly#1509]
Hi,

A question: the standard v.resize(s), if s > v.size(), allocates more memory than s (e.g., in VS19, the capacity grows geometrically as follows:  const size_type _Geometric = _Oldcapacity + _Oldcapacity / 2;).

resizeWithoutInitialization doesn't seem to follow suit. It seems that resizeWithoutInitialization(v, s) allocates precisely **s** entries. 

Is my observation correct?

Thanks,
  Alex.

**Comment by nbronson** [comment]
If s > v.capacity(), resizeWithoutInitialization uses reserve(s) to grow the vector. On the platforms I've looked at this grows it to the exact size, as you hypothesize. If you'd like to use a different strategy you can call reserve yourself, then call resizeWithoutInitialization. resizeWithoutInitialization takes care to never decrease the capacity.

**Comment by alexander-nadel** [comment]
I see, thanks for your reply!
