### ISSUE TITLE
Master build broken on Linux with ninja

### ISSUE THREAD

**Issue by chaiken** [facebook/folly#1511]
Similar to #604 with Windows.  Folly source is at commit c7166a677 with commit ee1e6c7b7 reverted (because it breaks my build and is Android-specific).

Build system:
`$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux bullseye/sid"

$ uname -a
Linux version 5.9.0-3-amd64 (debian-kernel@lists.debian.org) (gcc-10 (Debian 10.2.0-17) 10.2.0, GNU ld (GNU Binutils for Debian) 2.35.1) #1 SMP Debian 5.9.9-1 (2020-11-19)

$ g++ --version
g++ (Debian 10.2.1-3) 10.2.1 20201224
`
Happy to upload log files if that helps.  commit a7001e5c7 that closed #604 is applied, but is MSVC-specific.

**Comment by Orvid** [comment]
How is it broken? What error are you seeing?

**Comment by chaiken** [comment]
On 2021-01-03 14:19, Orvid King wrote:

> How is it broken? What error are you seeing?

The build terminates with the same error message as in issue #604: 

ninja: error: manifest 'build.ninja' still dirty after 100 tries 

> 

Thus Linux builds have the same failure mode, and presumably need a fix
similar to commit a7001e5c, which fixes the problem only for MSVC. 

Thanks for publishing your libraries, 

Alison Chaiken

---
Alison Chaiken                   alison@she-devel.com
http://she-devel.com
what a jolly bad show if all you ever do is business you don't like --
Ian Dury

**Comment by chenrui333** [comment]
it failed with osx build for the last two releases as well, #1507

**Comment by chenrui333** [comment]
sorry, looks like I am using cmake, never mind.

**Comment by yfeldblum** [comment]
Closing due to age.
