### ISSUE TITLE
Folly failed to build due to error C2065 C2143 C4430 and C2059 on windows with MSVC

### ISSUE THREAD

**Issue by spacelg** [facebook/folly#1515]
Hi All,

Folly failed to build due to error C2065 C2143 C4430 and C2059 on windows with MSVC. It can be reproduced on latest commit and it failed to compile ..\folly\support\tests\main.cpp due to error **C2065: '__asm__': undeclared identifier** .  I guess it may be the failure caused by this commit [118e914 ](https://github.com/facebook/folly/commit/118e914136176e7a91b3938b7ed4e778e959b371). Could you please help take a look at this? Thanks in advance!

Environment
VCPKG(latest revision from github) + VS 2019 + Windows Server 2016

Repro steps:
1. Open X64 native tools command prompt for VS2019
2. git clone https://github.com/Microsoft/vcpkg F:\VCPKG\src
3. cd F:\VCPKG\src
4. bootstrap-vcpkg.bat
5. set path=%cd%;%path%
6. vcpkg install folly:x64-windows --head

[install-x64-windows-dbg-out.log](https://github.com/facebook/folly/files/5828275/install-x64-windows-dbg-out.log)

Actual result:
F:\VCPKG\src\buildtrees\folly\src\head\master-ade9d52cdb.clean\folly\support\tests\main.cpp(98): error C2065: '__asm__': undeclared identifier
F:\VCPKG\src\buildtrees\folly\src\head\master-ade9d52cdb.clean\folly\support\tests\main.cpp(98): error C2143: syntax error: missing ';' before 'volatile'
F:\VCPKG\src\buildtrees\folly\src\head\master-ade9d52cdb.clean\folly\support\tests\main.cpp(98): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
F:\VCPKG\src\buildtrees\folly\src\head\master-ade9d52cdb.clean\folly\support\tests\main.cpp(98): error C2059: syntax error: 'string'

**Comment by shixiao** [comment]
Ah, sorry about that. Will send a patch soon. I didn't have an MSVC environment handy so I missed this.
