### ISSUE TITLE
Build fail on mac air M1 silicon

### ISSUE THREAD

**Issue by kevinko1788** [facebook/folly#1518]
I am having a problem building folly on my mac air M1 silicon. I'm not entire sure what is the problem.

Tried to search Google but I couldn't find something related to folly.

Help much appreciated!

MacOS : 11.1
gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: arm64-apple-darwin20.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

Error message:
[511/744] Building CXX object CMakeFi...folly/container/test/F14MapTest.cpp.o
ninja: build stopped: subcommand failed.
Command '['/private/var/folders/98/1jwhb7sd78z_rxdx_92r16xh0000gn/T/fbcode_builder_getdeps-ZUsersZtsenghuikoZprojectsZfollyZbuildZfbcode_builder/installed/cmake-HZFeaek3U5xfYR0lhfCgPqzlAX23b8VgcEeaymt4TGI/bin/cmake', '--build', '/private/var/folders/98/1jwhb7sd78z_rxdx_92r16xh0000gn/T/fbcode_builder_getdeps-ZUsersZtsenghuikoZprojectsZfollyZbuildZfbcode_builder/build/folly', '--target', 'install', '--config', 'Release', '-j', '4']' returned non-zero exit status 1.
!! Failed

**Comment by Orvid** [comment]
This doesn't actually help us (we don't currently have an M1 mac to test with, and as far as I know, via homebrew, Folly should build fine on M1 macs), what is the actual build error? The error you provided effectively only says "build failed".

**Comment by 77Bala7790** [comment]
brew install folly in M1 chip MAC works fine. But it showed error like path to openssl is not set properly. May be Kevin would also have the same error. Not sure. Cross my hands and waiting for the error he got. I will post the exact error in a while.

**Comment by Orvid** [comment]
Any update on the actual error message?

**Comment by kevinko1788** [comment]
I was able to build with homebrew as you suggested above.
Still not sure how/where I can get the error message. Thus, I will close this for now.
