### ISSUE TITLE
exception_wrapper crash

### ISSUE THREAD

**Issue by stevezhou6** [facebook/folly#1519]
`
AsyncSocket::ReadResult
AsyncSSLSocket::performRead(void** buf, size_t* buflen, size_t* offset) {
      auto errError = ERR_get_error();
      const char* err_func = ERR_func_error_string(errError);
      const char* err_reason = ERR_reason_error_string(errError);
      VLOG(6) << "AsyncSSLSocket(fd=" << fd_ << ", "
              << "state=" << state_ << ", "
              << "sslState=" << sslState_ << ", "
              << "events=" << std::hex << eventFlags_ << "): "
              << "bytes: " << bytes << ", "
              << "error: " << error << ", "
              << "errno: " << errno << ", "
              << "func: " << (err_func ? err_func : "") << ", "
              << "reason: " << (err_reason ? err_reason : "");
      return ReadResult(
          READ_ERROR,
          std::make_unique<SSLException>(error, errError, bytes, errno));
}

void AsyncSocket::invokeConnectErr(const AsyncSocketException& ex) {
  VLOG(5) << "AsyncSocket(this=" << this << ", fd=" << fd_
          << "): connect err invoked with ex: " << ex;
}

namespace exception_wrapper_detail {
template <class Ex>
Ex&& dont_slice(Ex&& ex) {
  assert(typeid(ex) == typeid(std::decay_t<Ex>) ||
       !"Dynamic and static exception types don't match. Exception would "
        "be sliced when storing in exception_wrapper.");
  return std::forward<Ex>(ex);
}
} // namespace exception_wrapper_detail

template <
    class Ex,
    class Ex_,
    FOLLY_REQUIRES_DEF(Conjunction<
                       exception_wrapper::IsStdException<Ex_>,
                       exception_wrapper::IsRegularExceptionType<Ex_>>::value)>
inline exception_wrapper::exception_wrapper(Ex&& ex)
    : exception_wrapper{
          PlacementOf<Ex_>{},
          in_place_type<Ex_>,
          exception_wrapper_detail::dont_slice(std::forward<Ex>(ex))} {}

 assert(typeid(ex) == typeid(std::decay_t<Ex>)
`

**Comment by yfeldblum** [comment]
If `exception_wrapper` is constructed with a reference to an exception, it must be with the most-derived version of that reference, not with a reference to a base class.

**Comment by stevezhou6** [comment]
1. The following code causes the program to crash.
   ``` c++
      std::unique_ptr<const folly::AsyncSocketException> exception =
        std::make_unique<folly::SSLException>(5, 0x3c, 0, 0);
      VLOG(1) << "RunTaskSync thread " << *exception;

    crash at
    namespace exception_wrapper_detail {
   template <class Ex>
   Ex&& dont_slice(Ex&& ex) {
   assert(typeid(ex) == typeid(std::decay_t<Ex>) ||
       !"Dynamic and static exception types don't match. Exception would "
        "be sliced when storing in exception_wrapper.");
       return std::forward<Ex>(ex);
    }
   ``` 
2.  The following code is correct.
      ``` c++
        std::unique_ptr<const folly::SSLException> exception =
        std::make_unique<folly::SSLException>(5, 0x3c, 0, 0);
        VLOG(1) << "RunTaskSync thread " << *exception;
       ``` 
3.  But there is the same error in your AsyncSSLSocket that causes the program to crash.
     An exception of type SSLException is created in AsyncSSLSocket::performRead.
          ``` c++
        return ReadResult(
        READ_ERROR,
        std::make_unique<SSLException>(SSLError::CLIENT_RENEGOTIATION));
       ``` 
     In AsyncSocket::invokeConnectErr (const AsyncSocketException& ex), 
     it uses an AsyncSocketException exception, which triggers 
      assert (typeid (ex) = = typeid (std::decay_t < Ex >) 
      when it calls VLOG (5) to print the log.

    In AsyncSSLSocket, if it throws a SSLException exception, it will cause the program to crash. The crash stack is as follows.
   
   folly::exception_wrapper_detail::dont_slice<folly::AsyncSocketException const &>(const folly::AsyncSocketException & ex) 行 381	C++
folly::exception_wrapper::exception_wrapper<folly::AsyncSocketException const &,folly::AsyncSocketException,437>(const folly::AsyncSocketException & ex) 行 395	C++
folly::AsyncSocket::invokeConnectErr(const folly::AsyncSocketException & ex) 行 2986	C++
folly::AsyncSSLSocket::invokeConnectErr(const folly::AsyncSocketException & ex) 行 1366	C++
folly::AsyncSocket::invokeAllErrors(const folly::AsyncSocketException & ex) 行 2792	C++
folly::AsyncSocket::finishFail(const folly::AsyncSocketException & ex) 行 2815	C++
folly::AsyncSocket::failRead(const char * fn, const folly::AsyncSocketException & ex) 行 2848	C++
folly::AsyncSocket::handleRead() 行 2214	C++
folly::AsyncSSLSocket::handleRead() 行 1429	C++
folly::AsyncSocket::ioReady(unsigned short events) 行 1923	C++
folly::AsyncSocket::IoHandler::handlerReady(unsigned short events) 行 1156	C++
folly::EventHandler::libeventCallback(__int64 fd, short events, void * arg) 行 161	C++
