### ISSUE TITLE
build fails on AArch64, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [facebook/folly#1530]
[jw@cn06 folly]$ ./build.sh
Building on {distro=fedora, distro_vers=33, fb=off, os=linux, test=on}
Assessing boost...
Download https://versaweb.dl.sourceforge.net/project/boost/boost/1.69.0/boost_1_69_0.tar.bz2 -> /var/tmp/fbcode_builder_getdeps-ZdataZjwZfollyZbuildZfbcode_builder/downloads/boost-boost_1_69_0.tar.bz2 ...
 downloading 95084544 of 95078138  [Complete in 55.592084 seconds]
Date: Mon, 01 Mar 2021 12:10:41 GMT
Content-Type: application/octet-stream
Content-Length: 95078138
Last-Modified: Wed, 05 Dec 2018 20:46:58 GMT
Connection: close
ETag: "5c083942-5aac6fa"
Server: nginx centminmod
Accept-Ranges: bytes

Extract /var/tmp/fbcode_builder_getdeps-ZdataZjwZfollyZbuildZfbcode_builder/downloads/boost-boost_1_69_0.tar.bz2 -> /var/tmp/fbcode_builder_getdeps-ZdataZjwZfollyZbuildZfbcode_builder/extracted/boost-boost_1_69_0.tar.bz2
Building boost...
---
+ GETDEPS_BUILD_DIR=/var/tmp/fbcode_builder_getdeps-ZdataZjwZfollyZbuildZfbcode_builder/build \
+ GETDEPS_INSTALL_DIR=/var/tmp/fbcode_builder_getdeps-ZdataZjwZfollyZbuildZfbcode_builder/installed \
+ cd /var/tmp/fbcode_builder_getdeps-ZdataZjwZfollyZbuildZfbcode_builder/extracted/boost-boost_1_69_0.tar.bz2/boost_1_69_0 && \
+ /var/tmp/fbcode_builder_getdeps-ZdataZjwZfollyZbuildZfbcode_builder/extracted/boost-boost_1_69_0.tar.bz2/boost_1_69_0/bootstrap.sh \
+      --prefix=/var/tmp/fbcode_builder_getdeps-ZdataZjwZfollyZbuildZfbcode_builder/installed/boost-Y-_GWacxS4qa7TdRAlMvrd27XLwcYB6863g0T2FpeW0
Building Boost.Build engine with toolset gcc...
Failed to build Boost.Build build engine
Consult 'bootstrap.log' for more details
Command '['/var/tmp/fbcode_builder_getdeps-ZdataZjwZfollyZbuildZfbcode_builder/extracted/boost-boost_1_69_0.tar.bz2/boost_1_69_0/bootstrap.sh', '--prefix=/var/tmp/fbcode_builder_getdeps-ZdataZjwZfollyZbuildZfbcode_builder/installed/boost-Y-_GWacxS4qa7TdRAlMvrd27XLwcYB6863g0T2FpeW0']' returned non-zero exit status 1.
!! Failed
[jw@cn06 folly]$

**Comment by Orvid** [comment]
This is a build failure in boost, not folly. I recommend building boost separately. What failure is logged in `boostrap.log`?

**Comment by LutzWeischerFujitsu** [comment]
Where is 'bootstrap.log' located? Shouldn't 'sudo yum install -y boost boost-devel' be sufficient?

**Comment by Orvid** [comment]
Installing the dependencies is good enough, but you need to build directly via cmake not via the build script as the build script doesn't use any system dependencies

**Comment by LutzWeischerFujitsu** [comment]
:-)
