### ISSUE TITLE
Cannot build under CentOS7

### ISSUE THREAD

**Issue by pikapi12321** [facebook/folly#1540]
![image](https://user-images.githubusercontent.com/8817895/111246988-3af48900-8642-11eb-9498-e27d14469de1.png)

**Comment by pikapi12321** [comment]
I didn't realize that there is already a build directory shipped with source code, and the README file still says to create a build directory. And I erased its contents by accident . So that problem above has gone after I recovered the "build" directory.

However, there's a new problem...
![image](https://user-images.githubusercontent.com/8817895/111642339-f8e16800-8838-11eb-893d-b60b83994bc7.png)

**Comment by yfeldblum** [comment]
@vitaut

**Comment by vitaut** [comment]
You should install {fmt} as described in https://github.com/facebook/folly#ubuntu-1604-lts.

**Comment by pikapi12321** [comment]
> You should install {fmt} as described in https://github.com/facebook/folly#ubuntu-1604-lts.

Can I simply reference fmt source in CMakeLists.txt? By using add_subdirectory(fmt_src_dir) somewhere? I think that's a bit more convenient for embedding folly in my project.

**Comment by vitaut** [comment]
We decided against vendoring {fmt} in folly.

**Comment by noxiouz** [comment]
I am not from Facebook, but I highly recommend using get_deps.py or https://github.com/facebook/folly#buildsh
It downloads and builds everything for you:
```
fbcode_builder/getdeps.py build --no-tests --install-dir /temp/folly_build/ folly 
```
Then just use CMAKE_PREFIX_PATH.
It also works with fbtrhift, wangle, proxygen, fizz etc
I used that in combination with devtoolset to build on CentOS7

**Comment by yfeldblum** [comment]
Thanks for posting the tip, @noxiouz !

**Comment by pikapi12321** [comment]
> I am not from Facebook, but I highly recommend using get_deps.py or https://github.com/facebook/folly#buildsh
> It downloads and builds everything for you:
> 
> ```
> fbcode_builder/getdeps.py build --no-tests --install-dir /temp/folly_build/ folly 
> ```
> 
> Then just use CMAKE_PREFIX_PATH.
> It also works with fbtrhift, wangle, proxygen, fizz etc
> I used that in combination with devtoolset to build on CentOS7

Thanks. I didn't notice the --install-prefix option in build.sh.
