### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by dtrodrigues** [facebook/folly#1545]
What versions of macOS are supported by folly? The last release of folly that successfully built on 10.14 is from February 15, and newer versions of fizz and wangle depend on a newer version of folly. This has prevented all three of these packages from being updated in the macOS Homebrew package manager for over a month.

**Comment by Orvid** [comment]
As a general rule Folly only ever attempts to support the 2 latest versions of macOS, so 10.15 and 10.16 right now. I would recommend dropping support for 10.14 in the homebrew package.

**Comment by dtrodrigues** [comment]
Thanks!
