### ISSUE TITLE
 Does folly support Windows 32-bit system compilation？

### ISSUE THREAD

**Issue by ziguang89** [facebook/folly#1547]
I use vcvarsall.bat X86 compiles folly with 32-bit dependent libraries, while Cmake has the follwing errors:
CMake Error at CmakeLists.txt：82 （message）:
    Folly requires a 64 bit target architecture.
If I remove this line temporarily, there will be the following error：
z:\repos\github.com-facebook-folly.git\folly\hash\detail\Crc32CombineDetail.cpp(86):error C3861:"_mm_cvtsi128_si64":找不到标识符

So I would like to ask: if I want to successfully compile 32-bit folly, what can I do？ Thank you!

**Comment by Orvid** [comment]
At this time folly does not generally support 32-bit on Windows. There is likely a small subset that will work, however it is entirely untested and there are certain components that will never work on 32-bit Windows.

**Comment by ziguang89** [comment]
Ok, i see. Thank you very much!
