### ISSUE TITLE
building exception_tracer

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [facebook/folly#1568]
How do you build that library? 
What I get while trying to build it is
```
CMake Warning (dev) in CMakeLists.txt:                                                                                 
  No project() command is present.  The top-level CMakeLists.txt file must                                                                                                                                                                    
  contain a literal, direct call to the project() command.  Add a line of
  code such as                                                                                                         
                                                           
    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by Jaimies** [comment]
First of all, this is just a warning, so you can ignore it if you want. But can you share your project's `CMakeLists.txt`?

**Comment by Alessandro-Barbieri** [comment]
I've wanted to build it as standalone (not as a part of a project), so I've unpacked the tarball, cd into exception_tracer and built from there.

I've somewhat solved this issue by removing https://github.com/facebook/folly/blob/4e7efffdcadf373d1ae7d17722634d3a849c1f7a/CMakeLists.txt#L152 and building folly

**Comment by Jaimies** [comment]
I see. From my understanding, you didn't run `build.sh`, right? 
You can do that by cloning the repo into a folder and then `cd folly` and `./build.sh` if you're on Linux or macOS, or `./build.bat` if you're on Windows.

**Comment by Alessandro-Barbieri** [comment]
I'm not using custom build scripts because I'm packaging it for gentoo::guru

**Comment by Alessandro-Barbieri** [comment]
It build now
