### ISSUE TITLE
5341023393544803

### ISSUE THREAD

**Issue by thierno22** [facebook/folly#1574]
Sorry, to be more clear:

With `std::string`:

- linux:
  - utf8 aware and std::string can handle all characters
    
-  windows:
   - depends on the charset/codepage on the machine, so behavior really boiled down to the specific machine...
   - wchar_t or std::wstring is always UTF-16

So writing something like 'é' will print correctly 100% of the time in linux but depends on the system in windows. 
This is why gtk folks came up with `ustring` as a cross platform UTF-8 aware string. How does FBString handles these cases?

_Originally posted by @Namburger in https://github.com/facebook/folly/issues/1573#issuecomment-832942404_

**Comment by yfeldblum** [comment]
Duplicate.
