### ISSUE TITLE
Getting folly working on Android NDK

### ISSUE THREAD

**Issue by karol-bisztyga** [facebook/folly#1576]
## Description

Hey!

I tried to get folly working with Android NDK on the React Native project. I have [fbjni](https://github.com/facebookincubator/fbjni) set up and a native jsi module. The problem is I cannot get this project to compile. I keep receiving the following error:
```
fatal error: 'folly/folly-config.h' file not found
```

Folly downloads and unpacks to the `build` folder properly but something's missing there and I'm not sure how to solve it.

Is it a piece of docs about this or is it explained anywhere? I had a hard time looking for any solid information regarding folly + ndk.

Any ideas of how I can make it work?

## Repro

[Here](https://github.com/karol-bisztyga/rnfbjni/commit/704994b32c2d396e0dae106ab6b922ca915967ef) is the repository containing a project(already navigated to the diff that was supposed to install folly, the changes are on the branch named `folly`).

The diff itself works but if you uncomment [here](https://github.com/karol-bisztyga/rnfbjni/commit/704994b32c2d396e0dae106ab6b922ca915967ef#diff-9f6307a6a467c67409d41f178b99fb33134947a84a45f9af4a7e930eb0133df5R56)(adds folly in `CmakeLists.txt`) or [here](https://github.com/karol-bisztyga/rnfbjni/commit/704994b32c2d396e0dae106ab6b922ca915967ef#diff-7ae1e6e3123bcd6fc9283bd67fbc865a5db3aa835acd04167de975ea4060dfc4R3)(includes some folly item in the native module) the errors will be thrown during a build.

Doesn't matter if I use Hermes or not.

Thanks in advance!

**Comment by Ashoat** [comment]
This can be addressed by adding the following config to `CMakeList.txt`:

```
add_definitions(
    -DFOLLY_USE_LIBCPP=1
    -DFOLLY_NO_CONFIG=1
    -DFOLLY_HAVE_MEMRCHR=1
)
```

It leads to another `boost`-related issue, but it gets around the `folly-config.h` issue.

**Comment by yfeldblum** [comment]
The file `folly/folly-config.h` is generated by cmake.

Internally for android, we build folly with buck and not cmake, but we have hardcoded versions of the file corresponding to what cmake might have generated were it to be run in the internal environment.

Perhaps something like that approach can be used here.

**Comment by karol-bisztyga** [comment]
@Ashoat's idea works, also, thanks for explaining @yfeldblum!
