### ISSUE TITLE
hwo to integration coro and promise.

### ISSUE THREAD

**Issue by IronsDu** [facebook/folly#1577]
I already has async rpc library, api like this: asyncDo(req, callback);

Can i use coco write sync code:
```
Task<Reply> foo(req)
{
    Promise<Reply> reply;
    asyncDo(req, [=](Reply r) {
        reply.setValue(r);
    });
    await reply.getFuture();
}
```
so , i can used like this:
```
auto reply = await  foo(req);
```

**Comment by yfeldblum** [comment]
Yes, something like this would work.

**Comment by IronsDu** [comment]
> Yes, something like this would work.

Whether have a better ？thank you.
