### ISSUE TITLE
[2021.05.17.00] Fails to build on FreeBSD: error: no member named '__cxa_allocate_exception' in namespace '__cxxabiv1'

### ISSUE THREAD

**Issue by yurivict** [facebook/folly#1582]
```
wrkdirs/usr/ports/devel/folly/work/folly-2021.05.17.00/folly/lang/Exception.cpp:180:24: error: no member named '__cxa_allocate_exception' in namespace '__cxxabiv1'
    auto object = abi::__cxa_allocate_exception(0);
                  ~~~~~^
/wrkdirs/usr/ports/devel/folly/work/folly-2021.05.17.00/folly/lang/Exception.cpp:190:10: error: no type named '__cxa_free_exception' in namespace '__cxxabiv1'; did you mean '__cxa_exception'?
    abi::__cxa_free_exception(object); // no need for decref
    ~~~~~^~~~~~~~~~~~~~~~~~~~
         __cxa_exception
/usr/include/c++/v1/cxxabi.h:77:8: note: '__cxa_exception' declared here
struct __cxa_exception
       ^
/wrkdirs/usr/ports/devel/folly/work/folly-2021.05.17.00/folly/lang/Exception.cpp:190:30: warning: parentheses were disambiguated as redundant parentheses around declaration of variable named 'object' [-Wvexing-parse]
    abi::__cxa_free_exception(object); // no need for decref
                             ^~~~~~~~
/wrkdirs/usr/ports/devel/folly/work/folly-2021.05.17.00/folly/lang/Exception.cpp:190:5: note: add enclosing parentheses to perform a function-style cast
    abi::__cxa_free_exception(object); // no need for decref
    ^
    (                                )
/wrkdirs/usr/ports/devel/folly/work/folly-2021.05.17.00/folly/lang/Exception.cpp:190:30: note: remove parentheses to silence this warning
    abi::__cxa_free_exception(object); // no need for decref
                             ^      ~

/wrkdirs/usr/ports/devel/folly/work/folly-2021.05.17.00/folly/lang/Exception.cpp:190:31: error: redefinition of 'object'
    abi::__cxa_free_exception(object); // no need for decref
                              ^
/wrkdirs/usr/ports/devel/folly/work/folly-2021.05.17.00/folly/lang/Exception.cpp:180:10: note: previous definition is here
    auto object = abi::__cxa_allocate_exception(0);
         ^
1 warning and 3 errors generated.
```

```2021.05.10.00``` was building fine.

FreeBSD 12.2
clang-10

**Comment by yfeldblum** [comment]
What preprocessor define is best to use for the freebsd variant of libc++? (Is that what's happening? I see libc++ ships with its own cxxabi.h but freebsd is not using it?)

**Comment by yurivict** [comment]
```/usr/include/c++/v1/cxxabi.h``` is installed on FreeBSD.

**Comment by yfeldblum** [comment]
Alright, this is clearly not llvm's cxxabi even though this is in `#if defined(_LIBCPP_VERSION)`.

Curious why that is - what's going on here?

And, where can I find the cxxabi in use?

**Comment by yfeldblum** [comment]
Looks like this is libcxxrt?

If so, do you know if there is some clear, unambiguous way to detect this implementation at preprocessor time?

**Comment by yurivict** [comment]
Here is this file: https://cgit.freebsd.org/src/tree/contrib/libcxxrt/cxxabi.h

**Comment by yurivict** [comment]
IMO you don't need to detect this particular implemention.
Instead you can just use
```
#ifdef __FreeBSD__
#endif
```

**Comment by yfeldblum** [comment]
It seems like it might be a bit tricky. What if something were building folly on freebsd using libstdc++? Or using upstream libcxxrt but not freebsd's libcxxrt? How to interpret the `__FreeBSD__` symbol?

**Comment by yurivict** [comment]
> It seems like it might be a bit tricky. What if something were building folly on freebsd using libstdc++?

Can't you use the ```__CXXABI_H_``` define?

Another approach is to make it cmake option based, so that this would become a responsibility of the user.

> How to interpret the __FreeBSD__ symbol?

This symbol identifies the OS.

**Comment by yfeldblum** [comment]
The tricky bit that I'm looking at is that the `__FreeBSD__` symbol identifies the OS but does not identify whether or not a user is using the standard library and runtime which are packaged by and shipped with the OS. I.e., whether the user is using libstdc++ or is using unpatched libc++ with libcxxabi or is using libc++ with unpatched libcxxrt.

What sort of cmake option were you envisioning?

**Comment by yurivict** [comment]
On FreeBSD clang always uses libcxxrt. Gcc probably uses something else.
You can use the combination of OS and compiler identification.

BTW, gcc-10 fails to compile folly on FreeBSD:
```
In file included from /usr/local/include/boost/core/demangle.hpp:32,
                 from /usr/local/include/boost/type_index/stl_type_index.hpp:34,
                 from /usr/local/include/boost/type_index.hpp:29,
                 from /usr/local/include/boost/function/function_base.hpp:21,
                 from /usr/local/include/boost/function/detail/prologue.hpp:17,
                 from /usr/local/include/boost/function.hpp:30,
                 from /usr/local/include/boost/algorithm/string/detail/find_iterator.hpp:18,
                 from /usr/local/include/boost/algorithm/string/find_iterator.hpp:24,
                 from /usr/local/include/boost/algorithm/string/iter_find.hpp:27,
                 from /usr/local/include/boost/algorithm/string/split.hpp:16,
                 from /usr/local/include/boost/algorithm/string.hpp:23,
                 from /disk-samsung/freebsd-ports/devel/folly/work/folly-2021.05.17.00/folly/json.cpp:25:
/usr/local/lib/gcc10/include/c++/cxxabi.h: At global scope:
/usr/local/lib/gcc10/include/c++/cxxabi.h:605:3: error: declaration of '__cxxabiv1::__cxa_eh_globals* __cxxabiv1::__cxa_get_globals() noexcept' has a different exception specifier
  605 |   __cxa_get_globals() _GLIBCXX_NOTHROW __attribute__ ((__const__));
      |   ^~~~~~~~~~~~~~~~~
```

**Comment by yfeldblum** [comment]
The next question is where is the actual definition in use of the type-info types? We need to replicate the right vtable to call the right rtti-upcast function (named `can_catch` in libc++ and `__do_catch` in libsupc++). I can't quite figure out how to deduce just from browsing the freebsd-src repo on github what rtti definitions libc++/freebsd is using.

**Comment by yurivict** [comment]
cmake allows to run test programs and define variables based on success/faiilure.
You should run such programs and defined like ```-DHAVE_LIBCXX```, etc.

**Comment by yfeldblum** [comment]
#1585 might be the fix?
