### ISSUE TITLE
error: /usr/local/lib/libfolly.so.0.58.0-dev: undefined reference to typeinfo for snappy::Source

### ISSUE THREAD

**Issue by yurivict** [facebook/folly#1583]
libfolly.so appears to be missing some snappy symbols, see details here https://github.com/facebook/proxygen/issues/361

**Comment by yfeldblum** [comment]
@yurivict Based on the status of https://github.com/facebook/proxygen/issues/361, it looks like this is solved?

**Comment by yurivict** [comment]
Yes, thanks.
