### ISSUE TITLE
static assert fails in C++20

### ISSUE THREAD

**Issue by AndWass** [facebook/folly#1594]
In C++20 `std::atomic` is no longer trivial, causing at least the `static_assert(
      std::is_trivial<GlobalState>::value || kCpplibVer, "not trivial");` on line 208 in `folly/concurrency/CacheLocality.h` to fail.

**Comment by alex-700** [comment]
hasn't fixed in [14c2b1d](https://github.com/facebook/folly/commit/14c2b1dc4f9f937dd793d679a31e9795d63b9ce7) due to copy-pasted [static_assert](https://github.com/facebook/folly/blob/ff841baa23dbcd653acedaa0a4f8cc2a896b49d9/folly/concurrency/CacheLocality.h#L260) in descendant.
