### ISSUE TITLE
error when use vcpkg

### ISSUE THREAD

**Issue by hjhj111** [facebook/folly#1620]
Starting package 1/45: boost-exception:x86-windows
Building package boost-exception[core]:x86-windows...
-- Using cached E:/vcpkg-master/downloads/boostorg-exception-boost-1.75.0.tar.gz
-- Cleaning sources at E:/vcpkg-master/buildtrees/boost-exception/src/ost-1.75.0-89fb56d2c9.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/vcpkg-master/downloads/boostorg-exception-boost-1.75.0.tar.gz
-- Using source at E:/vcpkg-master/buildtrees/boost-exception/src/ost-1.75.0-89fb56d2c9.clean
-- Building x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: E:/vcpkg-master/installed/x64-windows/tools/boost-build/b2.exe --stagedir=E:/vcpkg-master/buildtrees/boost-exception/x86-windows-rel/stage --build-dir=E:/vcpkg-master/buildtrees/boost-exception/x86-windows-rel --user-config=E:/vcpkg-master/buildtrees/boost-exception/x86-windows-rel/user-config.jam -j20 --debug-configuration --debug-building --debug-generators --disable-icu --ignore-site-config --hash -q -sZLIB_INCLUDE=E:/vcpkg-master/installed/x86-windows/include -sBZIP2_INCLUDE=E:/vcpkg-master/installed/x86-windows/include -sLZMA_INCLUDE=E:/vcpkg-master/installed/x86-windows/include -sZSTD_INCLUDE=E:/vcpkg-master/installed/x86-windows/include threading=multi threadapi=win32 runtime-link=shared link=shared address-model=32 architecture=x86 asmflags=/safeseh -sZLIB_BINARY=zlib -sZLIB_LIBPATH=E:/vcpkg-master/installed/x86-windows/lib -sBZIP2_BINARY=bz2 -sBZIP2_LIBPATH=E:/vcpkg-master/installed/x86-windows/lib -sLZMA_BINARY=lzma -sLZMA_LIBPATH=E:/vcpkg-master/installed/x86-windows/lib -sZSTD_BINARY=zstd -sZSTD_LIBPATH=E:/vcpkg-master/installed/x86-windows/lib variant=release debug-symbols=on
    Working Directory: E:/vcpkg-master/buildtrees/boost-exception/src/ost-1.75.0-89fb56d2c9.clean/build
    Error code: 1
    See logs for more information:
      E:\vcpkg-master\buildtrees\boost-exception\build-x86-windows-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:332 (vcpkg_execute_required_process)
  ports/boost-exception/portfile.cmake:15 (boost_modular_build)
  scripts/ports.cmake:142 (include)

Error: Building package boost-exception:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-exception:x86-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

**Comment by Orvid** [comment]
This is an error in boost. Please file the error against vcpkg as it is unrelated to folly.
