### ISSUE TITLE
Why does TurnSequencer.h use glog instead of folly logging

### ISSUE THREAD

**Issue by luxapana** [facebook/folly#1626]
I can see that TurnSequencer.h includes glog.h for CHECK macros. This essentially means that glog is a dependency for folly. Anyone who wants to use Folly will have to use glog (even if you dont use glog as the logging api, we will have to init it atleast). It would be great if we had the flexibility to use a different logging library instead of glog.

**Comment by yfeldblum** [comment]
Historically, folly has used glog extensively since long before folly logging was introduced. Revising all of the log lines has not yet been anyone's top priority.
