### ISSUE TITLE
speific g++ and disable gcc option in bazel

### ISSUE THREAD

**Issue by yangelaboy** [facebook/folly#1630]
hello, I encountered a problem with bazel.
I built folly from source, and wrote a simple example as follows.
It was ok to build the example with g++, but is was wrong with bazel.

note: bazel is of version 4.0.0, g++ and gcc are of version 10.0.1.

- **gcc command succeed**

`g++ -std=c++17 test1.cpp -pthread -levent -ldouble-conversion -lgflags -lglog -lboost_system -lboost_context -ldl -lfolly -lboost_thread`

- **gcc command with tag -fuse-ld=gold failed**

`g++ -std=c++17 test1.cpp -pthread -levent -ldouble-conversion -lgflags -lglog -lboost_system -lboost_context -ldl -lfolly -lboost_thread -fuse-ld=gold`

-  **gcc cmmoand failed**
`gcc -std=c++17 test1.cpp -pthread -levent -ldouble-conversion -lgflags -lglog -lboost_system -lboost_context -ldl -lfolly -lboost_thread`

-  **gcc with tag -fuse-ld=gold failed**
`gcc -std=c++17 test1.cpp -pthread -levent -ldouble-conversion -lgflags -lglog -lboost_system -lboost_context -ldl -lfolly -lboost_thread -fuse-ld=gold`

- **bazel command failed**
I found bazel would use gcc(/usr/bin/gcc) and add gcc options **-fuse-ld=gold**

`bazel test --jobs 8 --verbose_failures -c dbg  -s --verbose_failures --sandbox_debug :example`.

**here is my question: how can I specific compiler and disable the default -fuse-ld tag???**

- example

`
#include <folly/futures/Future.h>
#include<iostream>
using namespace folly;
using namespace std;
void foo(int x)
{
  // do something with x
     cout << "foo(" << x << ")" << endl;
 }
 // ...
 int main()
 {
     cout << "making Promise" << endl;
     Promise<int> p;
     Future<int> f = p.getFuture();
     return 0;
 }
`

- BUILD file

`package(default_visibility = ["//visibility:public"])
cc_test(
  name = "example",
  srcs = glob(["src/*.cpp"]),
  copts = [
    "-g",
    "-gdwarf-2",
    "-flto",
    "-rdynamic",
    "-std=c++17",
    "-flto",
    "-fno-omit-frame-pointer",
    "-Wno-deprecated",
    "-DENABLE_LOGGER",
    "-O0",
    "-fno-builtin-malloc",
    "-fno-builtin-calloc",
    "-fno-builtin-realloc",
    "-fno-builtin-free",
    #"--verbose",
  ],
  linkstatic = True,
  linkopts = [
    "-Wl,-v -Bdynamic",
    "-pthread",
    "-levent",
    "-ldouble-conversion",
    "-lgflags",
    "-lglog",
    "-lboost_system",
    "-lboost_context",
    "-ldl",
    "-Wl, -v -Bstatic",
    "-lfolly",
  ],
)
`

**Comment by yangelaboy** [comment]
`g++ -std=c++17 test1.cpp -pthread -levent -ldouble-conversion -lgflags -lglog -lboost_system -lboost_context -ldl -lfolly -lboost_thread`
g

**Comment by yangelaboy** [comment]
the LD_LIBRARY_PATH:

**Comment by yangelaboy** [comment]
![image](https://user-images.githubusercontent.com/16263873/129018893-f989ae19-7d10-4e52-a08a-dbd10163da99.png)

**Comment by yangelaboy** [comment]
![image](https://user-images.githubusercontent.com/16263873/129019123-dcb17bfd-c21a-482f-afcc-ba68f3345ff2.png)

**Comment by yangelaboy** [comment]
![image](https://user-images.githubusercontent.com/16263873/129019535-5c1bccbd-a8aa-4847-83bb-56dddbf30ae2.png)
![image](https://user-images.githubusercontent.com/16263873/129019672-e3cc4eec-0f1e-46fb-b33a-9a61d8bcfc55.png)

**Comment by yfeldblum** [comment]
I don't think we currently have the ability to diagnose build problems with bazel.
