### ISSUE TITLE
failed to build test cases in the clion

### ISSUE THREAD

**Issue by nanboxian** [facebook/folly#1634]
![image](https://user-images.githubusercontent.com/9002466/130336675-6db42749-663b-4bef-b621-ac7edb546dda.png)
i fail to find the all gtest cases in the clion now. And i find that it was caused by this commit  4033d186108b5bca4f7347fa0c364eb3a0e9cbab
i'd like to know is there anyone else meet the same issue? should i config anything to make it work again?

**Comment by vegertar** [comment]
I'm not using CLion, but I cannot even find any test executable files under build directory at all, whatever with "./build.sh  --extra-cmake-defines '{"BUILD_TESTS": "ON"}'" or "cmake ..  -DBUILD_TESTS=ON".
If run with ctest, always got a "No tests were found!!". e.g.:
```bash
 ./run_cmake.py --test
Running: '/tmp/fbcode_builder_getdeps-ZhomeZubuntuZfollyZbuildZfbcode_builder/installed/cmake-RxWkKWcnLBmWGDyoomkMmr1dAEiGd4aVo9b_5e0xBm0/bin/ctest --output-on-failure -j4'
Test project /tmp/fbcode_builder_getdeps-ZhomeZubuntuZfollyZbuildZfbcode_builder/build/folly
No tests were found!!!
```
It's probably need taking a glance at the cmake files.

**Comment by ahornby** [comment]
ctest tests are fixed
