### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by swrobel** [facebook/folly#1655]
This error occurs when building with newer folly on React Native for iOS. Here is [the issue from the Flipper repo](https://github.com/facebook/flipper/issues/2600) with more detail:
```
Undefined symbols for architecture arm64:
  "___cxa_increment_exception_refcount", referenced from:
      folly::exception_ptr_get_type(std::exception_ptr const&) in libRCT-Folly.a(Exception.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
It seems to be tied to [this line of code](https://github.com/facebook/folly/blob/master/folly/lang/Exception.cpp#L233), which was changed in recent versions of folly.

**Comment by yfeldblum** [comment]
I commented on facebook/flipper#2600. Presumably, flipper needs to update its build to account for the new direct dependency, on apple platforms, of folly on c++abi. Hopefully that should help.
