### ISSUE TITLE
Typedef redefinition

### ISSUE THREAD

**Issue by arthurgeron-work** [facebook/folly#1658]
When building a react native project with Folly `0.110.0` I get the following error:
```ios/Pods/RCT-Folly/folly/portability/Time.h:52:17: Typedef redefinition with different types ('uint8_t' (aka 'unsigned char') vs 'enum clockid_t')```

**Comment by arthurgeron-work** [comment]
created on my work account, closing

**Comment by Simar05519** [comment]
Do we have to explain typedef?

**Comment by DominicGBauer** [comment]
I experience the same issue.

I've gotten it down to changing from platform :ios, '11.0' to 12.0'.

**Comment by yfeldblum** [comment]
Closing on the assumption that #1724 fixes the problem.
