### ISSUE TITLE
Function: inconsistent terminate behaviour when declared noexcept

### ISSUE THREAD

**Issue by jonlin00** [facebook/folly#1663]
```
template <typename ReturnType, typename... Args>
struct FunctionTraits<ReturnType(Args...) noexcept> {
// removed for clarity...
  static ReturnType uninitCall(CallArg<Args>..., Data&) noexcept {
    terminate_with<std::bad_function_call>();
  }
// removed for clarity...
};

template <typename ReturnType, typename... Args>
struct FunctionTraits<ReturnType(Args...) const noexcept> {
// removed for clarity...
  static ReturnType uninitCall(CallArg<Args>..., Data&) noexcept {
    throw_exception<std::bad_function_call>();
  }
// removed for clarity...
};
```
Sample taken from [https://github.com/facebook/folly/blob/a79234f07321986dc1863ec11ab25dc4ad1da442/folly/Function.h#L462](url)
It is not clear why FunctionTraits terminates using different methods when declared const versus not-const.
Suggested edit:
Change `throw_exception<std::bad_function_call>()` to `terminate_with<std::bad_function_call>()` or add a comment describing why one throws while the other one just terminates.

This is my first ever issue, if you want me to elaborate some point or add some extra info for future reference please let me know.

**Comment by yfeldblum** [comment]
There is no reason for this difference, but I think this was subsequently changed.
