### ISSUE TITLE
Please add to README how to run tests

### ISSUE THREAD

**Issue by yurivict** [facebook/folly#1671]
It has the section ```Building tests``` but it doesn't have the section ```Running tests```.

**Comment by sjanel** [comment]
I agree, it's not clear how to launch tests locally. 
After this series of commands (from `folly` root directory), I would expect the tests to be launched:
```
mkdir -p _build && cd _build
cmake -DBUILD_TESTS=ON ..
make
ctest
```

Also, I think that it's strange to have `BUILD_TESTS` to `OFF` by default, especially when working in `folly` as a main project.

**Comment by yurivict** [comment]
cmake prints:
> No tests were found!!!

**Comment by ahornby** [comment]
ctest should work now

**Comment by ahornby** [comment]
README updated
