### ISSUE TITLE
🐛 MacCatalyst: DoubleConversion.h not found

### ISSUE THREAD

**Issue by ZComwiz** [facebook/folly#1680]
**Problem**
When building React Native on versions AFTER 64.0 to MacCatalyst target, Flipper-Folly cannot find `<double-conversion/double-conversion.h>` in `Conv.h`

Likely this is because Folly switched to using an xcFramework pattern but did not properly include MacCatalyst slices (speculating). 

There is some scripting info [here on how to possibly go about that](https://github.com/transistorsoft/react-native-background-fetch/issues/311#issuecomment-774781786) and also here on this [blog post](https://pspdfkit.com/blog/2020/supporting-xcframeworks/).

If either @simpkins or @Orvid can weigh in on this, that would be awesome 🤩

**Comment by yfeldblum** [comment]
I don't think this issue really applies to folly. This might be better raised in the react-native repo.
