### ISSUE TITLE
undefined reference to `fmt::v7::detail::vformat[abi:cxx11](fmt::v7::basic_string_view<char>, fmt::v7::format_args)'?

### ISSUE THREAD

**Issue by liuzhuang1024** [facebook/folly#1690]
![image](https://user-images.githubusercontent.com/23006154/146305359-198d831d-33a2-4115-b086-0705f904894b.png)

**Comment by yfeldblum** [comment]
I don't know how one would repro this locally.

**Comment by val3ra-git** [comment]
@liuzhuang1024 Have you managed to resolve this issue on your device?
