### ISSUE TITLE
clock_gettime not implemented on OS X

### ISSUE THREAD

**Issue by 191919** [facebook/folly#170]
FunctionScheduler.cpp failed to compile on OS X Yosemite (or previous versions) because the missing of implementation of `clock_gettime`.

Here is a workaround. Now I can compile the homebrew version of folly 32.0.

```
diff --git a/folly/experimental/FunctionScheduler.cpp b/folly/experimental/FunctionScheduler.cpp
index 78b0aee..6957b6d 100644
--- a/folly/experimental/FunctionScheduler.cpp
+++ b/folly/experimental/FunctionScheduler.cpp
@@ -29,6 +29,23 @@ using namespace std;
 using std::chrono::seconds;
 using std::chrono::milliseconds;
 
+#ifdef __MACH__
+
+#include <sys/time.h>
+
+#define CLOCK_MONOTONIC 0
+
+static int clock_gettime(int /*clk_id*/, struct timespec* t) {
+    struct timeval now;
+    int rv = gettimeofday(&now, NULL);
+    if (rv) return rv;
+    t->tv_sec  = now.tv_sec;
+    t->tv_nsec = now.tv_usec * 1000;
+    return 0;
+}
+
+#endif
+
 static milliseconds nowInMS() {
   struct timespec ts /*= void*/;
   if (clock_gettime(FOLLY_TIME_MONOTONIC_CLOCK, &ts)) {
```

**Comment by peroxyacyl** [comment]
How about this workaround from https://gist.github.com/alfwatt/3588c5aa1f7a1ef7a3bb ?
It may be more accurate implementation of clock_gettime. I can compile it at 34.0.

```
#ifdef __MACH__

#include <sys/time.h>
#include <mach/mach_time.h>
#include <sys/types.h>
#include <sys/_types/_timespec.h>
#include <mach/mach.h>
#include <mach/clock.h>

#define TIMER_ABSTIME -1
#define CLOCK_REALTIME CALENDAR_CLOCK
#define CLOCK_MONOTONIC SYSTEM_CLOCK
#define MT_NANO (+1.0E-9)
#define MT_GIGA UINT64_C(1000000000)

static double mt_timebase = 0.0;
static uint64_t mt_timestart = 0;

static int clock_gettime(int clk_id, struct timespec *tp)
{
    kern_return_t retval = KERN_SUCCESS;
    if( clk_id == TIMER_ABSTIME)
    {
        if (!mt_timestart) { // only one timer, initilized on the first call to the TIMER
            mach_timebase_info_data_t tb = { 0 };
            mach_timebase_info(&tb);
            mt_timebase = tb.numer;
            mt_timebase /= tb.denom;
            mt_timestart = mach_absolute_time();
        }
 
        double diff = (mach_absolute_time() - mt_timestart) * mt_timebase;
        tp->tv_sec = diff * MT_NANO;
        tp->tv_nsec = diff - (tp->tv_sec * MT_GIGA);
    }
    else // other clk_ids are mapped to the coresponding mach clock_service
    {
        clock_serv_t cclock;
        mach_timespec_t mts;
 
        host_get_clock_service(mach_host_self(), clk_id, &cclock);
        retval = clock_get_time(cclock, &mts);
        mach_port_deallocate(mach_task_self(), cclock);
 
        tp->tv_sec = mts.tv_sec;
        tp->tv_nsec = mts.tv_nsec;
    }
 
    return retval;
}

#endif
```

**Comment by fish2000** [comment]
@191919 – your patch worked for me as well, I integrated it into a formula for Folly here:

https://github.com/fish2000/homebrew-praxa/blob/master/folly.rb

… I was working on this anyway when I found this issue, incidentally, but I couldn’t find a previously-published Folly fomula in Homebrew’s master or in any of the usual taps. But so if anyone is interested, it’s in [my personal tap](https://github.com/fish2000/homebrew-praxa), `fish2000/praxa` (which also contains [a formula](https://github.com/fish2000/homebrew-praxa/blob/master/fatal.rb) for [the Facebook C++ template library, Fatal](https://github.com/facebook/fatal)).

The Folly formula will build Folly 37.0 using the autoconf/automake system, without relying on the homebrew bootstrap script that ships in Folly’s codebase but using the same vendor-library methods for dealing with `double-conversion` and `gtest` dependencies. It needs Homebrew LLVM 3.51 installed using the `--with-clang` option, but if you can stomach that (and a long compile time for Folly itself) you can use C++11 (the default) or gnu++0x.

Two tests were failing for me (thread-local and atomic hash map), so they’re manually disabled in the formula for now. 

Anyway, so: if this works for any of you, do let me know, thanks.

**Comment by sgolemon** [comment]
This is now covered by folly/detail/Clock.{h,cpp}
