### ISSUE TITLE
Question on variable comparison in ThreadPoolExecutor.

### ISSUE THREAD

**Issue by JingLiofLiJing** [facebook/folly#1700]
In ThreadPoolExecutor::setNumThreads(size_t numThreads) function [link](https://github.com/facebook/folly/blob/bf2a54fec7e8f160ecb009a3aac270d7decf4ed5/folly/executors/ThreadPoolExecutor.cpp#L197), i can figure out that:
```cpp
maxThreads_.store(numThreads, std::memory_order_relaxed); 
auto active = activeThreads_.load(std::memory_order_relaxed);
auto minthreads = minThreads_.load(std::memory_order_relaxed);
if (numThreads < minthreads) {`
    minthreads = numThreads;`
    minThreads_.store(numThreads, std::memory_order_relaxed);
}
/* numThreads(maxThreads_) >= minthreads(minThreads_) */
if (active > numThreads) {
    /* active > numThreads >= minthreads */
    numThreadsToJoin = active - numThreads;
    if (numThreadsToJoin > active - minthreads) {    // will be always false ?
        numThreadsToJoin = active - minthreads;      // never goto this line ?
    }
.....
```
I’m confused that is there a situation can break the invariant？

**Comment by yfeldblum** [comment]
It seems to me that your analysis is right and the condition will always fail. I have submitted an internal change to change this to an assertion. Thanks for pointing this out.

**Comment by JingLiofLiJing** [comment]
@yfeldblum Thanks！
