### ISSUE TITLE
Parameter types in continuations

### ISSUE THREAD

**Issue by benlandrum** [facebook/folly#1708]
For callbacks added to `Future`s, is ever advantageous to use an rvalue reference parameter (e.g., `[](std::string&&){...}`), or are value parameters (e.g., `[](std::string){}`) preferred? I see the latter in examples in [your documentation](https://github.com/facebook/folly/blob/main/folly/docs/Futures.md).

**Comment by yfeldblum** [comment]
Reference parameters may be either cheaper or more expensive depending on the case. There is no universal rule here.

Note that continuations are always called with the value passed by rvalue-reference. So you can write your code how you like, with either value or rvalue-reference or const-lvalue-reference parameters.
