### ISSUE TITLE
'folly/folly-config.h' file not found

### ISSUE THREAD

**Issue by hellforever** [facebook/folly#1709]
I am updating react native version from 0.63.3 to 0.67.1, after I run `npm install` and `pod install`, I got 'folly/folly-config.h' file not found error while compiling in my Xcode. 

React info:
System:
    OS: macOS 11.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 131.60 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.3 - ~/.nvm/versions/node/v14.18.3/bin/node
    Yarn: Not Found
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.3/bin/npm
    Watchman: 2022.01.17.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /Users/fepc-412/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 28.0.3, 29.0.1, 29.0.2, 30.0.1, 30.0.2, 30.0.3, 31.0.0
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google APIs ARM 64 v8a, android-31 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8092744
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_291 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by yfeldblum** [comment]
This file does not exist in the repo. It is generated at configure time when using cmake either directly or via fbcode-builder.

If you are not using either one of these, then you would want to set up your build environment with a `folly/folly-config.h` as it would have been generated by cmake at configure time.

**Comment by Ahsanali012** [comment]
> This file does not exist in the repo. It is generated at configure time when using cmake either directly or via fbcode-builder.
> 
> If you are not using either one of these, then you would want to set up your build environment with a `folly/folly-config.h` as it would have been generated by cmake at configure time.

Can you please guide me how to resolve this as i didnt understood
