### ISSUE TITLE
Why only SCOPE_SUCCESS macro accepts the default non-noexcept lambda？

### ISSUE THREAD

**Issue by JingLiofLiJing** [facebook/folly#1718]
In [ScopeGuard.h](https://github.com/facebook/folly/blob/fe501cc8a66f432c405d16fc348e83cb56c563da/folly/ScopeGuard.h#L304)，i can figure out that：
1. **ExecuteOnException in ScopeGuardForNewException** corresponds to **InvokeNoexcept in ScopeGuardImpl**.
2. **InvokeNoexcept(true) via SCOPE_EXIT and SCOPE_FAIL**  makes dtor() and execute() noexcept in ScopeGuardImpl，so after function_ thorws an exception, terminate() will leave a message to cerr, then the whole program will shutdown immediately because noexcept terminate() thorws an exception.
3. **InvokeNoexcept(false) via SCOPE_SUCCESS** removes all noexcept symbols and terminate() will never be called.  So dtor() behaves like a normal function_ calling, the throwing exception will be brocasted.

I'm confused that:
1. Is the template value ExecuteOnException **only** affects "**noexcept**" symbols of the calling-links below and the behaviour  when function_  throws an exception ?
```
ScopeGuardForNewException::dtor()
--> ScopeGuardImpl::dtor()
---->  ScopeGuardImpl::execute() 
------>  ScopeGuardImplBase::terminate() noexcept
```
2. Why makeFailsafe(std::false_type, ...) marks noexcept, seems that ScopeGuardImpl::ctor(...) is inferred non-noexcept ?
3. Why SCOPE_EXIT and SCOPE_FAIL macros make noexcept by default but SCOPE_SUCCESS doesn't ?

**Comment by yfeldblum** [comment]
The operating principle here is that cleanup operations should be infallible, where failure means a raised error. This is why the default for object destructors is to be `noexcept`.

In the case of `SCOPE_SUCCESS`, there is no possibility that the block is executed in a cleanup operation. So it is okay for the block to be fallible. But in the case `SCOPE_FAIL`, the block is always executed in a cleanup operation. So it is generally a problem for the block to be fallible. And in the case of `SCOPE_EXIT`, it is possible for the block to be executed in a cleanup operation, so it must work like `SCOPE_FAIL`.
