### ISSUE TITLE
FAILED: CMakeFiles/folly_base.dir/folly/io/async/AsyncSocket.cpp.o

### ISSUE THREAD

**Issue by yxbu1996** [facebook/folly#1729]
[7/354] Building CXX object CMakeFiles/folly_base.dir/folly/io/async/AsyncSocket.cpp.o
FAILED: CMakeFiles/folly_base.dir/folly/io/async/AsyncSocket.cpp.o
/usr/bin/ccache /opt/rh/devtoolset-7/root/usr/bin/c++ -DFMT_LOCALE -DFOLLY_XLOG_STRIP_PREFIXES=\"/home/yxbu/folly:/tmp/fbcode_builder_getdeps-ZhomeZyxbuZfollyZbuildZfbcode_builder-root/build/folly\" -DGFLAGS_IS_A_DLL=0 -D_GNU_SOURCE -D_REENTRANT -I/home/yxbu/folly -I/tmp/fbcode_builder_getdeps-ZhomeZyxbuZfollyZbuildZfbcode_builder-root/build/folly -I/tmp/fbcode_builder_getdeps-ZhomeZyxbuZfollyZbuildZfbcode_builder-root/installed/gflags-42azALcCjA-9sZwYiOUZkY4eYMX0oHio--azPH8nDwE/include -I/tmp/fbcode_builder_getdeps-ZhomeZyxbuZfollyZbuildZfbcode_builder-root/installed/glog-njas0PWe7cwKzg9VmZbfDMZpg4R5StsTUGiUvEIMgpU/include -I/tmp/fbcode_builder_getdeps-ZhomeZyxbuZfollyZbuildZfbcode_builder-root/installed/snappy-87r_NeHOmJ_Qf3xx3ezKUKwXSN5xVQEZwSXyQBGRpDI/include -I/tmp/fbcode_builder_getdeps-ZhomeZyxbuZfollyZbuildZfbcode_builder-root/installed/fmt-tvjC_o0MODpoLluHlVyVQQB6xs0Hx_nQ7VG_jr80SSw/include -O2 -g -DNDEBUG -g -std=gnu++1z -finput-charset=UTF-8 -fsigned-char -Wall -Wno-deprecated -Wno-deprecated-declarations -Wno-sign-compare -Wno-unused -Wuninitialized -Wunused-label -Wunused-result -Wshadow-compatible-local -Wno-noexcept-type -faligned-new -fopenmp -std=gnu++1z -MD -MT CMakeFiles/folly_base.dir/folly/io/async/AsyncSocket.cpp.o -MF CMakeFiles/folly_base.dir/folly/io/async/AsyncSocket.cpp.o.d -o CMakeFiles/folly_base.dir/folly/io/async/AsyncSocket.cpp.o -c /home/yxbu/folly/folly/io/async/AsyncSocket.cpp
/home/yxbu/folly/folly/io/async/AsyncSocket.cpp:215:7: error: ‘scm_timestamping’ does not name a type; did you mean ‘LN_ad_timeStamping’?
 const scm_timestamping* FOLLY_NULLABLE
       ^~~~~~~~~~~~~~~~
       LN_ad_timeStamping
/home/yxbu/folly/folly/io/async/AsyncSocket.cpp: In member function ‘folly::Optional<folly::AsyncTransport::ByteEvent> folly::AsyncSocket::ByteEventHelper::processCmsg(const cmsghdr&, size_t)’:
/home/yxbu/folly/folly/io/async/AsyncSocket.cpp:498:27: error: ‘cmsgToScmTimestamping’ was not declared in this scope
   } else if (auto scmTs = cmsgToScmTimestamping(cmsg)) {
                           ^~~~~~~~~~~~~~~~~~~~~

i compile folly on centos7

**Comment by jq2252** [comment]
I have the same issue on centos 7.
Do you compile folly on centos 7 successfully?

**Comment by eastwiner** [comment]
the above fix does not work, still compile fail on centos 7

**Comment by jinhaichen** [comment]
I still compile fail with the same problem. Is there any solution?

**Comment by lingbin** [comment]
Unfortunately, I also encountered this problem with `folly-2023.02.13.00`  :-(

**Comment by zhangnew** [comment]
Has anyone solved this problem?
