### ISSUE TITLE
Call folly exception

### ISSUE THREAD

**Issue by lyb332442181** [facebook/folly#1753]
12	
PNCBank	
std::__1::vector<folly::dynamic, std::__1::allocator<folly::dynamic> >::__vallocate(unsigned long) (in PNCBank) (vector:937)
13	
PNCBank	
std::__1::vector<folly::dynamic, std::__1::allocator<folly::dynamic> >::vector(std::__1::vector<folly::dynamic, std::__1::allocator<folly::dynamic> > const&) (in PNCBank) (vector:1213)
14	
PNCBank	
folly::dynamic::operator=(folly::dynamic const&) (in PNCBank) (dynamic.cpp:144)
15	
PNCBank	
std::__1::pair<folly::dynamic const, folly::dynamic>::pair(std::__1::pair<folly::dynamic const, folly::dynamic> const&) (in PNCBank) (utility:324)
16	
PNCBank	
std::__1::unique_ptr<std::__1::__hash_node<std::__1::__hash_value_type<folly::dynamic, folly::dynamic>, void*>, std::__1::__hash_node_destructor<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<folly::dynamic, folly::dynamic>, void*> > > > std::__1::__hash_table<std::__1::__hash_value_type<folly::dynamic, folly::dynamic>, std::__1::__unordered_map_hasher<folly::dynamic, std::__1::__hash_value_type<folly::dynamic, folly::dynamic>, folly::detail::DynamicHasher, true>, std::__1::__unordered_map_equal<folly::dynamic, std::__1::__hash_value_type<folly::dynamic, folly::dynamic>, folly::detail::DynamicKeyEqual, true>, std::__1::allocator<std::__1::__hash_value_type<folly::dynamic, folly::dynamic> > >::__construct_node_hash<std::__1::pair<folly::dynamic const, folly::dynamic> const&>(unsigned long, std::__1::pair<folly::dynamic const, folly::dynamic> const&) (in PNCBank) (__hash_table:2308)
17	
PNCBank	
std::__1::unordered_map<folly::dynamic, folly::dynamic, folly::detail::DynamicHasher, folly::detail::DynamicKeyEqual, std::__1::allocator<std::__1::pair<folly::dynamic const, folly::dynamic> > >::unordered_map(std::__1::unordered_map<folly::dynamic, folly::dynamic, folly::detail::DynamicHasher, folly::detail::DynamicKeyEqual, std::__1::allocator<std::__1::pair<folly::dynamic const, folly::dynamic> > > const&) (in PNCBank) (unordered_map:1259)
18	
PNCBank	
folly::dynamic::operator=(folly::dynamic const&) (in PNCBank) (dynamic.cpp:144)
19	
PNCBank	
std::__1::vector<folly::dynamic, std::__1::allocator<folly::dynamic> >::vector(std::__1::vector<folly::dynamic, std::__1::allocator<folly::dynamic> > const&) (in PNCBank) (vector:1213)
20	
PNCBank	
folly::dynamic::operator=(folly::dynamic const&) (in PNCBank) (dynamic.cpp:144)
21	
PNCBank	
__copy_helper_block_ea8_32c71_ZTSKZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiE3$_0 (in PNCBank) (RCTNativeModule.mm:0)

We are using reactnative0 In version 59.9, similar exceptions are occasionally thrown. May I ask why

**Comment by yfeldblum** [comment]
I'm not sure it is possible to conjure up a reason why an exception like this is thrown, purely from the partial stacktrace in this issue.
