### ISSUE TITLE
[Folly] Unable to parse [libunwind] configuration due to downstream [golg] provided and exported

### ISSUE THREAD

**Issue by FrankXie05** [facebook/folly#1757]
Hi, I'm the maintainer of vcpkg.
We received an issue about `folly `being unable to parse the `glog ` exported the cmake configuration of libunwind.
**Host Environment**

- OS: Debian bookworm/sid
- Compiler: gcc 11.2.0

**To Reproduce**
 Reproduce the issue steps: https://pastebin.com/GRSKXpKa
 
 **Failure logs**
 ````
 CMake Error at /home/chaoyi/.vcpkg/scripts/buildsystems/vcpkg.cmake:816 (_find_package):
  By not providing "FindUnwind.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Unwind", but
  CMake did not find one.

  Could not find a package configuration file provided by "Unwind" (requested
  version 1.3.2) with any of the following names:

    UnwindConfig.cmake
    unwind-config.cmake

  Add the installation prefix of "Unwind" to CMAKE_PREFIX_PATH or set
  "Unwind_DIR" to a directory containing one of the above files.  If "Unwind"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /usr/share/cmake-3.23/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /home/chaoyi/.vcpkg/installed/x64-linux/share/glog/glog-config.cmake:24 (find_dependency)
  /home/chaoyi/.vcpkg/scripts/buildsystems/vcpkg.cmake:816 (_find_package)
  CMake/folly-deps.cmake:55 (find_package)
  CMakeLists.txt:118 (include)
  ````

 Related vcpkg issue: https://github.com/microsoft/vcpkg/issues/24064#issuecomment-1095477163

 References： [Folly] : https://github.com/facebook/folly/blob/5bbfb175cb8fc7edab442f06105d4681654732e9/build/fbcode_builder/CMake/FindLibUnwind.cmake
 [glog]: https://github.com/google/glog/blob/224f66bb63393b63d254cac3ff67c2b247a95a36/cmake/FindUnwind.cmake
 
 I would like to ask, is `glog `a mandatory dependency of `folly`, and if so should it be consistent in the way to find libraries, or some other workaround. :)
 
 Thanks,
 Frank

**Comment by Orvid** [comment]
This actually sounds like an issue with glog, not folly. If glog depends on libunwind being locatable with a FindUnwind.cmake, then it should be making it available when importing the glog targets, shouldn't it? The way folly finds libunwind for its own purposes shouldn't matter as far as I understand.

**Comment by FrankXie05** [comment]
@Orvid Thanks for your reply, I will open an issue to `glog` .

**Comment by Orvid** [comment]
Folly cannot depend on the existence of glog's implementation of `FindUnwind`, and glog cannot depend on folly's implementation of `FindLibUnwind` - glog could remove their dependency on libunwind at any time. The way `/home/chaoyi/.vcpkg/installed/x64-linux/share/glog/glog-config.cmake` is currently being generated means that it's dependent on whatever project it is being used in to provide a `FindUnwind`, which is neither safe, nor correct.

If something other than the system libunwind is needed, both folly and glog provide cmake variables that can be set to provide that non-default path.

**Comment by FrankXie05** [comment]
@Orvid It's not folly's problem. Thanks for help. :)
