### ISSUE TITLE
folly link error when build my project

### ISSUE THREAD

**Issue by chuckleLZY** [facebook/folly#1771]
Hi, I build my project, and use the newest version of folly to build, but when I build my program, it came out this error about folly: undefined reference to `folly::f14::detail::F14LinkCheck<(folly::f14::detail::F14IntrinsicsMode)2>::check()'.

I tried to use the older version of folly, but it still came out with same error.

has anybody already encountered this problem and solved it?

**Comment by ruclz** [comment]
same error, I need to build the velox, but when i link the folly,  the error appears.

**Comment by Orvid** [comment]
This error is intentional, and occurs when you build Folly with a different set of instructions available than when you go to use it. For x86_64, that would be SSE 4.2. The default OSS build of folly doesn't have SSE4.2 enabled, but the project you're trying to use folly in might, which would cause this error.

**Comment by ruclz** [comment]
Thanks, but how can i build folly with SSE4.2?

**Comment by weimingdiit** [comment]
@chuckleLZY  Hi, We have the same problem, do you have a solution? Can you give me some advice?

**Comment by chuckleLZY** [comment]
Hi Ming, actually I don't know how to fix this problem. Because when I double checked my project again, I found there are two modules(projects) that need to be integrated, using two different version of folly, which may cause that error. So I recommend you to check your project again, check all the dependents, to make sure the same dependents have the same version. Or if it doesn't work, please think about the answer that Orvid answered. 
I am not recommend you to find the problem in the folly code. Because it is hard and cost a lot of time.
I wish you can fix the problem.

> @chuckleLZY Hi, We have the same problem, do you have a solution? Can you give me some advice?

**Comment by weimingdiit** [comment]
@chuckleLZY  thanks Chuckle！
