### ISSUE TITLE
build error with v2022.06.27.00

### ISSUE THREAD

**Issue by chenxue1** [facebook/folly#1810]
after I installed all the dependency with following command
sudo ./build/fbcode_builder/getdeps.py install-system-deps --recursive,

I build with the following command  
python3 ./build/fbcode_builder/getdeps.py --allow-system-packages build

I meet the error, in CMakeError.log
/usr/bin/ld: src.c:(.text+0x52): undefined reference to `pthread_detach'
/usr/bin/ld: src.c:(.text+0x63): undefined reference to `pthread_join'

I test with a simple code which also using the pthread, but it can be compile with -lpthread.

I don't know why?

**Comment by Orvid** [comment]
What is the actual build error you're seeing? The pthread error looks like it's from one of the configuration tests, which are expected to have a large number fail, since the failures are how it determines what configuration flags are needed to build with.

**Comment by chenxue1** [comment]
> What is the actual build error you're seeing? The pthread error looks like it's from one of the configuration tests, which are expected to have a large number fail, since the failures are how it determines what configuration flags are needed to build with.
The error Iwas seeing is 
/usr/bin/ld: src.c:(.text+0x52): undefined reference to pthread_detach' /usr/bin/ld: src.c:(.text+0x63): undefined reference to pthread_join'

**Comment by chenxue1** [comment]
The reason why I compile error maybe there is something not download complete, now I can compile it now
