### ISSUE TITLE
Bug about folly/lang/CheckedMath.h

### ISSUE THREAD

**Issue by ShiZhanHuang** [facebook/folly#1811]
In folly::detail::generic_checked_add

**Comment by ShiZhanHuang** [comment]
if (FOLLY_LIKELY(a < std::numeric_limits<T>::max() - b)) {
    ....
  } else {
    ....
  }
fix:
  if (FOLLY_LIKELY(a <= std::numeric_limits<T>::max() - b)) {
    ....
  } else {
    ....
  }

**Comment by AshleyHaw** [comment]
Try {Likely_Folly} 



<html>
