### ISSUE TITLE
Some dependent projects break: undefined reference to folly::detail::base64_detail::base64Decode_SSE4_2(char const*, char const*, char*)

### ISSUE THREAD

**Issue by yurivict** [facebook/folly#1823]
proxygen-2022.07.18.00 fails:
```
ld: error: /usr/local/lib/libfolly.so.0.58.0-dev: undefined reference to folly::detail::base64_detail::base64Decode_SSE4_2(char const*, char const*, char*) [--no-allow-shlib-undefined]
ld: error: /usr/local/lib/libfolly.so.0.58.0-dev: undefined reference to folly::detail::base64_detail::base64URLEncode_SSE4_2(char const*, char const*, char*) [--no-allow-shlib-undefined]
ld: error: /usr/local/lib/libfolly.so.0.58.0-dev: undefined reference to folly::detail::base64_detail::base64Encode_SSE4_2(char const*, char const*, char*) [--no-allow-shlib-undefined]
c++: error: linker command failed with exit code 1 (use -v to see invocation)
```

See https://github.com/facebook/proxygen/issues/419

clang-13
FreeBSD 13.1

**Comment by Orvid** [comment]
I suspect https://github.com/facebook/folly/commit/9d6acb35763d329d3fd6f4223ebf134f03e65d15 probably needed to be included for things to work. Could you try with that applied? If it works, I can release a patch version of folly and get everything else updated to that patch version.

**Comment by yurivict** [comment]
It fails the same way with this patch.

**Comment by rickkkyrich** [comment]
I am seeing the same issue when installing CacheLib 

make[2]: Leaving directory '/root/Desktop/Ritesh/new/CacheLib/build-folly'
[ 99%] Built target folly_exception_counter
../../../libfolly.so.0.58.0-dev: undefined reference to `folly::detail::base64_detail::base64Decode_SSE4_2(char const*, char const*, char*)'
../../../libfolly.so.0.58.0-dev: undefined reference to `folly::detail::base64_detail::base64Encode_SSE4_2(char const*, char const*, char*)'
../../../libfolly.so.0.58.0-dev: undefined reference to `folly::detail::base64_detail::base64URLEncode_SSE4_2(char const*, char const*, char*)'
collect2: error: ld returned 1 exit status
make[2]: *** [folly/logging/example/CMakeFiles/logging_example.dir/build.make:113: folly/logging/example/logging_example] Error 1
make[2]: Leaving directory '/root/Desktop/Ritesh/new/CacheLib/build-folly'
make[1]: *** [CMakeFiles/Makefile2:433: folly/logging/example/CMakeFiles/logging_example.dir/all] Error 2
make[1]: Leaving directory '/root/Desktop/Ritesh/new/CacheLib/build-folly'
make: *** [Makefile:130: all] Error 2
build-package.sh: error: make failed
build.sh: error: failed to build dependency 'folly'

**Comment by cho-m** [comment]
I also hit this issue building `folly` in Homebrew (https://github.com/Homebrew/homebrew-core/pull/106363) as our Linux runner builds `folly` with `-march=core2` (i.e. no SSE4.2).

At least in our failure with `v2022.07.18.00` tag, the following diff worked to avoid compilation of SSE4.2 code when it wasn't supported on target.
```diff
diff --git a/folly/detail/base64_detail/Base64Api.cpp b/folly/detail/base64_detail/Base64Api.cpp
index b02148a64..ad074525b 100644
--- a/folly/detail/base64_detail/Base64Api.cpp
+++ b/folly/detail/base64_detail/Base64Api.cpp
@@ -19,13 +19,13 @@
 #include <folly/detail/base64_detail/Base64Api.h>
 #include <folly/detail/base64_detail/Base64SWAR.h>
 
-#if FOLLY_X64
+#if FOLLY_X64 && FOLLY_SSE_PREREQ(4, 2)
 #include <folly/detail/base64_detail/Base64_SSE4_2.h>
 #endif
 
 namespace folly::detail::base64_detail {
 
-#if FOLLY_X64
+#if FOLLY_X64 && FOLLY_SSE_PREREQ(4, 2)
 Base64RuntimeImpl base64EncodeSelectImplementation() {
   if (folly::CpuId().sse42()) {
     return {
```

**Comment by Orvid** [comment]
Sorry it's taken so long to actually get this fix landed, https://github.com/facebook/folly/commit/437b29dd062a40c741b2147827025a2f413b76c7 should fix this issue.

**Comment by cho-m** [comment]
`v2022.07.25.00` fails to build for me in Homebrew environment on macOS (with `-march=nehalem` so SSE4.2 supported, AVX not):
```
Undefined symbols for architecture x86_64:
  "folly::detail::base64_detail::base64Decode_SSE4_2(char const*, char const*, char*)", referenced from:
      folly::detail::base64_detail::base64EncodeSelectImplementation() in Base64Api.cpp.o
...
```

---

Issues appear to be due to CMake logic that was previously referenced.
- One issue is `CMAKE_LIBRARY_ARCHITECTURE` is not guaranteed to be set. Testing on macOS, this appears to be empty.
- More important issue is the corresponding CMake logic that uses above value doesn't look right. The conditional uses `IS_X86_64_ARCH` but the actual behavior is for non-x86_64:
   https://github.com/facebook/folly/blob/6198adf4bdf9e971ecd0517592afcad86810ce7d/CMakeLists.txt#L235-L241

---

Also, I wanted to check how `-m` compiled code will handle running on non-SSE/AVX-compatible architectures:
https://github.com/facebook/folly/blob/6198adf4bdf9e971ecd0517592afcad86810ce7d/CMakeLists.txt#L254-L255

Does `folly` handle CPU runtime detection for all scenarios?

**Comment by rleshchinskiy** [comment]
It seems this test is the wrong way round? https://github.com/facebook/folly/blob/main/CMakeLists.txt#L233

**Comment by Orvid** [comment]
Everything around this should be fixed at this point as far as I know.
