### ISSUE TITLE
File.cpp:124:23: error: 'F_DUPFD_CLOEXEC' was not declared in this scope; did you mean 'FD_CLOEXEC'?

### ISSUE THREAD

**Issue by barracuda156** [facebook/folly#1833]
Compiling with `gcc12` on 10.6.8 for `ppc`, the build fails on:
```
/opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_folly/folly/work/folly-v2022.08.01.00/folly/File.cpp:124:23: error: 'F_DUPFD_CLOEXEC' was not declared in this scope; did you mean 'FD_CLOEXEC'?
  124 |     fd = ::fcntl(fd_, F_DUPFD_CLOEXEC, 0);
      |                       ^~~~~~~~~~~~~~~
      |                       FD_CLOEXEC
```

**Comment by barracuda156** [comment]
I have found a similar error with another port: https://lore.kernel.org/bpf/6af1530a-a4bf-dccf-947d-78ce235a4414@iogearbox.net/t/

A patch there suggests this:
```
+#ifndef F_DUPFD_CLOEXEC
+#define F_DUPFD_CLOEXEC 1030
+#endif
```

I have no idea if this value is applicable to `folly` case though.

**Comment by barracuda156** [comment]
Then, Darwin `xnu` has:
```
#if __DARWIN_C_LEVEL >= 200809L
#define F_DUPFD_CLOEXEC         67      /* mark the dup with FD_CLOEXEC */
#endif
```
https://opensource.apple.com/source/xnu/xnu-6153.41.3/bsd/sys/fcntl.h

**Comment by Orvid** [comment]
We only support the two most recent named versions of OSX, currently 11 (Big Sur) and 12 (Monterey), so breakages for ancient versions of OSX are expected.
