### ISSUE TITLE
Namespace "ranges" is introduced into the global namespace even when ranges-v3 is not present.

### ISSUE THREAD

**Issue by rdxroman** [facebook/folly#1853]
This change was introduced in this commit: d9fd5f23852294b665323f6b00e2d1744ea8f782

This creates a problem for projects that, as example, have alias ranges = std::ranges.

**Comment by yfeldblum** [comment]
This would be roughly equivalent to this header `#include`ing `<range/v3/...>`. Which we currently do in select places.
