### ISSUE TITLE
don't know how to install any packages on this system linux-pop!_os-22.04

### ISSUE THREAD

**Issue by omac777** [facebook/folly#1856]
```
$ sudo ./build/fbcode_builder/getdeps.py install-system-deps --recursive
I don't know how to install any packages on this system linux-pop!_os-22.04
```

**Comment by omac777** [comment]
To be honest, I was surprised to see a big company such as facebook not providing pre-built packages for folly if they were expecting other developers to adopt it as an industry standard.  The c++ side of folly/cxx-async could be integrated within boost and the rest of the rust side can remain in the existing recommended rust cxx-async crates.  This would help adoption a great deal as developers wouldn't have headaches to install folly.  They would only need to install boost-folly-dev as a package rather than deal with the complexities proposed in the facebook build python script.

Thank you for listening.

**Comment by Kundanagrawalofficial** [comment]
The command you provided, sudo ./build/fbcode_builder/getdeps.py install-system-deps --recursive, is used to install system dependencies for a specific project. The command installs the dependencies recursively, which means that it will install any dependencies of the dependencies as well.

However, it seems that you are using a specific Linux distribution, Pop!_OS 22.04 and the command you provided is specific to the project you are working on and may not work on other distributions.

To install system dependencies on Pop!_OS 22.04, you can use the package manager "apt" which is used to install, update and remove packages on Ubuntu and Debian based systems. Here is an example of how you can use apt to install a package:

Copy code
sudo apt-get install <package-name>
You can also use the "apt-cache search" command to search for available packages and "apt-cache show" command to show package information.

Copy code
sudo apt-cache search <package-name>
sudo apt-cache show <package-name>
If you are trying to install a specific library that is not available via apt, you can also try to download and install it manually.

Please note that you will need to be root (or use "sudo") to install system packages, and that it's always a good idea to keep your system up to date by running "sudo apt-get update" and "sudo apt-get upgrade" regularly.

You can also check the project documentation or readme file for more information about the dependencies that are required for the project you are working on.
