### ISSUE TITLE
error: no template named '__vector_base' in namespace 'std'

### ISSUE THREAD

**Issue by yurivict** [facebook/folly#1867]
```
In file included from /disk-samsung/freebsd-ports/devel/folly/work/folly-2022.09.26.00/folly/memory/test/UninitializedMemoryHacksTest.cpp:17:
/disk-samsung/freebsd-ports/devel/folly/work/folly-2022.09.26.00/folly/memory/UninitializedMemoryHacks.h:302:23: error: no template named '__vector_base' in namespace 'std'
    using Base = std::__vector_base<T, std::allocator<T>>;
                 ~~~~~^
```

Where is ```std::__vector_base``` specified?
https://en.cppreference.com/ doesn't have any information about it.

Version: 2022.09.26.00
FreeBSD 13.1

**Comment by Orvid** [comment]
It used to be defined in `<vector>` when using libc++, but it looks like newer versions of libc++ don't have it, so that bit of code will need to be reworked in order to build against the newer libc++ :(

**Comment by yfeldblum** [comment]
@yurivict Would you be able to test https://github.com/facebook/folly/pull/1912?
