### ISSUE TITLE
what is the required pair of folly and fmt versions?

### ISSUE THREAD

**Issue by chakpongchung** [facebook/folly#1870]
the changelog here says 

```
Upgrade folly to 2022.03.14.00 (from 2021.05.10.00).

Upgrade fmt to 8.0.0 (from 7.1.3).
```
but conda install cannot resolve it:

```
Encountered problems while solving:
  - package folly-2022.03.14.00-h1234567_1_jemalloc requires fmt >=8.1.1,<9.0a0, but none of the providers can be installed

```

https://facebookincubator.github.io/velox/monthly-updates/april-2022.html

**Comment by Orvid** [comment]
Please open this against the [velox repo](https://github.com/facebookincubator/velox) as the folly team doesn't maintain the  conda packages.
