### ISSUE TITLE
pedido de ajuda

### ISSUE THREAD

**Issue by savio27022022** [facebook/folly#1875]
gente, boa noite ! Meu nome é Sávio e eu sou aluno de Desenvolvimento de Sistemas .a professora passou um trabalho pra ser feito em Linguagem C só que eu não estou conseguindo fazer o código. A própria professora me disse que  eu poderia vir e pegar o código aqui e estudar ele pra fazer o trabalho. Alguém sabe me dizer como eu faço pra eu pedir esse código aqui no Github e alguém me  enviar o código? eu vou ver se mando aqui e me disponibilizam o código.

**Comment by kassane** [comment]
Hi Sávio,

I suggest you rewrite your problem situation to english please.
