### ISSUE TITLE
folly fails to build with nix on aarch64 due to defaulting to x86

### ISSUE THREAD

**Issue by keksbg** [facebook/folly#1880]
While updating a package I maintain over at the nixpkgs repository, I encountered a regression in the aarch64 build (found [here](https://github.com/NixOS/nixpkgs/pull/197592)). Digging further this led me to discovering this is a regression in folly.
It appears that, most likely, [the x86 platform check](https://github.com/facebook/folly/blob/main/CMakeLists.txt#L244) is somehow invalid, and causing build failures, like [here](https://logs.nix.ci/?key=nixos/nixpkgs.197592&attempt_id=5705b492-6506-4c8e-85f7-9de67c3a6a92)
<details>

```
[...]
-- Performing Test COMPILER_HAS_F_COROUTINES - Failed
-- GCC does not have support for C++ coroutines, disabling Folly coroutine support.
-- arch  matches x86_64, building SSE4.2 version of base64
-- Performing Test COMPILER_HAS_M_PCLMUL
-- Performing Test COMPILER_HAS_M_PCLMUL - Failed
-- compiler does not have flag pclmul, skipping setting compile flags for /build/source/folly/folly/hash/detail/ChecksumDetail.cpp;/build/source/folly/folly/hash/detail/Crc32CombineDetail.cpp;/build/source/folly/folly/hash/detail/Crc32cDetail.cpp
[...]
[ 17%] Building CXX object folly/CMakeFiles/folly_base.dir/folly/executors/CPUThreadPoolExecutor.cpp.o
g++: error: unrecognized command line option '-msse4.2'
[ 17%] Building CXX object folly/CMakeFiles/folly_base.dir/folly/executors/Codel.cpp.o
make[2]: *** [folly/CMakeFiles/folly_base.dir/build.make:832: folly/CMakeFiles/folly_base.dir/folly/detail/base64_detail/Base64_SSE4_2.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[...]
```

</details>

We have a hack to get it to work in the mean time, but this is a weird bug that should be fixed.

UPDATE: Apparently the issue stems from setting the `CMAKE_LIBRARY_ARCHITECTURE` to x86 *by default*, which is most definitely not a good approach considering you have x86-only build parameters that absolutely don't work on any other platform. 61d50e0010aee0f6c6a3b06a7a58173a6ab00926 should either be reverted, or the code be modified to default to something harmless.

**Comment by tpwrules** [comment]
This issue was fixed by https://github.com/facebook/folly/pull/1944, it can be closed.
