### ISSUE TITLE
Starting line

### ISSUE THREAD

**Issue by Elite843** [facebook/folly#1921]
Before addressing my issue I’d like to do some of the prerequisites. Could someone please direct me, scorecard etc?

**Comment by Kundanagrawalofficial** [comment]
It's great that you want to address your issue, but first want to understand the prerequisites. Here are a few steps that you can take to prepare yourself:

Familiarize yourself with the project: Before you can start addressing an issue, you need to understand the project and its architecture. This means reading the documentation, browsing the codebase, and experimenting with the software.

Understand the scoring system: Many open-source projects use a scoring system to prioritize issues. This system assigns points or levels to issues based on their complexity, priority, and impact. Understanding the scoring system will help you identify which issues you can tackle first.

Read the contributing guidelines: Every open-source project has different guidelines for contributing. It is important to read and follow these guidelines to ensure that your contributions are accepted.

Learn the development workflow: Many open-source projects use a specific development workflow, such as Git Flow, Github Flow, or GitLab Flow. Understanding the development workflow will help you navigate the codebase and make contributions effectively.

Get to know the community: Open-source projects are built and maintained by communities of developers. Joining the community and participating in discussions will help you understand the needs of the project and the goals of the community.

Look for good first issues: Many open-source projects have issues labeled as "good first issue" or "beginner-friendly". These issues are typically smaller in scope and simpler to solve, making them a great starting point for new contributors.

Look for mentorship programs: Some open-source projects have mentorship programs that pair new contributors with experienced developers. Participating in these programs can be a great way to learn and get guidance as you work on your first contributions.

Don't hesitate to reach out to the community, developers and maintainers, they are always happy to help and guide new contributors.

I hope these suggestions will help you to get started with your open-source journey.
