### ISSUE TITLE
Undefined symbols for architecture x86_64:   "folly::f14::detail::F14LinkCheck<(folly::f14::detail::F14IntrinsicsMode)1>::check()

### ISSUE THREAD

**Issue by panghaibo** [facebook/folly#1939]
Hi anybody who can help me with this , I try to use folly in my project, but when compiling project, occurs errors as follow:

Undefined symbols for architecture x86_64:
  "folly::f14::detail::F14LinkCheck<(folly::f14::detail::F14IntrinsicsMode)1>::check()", referenced from:
      folly::f14::detail::F14Table<folly::f14::detail::NodeContainerPolicy<folly::dynamic, folly::dynamic, folly::detail::DynamicHasher, folly::detail::DynamicKeyEqual, void> >::rehashImpl(unsigned long, unsigned long, unsigned long, unsigned long, unsigned long)::'lambda'()::operator()() const in server-89b8a6.o

btw, I use MacOS

**Comment by Orvid** [comment]
This is an intentional safety check that you're triggering. If Folly is built with SSE4.2 available then your project also needs to have SSE4.2 enabled, or else one side will be expecting F14 maps to be structured slightly differently than the other.

**Comment by xxr5566833** [comment]
> SSE4.2
how to make my project have SSE4.2 enabled?

**Comment by guyuqi** [comment]
> This is an intentional safety check that you're triggering. If Folly is built with SSE4.2 available then your project also needs to have SSE4.2 enabled, or else one side will be expecting F14 maps to be structured slightly differently than the other.



I also met this issue when build Velox on Arm64 Ubuntu-22.04.
I'm lucky to find your comments here. That's informative.  Thanks, @Orvid 

In Velox, I set CXX flags: `-march=armv8-a+crc+crypto` to enable simd.
In Folly,  I also enabled the SIMD:

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index ddfdc766e..8055fd27b 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -90,6 +90,10 @@ else()
   endif()
 endif()

+if(${CMAKE_SYSTEM_PROCESSOR} MATCHES "aarch64|AARCH64|ARM64|arm64")
+  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=armv8-a+crc+crypto")
+endif()
+
```

But it doesn't work.
Could you please help to give some further info? Thank you very much.

**Comment by guyuqi** [comment]
> This is an intentional safety check that you're triggering. If Folly is built with SSE4.2 available then your project also needs to have SSE4.2 enabled, or else one side will be expecting F14 maps to be structured slightly differently than the other.

That's informative.

**Comment by versusvoid** [comment]
I think there is some problem with check mechanism.

I build folly on my machine with `CXXFLAGS='-march=native'`, install it, then try to build edencommon with same CXXFLAGS and it fails, meaning there is some difference in SSE availability detection when building folly itself and another code which includes folly's headers.

gcc 13.2.1 20230801

**Comment by kinmioliu** [comment]
I encountered this issue when integrating Velox into my project. My env is an aarch64-ubuntu20.4 container hosted in M1-MAC.
I fixed that by adding '-mcpu=neoverse-n1' cxxflags at the top level CMakeLists.txt.
You should add '-msse4.2' if the env is X8664-arch.

**Comment by weimingdiit** [comment]
@guyuqi @versusvoid @kinmioliu  I also met this issue when build Velox, is there a final solution to this problem?

**Comment by wraymo** [comment]
@weimingdiit Did you fix the issue?
