### ISSUE TITLE
Build of folly fails on s390x (Linux on IBM zSystems)

### ISSUE THREAD

**Issue by karuvally** [facebook/folly#1951]
Hi Team,

I am trying to build folly on s390x platform (with Ubuntu 22.04 LTS as the distribution) but hitting the following error
```
aswin@xan1:~/folly-upstream$ python3 build/fbcode_builder/getdeps.py --allow-system-packages build
...
FAILED: CMakeFiles/folly_base.dir/folly/detail/base64_detail/Base64SWAR.cpp.o 
/usr/bin/c++ -DBOOST_ALL_NO_LIB -DFMT_LOCALE -DFOLLY_XLOG_STRIP_PREFIXES=\"/home/aswin/folly-upstream:/tmp/fbcode_builder_getdeps-ZhomeZaswinZfolly-upstreamZbuildZfbcode_builder/build/folly\" -DGFLAGS_IS_A_DLL=0 -D_GNU_SOURCE -D_REENTRANT -I/home/aswin/folly-upstream -I/tmp/fbcode_builder_getdeps-ZhomeZaswinZfolly-upstreamZbuildZfbcode_builder/build/folly -I/tmp/fbcode_builder_getdeps-ZhomeZaswinZfolly-upstreamZbuildZfbcode_builder/installed/fmt-DQmBm_iq6bthkmYOCFuykLrPRp5BZ5geX9lD0I9fm8g/include -O2 -g -DNDEBUG -fcoroutines -g -std=gnu++1z -finput-charset=UTF-8 -fsigned-char -Wall -Wno-deprecated -Wno-deprecated-declarations -Wno-sign-compare -Wno-unused -Wuninitialized -Wunused-label -Wunused-result -Wshadow-compatible-local -Wno-noexcept-type -faligned-new -fopenmp -std=gnu++17 -MD -MT CMakeFiles/folly_base.dir/folly/detail/base64_detail/Base64SWAR.cpp.o -MF CMakeFiles/folly_base.dir/folly/detail/base64_detail/Base64SWAR.cpp.o.d -o CMakeFiles/folly_base.dir/folly/detail/base64_detail/Base64SWAR.cpp.o -c /home/aswin/folly-upstream/folly/detail/base64_detail/Base64SWAR.cpp
/home/aswin/folly-upstream/folly/detail/base64_detail/Base64SWAR.cpp: In function ‘uint32_t folly::detail::base64_detail::{anonymous}::base64DecodeSWARMainLoop(const char*&, const char*, char*&)’:
/home/aswin/folly-upstream/folly/detail/base64_detail/Base64SWAR.cpp:107:14: error: static assertion failed: Big endian requires a redesigned table
  107 |       folly::kIsLittleEndian, "Big endian requires a redesigned table");
      |       ~~~~~~~^~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
Command '['/usr/bin/cmake', '--build', '/tmp/fbcode_builder_getdeps-ZhomeZaswinZfolly-upstreamZbuildZfbcode_builder/build/folly', '--target', 'install', '--config', 'Release', '-j', '1']' returned non-zero exit status 1.
!! Failed
```

Looking into the source code, the `folly/detail/base64_detail/Base64SWAR.cpp` file which is causing the error seems to be dealing with Base64 encoding / decoding and the `table` in the error is the lookup table implemented for the process.

Can someone from the community or folly team please provide some pointers on how to redesign the table for s390x, which is a big-endian platform?

Any help is appreciated 🙂 

Thanks!
Aswin

**Comment by Orvid** [comment]
The basic description of what SWAR decoding is actually doing is here: https://github.com/facebook/folly/tree/main/folly/detail/base64_detail#decoding-swar

The table it's referring to is built here: https://github.com/facebook/folly/blob/main/folly/detail/base64_detail/Base64HiddenConstants.h#L35

I would imagine it's mostly a matter of ensuring the bits end up in the right location. If there's not enough information in that, I can poke the original author more directly and see if he has any thoughts.

**Comment by karuvally** [comment]
Hi @Orvid,
Thanks for the response!
We are working to fix the issues with folly now.

Kind regards,
Aswin

**Comment by barracuda156** [comment]
@karuvally @Orvid Ah, so have there been any update on this matter?
