### ISSUE TITLE
how to tell whether the current thread is an folly::executor thread or not?

### ISSUE THREAD

**Issue by shiyu-bytedance** [facebook/folly#1977]
a general folly::executor question, is there a way to tell whether the current thread is an folly::executor thread or not?
For example, something like an API static folly::Executor* folly::executor::getExecutor(), which returns a nullptr if current thread is not an executor thread.

**Comment by yfeldblum** [comment]
This is not currently a facility supported by folly executors. In particular, in any given thread, there may be multiple executors at once.
