### ISSUE TITLE
Folly::folly not found

### ISSUE THREAD

**Issue by cedricai** [facebook/folly#1990]
find_package(Threads REQUIRED)
find_package(gflags REQUIRED)
find_package(glog REQUIRED)
add_subdirectory(third_party/folly) 
if(TARGET Folly::folly)
   message(STATUS "Folly found")
else()
   message(STATUS "Folly not found")
endif()

Folly::folly not found by using above commands in CMakeList.txt. What should I do to solve it?

**Comment by faithk7** [comment]
From line 429 - 431 in CmakeList.txt:

 add_library(folly
  $<TARGET_OBJECTS:folly_base>
)

The library target name is supposed to folly. So I think if you change the if statement (if(TARGET Folly::folly)
) to if(TARGET folly), you would get the "Folly Found" message.

**Comment by cedricai** [comment]
I mean，I need Folly::folly to link libraries to my library, but by means of add_subdirectory it doesn't generate Folly::folly. Besides, if I install folly and use find_package(Folly REQUIRED), this will generate Folly::folly. So I want to know how to generate Folly::folly by using add_subdirectory.

**Comment by Orvid** [comment]
There is no way currently to generate `Folly::folly` when using `add_subdirectory`, if you want to build things with `add_subdirectory`, you'll need to refer directly to `folly`, not `Folly::folly`.
