### ISSUE TITLE
Base64 test of folly passes on s390x (Linux on IBM zSystems)

### ISSUE THREAD

**Issue by karuvally** [facebook/folly#1993]
Hi Team,

This is to build upon an issue I raised previously within the community (https://github.com/facebook/folly/issues/1951) where we were having trouble building the folly library with s390x (Linux on IBM zSystems mainframe).

Specifically, we were having trouble due to an assertion in `folly/detail/base64_detail/Base64SWAR.cpp`, which checked if the host machine was big-endian (IBM zSystems are big-endian). I was advised to understand the SWAR table used in the Base64 decode process and adapt it for big-endian platform.

For debugging, I tried commenting out the assertion and built folly on s390x. Also, I tried pulling out `folly/test/base64_test.cpp` and built it manually. Strangely, the test succeeds when run.

```
Running main() from /root/vcpkg/buildtrees/gtest/src/v1.13.0-0674f4ed11.clean/googletest/src/gtest_main.cc
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from Base64Test
[ RUN      ] Base64Test.NormalTest
[       OK ] Base64Test.NormalTest (0 ms)
[----------] 1 test from Base64Test (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 1 test.
```

Can someone shed some light into why the test is succeeding on the big-endian IBM zSystems?
I was of understanding that the little-endian specific implementation of SWAR table used would cause the test to fail.

Thanks!

**Comment by Orvid** [comment]
I believe the initial lockout of big endian systems was out of precaution (since we don't have any readily accessible means of testing). If it's passing tests and working fine, we can probably just remove the assert that was keeping things from compiling on big endian hosts.

**Comment by karuvally** [comment]
Thanks @Orvid!
We will continue our tests and update here if we hit any endian related roadblocks :)

**Comment by barracuda156** [comment]
This may fix https://github.com/facebook/folly/issues/1834 perhaps for MacOS too. Let me try.
