### ISSUE TITLE
CPortability.h contains incorrect logic

### ISSUE THREAD

**Issue by tiagomacarios** [facebook/folly#2003]
Some preprocessor checks in  folly/folly/CPortability.h are bogus.
Using https://github.com/facebook/folly/blob/2aa5ba681d49a7e4f0cacdf2f95432f15fc9a12f/folly/CPortability.h#L74-L102 as a reference:

If a user compiles this with `-DFOLLY_SANITIZE_ADDRESS=0` the block on lines 84-98 will be parsed.
Most likely the intent was to `#if FOLLY_SANITIZE_ADDRESS` on line 83 instead.

This happens on multiples lines on this file: 83, 112, 129, 146, 164

**Comment by yfeldblum** [comment]
As a rule and across libraries, only select preprocessor symbols are publicly advertised as being configuration. All other preprocessor symbols are not configuration and must not be passed with `-D`.

In folly, `FOLLY_SANITIZE_ADDRESS` is not configuration and must not be passed.

**Comment by tiagomacarios** [comment]
@yfeldblum your comment does not make much sense. The code comment right above says this is configurable
