### ISSUE TITLE
question about installing dependencies

### ISSUE THREAD

**Issue by jinz2014** [facebook/folly#2004]
Which file does a user need to edit to disable the installation of certain dependencies (e.g. cmake) ?

I observe the following error, and would like to disable folly to install cmake. Thanks.

/usr/bin/ld: lib/libcmcurl.a(openssl.c.o): in function `ossl_connect_step1':
openssl.c:(.text+0x4128): undefined reference to `SSL_CTX_set_min_proto_version'
/usr/bin/ld: openssl.c:(.text+0x417c): undefined reference to `SSL_CTX_set_max_proto_version'
/usr/bin/ld: openssl.c:(.text+0x4968): undefined reference to `SSL_CTX_set_min_proto_version'
/usr/bin/ld: openssl.c:(.text+0x4978): undefined reference to `SSL_CTX_set_max_proto_version'

**Comment by yfeldblum** [comment]
This doesn't look like it's related to folly.
