### ISSUE TITLE
Does the iterator of ConcurrentSkipList support the -- operator?

### ISSUE THREAD

**Issue by wqshr12345** [facebook/folly#2013]
Hello!
I have a requirement to find the smallest element greater than a given key and the largest element smaller than the key.
Initially, I expected to use the lower_bound() method of Accessor to get the iterator of the first element greater than or equal to the key, and then decrement it to obtain the iterator of the first element smaller than the key. However, when I was writing the code, I found that the iterator does not support the -- operator. 
Do you have any good suggestions on how to implement my requirement? Thank you!

**Comment by Leumim2020** [comment]
Hi, do you can sent your code?

**Comment by Leumim2020** [comment]
> Hello!
> I have a requirement to find the smallest element greater than a given key and the largest element smaller than the key.
> Initially, I expected to use the lower_bound() method of Accessor to get the iterator of the first element greater than or equal to the key, and then decrement it to obtain the iterator of the first element smaller than the key. However, when I was writing the code, I found that the iterator does not support the -- operator. 
> Do you have any good suggestions on how to implement my requirement? Thank you!

Hi, do you can sent your code? because that makes it difficult to help

**Comment by Leumim2020** [comment]
> > Hello!
> > I have a requirement to find the smallest element greater than a given key and the largest element smaller than the key.
> > Initially, I expected to use the lower_bound() method of Accessor to get the iterator of the first element greater than or equal to the key, and then decrement it to obtain the iterator of the first element smaller than the key. However, when I was writing the code, I found that the iterator does not support the -- operator. 
> > Do you have any good suggestions on how to implement my requirement? Thank you!
> 
> Hi, do you can sent your code? because that makes it difficult to help

Because iterators has suport the ++, --, but depends in how you are make.

**Comment by yfeldblum** [comment]
Iterators are not all the same - [bidirectional iterators](https://en.cppreference.com/w/cpp/iterator/bidirectional_iterator) support decrement, but iterators which are not bidirectional, such as [forward iterators](https://en.cppreference.com/w/cpp/iterator/forward_iterator), support increment but not necessarily decrement.
