### ISSUE TITLE
[MSVC] Folly failed to build due to error C2338: static_assert failed: 'Cannot format an argument. To make type T formattable provide a formatter<T> specialization

### ISSUE THREAD

**Issue by Zhaojun-Liu** [facebook/folly#2018]
Hi All,

We use vcpkg to install and build folly. It failed due to below error, could you please take a look at this issue? Thanks.
`F:\gitP\microsoft\vcpkg\installed\x64-windows\include\fmt\core.h(1691): error C2338: static_assert failed: 'Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt'`

**Repro steps:**
1. git clone https://github.com/microsoft/vcpkg F:\gitP\Microsoft\vcpkg
2. cd /d F:\gitP\Microsoft\vcpkg
3. bootstrap-vcpkg.bat
4. set path=%cd%;%path%
5. vcpkg install folly:x64-windows --head --binarysource=clear

**Expected result:**
Build successfully.

OS: Windows server 2022
Detailed log: [build.log](https://github.com/facebook/folly/files/11783630/build.log)

**Comment by carlocab** [comment]
Likely due to https://github.com/facebook/folly/commit/a42f81880ada1c8f5cc342f9b438490978ee7cce. Probably not MSVC specific. It is, however, fmt 10-specific.

**Comment by Zhaojun-Liu** [comment]
Any update for this issue? Or workaround? 😃

**Comment by carlocab** [comment]
A workaround is to use fmt 9.

**Comment by Zhaojun-Liu** [comment]
> A workaround is to use fmt 9.
Thank you for looking this issue and reply. I tried the fmt 9.0.0, the issue still exists. I checked the attachment build.log, the fmt version is 9.1.0 like below image:
![image](https://github.com/facebook/folly/assets/103498042/34f8dc55-01ac-484c-b176-e7b0a0fe49d3)

**Comment by Zhaojun-Liu** [comment]
> A workaround is to use fmt 9.

Thank you for looking this issue and reply. I tried the fmt 9.0.0, the issue still exists. I checked the attachment build.log, the fmt version is 9.1.0 like below image:
![image](https://github.com/facebook/folly/assets/103498042/34f8dc55-01ac-484c-b176-e7b0a0fe49d3)

**Comment by Orvid** [comment]
This should be fixed by https://github.com/facebook/folly/commit/e74fe5c99dd9d96b80b17f8396ce2568f2becb45

**Comment by carlocab** [comment]
Thanks for the fix!

**Comment by Zhaojun-Liu** [comment]
Thanks for the fix ❤️
