### ISSUE TITLE
Can folly support localhost ?

### ISSUE THREAD

**Issue by jiangjiguang** [facebook/folly#2020]
when I use velox, I have the following exception message：
folly::IPAddressFormatException: Invalid IP address 'localhost'

**Comment by Orvid** [comment]
This is an issue with velox, not Folly. Please file this as an issue against velox. It may be worth it for them to special-case `localhost`. 

For now, wherever you have specified `localhost` in your config, you can replace it with `127.0.0.1` if it's for ipv4, or `::1` if it's an ipv6 field.
