### ISSUE TITLE
Installation with homebrew fails (Mac)

### ISSUE THREAD

**Issue by marnixhoh** [facebook/folly#2031]
I am trying to install `folly` on my Mac using homebrew: `brew install folly`. I need `folly`as it is a dependency of `watchman`.

Unfortunately it fails and I receive the following error:
```
Last 15 lines from /Users/xxx/Library/Logs/Homebrew/folly/02.cmake:
/tmp/folly-20230629-51773-87s7za/folly-2023.06.26.00/folly/io/async/fdsock/AsyncFdSocket.cpp:129:16: error: cannot initialize object parameter of type 'folly::AsyncSocket' with an expression of type 'folly::AsyncFdSocket'
  AsyncSocket::setSendMsgParamCB(&sendMsgCob_);
               ^~~~~~~~~~~~~~~~~
/tmp/folly-20230629-51773-87s7za/folly-2023.06.26.00/folly/io/async/fdsock/AsyncFdSocket.cpp:136:16: error: cannot initialize object parameter of type 'folly::AsyncSocket' with an expression of type 'folly::AsyncFdSocket'
  AsyncSocket::releaseIOBuf(std::move(buf), callback);
               ^~~~~~~~~~~~
/tmp/folly-20230629-51773-87s7za/folly-2023.06.26.00/folly/io/async/fdsock/AsyncFdSocket.cpp:298:18: error: cannot initialize object parameter of type 'folly::AsyncSocket' with an expression of type 'folly::AsyncFdSocket'
    AsyncSocket::failRead(__func__, ex);
                 ^~~~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [CMakeFiles/folly_base.dir/folly/io/async/fdsock/AsyncFdSocket.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/folly_base.dir/all] Error 2
make: *** [all] Error 2
```

Thank you so much for any help or guidance! :)

PS My mac is running on `macOS 10.15`, which is officially no longer supported by homebrew. Nevertheless, I hope there is some sort of solution / workaround.

**Comment by Di3go-Opr3a** [comment]
I really think the problem is because it is no longer supported. Have you tried if to see if it is possible to upgrade your macOs ? Otherwise, you can try using a version manager such as "asdf" or "pyenv" to handle different versions of dependencies

**Comment by marnixhoh** [comment]
@Di3go-Opr3a Thank you for your reply! Unfortunately, upgrading my os is not possible as my Macbook Pro does not support any newer versions of macOs...

Yeah I was considering that but the problem is that I can't seem to find folly's changelog anywhere. So I can't check which version might work for me

**Comment by Di3go-Opr3a** [comment]
@marnixhoh look I tried to search a little, but precisely I can not tell you however I found this !
Practically reading problems of other users it seems that your version is compatible with folly of 2021. So i suggest you to try some version of 2021 to see if it works:
version: https://github.com/facebook/folly/releases?page=8
supporto macOS #1545 
2021.03.08.00 #72752

**Comment by marnixhoh** [comment]
@Di3go-Opr3a Thank you sooo much for digging into this for me. I tried installing the version of `Folly` at the time of #1545  and it worked!

It would be really nice if `Folly`'s changelog would be public somewhere, so I could find the last version that is supported for my OS. Oh well...

Thank you so much again!! Really appreciate it 😄

**Comment by sid-bhargav** [comment]
@marnixhoh @Di3go-Opr3a Hi! I apologize if this is sort of stupid question but I'm having the same issue as you and since I'm new to macOS I'm a little bit confused about what to do.

How do I install an older release of folly? And when I try to install watchman with homebrew once more will it not try to update my installation of folly?

Again, I apologize if these are trivial questions. I have struggled to understand what to Google and where to learn how to do this, so any guidance on where to learn more about this would also be greatly appreciated.

Thanks for your time.

**Comment by marnixhoh** [comment]
Hi @sid-bhargav! Let me quickly try to help you out here ;)

Installing older versions of software with `homebrew` is notoriously cumbersome, but it can be done. I recommend checking out this link: https://github.com/orgs/Homebrew/discussions/155#discussioncomment-133894

To your next question, I just found that out myself, after I successfully installed an older version of `folly`... When installing the latest or even older versions of a package through `homebrew`, it will download the latest version of its dependencies. This effectively means that installing `watchman` through `homebrew` with an older version of `folly` is not possible. (at least not to my knowledge.)

I hope I have answered your questions here and if you do end up finding a way to install `watchman` with an older version of `folly` using `homebrew` then please let me know 😄

**Comment by sryze** [comment]
I have the same issue with upgrading folly on Catalina (it's a dependency of a package that I have previously installed).

But what's funny is that I can build the same version of folly (v2023.10.02.00) successfully from git with the same cmake flags as Homebrew uses.

**Comment by marnixhoh** [comment]
@sryze I have no idea how you have found that workaround, but thank you so much! 🚀 

I think you meant this though (wrong version number):
```
sudo nano /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/i386/_param.h
```

**Comment by sryze** [comment]
Ah, yes, I meant 10.15. Glad that it helped you 😃

**Comment by Tony-MK** [comment]
@sryze, Thank you so much. 😄 🚀
It worked on my Mac, which is running macOS 10.15.7.

**Comment by Paras534** [comment]
i had also done this but it gives me still this:

Last 15 lines from /Users/Paras/Library/Logs/Homebrew/folly/02.cmake:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/netinet/in.h:659:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/netinet6/in6.h:171:2: error: unknown type name 'sa_family_t'
        sa_family_t     sin6_family;    /* AF_INET6 (sa_family_t) */
        ^
In file included from /tmp/folly-20231130-4920-ztd55l/folly-2023.11.27.00/folly/FileUtil.cpp:26:
In file included from /tmp/folly-20231130-4920-ztd55l/folly-2023.11.27.00/folly/net/NetOps.h:99:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/un.h:78:2: error: unknown type name 'sa_family_t'
        sa_family_t     sun_family;     /* [XSI] AF_UNIX */
        ^
11 errors generated.
make[2]: *** [CMakeFiles/folly_base.dir/folly/FileUtil.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/folly_base.dir/all] Error 2
make: *** [all] Error 2

**Comment by barracuda156** [comment]
`folly` has been broken by a few commits in the beginning of 2023. See: https://github.com/facebook/folly/issues/2099

**Comment by barracuda156** [comment]
@marnixhoh Well, even if that works to bypass the problem at hand, hacking the SDK is not something desirable, and is likely to cause unknown number of breakages, since no software will expect that.

**Comment by barracuda156** [comment]
Perhaps placing something like this in an appropriate `folly` header gonna work:
```
#if defined(__APPLE__) && MAC_OS_X_VERSION_MIN_REQUIRED < 110000
#ifdef __DARWIN_ALIGN32
#undef __DARWIN_ALIGN32
#define __DARWIN_ALIGN32(p) ((__darwin_size_t)((__darwin_size_t)(p) + __DARWIN_ALIGNBYTES32) &~ __DARWIN_ALIGNBYTES32)
#endif
#endif
```

**Comment by barracuda156** [comment]
Adding this to `folly/io/async/fdsock/AsyncFdSocket.h`:
```
#ifdef __APPLE__
#include <AvailabilityMacros.h>
#if MAC_OS_X_VERSION_MIN_REQUIRED < 110000
#ifdef __DARWIN_ALIGN32
#undef __DARWIN_ALIGN32
#define __DARWIN_ALIGN32(p) ((__darwin_size_t)((__darwin_size_t)(p) + __DARWIN_ALIGNBYTES32) &~ __DARWIN_ALIGNBYTES32)
#endif
#endif
#endif
```
@sryze Thank you for finding the cause of the problem!
