### ISSUE TITLE
makeFuture exception

### ISSUE THREAD

**Issue by jiazho** [facebook/folly#2041]
### compiler env
gcc830 x86_64

### folly version
https://github.com/facebook/folly/releases/tag/v2018.08.20.00

### code to repro
```
struct S {
  int code = 0;
  std::string title;
};
folly::Future<S> Func() {
  return folly::makeFuture<S>({
    .code = 0,
    .title = "test_title",
  });
}
int main(int argc, char** argv) {
  Func().then([](folly::Try<S> &&ret) {
    if (ret.hasException()) {
      std::cout << "has exception" << std::endl; // here
    } else {
      std::cout << "no exception" << std::endl;
    }
  });
  Func().then([](S &&ret) {
    std::cout << "ok" << std::endl;
  });
  return 0;
}
```
only the “has exception” line is output to the screen...
Could you shed some light here?

**Comment by yfeldblum** [comment]
It is expected to be called as:

```
return folly::makeFuture(S{
  .code = 0,
  .title = "test_title",
});
```

Where the argument passed is not a brace-enclosed initializer list but rather is (a reference to) the actual value-type, and where the parameter type is deduced. `makeFuture(S{...})` v.s. `makeFuture<S>({...})`.
