### ISSUE TITLE
packit PR for rpm-build copr build failures, please take a look

### ISSUE THREAD

**Issue by ahornby** [facebook/folly#2082]
https://pagure.io/meta/folly/pull-request/1 removes a patch that is failing to apply and breaking the COPR builds in github actions

**Comment by ahornby** [comment]
@Orvid is fixing rpm build via copr the right place to raise the PR?

**Comment by Orvid** [comment]
I don't actually appear to have access to that, but that is probably the right location. Give me a bit to figure out who actually has access to be able to merge that.

**Comment by Orvid** [comment]
I've found the right person to merge it, but they're currently on holiday so it may be a bit before it can be merged.
