### ISSUE TITLE
Is ConcurrentHashMap read lock-free?

### ISSUE THREAD

**Issue by NoWarnNoError** [facebook/folly#2103]
when I read the ConcurrentHashMap implementation, the ConcurrentHashMap's _operator[]_ will finally call 
"_ensureSegment(segment)->insert(res.first.it_, h, std::move(foo));_", which uses _BucketTable's_ _doInsert_ function. And at the function begining, has a  _unique_lock_. So I think ConcurrentHashMap's read is not lock-free. Do I get mistake on this question?

**Comment by instw** [comment]
Technically ConcurrentHashMap reads are indeed lock-free (and wait-free). An operation like `find()` will does not need to lock a bucket.

However the `operator[]` is not a read-only operation. Similar to a regular `std::unordered_map`, doing a `auto& value = map[5];` when `5` doesn't exist would result in creating an entry for key = 5 with default constructing it's value, and then returning a reference to that value. 
An alternative would be to use `map.at(5)` which is indeed lock-free.
