### ISSUE TITLE
[MSVC] Folly failed due to error C7555: use of designated initializers requires at least '/std:c++20'

### ISSUE THREAD

**Issue by NEIL-smtg** [facebook/folly#2138]
Hi all,

We are using vcpkg to install and build Folly. It failed due to the following error: 

`\folly\experimental\io\MuxIOThreadPoolExecutor.cpp(58): error C7555: use of designated initializers requires at least '/std:c++20'`

Could you please take a look at this issue? Thanks.

**Repro steps:**

1. git clone https://github.com/microsoft/vcpkg F:\gitP\Microsoft\vcpkg
2. cd /d F:\gitP\Microsoft\vcpkg
3. bootstrap-vcpkg.bat 2>&1
4. set path=%cd%;%path%
5.  vcpkg install folly:x64-windows --head --binarysource=clear 2>&1

**Expected result:**
Build successfully.

**OS**: Windows Server 2022
**Detailed log**: [build.log](https://github.com/facebook/folly/files/14159975/build.log)

**Comment by Orvid** [comment]
This should be fixed by https://github.com/facebook/folly/commit/8901d8274d2fd6ed35d55f874542ed0f5dd5573a.
