### ISSUE TITLE
How should I run folly on riscv64?

### ISSUE THREAD

**Issue by JasenChao** [facebook/folly#2173]
I see riscv support in the code, and when I want to run folly on riscv64, I find that the `FOLLY_HAVE_INT128_T` is undef, how do I start it?

**Comment by Orvid** [comment]
@luhenry Since you added the initial support, do you have any ideas here?

**Comment by JasenChao** [comment]
I passed the `-DFOLLY_HAVE_INT128_T=1` option in cmake, I wonder if that makes sense and if there are any other `define` to be needed?  It just seems to compile successfully.

**Comment by luhenry** [comment]
It depends if you're building folly as part of your cmake build or if you're using it as an installed dependency.

In case you're building folly as part of your cmake build, you can add a `set(FOLLY_HAVE_INT128_T 1)` before doing your `FetchContent_MakeAvailable`. See https://github.com/facebookincubator/velox/blob/main/CMake/resolve_dependency_modules/folly/CMakeLists.txt#L46 for example.

And in case you're using an installed folly (via `find_package` for example), then you would need to do `add_compile_definitions(FOLLY_HAVE_INT128_T=1)` as you've suggested.

**Comment by JasenChao** [comment]
> It depends if you're building folly as part of your cmake build or if you're using it as an installed dependency.
> 
> In case you're building folly as part of your cmake build, you can add a `set(FOLLY_HAVE_INT128_T 1)` before doing your `FetchContent_MakeAvailable`. See https://github.com/facebookincubator/velox/blob/main/CMake/resolve_dependency_modules/folly/CMakeLists.txt#L46 for example.
> 
> And in case you're using an installed folly (via `find_package` for example), then you would need to do `add_compile_definitions(FOLLY_HAVE_INT128_T=1)` as you've suggested.

Got it. Thank you.
