### ISSUE TITLE
Configure error libssl required. Already installed libssl-dev on Ubuntu 14.04

### ISSUE THREAD

**Issue by Geekrick88** [facebook/folly#219]
I am trying to use folly with fbcunn. I have cloned the latest repo. However upon configuration I am receiving the following error 
checking for SSL_ctrl in -lssl... no
configure: error: "Error: libssl required"

I have checked and checked, it seems libssl-dev is installed properly. A locate returns the following directories

/lib/i386-linux-gnu/libssl.so.1.0.0
/lib/x86_64-linux-gnu/libssl.so.1.0.0
/usr/lib/x86_64-linux-gnu/libssl.so
/usr/local/MATLAB/R2015a/bin/glnxa64/libssl.so.1
/usr/local/MATLAB/R2015a/bin/glnxa64/libssl.so.1.0.0

Any help regarding this issue?

**Comment by sgolemon** [comment]
Could you paste the section of your `config.log` file where it's checking for ssl?

Roughly from this line `configure:16561: checking for SSL_ctrl in -lssl` to this one `configure:16658: checking for boostlib >= 1.51.0`

**Comment by vadimkantorov** [comment]
I fixed a similar issue by exporting LIBS='-lcrypto -ldl' before configure

**Comment by qizhuli** [comment]
@vadimkantorov I had the same problem and your solution works! Thanks for sharing!

**Comment by Jockey1993** [comment]
I had the same problem ,how do you to resolve it?Thank you ! @Geekrick88

**Comment by Jockey1993** [comment]
i can't get your word ,how to export LIBS='-lcrypto -ldl' before configure,in my ~.bashrc  file? Thank you! @vadimkantorov @qizhuli

**Comment by lessSleep** [comment]
> i can't get your word ,how to export LIBS='-lcrypto -ldl' before configure,in my ~.bashrc file? Thank you! @vadimkantorov @qizhuli

wget https://ftp.openssl.org/source/openssl-1.1.1k.tar.gz
tar -xzvf openssl-1.1.1k.tar.gz
cd openssl-1.1.1k
./config --prefix=/usr --openssldir=/etc/ssl --libdir=lib no-shared zlib-dynamic
make install
export LD_LIBRARY_PATH=/usr/lib

**Comment by lessSleep** [comment]
try 
wget https://ftp.openssl.org/source/openssl-1.1.1k.tar.gz
tar -xzvf openssl-1.1.1k.tar.gz
cd openssl-1.1.1k
./config --prefix=/usr --openssldir=/etc/ssl --libdir=lib no-shared zlib-dynamic
make install
export LD_LIBRARY_PATH=/usr/lib
