### ISSUE TITLE
error: 'struct tcp_info' has no member named 'tcpi_total_retrans'

### ISSUE THREAD

**Issue by ffmpbgrnn** [facebook/folly#221]
Hi,
I am using Centos 5.6, and the kernel I am running doesn't support `tcpi_total_retrans`. Can you please take time to fix this?

Thank you very much!

**Comment by ffmpbgrnn** [comment]
Hi,
I pass this error by change `folly/wangle/acceptor/TransportInfo.cpp:L23 `to `#if defined(__linux__) && defined(__FreeBSD__)`.
When I run `make check`, I met the #205 and followed @fifilyu's solution, it works!
But the final test report is frustrating, none tests passed. And the error is `ELF file OS ABI invalid`
I am running Centos 5.6 with gcc4.9.2. 

Thank you in advance for your great help!

**Comment by sgolemon** [comment]
64f036b4965a0338d5ff7e30cd673982d993848d may have resolved this, could you pull and try compiling again?

**Comment by ffmpbgrnn** [comment]
Hi,
It passed compile and still failed when link to the shared library. The error was `ELF file OS ABI invalid`.
Thank you!

**Comment by sgolemon** [comment]
The OS ABI error is unrelated to tcpi_total_retrans issue.
I'm really not sure why that would be happening at all.
You're not building on one machine and trying to run on another, are you?

What's the output of these commands?

```
file folly/.libs/libfolly.a
file folly/.libs/libfolly.so
ldd folly/.libs/libfolly.so
```

**Comment by ffmpbgrnn** [comment]
No, I build and run on the same machine. I use the the following commands to build
```bash
./configure --prefix=$HOME --enable-shared --with-boost-libdir=$HOME/lib --libdir=$HOME/lib CFLAGS="-fPIC" CXXFLAG="-fPIC"
make -j10 && make install
```
And the result of those commands are
```bash
$ file folly/.libs/libfolly.a
folly/.libs/libfolly.a: current ar archive
$ file folly/.libs/libfolly.so.47.0.0
folly/.libs/libfolly.so.47.0.0: ELF 64-bit LSB shared object, AMD x86-64, version 1 (GNU/Linux), not stripped
$ ldd folly/.libs/libfolly.so
        not a dynamic executable
```
I am using gcc4.9.2 in Centos 5.6.
Thank you for your help!

**Comment by ffmpbgrnn** [comment]
Also, there are several warnings during the building process:
```bash
libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
libtool: warning: '/home/archy/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../libsnappy.la' seems to be moved
libtool: warning: '/home/archy/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../libevent.la' seems to be moved
libtool: warning: '/home/archy/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../libgflags.la' seems to be moved
libtool: warning: '/home/archy/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../libglog.la' seems to be moved
libtool: warning: '/home/archy/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib64/libstdc++.la' seems to be moved

libtool: warning: relinking 'libfollybenchmark.la'
libtool: install: (cd /home/archy/torch/pkg/folly/folly; /bin/sh "/home/archy/torch/pkg/folly/folly/libtool"  --tag CXX --mode=relink /home/archy/bin/g++ -std=gnu++0x -g -O2 -lboost_context -lboost_thread -lboost_filesystem -lboost_system -lboost_regex -lpthread -version-info 47:0:0 -o libfollybenchmark.la -rpath /home/archy/lib Benchmark.lo libfolly.la -lz -lsnappy -lrt -levent -ldouble-conversion -lssl -lgflags -lglog )
libtool: warning: '/home/archy/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../libsnappy.la' seems to be moved
libtool: warning: '/home/archy/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../libevent.la' seems to be moved
libtool: warning: '/home/archy/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../libgflags.la' seems to be moved
libtool: warning: '/home/archy/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../libglog.la' seems to be moved
libtool: warning: '/home/archy/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib64/libstdc++.la' seems to be moved
```

**Comment by sgolemon** [comment]
Ah.... that last comment provides a good clue.  libtool might not be updating the shlib paths when it installs libfolly.so (I assume you're running `sudo make install` and not manually copying the files or anything).
