### ISSUE TITLE
error in Format.md

### ISSUE THREAD

**Issue by jacobwpeng** [facebook/folly#228]
std::map<std::string, std::string> m { {"what", "answer"}, {"value", "42"} };
std::string result = svformat("The only {0[what]} is {0[value]}", m);
// => "The only answer is 42"

This format is invalid, it causes a core dump after std::map::at throw a std::out_of_range exception.
This is a container mode format, and each argument has a index and a key, but the key is overwritten by index(parsed from piece(Format-inl.h:225)), so it tries to find a key "0" from m, but not exists.

**Comment by jacobwpeng** [comment]
And possible fix maybe add "if (arg.keyEmpty())" before "arg.setNextKey(piece);" since we never want to overwrite the saved key.

**Comment by sgolemon** [comment]
Nice catch.  The fix for this is up for review internally and should land shortly: D2184334

Like, really shortly. :p
