### ISSUE TITLE
modularity of the 'library'

### ISSUE THREAD

**Issue by micpub** [facebook/folly#2288]
currently there is no way to build / easily use a part of the folly, for example if i wanted to use just a 'Synchronized' or something other - it is impossible right now without taking everything (with deps).
BUCK seems to have defined many targets 'synchronized' included but is there a way to use it?
cmake 'projects' doesnt seem to offer such functionality.

is there a need for everyone to 
`gcc -I. -MM folly/Synchronized.h`
later to find cpp files manually and creating library?

**Comment by yfeldblum** [comment]
There is an effort to make the `BUCK` files work for the public build in addition to the internal build. If your own build uses buck, this could be helpful.

But I don't think we would be able to split up the cmake build finely the way we can split up the buck build.

**Comment by micpub** [comment]
it would still be nice to be able to build static lib using BUCK that has only the functionality that i need.
i would later be able to just link to it in the cmake.
it would mean that  it would have less deps (third party libs)
