### ISSUE TITLE
Is it necessary to require autoreconf during build?

### ISSUE THREAD

**Issue by eherot** [facebook/folly#237]
X-posted (by request) from `mcrouter` (original issue: facebook/mcrouter#69):

Is there a reason you guys chose not to run `autoreconf --install` against the source tree before zipping it up? Deviating from the standard `./configure && make && make install` procedure is kind of an anti-pattern and prevents me from being able to use a handy built-in build action in the ark cookbook (for Chef).

See: http://stackoverflow.com/questions/19263899/why-is-autoreconf-not-used-often

Same goes for the `folly` project...

**Comment by sgolemon** [comment]
As a matter of fact... we don't zip it up.  The tarball you get from github is made dynamically by github from the sources for a given tag.

There's a number of things I'm looking into improving about folly (I just took the project over a few weeks ago).  One is the versioning scheme (which sucks), the other is the build system (which is a mess).

If you have specific pain points (like the lack of a checked in ./configure file), I can incorporate that into my process.

**Comment by eherot** [comment]
As mentioned in facebook/mcrouter#69, the inclusion of the `autoreconf --install` command into an `autogen.sh` script would probably be sufficient for my needs.

**Comment by Orvid** [comment]
As a random note, it would be nice for projects like HHVM if CMake were used instead, but that would be a complete change in the build system, and I would imagine is not very likely to happen.
