### ISSUE TITLE
Fails to build with Ubuntu 15.04

### ISSUE THREAD

**Issue by js7222** [facebook/folly#240]
Here is the output from trying to build folly, boost version is 1.58. Interestingly works on another machine with a similar setup. Haven't actually tried debugging the issue at all yet.

make  all-recursive
make[1]: Entering directory '/home/james/folly/folly'
Making all in .
make[2]: Entering directory '/home/james/folly/folly'
./generate_fingerprint_tables
depbase=`echo futures/Future.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I./.. -pthread -I/usr/include   -std=gnu++0x -g -O2 -MT futures/Future.lo -MD -MP -MF $depbase.Tpo -c -o futures/Future.lo futures/Future.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
depbase=`echo io/async/AsyncTimeout.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I./.. -pthread -I/usr/include   -std=gnu++0x -g -O2 -MT io/async/AsyncTimeout.lo -MD -MP -MF $depbase.Tpo -c -o io/async/AsyncTimeout.lo io/async/AsyncTimeout.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
depbase=`echo io/async/AsyncUDPSocket.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I./.. -pthread -I/usr/include   -std=gnu++0x -g -O2 -MT io/async/AsyncUDPSocket.lo -MD -MP -MF $depbase.Tpo -c -o io/async/AsyncUDPSocket.lo io/async/AsyncUDPSocket.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
depbase=`echo io/async/AsyncServerSocket.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I./.. -pthread -I/usr/include   -std=gnu++0x -g -O2 -MT io/async/AsyncServerSocket.lo -MD -MP -MF $depbase.Tpo -c -o io/async/AsyncServerSocket.lo io/async/AsyncServerSocket.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++0x -g -O2 -MT futures/Future.lo -MD -MP -MF futures/.deps/Future.Tpo -c futures/Future.cpp  -fPIC -DPIC -o futures/.libs/Future.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++0x -g -O2 -MT io/async/AsyncTimeout.lo -MD -MP -MF io/async/.deps/AsyncTimeout.Tpo -c io/async/AsyncTimeout.cpp  -fPIC -DPIC -o io/async/.libs/AsyncTimeout.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++0x -g -O2 -MT io/async/AsyncUDPSocket.lo -MD -MP -MF io/async/.deps/AsyncUDPSocket.Tpo -c io/async/AsyncUDPSocket.cpp  -fPIC -DPIC -o io/async/.libs/AsyncUDPSocket.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++0x -g -O2 -MT io/async/AsyncServerSocket.lo -MD -MP -MF io/async/.deps/AsyncServerSocket.Tpo -c io/async/AsyncServerSocket.cpp  -fPIC -DPIC -o io/async/.libs/AsyncServerSocket.o
In file included from ./../folly/io/async/EventHandler.h:24:0,
                 from ./../folly/io/async/AsyncServerSocket.h:20,
                 from io/async/AsyncServerSocket.cpp:21:
./../folly/io/async/EventUtil.h: In static member function 'static bool folly::EventUtil::isEventRegistered(const event*)':
./../folly/io/async/EventUtil.h:38:17: error: 'const struct event' has no member named 'ev_flags'
     return (ev->ev_flags & EVLIST_REGISTERED);
                 ^
In file included from io/async/AsyncTimeout.cpp:23:0:
./../folly/io/async/EventUtil.h: In static member function 'static bool folly::EventUtil::isEventRegistered(const event*)':
./../folly/io/async/EventUtil.h:38:17: error: 'const struct event' has no member named 'ev_flags'
     return (ev->ev_flags & EVLIST_REGISTERED);
                 ^
In file included from io/async/AsyncTimeout.cpp:26:0:
io/async/AsyncTimeout.cpp: In static member function 'static void folly::AsyncTimeout::libeventCallback(int, short int, void*)':
io/async/AsyncTimeout.cpp:147:27: error: 'struct event' has no member named 'ev_flags'
   assert((timeout->event_.ev_flags & ~EVLIST_INTERNAL) == EVLIST_INIT);
                           ^
Makefile:1203: recipe for target 'io/async/AsyncTimeout.lo' failed
make[2]: *** [io/async/AsyncTimeout.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from ./../folly/io/async/EventHandler.h:24:0,
                 from ./../folly/io/async/AsyncUDPSocket.h:23,
                 from io/async/AsyncUDPSocket.cpp:17:
./../folly/io/async/EventUtil.h: In static member function 'static bool folly::EventUtil::isEventRegistered(const event*)':
./../folly/io/async/EventUtil.h:38:17: error: 'const struct event' has no member named 'ev_flags'
     return (ev->ev_flags & EVLIST_REGISTERED);
                 ^
Makefile:1203: recipe for target 'io/async/AsyncUDPSocket.lo' failed
make[2]: *** [io/async/AsyncUDPSocket.lo] Error 1
Makefile:1203: recipe for target 'io/async/AsyncServerSocket.lo' failed
make[2]: *** [io/async/AsyncServerSocket.lo] Error 1

**Comment by rklabs** [comment]
Please check the libevent version on your Ubuntu system. Below link may help

https://github.com/facebook/hhvm/issues/3871

**Comment by js7222** [comment]
I downgraded to libevent to release-2.0.22-stable and it compiles fine. Is there a plan to have this support 2.1.* versions of libevent?

**Comment by datosh** [comment]
Hey I'm having similar problem. 

make  all-recursive
make[1]: Entering directory '/home/datosh/Documents/git/folly/folly'
Making all in .
make[2]: Entering directory '/home/datosh/Documents/git/folly/folly'
depbase=`echo futures/Future.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I./.. -pthread -I/usr/include   -std=gnu++0x -g -O2 -MT futures/Future.lo -MD -MP -MF $depbase.Tpo -c -o futures/Future.lo futures/Future.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++0x -g -O2 -MT futures/Future.lo -MD -MP -MF futures/.deps/Future.Tpo -c futures/Future.cpp  -fPIC -DPIC -o futures/.libs/Future.o
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Makefile:1265: recipe for target 'futures/Future.lo' failed
make[2]: *** [futures/Future.lo] Error 1
make[2]: Leaving directory '/home/datosh/Documents/git/folly/folly'
Makefile:1321: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/datosh/Documents/git/folly/folly'
Makefile:846: recipe for target 'all' failed
make: *** [all] Error 2


Although I have libevent-2.0.* installed

apt --installed list | grep libevent

WARNING: apt does not have a stable CLI interface yet. Use with caution in scripts.

libevent-2.0-5/wily,now 2.0.21-stable-2 amd64 [installed,automatic]
libevent-core-2.0-5/wily,now 2.0.21-stable-2 amd64 [installed,automatic]
libevent-dev/wily,now 2.0.21-stable-2 amd64 [installed]
libevent-extra-2.0-5/wily,now 2.0.21-stable-2 amd64 [installed,automatic]
libevent-openssl-2.0-5/wily,now 2.0.21-stable-2 amd64 [installed,automatic]
libevent-pthreads-2.0-5/wily,now 2.0.21-stable-2 amd64 [installed,automatic]

Any ideas what I can try for a fix?

**Comment by abhiguru** [comment]
Getting a runtime segfault with libevent - 2.0.21-stable-2ubuntu0.16.04.1 AARM-64
