### ISSUE TITLE
Latest release fails to configure on ubuntu 14.04.1 LTS

### ISSUE THREAD

**Issue by kevinquinnyo** [facebook/folly#291]
I have not looked into this deeply yet -- I'm about to.  I suspect however, that this commit might be responsible:

https://github.com/facebook/folly/commit/838cf14637f0c50fd8596a3de50c0fe79ab21735

The configure error:
```
[..snip..]
checking for boostlib >= 1.51.0... yes
checking whether the Boost::Context library is available... yes
checking for exit in -lboost_context... yes
checking whether the Boost::Program_Options library is available... yes
configure: error: Could not link against boost_context !
```

This happens when it is installed as a dependency of mcrouter via the mcrouter script installation - `install_ubuntu_14.04.sh`

It worked last week for me without issues on several identical ubuntu 14.04.1 LTS.

I'll see if I can figure out what's going on, but I figured I'd open the issue here in case someone else might already know what the solution is.

**Comment by kevinquinnyo** [comment]
I can at least confirm that it works if I checkout the previous tagged release:

`git checkout 8cf17bb`

**Comment by kevinquinnyo** [comment]
This is looking more like a problem in https://github.com/facebook/mcrouter/blob/master/mcrouter/scripts/install_ubuntu_14.04.sh

I see.  It just needs program options, libboost-program-options1.54-dev

https://github.com/facebook/mcrouter/pull/76 should resolve it

**Comment by jeffbyrnes** [comment]
While [facebook/mcrouter#76’s](https://github.com/facebook/mcrouter/pull/76) resolution works for that software, the README for folly should be updated to mention this dependency.

**Comment by guochangmao** [comment]
I used the ubuntu 14.04 have no this issue.
But I met a new issue for doing "make check" command, a error raised.

In file included from gtest-1.7.0/include/gtest/gtest.h:58:0,
from FunctionTest.cpp:22:
gtest-1.7.0/include/gtest/internal/gtest-internal.h:1111:44: error: no matching function for call to ‘testing::AssertionResult::AssertionResult(folly::Function&)’
::testing::AssertionResult(expression)) \

Has you come with this error too??

**Comment by kevinquinnyo** [comment]
You might want to open a new issue for that @guochangmao.  It seems unrelated to this and since it's closed, the devs who could fix this might not see it.

**Comment by Orvid** [comment]
Already fixed upstream.
