### ISSUE TITLE
HHVM crashes with latest folly

### ISSUE THREAD

**Issue by lbianc** [facebook/folly#300]
I've just updated folly in HHVM to commit 1e06e1dbc68fec05e415ca1fe3380fd01be6b90d and I'm getting the following error:

```
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0812 08:45:04.059198   910 AtomicHashMap-inl.h:38] Check failed: config.maxLoadFactor > 0.0 && config.maxLoadFactor < 1.0
*** Check failure stack trace: ***
Aborted
```

Looking the commit history, the change responsible for the error is this: https://github.com/PPC64/folly/commit/a64e4f2d3c7dda6698791564d83e13e58cb824b7.

Removing the "constexpr" makes the parameters of "Config" structure not be set on compilation time, so any code using it with its default values (before main start) will get zero for the parameters: maxLoadFactor, growthFactor, entryCountThreadCacheSize and capacity.

**Comment by lbianc** [comment]
@yfeldblum, could you check this? Thanks!

**Comment by yfeldblum** [comment]
Looking.

**Comment by yfeldblum** [comment]
@lbianc - Does the linked commit help?
