### ISSUE TITLE
PackedSyncPtr on AMD

### ISSUE THREAD

**Issue by AndreiBarsan** [facebook/folly#313]
I was reading [the PackedSyncPtr documentation](https://github.com/facebook/folly/blob/master/folly/docs/PackedSyncPtr.md) which claimed that it would be safe to take advantage of the top two bytes of an x64 address, since they would normally be zero anyway.

However, the [Wikipedia article to which the documentation pointed](https://en.wikipedia.org/wiki/X86-64#Canonical_form_addresses) states that:

> In addition, the AMD specification requires that bits 48 through 63 of any virtual address must be copies of bit 47 (in a manner akin to sign extension), or the processor will raise an exception.

Doesn't this mean that this structure would not work on an AMD processor? Or are they not enforcing that rule? I don't have access to one, so I can't test it, but it looks like it could be problematic.

**Comment by tudor** [comment]
We mask out bits 48..63 before dereferencing the pointer.

We get a pointer, bits 48..63 are always the same value (0 in userland, except the stack on Solaris, which we don't support), so we can use those bits to store 16 bits of arbitrary data; but before using the pointer (see PackedSyncPtr::get), we copy the value and set those bits back to 0 in the copy that we return to the user.
