### ISSUE TITLE
Mac OSx brew script not working anymore

### ISSUE THREAD

**Issue by raphaottoni** [facebook/folly#327]
I believe the double-conversion brew formula isn't supported anymore:

./build/bootstrap-osx-homebrew.sh

    + set -e
    +++ dirname -- ./build/bootstrap-osx-homebrew.sh
    ++ cd ./build/..
    ++ pwd
    + BASE_DIR=/Users/rapha/projetos/qlikview/script/on-the-fly/libs/folly/folly
    + cd /Users/rapha/projetos/qlikview/script/on-the-fly/libs/folly/folly
    + brewget autoconf automake libtool
    + brew install autoconf automake libtool 
    Warning: autoconf-2.69 already installed 
    Warning: automake-1.15 already installed
    Warning: libtool-2.4.4 already installed 
    + brewget glog gflags boost libevent double-conversion
    + brew install glog gflags boost libevent double-conversion
    Error: No available formula for double-conversion 
    Searching formulae...
    Searching taps...
    + brew upgrade glog gflags boost libevent double-conversion
    Error: No available formula for double-conversion

What I did was to install it by myself (https://github.com/google/double-conversion/) and then remove the dependency from the  ./build/bootstrap-osx-homebrew.sh:
    
    ....
    # dependencies
    brewget glog gflags boost libevent #double-conversion
    ...

Would it be sufficient? 

thanks

**Comment by fugalh** [comment]
Sigh. I wish they'd make up their minds. 

Yes, that should work, as would going back to before https://github.com/facebook/folly/commit/b75ef0a0af48766298ebcc946dd31fe0da5161e3
