### ISSUE TITLE
folly/Portability.h:203:20: fatal error: __config: No such file or directory

### ISSUE THREAD

**Issue by raphaottoni** [facebook/folly#328]
Hi,

 I am currently trying to use the atomic hashmap, but  after the folly installation, if I simply require the lib like 

    #include <folly/AtomicHashMap.h> 

The g++ compiler throws the following exception:

    In file included from /usr/local/include/folly/ThreadLocal.h:40:0,
                 from /usr/local/include/folly/ThreadCachedInt.h:31,
                 from /usr/local/include/folly/AtomicHashArray.h:41,
                 from /usr/local/include/folly/AtomicHashMap.h:93,
                 from cartesian_zero.cpp:11:
    /usr/local/include/folly/Portability.h:203:20: fatal error: __config: No such file or directory
    compilation terminated. 

I am  compiling my C++ code with: 

     g++-5.1.0 -std=c++11 -o3 -lhiredis -fopenmp cartesian_zero.cpp

is it a folly's issue or my fault?

**Comment by fredemmott** [comment]
```

// It turns out that GNU libstdc++ and LLVM libc++ differ on how they implement
// the 'std' namespace; the latter uses inline namepsaces. Wrap this decision
// up in a macro to make forward-declarations easier.
#if FOLLY_USE_LIBCPP
#include <__config>
```

What C++ lib does your system use?

**Comment by raphaottoni** [comment]
I believe it is 6.0.9: 

 
    ls /usr/lib/libstdc++*

    /usr/lib/libstdc++.6.0.9.dylib	/usr/lib/libstdc++.6.dylib	/usr/lib/libstdc++.dylib

**Comment by fredemmott** [comment]
cc @jwatzman who may have some idea about this from the OSX ports

**Comment by jwatzman** [comment]
You're building with gcc, but have defined `FOLLY_USE_LIBCPP` which tends to be for clang (I'm not sure if gcc can use clang's libcpp). Did you configure folly with a different compiler than you're using now? You should keep them consistent.
