### ISSUE TITLE
bootstrap-osx-homebrew.sh doesn't properly handle OpenSSL dependency on El Capitan

### ISSUE THREAD

**Issue by vbuslov** [facebook/folly#332]
Homebrew OpenSSL package isn't symlinked into /usr/local anymore:

```
==> Downloading https://homebrew.bintray.com/bottles/openssl-1.0.2d_1.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring openssl-1.0.2d_1.el_capitan.bottle.tar.gz
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash

This formula is keg-only, which means it was not symlinked into /usr/local.

Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include

==> Summary
🍺  /usr/local/Cellar/openssl/1.0.2d_1: 464 files, 17M
```

bootstrap-osx-homebrew.sh runs without errors but make fails:

```
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/local/include -std=gnu++0x -g -O2 -MT io/async/AsyncPipe.lo -MD -MP -MF io/async/.deps/AsyncPipe.Tpo -c io/async/AsyncPipe.cpp  -fno-common -DPIC -o io/async/.libs/AsyncPipe.o
In file included from io/async/AsyncPipe.cpp:16:
In file included from ./../folly/io/async/AsyncPipe.h:18:
./../folly/io/async/AsyncTransport.h:26:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^
1 error generated.
make[2]: *** [io/async/AsyncPipe.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by r8k** [comment]
Not sure if you have got this resolved, but you could do:
````
brew link openssl --force
````
to link the brew version of openssl

**Comment by RBlafford** [comment]
@r8k is there a better solution? brew is refusing to perform this command with this output:

`
Warning: Refusing to link: openssl
Linking keg-only openssl means you may end up linking against the insecure,
deprecated system OpenSSL while using the headers from Homebrew's openssl.
Instead, pass the full include/library paths to your compiler e.g.:
  -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib
`

**Comment by r8k** [comment]
@RBlafford OpenSSL not being linked with **`brew`** is due to this [issue](https://github.com/Homebrew/brew/pull/597).

You could try **`brew install folly`** according to the [docs](https://github.com/facebook/folly#os-x-homebrew), which should take care of the installing the dependencies.

**Comment by zcourts** [comment]
Work around by doing `export LIBS='-I/usr/local/opt/libressl/include -L/usr/local/opt/libressl/lib'` 

In your case `export LIBS='-I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib'` before building folly.

**Comment by Orvid** [comment]
`brew install folly` will account for the OpenSSL paths correctly, but we definitely should fix the bootstrap script (which is why I left this issue open).

**Comment by r8k** [comment]
@Orvid I can submit a PR if you would like help.

**Comment by Orvid** [comment]
Feel free. I'm waiting until at least Monday until I go poking at the homebrew stuff more, so that I can get the upstream recipe updated before trying to poke at things.

**Comment by RBlafford** [comment]
@r8k has any progress been made on this?

**Comment by Orvid** [comment]
No progress has been made on my side.

**Comment by r8k** [comment]
@RBlafford Yes I do, will be submitting a PR later in the day.
