### ISSUE TITLE
make check error

### ISSUE THREAD

**Issue by ayanamongol** [facebook/folly#335]
when i type in make check, came out following errors. How can I solve it ?

$make check
Making check in .                                                                                                             |
make[1]: Entering directory `/global-hadoop/home/ayana/folly/folly'
make[1]: Leaving directory `/global-hadoop/home/ayana/folly/folly'
Making check in test                                                                                                          |
make[1]: Entering directory `/global-hadoop/home/ayana/folly/folly/test'
Making check in .                                                                                                             |
make[2]: Entering directory `/global-hadoop/home/ayana/folly/folly/test'
make  libgtestmain.la libgtest.la benchmark_test concurrent_skiplist_benchmark sorted_vector_types_test foreach_test hash_test
 timeout_queue_test conv_test range_test bits_test bit_iterator_test spin_lock_test small_locks_test packed_sync_ptr_test smal
l_vector_test discriminated_ptr_test fbstring_test_using_jemalloc thread_cached_int_test thread_local_test fbvector_test dynam
ic_test json_test scope_guard_test endian_test rw_spinlock_test synchronized_test concurrent_skiplist_test histogram_test grou
p_varint_test map_util_test string_test producer_consumer_queue_test atomic_hash_array_test atomic_hash_map_test format_test f
ingerprint_test portability_test cpuid_test spooky_hash_v1_test spooky_hash_v2_test
make[3]: Entering directory `/global-hadoop/home/ayana/folly/folly/test'
make[3]: *** No rule to make target `gtest-1.7.0/src/gtest-all.cc', needed by `gtest-1.7.0/src/libgtestmain_la-gtest-all.lo'.
 Stop.
make[3]: Leaving directory `/global-hadoop/home/ayana/folly/folly/test'
make[2]: *** [check-am] Error 2
make[2]: Leaving directory `/global-hadoop/home/ayana/folly/folly/test'
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory `/global-hadoop/home/ayana/folly/folly/test'
make: *** [check-recursive] Error 1

**Comment by qizhuli** [comment]
Same problem here. Have you found a solution?

**Comment by abhiguru** [comment]
here too, solution ?

**Comment by shengxuanye** [comment]
I copied gtest-1.7.0 source code to test/gtest-1.7.0 and it works for me.
