### ISSUE TITLE
Add ./build/deps_ubuntu_14.04.sh similar to ./build/deps_ubuntu_12.04.sh ?

### ISSUE THREAD

**Issue by kevinquinnyo** [facebook/folly#336]
We're pre-compling binaries for .deb packages via docker to improve deployment speed on instances that utilize facebook/mcrouter for ubuntu 12.04 and ubuntu 14.04, and inside our Dockerfile we have logic like this:

```
RUN apt-get -y update && if [ ${RELEASE} = "12.04" ]; then \
        ./build/deps_ubuntu_12.04.sh && apt-get -y install libboost-program-options1.54-dev; \
        else \
        apt-get install -y \
        software-properties-common \
        python-software-properties \
        autoconf \
        binutils-dev \
        g++ \
        gcc \
        libboost-context1.54-dev \
        libboost-filesystem1.54-dev \
        libboost-program-options1.54-dev \
        libboost-regex1.54-dev \
        libboost-system1.54-dev \
        libboost-thread1.54-dev \
        libboost1.54-dev \
        libdouble-conversion-dev \
        libevent-dev \
        libgflags-dev \
        libgoogle-glog-dev \
        libssl-dev \
        libtool \
        make \
        python-dev \
        ragel; \
fi
```

If there were a `./build/deps_ubuntu_14.04.sh` it would make our downstream Dockerfile simpler and more reliable since the dependencies would be defined by folly instead of us for ubuntu 14.04.

I believe most of what's in `./build/deps_ubuntu_12.04.sh` do not apply for 14.04 and the only thing required are the toolchain packages above and the dev packages.

Is this something you'd be interested in looking into, or would you accept a PR if I added a very simple `/build/deps_ubuntu_14.04.sh`?

**Comment by Orvid** [comment]
Already added.
