### ISSUE TITLE
Undefined reference - boost error

### ISSUE THREAD

**Issue by js7222** [facebook/folly#340]
Hi,

I get the following link error when trying to build proxygen:

/bin/bash ../../../libtool  --tag=CXX   --mode=link g++  -DLIBMC_FBTRACE_DISABLE  -Wno-missing-field-initializers -Wno-deprecated -O3 -g -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -std=gnu++0x -g -O2   -o echo_server EchoHandler.o EchoServer.o ../../libproxygenhttpserver.la -liberty -lwangle -lfolly -lz -lssl -lcrypto -lcap -levent -lgflags -lglog  -L/usr/lib64 -lpthread -pthread -lfolly -lglog -ldouble-conversion -lboost_system -lboost_thread
libtool: link: g++ -DLIBMC_FBTRACE_DISABLE -Wno-missing-field-initializers -Wno-deprecated -O3 -g -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -std=gnu++0x -g -O2 -o .libs/echo_server EchoHandler.o EchoServer.o -pthread  ../../.libs/libproxygenhttpserver.so -liberty -lwangle -lz -lssl -lcrypto -lcap -levent -lgflags -L/usr/lib64 -lpthread -lfolly -lglog -ldouble-conversion -lboost_system -lboost_thread -pthread
/usr/local/lib/libfolly.so: undefined reference to `boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >::maybe_assign(boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > const&)'
/usr/local/lib/libfolly.so: undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/local/lib/libfolly.so: undefined reference to `boost::program_options::detail::cmdline::cmdline(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)'
/usr/local/lib/libfolly.so: undefined reference to `boost::re_detail::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'
/usr/local/lib/libfolly.so: undefined reference to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'
/usr/local/lib/libfolly.so: undefined reference to `boost::program_options::to_internal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status

I do see however that folly references boost::program_options:
ldd /usr/local/lib/libfolly.so | grep boost
        libboost_context.so.1.58.0 => /usr/local/lib/libboost_context.so.1.58.0 (0x00007f39d325d000)
        libboost_program_options.so.1.58.0 => /usr/local/lib/libboost_program_options.so.1.58.0 (0x00007f39d2fdd000)
        libboost_thread.so.1.58.0 => /usr/local/lib/libboost_thread.so.1.58.0 (0x00007f39d2db5000)
        libboost_filesystem.so.1.58.0 => /usr/local/lib/libboost_filesystem.so.1.58.0 (0x00007f39d2b95000)
        libboost_system.so.1.58.0 => /usr/local/lib/libboost_system.so.1.58.0 (0x00007f39d298d000)
        libboost_regex.so.1.58.0 => /usr/local/lib/libboost_regex.so.1.58.0 (0x00007f39d2675000)

**Comment by Satirev** [comment]
@js7222 did you build boost with C++11 support? It seems that you didn't, but you have to do this to build folly.

**Comment by tweej** [comment]
Which GCC? Maybe try: -D_GLIBCXX_USE_CXX11_ABI=0
https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html
