### ISSUE TITLE
make check failed ThreadLocalTest.o: undefined reference to symbol 'dlclose@@GLIBC_2.2.5'

### ISSUE THREAD

**Issue by nguyenxuantuong** [facebook/folly#341]
Hi,

I was able to compile folly successfully on ubuntu 14.04 (vagrant). But "make check" failed with the following error:

/usr/bin/ld: ThreadLocalTest.o: undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[3]: *** [thread_local_test] Error 1
make[3]: Leaving directory `/home/vagrant/downloads/folly/folly/test'
make[2]: *** [check-am] Error 2
make[2]: Leaving directory `/home/vagrant/downloads/folly/folly/test'
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory `/home/vagrant/downloads/folly/folly/test'
make: *** [check-recursive] Error 1

How to solve this?

Thanks!

**Comment by Thomas-Yang** [comment]
If you add '-ldl' to the LIBS variable inside the Makefiles under both folly and test directories, and then re-make, it solves the problem.
