### ISSUE TITLE
Performance of std::function

### ISSUE THREAD

**Issue by rigtorp** [facebook/folly#344]
This is just a question. Have you guys looked into the performance overhead of `std::function`? 

I've been building low latency systems and end up with specialized worker threads pulling data from a spsc/mpsc queue since the allocation overhead of `std::function` kills performance. I wanted the flexibility of `std::function` so I built a replacement that uses internal storage to store the lambda capture, guaranteeing heap free allocation for pod-types. This is similar to the space-performance trade off done in `FBString`. Implementation here https://github.com/rigtorp/Function/blob/master/Function.h

An alternative I haven't looked into is to use a custom allocator colocated with the `std::function`:

    struct {
      std::function<void()> fun;
      inplace_allocator<256> alloc;
    } work;
    work.fun = std::function<void()>(std::allocator_arg_t, work.alloc, []() { do_work(); });

Any thoughts?

**Comment by djwatson** [comment]
I think you're looking for folly/tests/function_benchmark ?

Yea we know std::function is slow-ish.

**Comment by rigtorp** [comment]
Looks like folly/tests/function_benchmark tests the invocation overhead. In my tests the invocation overhead of std::function is the same as calling a virtual function. In fact gcc 5.2 generates almost identical assembler for calls to std::function and virtual functions. You will always have some overhead due to the type erasure.

My implementation avoids heap allocation which is useful for things such as fast lockfree logging and work queues. In the end I needed to coalesce updates and ended up using a Seqlock instead: https://github.com/rigtorp/Seqlock
