### ISSUE TITLE
a tag that corresponds to commit 91499a64e87e95ac775edc56320bf74c4ad86626 for mcrouter v0.15.0

### ISSUE THREAD

**Issue by bobpattersonjr** [facebook/folly#346]
Could you create a tag that corresponds to commit 91499a64e87e95ac775edc56320bf74c4ad86626 for mcrouter v0.15.0

The latest tagged version is not compatible with the latest tagged version of mcrouter and it would be nice to build off of tagged versions

Thanks

**Comment by samveen** [comment]
The same is true for commit 3f93d7830a8cf7a3edfe13f87812b2d41825f70b and mcrouter v0.16.0
