### ISSUE TITLE
fbvector of std:maps is crashing

### ISSUE THREAD

**Issue by name-name** [facebook/folly#35]
Hi,

we have an older version of folly running (how do I check the version number?) and I tried compiling the newest version available but I was stuck on some boost-library issue in configure. [A step by step introduction how to get folly running and tests started would be very helpful btw.]

Anyway, the following code crashes at the foobar line in our version.
Could you check whether this is fixed already?
(sorry, that this is not with google test)

BOOST_AUTO_TEST_CASE( test_folly_fbvector_test )
{
    // using a std::vector instead of fbvector will work
    folly::fbvector<std::map<std::string, std::string>> vec_of_maps;

    vec_of_maps.push_back(std::map<std::string, std::string>());
    vec_of_maps.push_back(std::map<std::string, std::string>());
    BOOST_CHECK(vec_of_maps.size() == 2);

    // inserting into the second map works
    vec_of_maps[1]["hello"] = "world";
    BOOST_CHECK(vec_of_maps[0].size() == 0);
    BOOST_CHECK(vec_of_maps[1].size() == 1);

    // inserting into first map should work (but crashes)
    vec_of_maps[0]["foo"] = "bar";
    BOOST_CHECK(vec_of_maps[0].size() == 1);
    BOOST_CHECK(vec_of_maps[1].size() == 1);
}

**Comment by facebook-github-bot-5** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by facebook-github-bot-2** [comment]
Thank you for your patience. After 30 days with no updates from the core team, we're closing out the issue. If you're still experiencing the problem described, please reopen the issue - thanks!
