### ISSUE TITLE
Check for glog depends fail in configure

### ISSUE THREAD

**Issue by john-difool** [facebook/folly#355]
There was an issue a while ago (https://github.com/facebook/folly/issues/117) about the same problem. It got closed but the fix didn't stick. 

Here is the problem:
Run: ./build/bootstrap-osx-homebrew.sh 
.../...
checking for main in -lglog... no
configure: error: Please install google-glog library

I am on a Mac (El Captain) and I have installed glog with homebrew:

brew install glog        -> Warning: glog-0.3.4 already installed

This is the test that fails:

AC_CACHE_CHECK(
  [for glog viability],
  [folly_cv_prog_cc_glog],
  [AC_RUN_IFELSE(
    [AC_LANG_SOURCE[
      #include <glog/logging.h>
      int main(int argc, char** argv) {
        google::InitGoogleLogging(argv[0]);
        google::ShutdownGoogleLogging();
        return 0;
      }
    ]],
    [folly_cv_prog_cc_glog=yes],
    [folly_cv_prog_cc_glog=no]
  )]
)

In order to pass the test, there needs to be a -I & -L options passed to the compiler:

clang++ -I/usr/local/include -L/usr/local/lib -lglog main.cpp

How do I specify these two flags in the configuration? Shouldn't this be patched in bootstrap-osx-homebrew.sh?

**Comment by JadenGu** [comment]
I also face this issue. OSX.

**Comment by Orvid** [comment]
XCode needs to be initialized before it adds these paths to the defaults. `xcode-select --install` should get it working.
