### ISSUE TITLE
Arm support, objective-c++ 

### ISSUE THREAD

**Issue by fxfactorial** [facebook/folly#364]
Thank you for folly, this is great. 

I am curious about using folly with objective-c, specifically linking as objective-c++. I imagine that the library and all its dependencies then need to be recompiled for arm as well, i.e. boost and what not. 

Is this easily done now, or perhaps will be done later?

**Comment by Orvid** [comment]
For the most part, Folly does compile on AARCH64 and PPC64, though there are parts that don't work on 32-bit ARM.

**Comment by szenker** [comment]
Which parts exactly won't work on ARM 32-bit? Is it possible to get Futures working?

**Comment by Orvid** [comment]
Futures *probably* work, but I don't know if the OSS build system is setup to make it possible.
