### ISSUE TITLE
range_test and thread_local_test are failed in folly-bb5ed8070d533c016e1e93cd274e76ce28a780bb

### ISSUE THREAD

**Issue by jay7x** [facebook/folly#366]
I'm building folly-bb5ed8070d533c016e1e93cd274e76ce28a780bb on CentOS 6 (as mcrouter dependency). Build was successfull but 2 tests was failed on 'make check' stage.

So question is how safe is to use this build as mcrouter dependency?

Built with: gcc 4.8.2 (from devtoolset-2), boost 1.55.0

range_test failure message:
F0225 10:53:26.170635 10735 RangeSse42.cpp:41] Check failed: false Function qfind_first_byte_of_sse42 only works with SSE42!

thread_local_test failure message:
ThreadLocalTest.cpp:550: Failure
Expected: (nullptr) != (handle), actual: 8-byte object <00-00 00-00 00-00 00-00> vs NULL
ThreadLocalTest.cpp:557: Failure
Value of: dlsym_error
  Actual: 0x12d6010
Expected: nullptr
Which is: NULL

Here is test-suite.log:
[test-suite.txt](https://github.com/facebook/folly/files/146369/test-suite.txt)

**Comment by shindo** [comment]
thread_local_test fails because `ThreadLocalTestLib.cpp` isn't built into the shared library `lib_thread_local_test.so` that is needed for `TEST(ThreadLocal, SharedLibrary)`:
https://github.com/facebook/folly/blob/master/folly/test/ThreadLocalTest.cpp#L548

And you should add `-msse4.2` to `CXXFLAGS` to get range_test passed.

**Comment by enitihas** [comment]
I am also facing the exact same problem.
@shindo Can you please elaborate also on how to get the thread_local_test to pass?

**Comment by shindo** [comment]
Well, the simplest solution is to just disable the test (which I did for myself):
```
diff --git a/folly/test/ThreadLocalTest.cpp b/folly/test/ThreadLocalTest.cpp
index 106f6b1..75d99f6 100644
--- a/folly/test/ThreadLocalTest.cpp
+++ b/folly/test/ThreadLocalTest.cpp
@@ -543,7 +543,7 @@ TEST(ThreadLocal, Fork2) {
   }
 }
 
-TEST(ThreadLocal, SharedLibrary) {
+TEST(ThreadLocal, DISABLED_SharedLibrary) {
   auto exe = fs::executable_path();
   auto lib = exe.parent_path() / "lib_thread_local_test.so";
   auto handle = dlopen(lib.string().c_str(), RTLD_LAZY);
```

Actually there should be a rule in `folly/test/Makefile.am` that will build the shared library `lib_thread_local_test.so` from `ThreadLocalTestLib.cpp`.
I have tried to do this with the following patch:
```
diff --git a/folly/test/Makefile.am b/folly/test/Makefile.am
index deb2e69..415b876 100644
--- a/folly/test/Makefile.am
+++ b/folly/test/Makefile.am
@@ -80,9 +80,17 @@ TESTS += fbstring_test_using_jemalloc
 thread_cached_int_test_SOURCES = ThreadCachedIntTest.cpp
 thread_cached_int_test_LDADD = libfollytestmain.la $(top_builddir)/libfollybenchmark.la

+# lib_thread_local_test.so is needed for thread_local_test
+lib_thread_local_test_la_SOURCES = ThreadLocalTestLib.cpp
+lib_thread_local_test_la_CPPFLAGS = $(AM_CPPFLAGS)
+lib_thread_local_test_la_LDFLAGS = $(AM_LDFLAGS) -module -shared -avoid-version -export-dynamic
+lib_thread_local_test_la_LIBADD = $(top_builddir)/libfolly.la
+check_LTLIBRARIES += lib_thread_local_test.la
+
 thread_local_test_SOURCES = ThreadLocalTest.cpp
 thread_local_test_LDADD = libfollytestmain.la $(top_builddir)/libfollybenchmark.la
 thread_local_test_LDFLAGS = -ldl
+thread_local_test_DEPENDENCIES = lib_thread_local_test.la
 TESTS += thread_cached_int_test thread_local_test

 fbvector_test_SOURCES = FBVectorTest.cpp
```

But it doesn't work as libtool builds static library (even if noinst_LTLIBRARIES is used instead of check_LTLIBRARIES).

So there should be some libtool magic or a make rule that will build necessary shared library. I hope someone will manage to get it work.

**Comment by sudhagarc** [comment]
Noticed the same issue on CentOS 7.2.5211. Work around helped with range_test. Yet to figure the test_local_test workaround.

It would be good if this can be addressed.

**Comment by sudhagarc** [comment]
The following diff worked for Thread local test.

```
diff --git a/folly/test/Makefile.am b/folly/test/Makefile.am
index 0843c10..4b469a7 100644
--- a/folly/test/Makefile.am
+++ b/folly/test/Makefile.am
@@ -14,6 +14,12 @@ TESTS= \
        bits_test \
        bit_iterator_test
 
+lib_LTLIBRARIES = \
+       lib_thread_local_test.la
+
+lib_thread_local_test_la_SOURCES = ThreadLocalTestLib.cpp
+lib_thread_local_test_la_LDFLAGS = $(AM_LDFLAGS) -version-info $(LT_VERSION)
+
 check_LTLIBRARIES = libfollytestmain.la libgtest.la
 check_PROGRAMS =

```

**Comment by shindo** [comment]
Thanks! Your patch works for me too, with the only exception that `lib_thread_local_test.so` library is installed, because `lib_LTLIBRARIES` is used. But this problem can be easily solved by system packaging tools.

**Comment by Orvid** [comment]
Could you open a PR for this change?

**Comment by sudhagarc** [comment]
@Orvid,

Just want to confirm whether you are asking me to create a pull request for the change? Pls let me know.

**Comment by Orvid** [comment]
If it fixes the issue, then yes.

**Comment by daniel-lucio** [comment]
For CentOS, check #929
