### ISSUE TITLE
undefined reference to `google::LogMessageFatal::LogMessageFatal(char const*, int)'

### ISSUE THREAD

**Issue by abhiguru** [facebook/folly#368]
Hello,

Getting the error below  https://gist.github.com/abhiguru/9723557a69a9fad9446c I did install glog and dependencies verified ldconfig...

**Comment by avalchev** [comment]
Are you using clang ?

**Comment by abhiguru** [comment]
nope, Got it to work was a couple of things... a) Gtest is to be put inside the source/test as mentioned  and b) the CMakeLists.txt was missing the target_link_libraries for folly and dependent. Thanks for checking though!
