### ISSUE TITLE
Make check failed: undefined reference to `main' in function `_start'

### ISSUE THREAD

**Issue by pavan1267** [facebook/folly#369]
While building Folly release v0.57.0, I see the following error during make check. I was able to run configure and make successfully.

Making check in .
make[1]: Entering directory `/home/pavan/Documents/folly-0.57.0/folly'
make[1]: Leaving directory `/home/pavan/Documents/folly-0.57.0/folly'
Making check in test
make[1]: Entering directory `/home/pavan/Documents/folly-0.57.0/folly/test'
Making check in .
make[2]: Entering directory `/home/pavan/Documents/folly-0.57.0/folly/test'
make  libgtestmain.la libgtest.la benchmark_test concurrent_skiplist_benchmark sorted_vector_types_test foreach_test hash_test timeout_queue_test conv_test range_test bits_test bit_iterator_test spin_lock_test small_locks_test packed_sync_ptr_test small_vector_test discriminated_ptr_test cpuid_test fbstring_test_using_jemalloc thread_cached_int_test thread_local_test fbvector_test dynamic_test json_test scope_guard_test endian_test rw_spinlock_test synchronized_test concurrent_skiplist_test histogram_test group_varint_test map_util_test string_test producer_consumer_queue_test atomic_hash_array_test atomic_hash_map_test format_test fingerprint_test portability_test spooky_hash_v1_test spooky_hash_v2_test token_bucket_test futures_test
make[3]: Entering directory `/home/pavan/Documents/folly-0.57.0/folly/test'
make[3]: `libgtestmain.la' is up to date.
make[3]: `libgtest.la' is up to date.
make[3]: `benchmark_test' is up to date.
make[3]: `concurrent_skiplist_benchmark' is up to date.
make[3]: `sorted_vector_types_test' is up to date.
make[3]: `foreach_test' is up to date.
make[3]: `hash_test' is up to date.
make[3]: `timeout_queue_test' is up to date.
make[3]: `conv_test' is up to date.
make[3]: `range_test' is up to date.
make[3]: `bits_test' is up to date.
make[3]: `bit_iterator_test' is up to date.
make[3]: `spin_lock_test' is up to date.
make[3]: `small_locks_test' is up to date.
make[3]: `packed_sync_ptr_test' is up to date.
make[3]: `small_vector_test' is up to date.
make[3]: `discriminated_ptr_test' is up to date.
make[3]: `cpuid_test' is up to date.
make[3]: `fbstring_test_using_jemalloc' is up to date.
make[3]: `thread_cached_int_test' is up to date.
make[3]: `thread_local_test' is up to date.
make[3]: `fbvector_test' is up to date.
make[3]: `dynamic_test' is up to date.
make[3]: `json_test' is up to date.
make[3]: `scope_guard_test' is up to date.
make[3]: `endian_test' is up to date.
make[3]: `rw_spinlock_test' is up to date.
make[3]: `synchronized_test' is up to date.
make[3]: `concurrent_skiplist_test' is up to date.
make[3]: `histogram_test' is up to date.
make[3]: `group_varint_test' is up to date.
make[3]: `map_util_test' is up to date.
make[3]: `string_test' is up to date.
make[3]: `producer_consumer_queue_test' is up to date.
make[3]: `atomic_hash_array_test' is up to date.
make[3]: `atomic_hash_map_test' is up to date.
make[3]: `format_test' is up to date.
make[3]: `fingerprint_test' is up to date.
make[3]: `portability_test' is up to date.
make[3]: `spooky_hash_v1_test' is up to date.
make[3]: `spooky_hash_v2_test' is up to date.
/bin/bash ../libtool  -/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crt1.o-tag=CXX   --mode=link g++  -std=gnu++0x -g -O2 -lboost_context -lboost_program_options -lboost_thread -lboost_filesystem -lboost_system -lboost_regex -lpthread  -o token_bucket_test TokenBucketTest.o libgtest.la ../libfolly.la ../libfollybenchmark.la -llzma -lz -lsnappy -llz4 -liberty -ljemalloc -levent -ldouble-conversion -lssl -lgflags -lglog 
libtool: link: g++ -std=gnu++0x -g -O2 -o .libs/token_bucket_test TokenBucketTest.o  ./.libs/libgtest.a -lboost_context -lboost_program_options -lboost_thread -lboost_filesystem -lboost_system -lboost_regex -lpthread ../.libs/libfolly.so ../.libs/libfollybenchmark.so -llzma -lz -lsnappy -llz4 -liberty -ljemalloc -levent -ldouble-conversion -lssl -lgflags -lglog
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 0 has invalid symbol index 11
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 1 has invalid symbol index 12
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 2 has invalid symbol index 2
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 3 has invalid symbol index 2
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 4 has invalid symbol index 11
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 5 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 6 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 7 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 8 has invalid symbol index 12
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 9 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 10 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 11 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 12 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 13 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 14 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 15 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 16 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 17 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 18 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 19 has invalid symbol index 21
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_line): relocation 0 has invalid symbol index 2
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
make[3]: *** [token_bucket_test] Error 1
make[3]: Leaving directory `/home/pavan/Documents/folly-0.57.0/folly/test'
make[2]: *** [check-am] Error 2
make[2]: Leaving directory `/home/pavan/Documents/folly-0.57.0/folly/test'
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory `/home/pavan/Documents/folly-0.57.0/folly/test'
make: *** [check-recursive] Error 1

**Comment by flyzhang007** [comment]
did you fix this? 3x
