### ISSUE TITLE
usr/local/include/folly/futures/Future.h:50:3: error: declared here    Future(Future const&) = delete;

### ISSUE THREAD

**Issue by abhiguru** [facebook/folly#371]
Getting the error below when pushing a future to a std::vector<Future<T>> assuming it is missing a copy operator which is why the error but I read on a couple of threads that it was "fixed" and it should no longer happen so would like to find out what is the current status 

In file included from /usr/include/x86_64-linux-gnu/c++/4.8/bits/c++allocator.h:33:0,
                 from /usr/include/c++/4.8/bits/allocator.h:46,
                 from /usr/include/c++/4.8/string:41,
                 from /usr/include/c++/4.8/bits/locale_classes.h:40,
                 from /usr/include/c++/4.8/bits/ios_base.h:41,
                 from /usr/include/c++/4.8/ios:42,
                 from /usr/include/c++/4.8/ostream:38,
                 from /usr/include/c++/4.8/iostream:39,
                 from /home/abhi/ws/smartCam/src/detect2/detect2.cpp:4:
/usr/include/c++/4.8/ext/new_allocator.h: In instantiation of ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = folly::Future<vcu::InputImageStruct>; _Args = {const folly::Future<vcu::InputImageStruct>&}; _Tp = folly::Future<vcu::InputImageStruct>]’:
/usr/include/c++/4.8/bits/alloc_traits.h:254:4:   required from ‘static typename std::enable_if<std::allocator_traits<_Alloc>::__construct_helper<_Tp, _Args>::value, void>::type std::allocator_traits<_Alloc>::_S_construct(_Alloc&, _Tp*, _Args&& ...) [with _Tp = folly::Future<vcu::InputImageStruct>; _Args = {const folly::Future<vcu::InputImageStruct>&}; _Alloc = std::allocator<folly::Future<vcu::InputImageStruct> >; typename std::enable_if<std::allocator_traits<_Alloc>::__construct_helper<_Tp, _Args>::value, void>::type = void]’
/usr/include/c++/4.8/bits/alloc_traits.h:393:57:   required from ‘static decltype (_S_construct(__a, __p, (forward<_Args>)(std::allocator_traits::construct::__args)...)) std::allocator_traits<_Alloc>::construct(_Alloc&, _Tp*, _Args&& ...) [with _Tp = folly::Future<vcu::InputImageStruct>; _Args = {const folly::Future<vcu::InputImageStruct>&}; _Alloc = std::allocator<folly::Future<vcu::InputImageStruct> >; decltype (_S_construct(__a, __p, (forward<_Args>)(std::allocator_traits::construct::__args)...)) = <type error>]’
/usr/include/c++/4.8/bits/stl_vector.h:906:34:   required from ‘void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = folly::Future<vcu::InputImageStruct>; _Alloc = std::allocator<folly::Future<vcu::InputImageStruct> >; std::vector<_Tp, _Alloc>::value_type = folly::Future<vcu::InputImageStruct>]’
/home/abhi/ws/smartCam/src/detect2/detect2.hpp:221:32:   required from here
/usr/include/c++/4.8/ext/new_allocator.h:120:4: error: use of deleted function ‘folly::Future<T>::Future(const folly::Future<T>&) [with T = vcu::InputImageStruct]’
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
    ^
In file included from /home/abhi/ws/smartCam/src/detect2/detect2.cpp:22:0:
/usr/local/include/folly/futures/Future.h:50:3: error: declared here
   Future(Future const&) = delete;

**Comment by Orvid** [comment]
`folly:Future`'s copy constructor is deleted on purpose. You want to `std::move` the value instead of copy it.
