### ISSUE TITLE
Test program compilation issue 

### ISSUE THREAD

**Issue by pavan1267** [facebook/folly#372]
```
#include <folly/futures/Future.h>
#include<iostream>
 using namespace folly;
 using namespace std;

 void foo(int x)
 {
    cout << "foo(" << x << ")" << endl;
 }
  
 int main()
 {

          cout << "making Promise" << endl;
          Promise<int> p;
          Future<int> f = p.getFuture();
          return 0;         
 }
sample.cpp
```
I was able to install Folly successfully.

LD_LIBRARY_PATH set to /usr/local/lib

g++ -std=c++11 sample.cpp -pthread -llzma -lz -lsnappy -llz4 -liberty -ljemalloc -levent -ldouble-conversion -lssl -lgflags -lglog -lboost_system

/tmp/ccuDCM19.o: In function main':
sample.cpp:(.text+0x1a7): undefined reference tofolly::Future::~Future()' /tmp/ccuDCM19.o: In function folly::RequestContext::setContext(std::shared_ptr<folly::RequestContext>)':
sample.cpp:(.text._ZN5folly14RequestContext10setContextESt10shared_ptrIS0_E[_ZN5folly14RequestContext10setContextESt10shared_ptrIS0_E]+0x11): undefined reference tofolly::RequestContext::getStaticContext()' /tmp/ccuDCM19.o: In function folly::Promise<int>::getFuture()':
sample.cpp:(.text._ZN5folly7PromiseIiE9getFutureEv[_ZN5folly7PromiseIiE9getFutureEv]+0x36): undefined reference tofolly::Future::Future(folly::detail::Core*)' collect2: error: ld returned 1 exit status

**Comment by avalchev** [comment]
Just as a hint... why you don't try to add all the libraries defined in [ubuntu 14.04 build file](https://github.com/facebook/folly/blob/master/folly/build/build_debs_ubuntu_14.04.sh).

**Comment by pavan1267** [comment]
Issue got resolved by adding -lfolly.
