### ISSUE TITLE
Map of Promises/Futures

### ISSUE THREAD

**Issue by pavan1267** [facebook/folly#373]
I would like to maintain a map of futures/promises so that I can use the promise at a later time.
``
map<int, Promise<int> > _mapPromise;
Promise<int> prms;
  _mapPromise[1] = prms;
``
This returns error because Promises are not copyable as in Promise.h
 // not copyable
  Promise(Promise const&) = delete;
  Promise& operator=(Promise const&) = delete;

I would like to know if there is a better approach to do this?

**Comment by abhiguru** [comment]
https://github.com/facebook/folly/tree/master/folly/futures#map ?

**Comment by gdfast** [comment]
(Assuming you're on at least C++11) I think you could do:
```
map<int, shared_ptr<Promise<int>>> _mapPromise;
_mapPromise[1] = make_shared<Promise<int>>();

auto future1 = _mapPromse[1]->getFuture();
```

I did something similar once successfully, although I'm not sure if this is considered a best practice
