### ISSUE TITLE
folly/Histogram does not support standard integer types except int64_t

### ISSUE THREAD

**Issue by guptaanuj04** [facebook/folly#374]
I wrote a simple program to create and add values to a histogram by combining pieces of the sample code give in folly/folly/docs/Histogram.md file. 

folly::Histogram<int64_t> latencies(100, 0, 5000); works but
folly::Histogram<uint64_t> latencies(100, 0, 5000); does not, 
folly::Histogram<int32_t> latencies(100, 0, 5000); does not,
folly::Histogram<uint32_t> latencies(100, 0, 5000); does not.

I see the following compilation error when I pass uint64_t type - 

/tmp/ccmUXL6e.o: In function `folly::Histogram<unsigned long>::Histogram(unsigned long, unsigned long, unsigned long)':
folly_demo.cpp:(.text._ZN5folly9HistogramImEC2Emmm[_ZN5folly9HistogramImEC5Emmm]+0x3f): undefined reference to `folly::detail::HistogramBuckets<unsigned long, folly::detail::Bucket<unsigned long> >::HistogramBuckets(unsigned long, unsigned long, unsigned long, folly::detail::Bucket<unsigned long> const&)'
/tmp/ccmUXL6e.o: In function `folly::detail::HistogramBuckets<unsigned long, folly::detail::Bucket<unsigned long> >::getByValue(unsigned long)':
folly_demo.cpp:(.text._ZN5folly6detail16HistogramBucketsImNS0_6BucketImEEE10getByValueEm[_ZN5folly6detail16HistogramBucketsImNS0_6BucketImEEE10getByValueEm]+0x1f): undefined reference to `folly::detail::HistogramBuckets<unsigned long, folly::detail::Bucket<unsigned long> >::getBucketIdx(unsigned long) const'
collect2: error: ld returned 1 exit status

**Comment by Orvid** [comment]
The first one is working for you purely because it's one that's instantiated explicitly in Folly. You need to include `folly/stats/Histogram-defs.h` in addition to the base Histogram header in order to actually use it.
