### ISSUE TITLE
missing: FOLLY_INCLUDE_DIR FOLLY_LIBRARIES

### ISSUE THREAD

**Issue by JaymeWX** [facebook/folly#376]
Followed step by https://github.com/facebook/fbcunn/blob/master/INSTALL.md, I got this problem.
missing: FOLLY_INCLUDE_DIR FOLLY_LIBRARIES
How to do with it.

**Comment by Orvid** [comment]
You may need to explicitly set FOLLY_INCLUDE_DIR and FOLLY_LIBRARIES when building, but it's better to file this against fbcunn rather than Folly.
