### ISSUE TITLE
Code only works when compiled with `NDEBUG`

### ISSUE THREAD

**Issue by yunjing** [facebook/folly#377]
I have some `wangle` code that only works with compiled with `NDEBUG` flag on. The error can be traced to https://github.com/facebook/folly/blob/2c8de414e51305fa00ef6efdab69de0fbda7aff1/folly/io/async/EventBase.cpp#L494

I also posted the issue in `wangle`: https://github.com/facebook/wangle/issues/32. I wonder what is the purpose of this check, and whether such failed check poses a correctness issue in production when `DCHECK` is compiled away.

**Comment by Orvid** [comment]
That means your wangle code is incorrect. NDEBUG is disabling the assertion, which is why it doesn't fail when that flag is set.
