### ISSUE TITLE
Understanding then in facebook folly Futures

### ISSUE THREAD

**Issue by pavan1267** [facebook/folly#380]
I have a question regarding then continuation in Folly Futures:
MsgType1 msg;
MsgType2 msg2;
MsgType2  foo(MsgType1 msg)
{
//Do something
return msg2;
}

obj.foo(msg).then(\[this\](MsgType2 msg)
{
//Do something 
return Future\<MsgType3\>;

}).then(\[this\](MsgType3 msg) //This chaining for future<MsgType3> is valid??
{
//Do Something.
});

In the above sample, I am returning a future of type MsgType3. Will I be able to chain this future of type MsgType3 outside?

**Comment by yfeldblum** [comment]
That example code looks fine. Using `then` multiple times in succession should be valid.

**Comment by pavan1267** [comment]
Thank you. The multiple succession of the thens in my example works as expected.
