### ISSUE TITLE
Couldn't find zipalign MAC

### ISSUE THREAD

**Issue by matejvida** [facebook/folly#386]
I ge this:

Optimization warning: Pure abstract class passed to encode: 1 occurrences
Couldn't find zipalign.  Your APK may not be fully optimized.

When using this cmd:

redex ./APK/app-dev-debug.apk -o ./APK/output.apk

Is this a bug ore something, because i have zipalign located /Users/hq/Library/Android/sdk/build-tools/23.0.2

Also this folder can change when android build tools update. 

Any suggestions?

**Comment by Orvid** [comment]
You should file this against Redex rather than Folly.
