### ISSUE TITLE
HHWheelTimer assert-fails when destroy() happens after cancelAll()

### ISSUE THREAD

**Issue by fabbree** [facebook/folly#397]
`cancelAll()` does not properly reset `count_`.
`HHWheelTimer` ends up in an incoherent state causing `assert(count_ == 0)` failure on destruction.

Zeroing `count_` before returning fixes the issue.

**Comment by Orvid** [comment]
Could you open a PR to make this change rather than reporting the change in an issue?

**Comment by fabbree** [comment]
Done!
