### ISSUE TITLE
Error int tests when doing "make check" after building folly

### ISSUE THREAD

**Issue by guochangmao** [facebook/folly#402]
Hi all, I'm trying to build folly on ubuntu 14.04.

All was going fine until (following the instructions of the github documentation) I execute the "make check" command. An error raised when the process inspected the tests folder (folly/folly/tests):

In file included from gtest-1.7.0/include/gtest/gtest.h:58:0,
                 from FunctionTest.cpp:22:
gtest-1.7.0/include/gtest/internal/gtest-internal.h:1111:44: error: no matching function for call to ‘testing::AssertionResult::AssertionResult(folly::Function<int(int), (folly::FunctionMoveCtor)0>&)’
       ::testing::AssertionResult(expression)) \

Has anyone come with this error too??
Any comment will be appreciated.
Thanks.

**Comment by shindo** [comment]
This is because `operator bool()` is declared as `explicit`.

You just need to explicitly cast to bool arguments in `EXPECT_TRUE`, `EXPECT_FALSE` checks in `folly/test/FunctionTest.cpp` where the argument is `folly::Function`.

**Comment by Orvid** [comment]
Could you open a PR to fix that @shindo?

**Comment by guochangmao** [comment]
I am not clear for your comment.
Could you please kindly share that how to fix this issue in detail? @shindo 
Thanks.

**Comment by shindo** [comment]
@Orvid, I'll try to make a pull request, when I'll update to the current `master`. At the moment my local patches are in conflict with your changes.

@guochangmao, just as an example (https://github.com/facebook/folly/blob/master/folly/test/FunctionTest.cpp#L197):
```
EXPECT_FALSE(f);
```
Here, `f` is the object of `folly::Function` that has `explicit operator bool()`, so you should explicitly cast `f` to bool:
```
EXPECT_FALSE(bool(f));
```
You just need to do this for all checks `EXPECT_TRUE` and `EXPECT_FALSE` where the argument is `folly::Function`.

**Comment by guochangmao** [comment]
thank you @shindo 
follow your suggestion, it work fine.
