### ISSUE TITLE
Error FAIL: range_test when doing "make check" after building folly

### ISSUE THREAD

**Issue by guochangmao** [facebook/folly#404]
I am building the folly on ubuntu 14.04.
executed command "make check", some error happened,
PASS: conv_test
../build-aux/test-driver: line 107:  2357 Aborted                 (core dumped) "$@" > $log_file 2>&1
FAIL: range_test
PASS: bits_test

Has anyone come with this error too??
Any comment will be appreciated.
Thanks.

**Comment by shindo** [comment]
Looks like you have the same problem as described here: https://github.com/facebook/folly/issues/366

**Comment by guochangmao** [comment]
I follow the solution about below, but it did not work. 
==========
diff --git a/folly/test/Makefile.am b/folly/test/Makefile.am
index 0843c10..4b469a7 100644
--- a/folly/test/Makefile.am
+++ b/folly/test/Makefile.am
@@ -14,6 +14,12 @@ TESTS= \
        bits_test \
        bit_iterator_test

+lib_LTLIBRARIES = \
+       lib_thread_local_test.la
+
+lib_thread_local_test_la_SOURCES = ThreadLocalTestLib.cpp
+lib_thread_local_test_la_LDFLAGS = $(AM_LDFLAGS) -version-info $(LT_VERSION)
+
 check_LTLIBRARIES = libfollytestmain.la libgtest.la
 check_PROGRAMS =
==========

The issue happened again.
