### ISSUE TITLE
Does folly support Windows/MSVC now ?

### ISSUE THREAD

**Issue by pengweichu** [facebook/folly#405]
Hello, i'm new to folly, our company consider using proxygen(which depends on folly) in our project, my question is: does folly support Windows/MSVS now ?

Thanks!

**Comment by Orvid** [comment]
Not quite yet, no. I'm in the process of adding support to Folly for the newest update of MSVC 2015, but it's a long process.

**Comment by yfeldblum** [comment]
Closing because this is a question and an answer, not a bug report.
