### ISSUE TITLE
Wrong offset basis used in the fnv32 hash

### ISSUE THREAD

**Issue by syvex** [facebook/folly#41]
According to http://www.isthe.com/chongo/tech/comp/fnv/, in Hash.h,

    const uint32_t FNV_32_HASH_START = 216613626UL;

should be

    const uint32_t FNV_32_HASH_START = 2166136261UL;

This may or may not have an averse affect on the quality of the FNV hashes.

The unit tests for this also need to be fixed as they also account for the wrong value--2 wrongs make a right :)

**Comment by sgolemon** [comment]
This was closed by 11b4d6ba2cc621adfbfb22476c0e1fff4353c435
