### ISSUE TITLE
Mac OSX error: use of undeclared identifier 'preadv'

### ISSUE THREAD

**Issue by romeo-nxp** [facebook/folly#412]
Hi,
I have compiled folly on Mac OSX 10.11.4, gcc-4.9, c++11.
I got the same error in both Homebrew and MacPorts build like below with **make** command:

**FileUtil.cpp:136:20:** error: **use of undeclared identifier 'preadv'**
  return wrapvFull(preadv, fd, iov, count, offset);
                   ^
**FileUtil.cpp:144:20:** error: **use of undeclared identifier 'pwritev'**
  return wrapvFull(pwritev, fd, iov, count, offset);
                   ^
In file included from FileUtil.cpp:26:
**./../folly/detail/FileUtilDetail.h:78:51:** error: **too many arguments to function call, expected 3, have 4**
    r = f(fd, iov, std::min<int>(count, kIovMax), offset...);
        ~                                         ^~~~~~
**FileUtil.cpp:136:10: note:** in instantiation of function template specialization 'folly::fileutil_detail::wrapvFull<long (*)(int, const iovec *, int), long long>'
      requested here
  return wrapvFull(preadv, fd, iov, count, offset);
3 errors generated.

Thanks for all help!!!

**Comment by Orvid** [comment]
You may need to re-run configure, as there are some additional functions that need to be checked when generating the config file.

**Comment by romeo-nxp** [comment]
Thanks Orvid, i have re-run configure many times and re-make but it's still not work

**Comment by Orvid** [comment]
Could you check and see what `FOLLY_HAVE_PREADV` is getting defined to in `folly-config.h`?

**Comment by romeo-nxp** [comment]
Yes, my folly-config.h
It's just have HAVE_PREADV flag.
...
/* Define to 1 if you have the `pow' function. */
#ifndef FOLLY_HAVE_POW
#define FOLLY_HAVE_POW 1
#endif

/* Define to 1 if you have the `preadv' function. */
/* #undef HAVE_PREADV */

/* Define to 1 if the compiler supports pthread_atfork */
#ifndef FOLLY_HAVE_PTHREAD_ATFORK
#define FOLLY_HAVE_PTHREAD_ATFORK 1
#endif 
...

**Comment by romeo-nxp** [comment]
Solved it.
I have added #if FOLLY_HAVE_PREADV and #if FOLLY_HAVE_PWRITEV before 2 functions in FileUtil.cpp like below:

**#if FOLLY_HAVE_PREADV**
ssize_t preadvFull(int fd, iovec* iov, int count, off_t offset) {
  return wrapvFull(preadv, fd, iov, count, offset);
}
#endif
**#if FOLLY_HAVE_PWRITEV**
ssize_t pwritevFull(int fd, iovec* iov, int count, off_t offset) {
  return wrapvFull(pwritev, fd, iov, count, offset);
}
#endif

I don't know why the current version of folly here missing it ? 
I also downloaded folly from https://github.com/librato/folly and build successfully without any changes and errors.

**Comment by Orvid** [comment]
Those are gone because the portability header is supposed to be implementing them, but it seems that  the configure process wasn't working like I was expecting it to, so I need to fix that.
