### ISSUE TITLE
folly readRawHugePageSizes() blatantly relies on the presence of hugepages configuration

### ISSUE THREAD

**Issue by aggarwaa** [facebook/folly#414]
https://github.com/facebook/folly/blob/d9e0b59db5fce150845190686bf681b715e418ae/folly/experimental/io/HugePages.cpp#L73-L87

Line 78 implicitly relies on the existence of hugepages on a linux system. So, if you use any of the functions that end up calling readRawHugePageSizes() and the system doesn't have huge pages configured (/sys/kernel/mm/hugepages doesn't exist), the program dies with an uncaught exception along the lines of:

`E0518 21:29:39.141229 12462 configprocessor.cc:695] XXXXXXXXXXXXXXXX: boost::filesystem::directory_iterator::construct: No such file or directory: "/sys/kernel/mm/hugepages"`

At a minimum, there needs to be error checking/exception handling here.

**Comment by suspend0** [comment]
This bug can be exposed if one uses MemoryMapping.h on a linux system without huge pages enabled.  I note this b/c HugePages is experimental and one could expect these types of things to be in there, but MemoryMapping.h is not. (Although the header does mention it uses huge pages).

Thanks.

**Comment by suspend0** [comment]
https://github.com/facebook/folly/pull/416
