### ISSUE TITLE
Mac OSX error: thread-local storage is not supported for the current target

### ISSUE THREAD

**Issue by romeo-nxp** [facebook/folly#415]
Hi,
When i do: make check, it's error show:
depbase=`echo SynchronizedTest.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	g++ -DHAVE_CONFIG_H   -I../.. -pthread -I/usr/local/include -Igtest-1.7.0/include  -std=gnu++11 -g -O2 -MT SynchronizedTest.o -MD -MP -MF $depbase.Tpo -c -o SynchronizedTest.o SynchronizedTest.cpp &&\
	mv -f $depbase.Tpo $depbase.Po
**SynchronizedTest.cpp:150:10: error**: thread-local storage is not supported for the current target
  static thread_local int lockCount_;

Doesn't Mac support it? 
My version of g++ and gcc

g++ --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

gcc --version
gcc (Homebrew gcc49 4.9.3) 4.9.3
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by zhangpan1992** [comment]
I have met the same problem. Do you solve it?

**Comment by Orvid** [comment]
There's a diff up internally to deal with this.

**Comment by sleaze** [comment]
What was the verdict on this?

**Comment by Orvid** [comment]
Already fixed.
