### ISSUE TITLE
AtomicHashArray can reach capacity when used from many threads

### ISSUE THREAD

**Issue by mspielberg** [facebook/folly#420]
It is easy for an AtomicHashArray to reach a state where there are no free cells. At this point, due to the nature of linear probing, any operation on the AHA (e.g. find, insert) will take O(N) time to complete, possibly with disastrous performance impact on the calling application.

Filling all cells is supposed to be prevented by over-allocation of cells (based on maxLoadFactor), and failing inserts once [numEntries exceeds maxSize] (https://github.com/facebook/folly/blob/v0.57.0/folly/AtomicHashArray-inl.h#L155). AtomicHashArray uses readFast(), so the result returned from readFast() may be less than the actual number of occupied cells, resulting in [more cells being occupied than specified] (https://github.com/facebook/folly/blob/v0.57.0/folly/AtomicHashArray-inl.h#L103) in maxSize. The amount by which this can happen is bounded by `entryCountThreadCacheSize * # of threads` inserting to the AtomicHashArray, and this can easily push the number of occupied cells to the underlying AHA capacity.

For example, our HHVM application writes to a single AtomicHashMap from 250 threads, with the default configuration (maxLoadFactor = 0.8, entryCountThreadCacheSize = 1000) and a maxSize of 500,000,  leading to a capacity of 625,000. `250 threads * 1000 cached increments = 250,000` possible discrepancy between numEntries.readFast() and the true state of the cell array. In practice, we are basically guaranteed that the AHA will hit its capacity if inserts are uniformly-distributed among the threads.

One could say that this is an application-level problem, and that clients need to set an appropriate entryCountThreadCacheSize based on the expected number of accessing threads and maxLoadFactor, but I think this is a pretty catastrophic way for a high-performance hashtable implementation to fail.

Proposed fix:
In insertInternal, switch from readFast() to readFull() if numProbes is greater than some small (tunable?) threshold (5?). This would retain the current high-performance for a lightly-loaded AHA, but be safer as the AHA fills and approaches dangerous levels of probing to find empty cells.

**Comment by Orvid** [comment]
This has been handled already.
