### ISSUE TITLE
Stable/tagged release policy?

### ISSUE THREAD

**Issue by UniqMartin** [facebook/folly#424]
Until the end of August 2015, `folly` has been tagged on a weekly basis. These “stable releases” have been used in the [Homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/folly.rb). However, because there have been no new releases despite continued activity in the `master` branch, Homebrew is stuck with an almost one year old release that is currently blocking our upgrade of Boost from 1.60.0 to 1.61.0 in Homebrew/homebrew-core#1200.

What is the policy/plan on stable releases, if any, and tagging releases? If it turns out that everyone is expected to build from `master`, that's unfortunately a moving target and as such unacceptable to Homebrew. Without any future stable releases this would mean we would have to remove `folly` from our core formula repository. Thanks!

**Comment by snarkmaster** [comment]
Would it be cool if `folly` generated a new tag once per week, with no other special magic, just like it did before? How about once per day?

**Comment by UniqMartin** [comment]
If the development is done in a way where `master` is effectively assumed to be always stable, I guess that would be fine (and once per week more than sufficient). Of course it would be even better if there was some meaning to the tags and there were actual releases …

**Comment by Orvid** [comment]
For a commit to land in master it has to have passed the unit tests for Folly itself, as well as the tests for the (currently) ~800 projects internally that use Folly. If there's a breaking change in Folly, everything is updated in the same commit that makes the breaking change. If you take the state of any of FB's repos that depend on Folly at any single point in time, all of FB's repos, including the Folly repo, will compile and pass tests if you checkout the version that was master at that point in time.

**Comment by UniqMartin** [comment]
@Orvid Thank you for this detailed response! I imagined something like this could be going on behind the scenes, but it's nice to be granted a peek behind the scenes. Can the weekly tagging be reinstated? That would be sufficient for Homebrew's purposes. If not, the `folly` formula (package) would still have to be removed from our core formula repository. (Installing from a constantly moving `master` is supported, but if this is the only option a formula is no longer eligible to remain in the core formula repository.)

**Comment by fredemmott** [comment]
Why would us automatically tagging YYYYMMDD be better than the homebrew recipe tagging to a different fixed rev of master every week?

Agreed on it being ideal to have a proper versioning system and stability guarantees - that's an ongoing discussion.

**Comment by yfeldblum** [comment]
@fredemmott - Upstream specifying what "nightly" or "weekly" or "monthly" refers to is probably a better idea, overall, than every downstream, including Homebrew, making up their own version of an upstream project's "nightly" or "weekly" or "monthly" for that downstream. Even when it's an automatic tag based on timestamps.

**Comment by UniqMartin** [comment]
Any news about reinstating the weekly tagging (or really any semi-regular official/upstream tagging)?

**Comment by UniqMartin** [comment]
(Speaking as a Homebrew maintainer:) FYI, Folly has been removed from Homebrew because building from a moving target like `master` doesn't fly with our policies and we were stuck with an overly old version (the last one tagged) that was blocking other updates from happening.

**Comment by Orvid** [comment]
We're in the process of getting the automated tagging setup, and it does seem like the recipe was actively used, as we've already got a bug report about the simple install instructions not working (#446). For the moment, I've created the 2016.07.26 tag (the format we'll go with for tag names is probably going to be the same as how Buck was doing them at one point, ie. v2016.07.26.1).

**Comment by bhamiltoncx** [comment]
I just put together an automated tagging setup to create weekly tags for Folly following the Buck setup (`vYYYY.MM.DD.XX`).

The script will run each Monday to create a new stable release for Folly. I created the first release just now:

https://github.com/facebook/folly/releases/tag/v2016.07.29.00

Sorry this took a while to set up. Homebrew can now re-instate Folly.

**Comment by UniqMartin** [comment]
Thanks for reinstating the weekly release tags! I'm pretty sure Homebrew is not the only downstream project happy about this. Please give us a few days to ship the Boost 1.61.0 update before we bring Folly back.

Feel free to ping me, if after a week you notice nothing has moved yet. But I definitely have this on my TO DO list for the upcoming days.

**Comment by UniqMartin** [comment]
Closing because tagging has been reinstated (thanks!) and bringing Folly back as a Homebrew formula (based on those tags) is being worked on in Homebrew/homebrew-core#3590.
