### ISSUE TITLE
Make check failed on ubuntu 14.04

### ISSUE THREAD

**Issue by MichaelTong** [facebook/folly#432]
uname -a:
3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

My make check failed here:

> In file included from ../../folly/ThreadLocal.h:53:0,
>                  from ThreadLocalTest.cpp:17:
> ../../folly/detail/ThreadLocalDetail.h: In instantiation of ‘folly::threadlocal_detail::ElementWrapper::set(Ptr, const Deleter&) [with Ptr = Widget*; Deleter = void(Widget*, folly::TLPDestructionMode)]::__lambda8’:
> ../../folly/detail/ThreadLocalDetail.h:110:57:   required from ‘struct folly::threadlocal_detail::ElementWrapper::set(Ptr, const Deleter&) [with Ptr = Widget*; Deleter = void(Widget*, folly::TLPDestructionMode)]::__lambda8’
> ../../folly/detail/ThreadLocalDetail.h:110:16:   required from ‘void folly::threadlocal_detail::ElementWrapper::set(Ptr, const Deleter&) [with Ptr = Widget*; Deleter = void(Widget*, folly::TLPDestructionMode)]’
> ../../folly/ThreadLocal.h:242:5:   required from ‘void folly::ThreadLocalPtr<T, Tag>::reset(T*, const Deleter&) [with Deleter = void(Widget*, folly::TLPDestructionMode); T = Widget; Tag = void]’
> ThreadLocalTest.cpp:73:52:   required from here
> ../../folly/detail/ThreadLocalDetail.h:111:46: error: variable ‘d’ has function type
>            void* pt, TLPDestructionMode mode) {
>                                               ^
> ../../folly/detail/ThreadLocalDetail.h:111:46: error: variable ‘d’ has function type
> ../../folly/detail/ThreadLocalDetail.h: In instantiation of ‘struct folly::threadlocal_detail::ElementWrapper::set(Ptr, const Deleter&) [with Ptr = Widget*; Deleter = void(Widget*, folly::TLPDestructionMode)]::__lambda8’:
> ../../folly/detail/ThreadLocalDetail.h:110:16:   required from ‘void folly::threadlocal_detail::ElementWrapper::set(Ptr, const Deleter&) [with Ptr = Widget*; Deleter = void(Widget*, folly::TLPDestructionMode)]’
> ../../folly/ThreadLocal.h:242:5:   required from ‘void folly::ThreadLocalPtr<T, Tag>::reset(T*, const Deleter&) [with Deleter = void(Widget*, folly::TLPDestructionMode); T = Widget; Tag = void]’
> ThreadLocalTest.cpp:73:52:   required from here
> ../../folly/detail/ThreadLocalDetail.h:110:57: error: field ‘folly::threadlocal_detail::ElementWrapper::set(Ptr, const Deleter&) [with Ptr = Widget*; Deleter = void(Widget*, folly::TLPDestructionMode)]::__lambda8::__d’ invalidly declared function type
>        deleter2 = new std::function<DeleterFunType>([d = d](
>                                                          ^
> In file included from ../../folly/ScopeGuard.h:20:0,
>                  from ../../folly/ThreadLocal.h:41,
>                  from ThreadLocalTest.cpp:17:
> /usr/include/c++/4.8/functional:2450:7: error: ‘std::function<_Res(_ArgTypes ...)>::function(_Functor) [with _Functor = folly::threadlocal_detail::ElementWrapper::set(Ptr, const Deleter&) [with Ptr = Widget*; Deleter = void(Widget*, folly::TLPDestructionMode)]::__lambda8; <template-parameter-2-2> = void; _Res = void; _ArgTypes = {void*, folly::TLPDestructionMode}]’, declared using local type ‘folly::threadlocal_detail::ElementWrapper::set(Ptr, const Deleter&) [with Ptr = Widget*; Deleter = void(Widget*, folly::TLPDestructionMode)]::__lambda8’, is used but never defined [-fpermissive]
>        function<_Res(_ArgTypes...)>::
>        ^

When I try to make install, it says:

> mv: cannot move 'libfollybenchmark.so.57.0.0' to 'libfollybenchmark.so.57.0.0U': Permission denied
It seems that there is no libfollybenchmark.so.57.0.0 file

Does anyone have any idea how to fix this?

**Comment by shindo** [comment]
You can try to apply the following patch:
```
diff --git a/folly/folly/detail/ThreadLocalDetail.h b/folly/folly/detail/ThreadLocalDetail.h
index ea9ae13..0ab19ac 100644
--- a/folly/detail/ThreadLocalDetail.h
+++ b/folly/detail/ThreadLocalDetail.h
@@ -23,6 +23,7 @@
 #include <functional>
 #include <mutex>
 #include <string>
+#include <type_traits>
 #include <vector>
 
 #include <glog/logging.h>
@@ -107,7 +108,7 @@ struct ElementWrapper {
     DCHECK(deleter2 == nullptr);
     if (p) {
       ptr = p;
-      deleter2 = new std::function<DeleterFunType>([d = d](
+      deleter2 = new std::function<DeleterFunType>([d = typename std::decay<Deleter>::type(d)](
           void* pt, TLPDestructionMode mode) {
         d(static_cast<Ptr>(pt), mode);
});
```

**Comment by Orvid** [comment]
We have a patch up internally to fix this. IIRC, the other alternative is `auto d2 = d;` and then `[d2]`.

**Comment by MichaelTong** [comment]
Thanks, it works now.
