### ISSUE TITLE
Unable to install folly in Ubuntu 14.04 (32 bit)

### ISSUE THREAD

**Issue by prakharnigam** [facebook/folly#442]
Hi i am unable to install folly in Ubuntu 14.04, (32 bit).
are you provide support in 32 bit system?

Logs are given below

make  all-recursive
make[1]: Entering directory `/fbthrift/thrift/build/deps/folly/folly'
Making all in .
make[2]: Entering directory `/fbthrift/thrift/build/deps/folly/folly'
depbase=`echo Bits.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I./.. -pthread -I/usr/include   -std=gnu++0x -g -O2 -MT Bits.lo -MD -MP -MF $depbase.Tpo -c -o Bits.lo Bits.cpp &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++0x -g -O2 -MT Bits.lo -MD -MP -MF .deps/Bits.Tpo -c Bits.cpp  -fPIC -DPIC -o .libs/Bits.o
In file included from Bits.cpp:19:0:
./../folly/CpuId.h: In function 'int (* {anonymous}::folly_popcount_ifunc())(unsigned int)':
./../folly/CpuId.h:49:62: error: PIC register clobbered by 'ebx' in 'asm'
     __asm__("cpuid" : "=a"(n) : "a"(0) : "ebx", "edx", "ecx");
                                                              ^
./../folly/CpuId.h:51:65: error: PIC register clobbered by 'ebx' in 'asm'
       __asm__("cpuid" : "=c"(f1c_), "=d"(f1d_) : "a"(1) : "ebx");
                                                                 ^
./../folly/CpuId.h: In function 'int (* {anonymous}::folly_popcountll_ifunc())(long long unsigned int)':
./../folly/CpuId.h:49:62: error: PIC register clobbered by 'ebx' in 'asm'
     __asm__("cpuid" : "=a"(n) : "a"(0) : "ebx", "edx", "ecx");
                                                              ^
./../folly/CpuId.h:51:65: error: PIC register clobbered by 'ebx' in 'asm'
       __asm__("cpuid" : "=c"(f1c_), "=d"(f1d_) : "a"(1) : "ebx");
                                                                 ^
make[2]: *** [Bits.lo] Error 1
make[2]: Leaving directory ` /fbthrift/thrift/build/deps/folly/folly'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/fbthrift/thrift/build/deps/folly/folly'
make: *** [all] Error 2

**Comment by Orvid** [comment]
A large amount of Folly assumes 64-bit, and even if it does compile on 32-bit, we don't test it on any 32-bit platforms, so there are likely a large number of other issues.

**Comment by serup** [comment]
@Orvid, is it possible to tell makefiles that 32bit code should be generated, or is this project relying too much on 64bit architecture?

**Comment by Orvid** [comment]
It's possible to do so by modifying the makefile, and there are parts of Folly that we do use on 32-bit platforms, but they are typically extremely limited in scope (fbstring, fbvector, Function, ScopeGuard etc.) Although we try not to, as we don't actively test on 32-bit, we also can't guarantee that we won't accidentally break things.

**Comment by serup** [comment]
reason for wanting 32bit is that I currently test in Virtual machines (virtual box within virtual bos) and it is pt. not possible to have a VM running a VM with same 64bit - it is however, possible to run a VM inside a VM if the architecture of the last VM is 32bit
