### ISSUE TITLE
`brew install folly` fails / installing on OSX fails

### ISSUE THREAD

**Issue by Tuzongyu** [facebook/folly#446]
`brew install folly` no longer works (`Error: No available formula with the name "folly"`).

The alternative brew-based OSX instructions from the readme...
```
cd folly
./build/bootstrap-osx-homebrew.sh
make
make check
```
...result in 62 warnings and 2 errors which appear largely related to SSL libraries being deprecated, the errors being:

```
io/async/SSLContext.cpp:85:29: error: use of undeclared identifier 'SSL_OP_NO_COMPRESSION'
  SSL_CTX_set_options(ctx_, SSL_OP_NO_COMPRESSION);

io/async/SSLContext.cpp:189:7: error: use of undeclared identifier 'SSL_CTX_set1_param'
  if (SSL_CTX_set1_param(ctx_, x509VerifyParam.get()) != 1) {
```

Is there any way to get around this in the OSX install?

**Comment by Tuzongyu** [comment]
I tried the following:

```
brew install openssl
cd folly
./build/bootstrap-osx-homebrew.sh
 autoreconf -ivf
./configure CPPFLAGS="-I/opt/local/include -I/usr/local/opt/openssl/include" LDFLAGS="-L/opt/local/lib -L/usr/local/opt/openssl/lib"
```
then, per https://gist.github.com/duedal/7887803 and errors I experienced, I ran:
```
cp String.cpp FollyString.cpp
cp String.h FollyString.h
```

now, `make` gives me this error:
```
In file included from fibers/Baton.cpp:16:
In file included from fibers/Baton.h:191:
In file included from ./../folly/fibers/Baton-inl.h:16:
./../folly/fibers/Fiber.h:68:34: error: unexpected type name 'intptr_t': expected expression
    const size_t size = std::abs<intptr_t>(
```

**Comment by JoeLoser** [comment]
I'm interested in following this discussion as well. I am running into similar problems. Reinstalling Homebrew using the command below to pass an additional flag:
```
brew install openssl --extra-include-dirs=/usr/local/opt/openssl/include
```
did not yield fruitful results, unfortunately. Looks like the weekly tagged stable builds will be a thing soon enough according to the issue 424 thread.

**Comment by UniqMartin** [comment]
If you want to be notified when the `folly` formula has been brought back to Homebrew, that's the PR you might want to subscribe to: Homebrew/homebrew-core#3590.

And speaking as a Homebrew maintainer:

> ```
> brew install openssl --extra-include-dirs=/usr/local/opt/openssl/include
> ```
>
> did not yield fruitful results, unfortunately.

I'm not sure what you hope this will do, but there's no `--extra-include-dirs=` option for the `openssl` formula and thus your invocation is no different from `brew install openssl`. It's also a bit weird that you try to reference a directory that is provided by the formula you are about to install. What is it that you try to accomplish here?

**Comment by Orvid** [comment]
It was already brought back into Homebrew.
