### ISSUE TITLE
Make failed in Ubuntu 16.04.1

### ISSUE THREAD

**Issue by ehzShelter** [facebook/folly#453]
What the hell is this?

Tried three times... same error
![hell](https://cloud.githubusercontent.com/assets/12381692/17645086/9de528ee-61bc-11e6-8d9d-2a31ecf18a0a.png)

**Comment by adlawren** [comment]
Ditto:

libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++1y -g -O2 -MT portability/SysMembarrier.lo -MD -MP -MF portability/.deps/SysMembarrier.Tpo -c portability/SysMembarrier.cpp  -fPIC -DPIC -o portability/.libs/SysMembarrier.o
portability/SysMembarrier.cpp: In function ‘bool folly::detail::sysMembarrierAvailable()’:
portability/SysMembarrier.cpp:43:37: error: ‘MEMBARRIER_CMD_QUERY’ was not declared in this scope
   auto r = syscall(__NR_membarrier, MEMBARRIER_CMD_QUERY, /* flags = */ 0);
                                     ^
portability/SysMembarrier.cpp:48:14: error: ‘MEMBARRIER_CMD_SHARED’ was not declared in this scope
   return r & MEMBARRIER_CMD_SHARED;
              ^
portability/SysMembarrier.cpp: In function ‘int folly::detail::sysMembarrier()’:
portability/SysMembarrier.cpp:56:35: error: ‘MEMBARRIER_CMD_SHARED’ was not declared in this scope
   return syscall(__NR_membarrier, MEMBARRIER_CMD_SHARED, /* flags = */ 0);
                                   ^
Makefile:1524: recipe for target 'portability/SysMembarrier.lo' failed
make[2]: *** [portability/SysMembarrier.lo] Error 1
make[2]: Leaving directory '/home/adlawren/Libs/folly/folly'
Makefile:1605: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/adlawren/Libs/folly/folly'
Makefile:986: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by adlawren** [comment]
Seems like the changes applied in [this commit](https://github.com/facebook/folly/commit/b8c8b1f838deaaa7b57acbb1d41fb464e25397c8) caused the issue? At least on my PC, reseting to [the commit before that commit](https://github.com/facebook/folly/commit/58ecc90355e2b311682a8136aec79e3dee279c14) results in a successful build. Afterwards, introducing the include statement added in the commit seems to cause the build failure.

Very perplexing...

**Comment by ehzShelter** [comment]
Folly community should update readme for ubuntu 16.04 LTS.. because it is one of the major OSs developers use. al least for noob people....  very perplexing :/

**Comment by lukenels** [comment]
Could you see if applying [this patch](https://gist.github.com/lukenels/502d8f36046c38191138ef864e21087f) to folly fixes your build errors? I'm not sure if this will fix it in all cases, but it appears to have fixed the build on my Ubuntu VM. Thanks!

**Comment by lukenels** [comment]
Existing PR with solution to this problem at https://github.com/facebook/folly/pull/455.

**Comment by ehzShelter** [comment]
Thank you @lukenels .. I am checking right now

**Comment by ehzShelter** [comment]
#440
 I am getting range_test error.. :\

**Comment by adlawren** [comment]
@lukenels Verified that compilation was successful using Ubuntu16.04 64-bit after introducing the include added in [that diff](https://gist.github.com/lukenels/502d8f36046c38191138ef864e21087f).

@ehzShelter I'm not sure if the test failure is related; it might be, but from what I recall there were some tests failing before I saw this issue.
