### ISSUE TITLE
Can't install on OS X

### ISSUE THREAD

**Issue by colin-ni** [facebook/folly#461]
Using `$brew install folly` gives the following errors:

`Error: No available formula with the name "folly" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.`.

And the other option, `cd folly; ./build/bootstrap-osx-homebrew.sh; make; make check`, throws the following errors:

`test/Makefile.am:175: error: HAVE_PTHREADS does not appear in AM_CONDITIONAL
test/Makefile.am:266: error: HAVE_PYTHON does not appear in AM_CONDITIONAL
autoreconf: /opt/local/bin/automake failed with exit status: 1`.

What should I try doing? And if this is a known problem, are there any work-arounds?

**Comment by colin-ni** [comment]
#446 reports a similar problem, and it's still open.

**Comment by Orvid** [comment]
Folly wasn't in the main brew repo for a while, but it's now back in.
