### ISSUE TITLE
Can't install on ubuntu 16.04

### ISSUE THREAD

**Issue by alejandronespereira** [facebook/folly#462]
When running:

```
autoreconf -ivf
./configure
```

it outputs:

configure: error: "libgflags invalid, see config.log for details"

However, I have libgflags installed and updated.

**Comment by Orvid** [comment]
What are the contents of config.log?

**Comment by alejandronespereira** [comment]
I found the root of the issue, there was a weird error on the libgflags from the previous installation. Sorry for the disturbance and thanks for the quick response.

**Comment by xusandai** [comment]
@alejandronespereira I come across the problem too. could you tell how did you solve it ? thank you .

**Comment by alejandronespereira** [comment]
@xusandai I did not start with a fresh ubuntu installation and I had a conflict because I had both the apt-get package and the compiled libraries from libflag. Removing the package ones fixed the issue.

**Comment by xusandai** [comment]
@alejandronespereira did you come across any error when run "make check"?

**Comment by alejandronespereira** [comment]
After I removed the conflcting versions the entire installation ran smoothly. Previous to that, the only problem I found was the one I described here.

**Comment by xusandai** [comment]
@alejandronespereira I see, thanks for your patience
