### ISSUE TITLE
Compilation fails on centos box with gcc-4.9

### ISSUE THREAD

**Issue by sayangoswami** [facebook/folly#472]
I cannot compile folly on a centos box with gcc-4.9 due to errors in fibers. The output snippet from make is attached.
``
In file included from /home/packages/compilers/gcc/4.9.0/include/c++/4.9.0/bits/shared_ptr.h:52:0,
                 from /home/packages/compilers/gcc/4.9.0/include/c++/4.9.0/memory:82,
                 from ./../folly/fibers/FiberManagerInternal.h:19,
                 from ./../folly/fibers/EventBaseLoopController.h:18,
                 from fibers/FiberManagerMap.h:18,
                 from fibers/FiberManagerMap.cpp:16:
/home/packages/compilers/gcc/4.9.0/include/c++/4.9.0/bits/shared_ptr_base.h: In instantiation of ‘std::__shared_ptr<_Tp, _Lp>::__shared_ptr(_Tp1*) [with _Tp1 = int; _Tp = void; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]’:
/home/packages/compilers/gcc/4.9.0/include/c++/4.9.0/bits/shared_ptr.h:113:32:   required from ‘std::shared_ptr<_Tp>::shared_ptr(_Tp1*) [with _Tp1 = int; _Tp = void]’
./../folly/fibers/EventBaseLoopController.h:65:47:   required from here
/home/packages/compilers/gcc/4.9.0/include/c++/4.9.0/bits/shared_ptr_base.h:874:4: error: static assertion failed: incomplete type
    static_assert( !is_void<_Tp>::value, "incomplete type" );
    ^
make[2]: *** [fibers/FiberManagerMap.lo] Error 1
make[2]: Leaving directory `/home/sgoswa1/folly/folly'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/sgoswa1/folly/folly'
make: *** [all] Error 2
``

**Comment by upsuperman** [comment]
I have the same problem...

**Comment by upsuperman** [comment]
Do you have solved this ?  please tell me 
thanks

**Comment by daniel-lucio** [comment]
For CentOS, check #929
