### ISSUE TITLE
no type named 'max_align_t' in the global namespace

### ISSUE THREAD

**Issue by janlely** [facebook/folly#474]
I rebuild boost1.58  with clang and libc++ ,  cause gcc4.8 do not support c++14  which is needed by proxygen
I got this error while rebuilding folly

./../folly/Portability.h:186:25: error: no type named 'max_align_t' in the global namespace; did you mean
      simply 'max_align_t'?
namespace std { typedef ::max_align_t max_align_t; }
                        ^~~~~~~~~~~~~
                        max_align_t
/usr/include/c++/v1/cstddef:55:21: note: 'max_align_t' declared here
typedef long double max_align_t;

**Comment by Orvid** [comment]
GCC 4.8 does support the features of C++14 that Proxygen (and Folly) use. What version of Clang and libc++ are you trying to build against?

**Comment by janlely** [comment]
clang  version 3.8.0
I don't know libc++ version,  I installed by apt-get install libc++-dev
system:  ubuntu 14.04

**Comment by Orvid** [comment]
This sounds like it's the result of using a mismatched version of compiler and runtime.
