### ISSUE TITLE
portability/BitsFunctexcept.cpp:24:6: error: redefinition of '__throw_length_error'

### ISSUE THREAD

**Issue by janlely** [facebook/folly#475]
I tried from gcc4.8 to clang,  
I tried boost 1.54, 1.58, 1.59, 1.61.  (only 1.59 works)
I update libc++ to the latest version
Now I still got problem
It's so hard to compile folly

This my info:
OS :      ubuntu 14.04
CC:       clang
CXX:     clang++
stdlib:    libc++ (latest)
boost:    boost1.59

ERROR:
portability/BitsFunctexcept.cpp:24:6: error: redefinition of '__throw_length_error'
void __throw_length_error(const char* msg) {
     ^
/usr/local/include/c++/v1/stdexcept:213:6: note: previous definition is here
void __throw_length_error(const char*__msg)
     ^
portability/BitsFunctexcept.cpp:28:6: error: redefinition of '__throw_logic_error'
void __throw_logic_error(const char* msg) {
     ^
/usr/local/include/c++/v1/stdexcept:183:6: note: previous definition is here
void __throw_logic_error(const char*__msg)
     ^
portability/BitsFunctexcept.cpp:32:6: error: redefinition of '__throw_out_of_range'
void __throw_out_of_range(const char* msg) {
     ^
/usr/local/include/c++/v1/stdexcept:223:6: note: previous definition is here
void __throw_out_of_range(const char*__msg)

**Comment by janlely** [comment]
in stdexcept   '__throw_out_of_range' is defined under namespace of std
how should clang give this error?

**Comment by janlely** [comment]
I found libc++ define '__throw_out_of_range'  out of namespace std

**Comment by janlely** [comment]
__throw_out_of_range is defined under namespace std
how should this error happen?

**Comment by janlely** [comment]
yes  BitsFunctexcept.h  redefine __throw_out_of_range

**Comment by Orvid** [comment]
Well, that isn't nice of it.... This shouldn't be too difficult to fix, it just needs some more checks to see if each of those individual functions is defined :(

**Comment by Orvid** [comment]
Could you try again now that https://github.com/facebook/folly/commit/60d9f8475af7b4cfca379279cc7dd3fe2ed83c1c has landed? Hopefully it should fix the issue for now.
