### ISSUE TITLE
make check failed.  undefined reference to `folly::init(int*, char***, bool)

### ISSUE THREAD

**Issue by janlely** [facebook/folly#476]
it's stange, I can grep  init   in libfolly.so.57.0.0
but still get this link error

libtool: link: /usr/bin/clang++ -std=gnu++1y -stdlib=libc++ -I/usr/local/include/c++/v1 -o .libs/mallctl_helper_test MallctlHelperTest.o  ./.libs/libfollytestmain.a /home/jay/Software/folly/folly/.libs/libfolly.so -lboost_context -lboost_program_options -lboost_thread -lboost_filesystem -lboost_system -lboost_regex -lpthread -lboost_chrono -lssl -lcrypto -llzma -lz -lsnappy -llz4 -liberty -ljemalloc -levent -ldouble-conversion -lglog -lgflags
MallctlHelperTest.o: In function `main':
MallctlHelperTest.cpp:(.text+0x15b4): undefined reference to `folly::init(int*, char***, bool)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by janlely** [comment]
it seems that `make` didn't enter  folly/init 
i can't find init.o   in folly/init

**Comment by rklabs** [comment]
You need to use `--enable-follytestmain` as option to `configure` script.
