### ISSUE TITLE
Cannot build folly on Mac: error: Please install google-gflags library

### ISSUE THREAD

**Issue by ustczxf** [facebook/folly#479]
In fact I've installed gflags, but it always reported this issue:
checking whether the g++ linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin15.6.0 dyld
checking how to hardcode library paths into programs... immediate
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking if g++ supports C++1y features without additional flags... no
checking if g++ supports C++1y features with -std=c++1y... yes
checking if g++ supports C++1y features with -std=gnu++1y... yes
checking for main in -lgflags... no
configure: error: Please install google-gflags library

brew info gflags
gflags: stable 2.1.2 (bottled)
Library for processing command-line flags
https://gflags.github.io/gflags/
/usr/local/Cellar/gflags/2.1.2 (20 files, 335.7K) *

who can provide some help? thanks

**Comment by ustczxf** [comment]
I also tried different versions of folly in centos, and it reported the same issue, what's wrong?:(

**Comment by ustczxf** [comment]
@Orvid hi, may you help to provide some suggestion? thanks

**Comment by Orvid** [comment]
Unless you're trying to build the tests you should be able to get away with compiling Folly without gflags, although I'm not certain how the default configure script is setup.

**Comment by rajan-chari** [comment]
Comment out the following in configure.ac to remove gflags dependency.

```
# # Checks for glog and gflags
# # There are no symbols with C linkage, so we do a try-run
# AC_HAVE_LIBRARY([gflags],[],[AC_MSG_ERROR(
#                 [Please install google-gflags library])])
# AC_CACHE_CHECK(
#   [for gflags viability],
#   [folly_cv_prog_cc_gflags],
#   [AC_RUN_IFELSE(
#     [AC_LANG_SOURCE[
#       #include <gflags/gflags.h>
#       DEFINE_bool(folly_truthy, true, "Sample truthy flag");
#       DEFINE_bool(folly_falsey, false, "Sample falsey flag");
#       int main(int argc, char** argv) {
#         return (FLAGS_folly_truthy && !FLAGS_folly_falsey) ? 0 : 1;
#       }
#     ]],
#     [folly_cv_prog_cc_gflags=yes],
#     [folly_cv_prog_cc_gflags=no]
#   )]
# )
#
# if test "$folly_cv_prog_cc_gflags" != "yes"; then
#   AC_MSG_ERROR(["libgflags invalid, see config.log for details"])
# fi
# FB_CHECK_PKG_CONFIG([GFLAGS], [libgflags])
```

**Comment by rajan-chari** [comment]
better option is to install gflags and point to the lib and include directory using environment variables

```
LDFLAGS='-L/usr/local/opt/double-conversion/lib -L/usr/local/Cellar/libevent/2.0.22/lib -L/usr/local/opt/gflags/lib -L/usr/local/opt/glog/lib -L/usr/local/opt/boost/lib"

CPPFLAGS='-I/usr/local/opt/openssl/include -I/usr/local/opt/double-conversion -I/usr/local/opt/double-conversion/include -I/usr/local/opt/gflags/include -I/usr/local/opt/glog/include'

CXXFLAGS=-msse4.2
```

run 
1) autoreconf --install
2) configure 
afterwards

**Comment by Orvid** [comment]
You need to have run `xcode-select --install` at least once or else the homebrew install directory won't be in your path.

**Comment by daniel-lucio** [comment]
For CentOS, check #929
