### ISSUE TITLE
Can't use small_vector::push on mac os x

### ISSUE THREAD

**Issue by YiqiuLiu** [facebook/folly#481]
folly installed using homebrew

```
#include <folly/small_vector.h>
#include <iostream>

int main() {
	folly::small_vector<int> s;
	s.push_back(2);
}
```
causes the error:
```
/usr/local/include/folly/small_vector.h:619:14: error: use of undeclared identifier 'malloc_usable_size'
      return malloc_usable_size(u.pdata_.heap_) / sizeof(value_type);
             ^
/usr/local/include/folly/small_vector.h:651:9: note: in instantiation of member function 'folly::small_vector<int, 1, void, void, void>::capacity' requested here
    if (capacity() == size()) {
        ^
/Users/lyqqq/Desktop/test/folly.cpp:6:4: note: in instantiation of member function 'folly::small_vector<int, 1, void, void, void>::push_back' requested here
        s.push_back(2);
          ^
```

**Comment by Orvid** [comment]
It should be referencing the implementation in: https://github.com/facebook/folly/blob/9ae9af6f6e23b2ef84168cad5f552cf87700de5d/folly/portability/Malloc.h#L34 

Is `FOLLY_HAVE_MALLOC_USABLE_SIZE` defined?

**Comment by YiqiuLiu** [comment]
<img width="687" alt="screen shot 2016-09-19 at 11 31 58 am" src="https://cloud.githubusercontent.com/assets/9411502/18644085/cb7be970-7e5c-11e6-9e82-90b9b0fc3329.png">

**Comment by Orvid** [comment]
Alright, then, what is it defined to? (it's possible that it's been defined to `0`, which isn't how the portability header assumes it works)

**Comment by YiqiuLiu** [comment]
Surprisingly it is defined as 1, which is why I am so confused.

**Comment by Orvid** [comment]
This sounds like there's something going on with the compilation environment rather than Folly.
