### ISSUE TITLE
Unable to  "brew install folly"

### ISSUE THREAD

**Issue by abhi18av** [facebook/folly#482]
Hii Folly team)

I'm unable to install the Folly library as a brew formula, even though all dependencies have been met.

<img width="1440" alt="screen shot 2016-09-20 at 6 22 58 pm" src="https://cloud.githubusercontent.com/assets/12799326/18670955/cba04d16-7f5f-11e6-8b1e-d990f770aede.png">
<img width="1440" alt="screen shot 2016-09-20 at 6 23 06 pm" src="https://cloud.githubusercontent.com/assets/12799326/18670961/d0126adc-7f5f-11e6-80fd-bc474832dc17.png">

**Comment by Orvid** [comment]
What version of OSX are you running?

**Comment by abhi18av** [comment]
Yosemite 10.10.5

So, I know about the "obvious solution" but I'd definitely like to install in about the same location as Boost libraries and preferably via Homebrew so @Orvid , upgrading is out of option ;)

But I'd really appreciate if you could help me figure out a way. 
Thanks)

**Comment by Orvid** [comment]
This is due to the OS being too old, and we don't have plans to support older versions of OSX than we currently do.

**Comment by abhi18av** [comment]
Wow,  @Orvid that was quick!  

But,  thank you for your time :)
