### ISSUE TITLE
Package for CentOS?

### ISSUE THREAD

**Issue by petrmanek** [facebook/folly#494]
I couldn't find any official package on the RHEL/EPEL repos. Is CentOS among the supported or soon-to-be-supported distributions?

Cheers, PM

**Comment by Orvid** [comment]
We don't currently package for any distros. There is a brew recipe for OSX though. We hope to eventually provide packages for a few distros, but that's currently a low-priority objective.

**Comment by daniel-lucio** [comment]
RPM For CentOS, check #929
