### ISSUE TITLE
FBVector breakes std::string (clang 3.8.0)

### ISSUE THREAD

**Issue by Dionis-mgn** [facebook/folly#498]
Hi guys!

I built my app using clang 3.8.0 and got segfault.

[Code to reproduce](https://gist.github.com/Dionis-mgn/bb67335ac419099635ef62c781f0cd4a)

I investigated this issue little bit and discovered this sequence:
- FBVector allocates chunk for two elements
- FBVector emplaces string into back
  - std::string stores data in this chunk (data length is small enough)
  - std::string stores pointer to this data (pointer to this chunk + some offset). std::string uses this pointers in cases when it isn't able to store data in itself.
- FBVector emplaces second string using the same mechanism
- FBVector emplaces third string
  - FBVector allocates new chunk
  - FBVector **moves data from old chunk to new one using std::memcpy**. So, data "moved" as supposed but pointer "moved" to. And points to old chunk.
  - FBVector frees old chunk an constructs string in new one
- FBVector destroys all strings
  - std::string tries to free data stored by pointer and... segfaults

It is really strange that std::string still tries to free heap even when string is short. In case of strings longer than 16 chars all works just fine: std::string uses heap and pointer points to external (to FBVector) memory area. So, maybe it is more libc++ issue, not FBVector.

Thanks!

**Comment by Orvid** [comment]
FBVector relies on a set of assumptions that Traits makes on `std::string` being relocatable. That assumption is likely wrong for Clang 3.8: https://github.com/facebook/folly/blob/master/folly/Traits.h#L585

**Comment by yfeldblum** [comment]
Closing this issue because it is too old. Also, I believe folly no longer marks `std::string` as relocatable.
