### ISSUE TITLE
ubuntu 14.04 dependency of pkg-config?

### ISSUE THREAD

**Issue by larryxiao** [facebook/folly#502]
i didn't have problem installing folly before on ubuntu 14.04

but on a new install on ubuntu 14.04, after installing the dependencies

`autoreconf -ivf` reports: `error: possibly undefined macro: AC_MSG_NOTICE`
which can be solved by installing pkg-config as discussed in http://stackoverflow.com/questions/8811381/possibly-undefined-macro-ac-msg-error

**Comment by dgarros** [comment]
I had the same issue and installing `pkg-config` solved it

**Comment by Orvid** [comment]
Support for the autotools build has been removed in favor of CMake, so I'm closing out this issue.
