### ISSUE TITLE
error in ubuntu 16.10 while doing make

### ISSUE THREAD

**Issue by junhua** [facebook/folly#503]
Error message:

`j@jeph:~/Downloads/folly/folly$ make
make  all-recursive
make[1]: Entering directory '/home/j/Downloads/folly/folly'
Making all in .
make[2]: Entering directory '/home/j/Downloads/folly/folly'
/bin/bash ./libtool  --tag=CXX   --mode=link g++  -std=gnu++1y -g -O2 -lboost_program_options -lboost_thread -lboost_filesystem -lboost_system -lboost_regex -lpthread -lboost_chrono  -lssl -lcrypto  -o generate_fingerprint_tables build/GenerateFingerprintTables.o libfollybase.la -llzma -lz -lsnappy -llz4 -liberty -ljemalloc -levent -ldouble-conversion -lglog -lgflags
libtool: link: g++ -std=gnu++1y -g -O2 -o generate_fingerprint_tables build/GenerateFingerprintTables.o  ./.libs/libfollybase.a -lboost_program_options -lboost_thread -lboost_filesystem -lboost_system -lboost_regex -lpthread -lboost_chrono -lssl -lcrypto -llzma -lz -lsnappy -llz4 -liberty -ljemalloc -levent -ldouble-conversion -lglog -lgflags
build/GenerateFingerprintTables.o: In function`std::string\* google::MakeCheckOpString<int, unsigned long long>(int const&, unsigned long long const&, char const_)':
/usr/include/glog/logging.h:672: undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
./.libs/libfollybase.a(Conv.o): In function`std::string_ google::MakeCheckOpString<unsigned long, unsigned long>(unsigned long const&, unsigned long const&, char const_)':
/usr/include/glog/logging.h:672: undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
./.libs/libfollybase.a(Format.o): In function`std::string_ google::MakeCheckOpString<int, int>(int const&, int const&, char const_)':
/usr/include/glog/logging.h:672: undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
collect2: error: ld returned 1 exit status
Makefile:1421: recipe for target 'generate_fingerprint_tables' failed
make[2]: *_\* [generate_fingerprint_tables] Error 1
make[2]: Leaving directory '/home/j/Downloads/folly/folly'
Makefile:1690: recipe for target 'all-recursive' failed
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory '/home/j/Downloads/folly/folly'
Makefile:1035: recipe for target 'all' failed
make: **\* [all] Error 2`

**Comment by Arsey** [comment]
try to install **glog** from the sources https://github.com/google/glog
if you'll encounter an error related to **aclocal**, then do  **autoreconf -vfi** first

**Comment by junhua** [comment]
I can install glog but still the same error:

j@jeph:~/Downloads/folly/folly$ make
 cd . && /bin/bash ./config.status Makefile depfiles
config.status: creating Makefile
config.status: executing depfiles commands
make  all-recursive
make[1]: Entering directory '/home/j/Downloads/folly/folly'
Making all in .
make[2]: Entering directory '/home/j/Downloads/folly/folly'
/bin/bash ./libtool  --tag=CXX   --mode=link g++  -std=gnu++1y -g -O2 -lboost_program_options -lboost_thread -lboost_filesystem -lboost_system -lboost_regex -lpthread -lboost_chrono  -lssl -lcrypto  -o generate_fingerprint_tables build/GenerateFingerprintTables.o libfollybase.la -llzma -lz -lsnappy -llz4 -liberty -ljemalloc -levent -ldouble-conversion -lglog -lgflags 
libtool: link: g++ -std=gnu++1y -g -O2 -o generate_fingerprint_tables build/GenerateFingerprintTables.o  ./.libs/libfollybase.a -lboost_program_options -lboost_thread -lboost_filesystem -lboost_system -lboost_regex -lpthread -lboost_chrono -lssl -lcrypto -llzma -lz -lsnappy -llz4 -liberty -ljemalloc -levent -ldouble-conversion -lglog -lgflags
build/GenerateFingerprintTables.o: In function `std::string* google::MakeCheckOpString<int, unsigned long long>(int const&, unsigned long long const&, char const*)':
/usr/include/glog/logging.h:672: undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
./.libs/libfollybase.a(Conv.o): In function `std::string* google::MakeCheckOpString<unsigned long, unsigned long>(unsigned long const&, unsigned long const&, char const*)':
/usr/include/glog/logging.h:672: undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
./.libs/libfollybase.a(Format.o): In function `std::string* google::MakeCheckOpString<int, int>(int const&, int const&, char const*)':
/usr/include/glog/logging.h:672: undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
collect2: error: ld returned 1 exit status
Makefile:1421: recipe for target 'generate_fingerprint_tables' failed
make[2]: *** [generate_fingerprint_tables] Error 1
make[2]: Leaving directory '/home/j/Downloads/folly/folly'
Makefile:1690: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/j/Downloads/folly/folly'
Makefile:1035: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by sansoy** [comment]
did u ever get this resolved? 

I'm getting the same "undefined reference" error

build/GenerateFingerprintTables.o: In function `std::string* google::MakeCheckOpString<unsigned int, unsigned long long>(unsigned int const&, unsigned long long const&, char const*)':
/usr/local/include/glog/logging.h:695: undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
build/GenerateFingerprintTables.o: In function `__static_initialization_and_destruction_0':
/home/ai/folly-master/folly/build/GenerateFingerprintTables.cpp:47: undefined reference to `google::FlagRegisterer::FlagRegisterer<long>(char const*, char const*, char const*, long*, long*)'
/home/ai/folly-master/folly/build/GenerateFingerprintTables.cpp:49: undefined reference to `google::FlagRegisterer::FlagRegisterer<long>(char const*, char const*, char const*, long*, long*)'
/home/ai/folly-master/folly/build/GenerateFingerprintTables.cpp:52: undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
/home/ai/folly-master/folly/build/GenerateFingerprintTables.cpp:55: undefined reference to `google::FlagRegisterer::FlagRegisterer<long>(char const*, char const*, char const*, long*, long*)'
/home/ai/folly-master/folly/build/GenerateFingerprintTables.cpp:58: undefined reference to `google::FlagRegisterer::FlagRegisterer<long>(char const*, char const*, char const*, long*, long*)'
/home/ai/folly-master/folly/build/GenerateFingerprintTables.cpp:61: undefined reference to `google::FlagRegisterer::FlagRegisterer<std::string>(char const*, char const*, char const*, std::string*, std::string*)'
/home/ai/folly-master/folly/build/GenerateFingerprintTables.cpp:63: undefined reference to `google::FlagRegisterer::FlagRegisterer<std::string>(char const*, char const*, char const*, std::string*, std::string*)'
./.libs/libfollybase.a(Conv.o): In function `std::string* google::MakeCheckOpString<unsigned long, unsigned long>(unsigned long const&, unsigned long const&, char const*)':
/usr/local/include/glog/logging.h:695: undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
./.libs/libfollybase.a(Format.o): In function `std::string* google::MakeCheckOpString<int, int>(int const&, int const&, char const*)':
/usr/local/include/glog/logging.h:695: undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
collect2: error: ld returned 1 exit status
Makefile:1551: recipe for target 'generate_fingerprint_tables' failed
make[2]: *** [generate_fingerprint_tables] Error 1
make[2]: Leaving directory '/home/ai/folly-master/folly'
Makefile:1851: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/ai/folly-master/folly'
Makefile:1122: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jack17529** [comment]
Here too the same error.But , I am also looking forward to contribute in this project can someone please help me which files to start reading to solve this bug?

**Comment by jack17529** [comment]
@sansoy @junhua , have you guys installed CMake use this to check - cmake --version.
If not installed use this - sudo apt install cmake
Then become root in Ubuntu and run the commands and you will get no more then 3 warnings.

**Comment by Orvid** [comment]
@jack17529 CMake is not required to build Folly. I have the script setup to error if you try to use it on anything other than Windows.

**Comment by jack17529** [comment]
@Orvid  Sorry , I too got the same error but, then I did what I have mentioned and everything works fine now . Although I have just started folly today.

**Comment by qimj** [comment]
u guys solved the problem? cause i got the damn same issue and i tried everything . reinstalled gflags ,even with -DGFLAGS_NAMESPACE=google args. reinstalled glog .it's all failed~

**Comment by yfeldblum** [comment]
Closing this issue because it is too old, and because Ubuntu 16.10 is no longer a target platform.
