### ISSUE TITLE
range_test and future_test failed!!!

### ISSUE THREAD

**Issue by eric2016fly** [facebook/folly#505]
Run "make check" command.

Get the following errors.

Below is my g++ version:

test@test-M3800:~/code/folly$ g++ --version
g++ (Ubuntu 5.4.1-2ubuntu1~14.04) 5.4.1 20160904
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Here is the log.
# 
#    folly 57.0: test/test-suite.log
# TOTAL: 56
# PASS:  54
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2
# FAIL: range_test

[==========] Running 48 tests from 10 test cases.
[----------] Global test environment set-up.
[----------] 17 tests from StringPiece
[ RUN      ] StringPiece.All
F1028 10:36:35.339525 14750 RangeSse42.cpp:32] Check failed: false Function qfind_first_byte_of_sse42 only works with SSE42!
**\* Check failure stack trace: ***
**\* Aborted at 1477622195 (Unix time, try 'date -d @1477622195') ***
**\* Signal 6 (SIGABRT) (0x3e90000399e) received by PID 14750 (pthread TID 0x2b3a4ef3e940) (linux TID 14750) (maybe from PID 14750, UID 1001), stack trace: ***
    @ 00002b3a50b292dd folly::symbolizer::(anonymous namespace)::signalHandler(int, siginfo_t_, void_)
                       /home/test/code/folly/folly/experimental/symbolizer/SignalHandler.cpp:458
    @ 00002b3a4fbaf32f (unknown)
    @ 00002b3a50788c37 gsignal
    @ 00002b3a5078c027 abort
    @ 00002b3a50001da9 (unknown)
    @ 00002b3a50001ce3 (unknown)
    @ 00002b3a500016e5 (unknown)
    @ 00002b3a50004686 (unknown)
    @ 00002b3a4f56b41f folly::detail::qfind_first_byte_of_sse42(folly::detail::StringPieceLite, folly::detail::StringPieceLite)
                       /home/test/code/folly/folly/detail/RangeSse42.cpp:32
    @ 000000000041dd72 StringPiece_All_Test::TestBody()
                       /home/test/code/folly/folly/test/../../folly/Range.h:1054
                       -> /home/test/code/folly/folly/test/RangeTest.cpp
    @ 000000000045a682 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test_, void (testing::Test::_)(), char const*)
                       /home/test/code/folly/folly/test/gtest-1.7.0/src/gtest.cc:2078
                       -> /home/test/code/folly/folly/test/gtest-1.7.0/src/gtest-all.cc
    @ 000000000044d896 testing::Test::Run()
                       /home/test/code/folly/folly/test/gtest-1.7.0/src/gtest.cc:2151
                       -> /home/test/code/folly/folly/test/gtest-1.7.0/src/gtest-all.cc
    @ 000000000044d93d testing::TestInfo::Run()
                       /home/test/code/folly/folly/test/gtest-1.7.0/src/gtest.cc:2326
                       -> /home/test/code/folly/folly/test/gtest-1.7.0/src/gtest-all.cc
    @ 000000000044da44 testing::TestCase::Run()
                       /home/test/code/folly/folly/test/gtest-1.7.0/src/gtest.cc:2444
                       -> /home/test/code/folly/folly/test/gtest-1.7.0/src/gtest-all.cc
    @ 000000000044dcf7 testing::internal::UnitTestImpl::RunAllTests()
                       /home/test/code/folly/folly/test/gtest-1.7.0/src/gtest.cc:4315
                       -> /home/test/code/folly/folly/test/gtest-1.7.0/src/gtest-all.cc
    @ 000000000044dfa3 testing::UnitTest::Run()
                       /home/test/code/folly/folly/test/gtest-1.7.0/src/gtest.cc:2078
                       -> /home/test/code/folly/folly/test/gtest-1.7.0/src/gtest-all.cc
    @ 0000000000406306 main
                       /home/test/code/folly/folly/test/gtest-1.7.0/include/gtest/gtest.h:2288
                       -> /home/test/code/folly/folly/test/common/TestMain.cpp
    @ 00002b3a50773f44 __libc_start_main
    @ 0000000000406366 (unknown)
    @ ffffffffffffffff (not found)
# FAIL: futures_test

[==========] Running 228 tests from 33 test cases.
[----------] Global test environment set-up.
[----------] 19 tests from Collect
[ RUN      ] Collect.collectAll
[       OK ] Collect.collectAll (0 ms)
[ RUN      ] Collect.collect
[       OK ] Collect.collect (0 ms)
[ RUN      ] Collect.collectNotDefaultConstructible
[       OK ] Collect.collectNotDefaultConstructible (0 ms)
[ RUN      ] Collect.collectAny
[       OK ] Collect.collectAny (0 ms)
[ RUN      ] Collect.collectAnyWithoutException
[       OK ] Collect.collectAnyWithoutException (0 ms)
[ RUN      ] Collect.alreadyCompleted
[       OK ] Collect.alreadyCompleted (0 ms)
[ RUN      ] Collect.parallel
[       OK ] Collect.parallel (2 ms)
[ RUN      ] Collect.parallelWithError
[       OK ] Collect.parallelWithError (0 ms)
[ RUN      ] Collect.allParallel
[       OK ] Collect.allParallel (1 ms)
[ RUN      ] Collect.allParallelWithError
[       OK ] Collect.allParallelWithError (0 ms)
[ RUN      ] Collect.collectN
[       OK ] Collect.collectN (0 ms)
[ RUN      ] Collect.smallVector
[       OK ] Collect.smallVector (0 ms)
[ RUN      ] Collect.collectAllVariadic
[       OK ] Collect.collectAllVariadic (0 ms)
[ RUN      ] Collect.collectAllVariadicReferences
[       OK ] Collect.collectAllVariadicReferences (0 ms)
[ RUN      ] Collect.collectAllVariadicWithException
[       OK ] Collect.collectAllVariadicWithException (0 ms)
[ RUN      ] Collect.collectVariadic
[       OK ] Collect.collectVariadic (0 ms)
[ RUN      ] Collect.collectVariadicWithException
[       OK ] Collect.collectVariadicWithException (0 ms)
[ RUN      ] Collect.collectAllNone
[       OK ] Collect.collectAllNone (0 ms)
[ RUN      ] Collect.noDefaultConstructor
[       OK ] Collect.noDefaultConstructor (0 ms)
[----------] 19 tests from Collect (3 ms total)

[----------] 1 test from Context
[ RUN      ] Context.basic
[       OK ] Context.basic (0 ms)
[----------] 1 test from Context (0 ms total)

[----------] 3 tests from Convert
[ RUN      ] Convert.subclassConstruct
[       OK ] Convert.subclassConstruct (0 ms)
[ RUN      ] Convert.subclassAssign
[       OK ] Convert.subclassAssign (0 ms)
[ RUN      ] Convert.ConversionTests
[       OK ] Convert.ConversionTests (0 ms)
[----------] 3 tests from Convert (0 ms total)

[----------] 1 test from Core
[ RUN      ] Core.size
[       OK ] Core.size (0 ms)
[----------] 1 test from Core (0 ms total)

[----------] 2 tests from Ensure
[ RUN      ] Ensure.basic
[       OK ] Ensure.basic (0 ms)
[ RUN      ] Ensure.mutableLambda
[       OK ] Ensure.mutableLambda (0 ms)
[----------] 2 tests from Ensure (0 ms total)

[----------] 10 tests from ManualExecutor
[ RUN      ] ManualExecutor.runIsStable
[       OK ] ManualExecutor.runIsStable (0 ms)
[ RUN      ] ManualExecutor.scheduleDur
[       OK ] ManualExecutor.scheduleDur (0 ms)
[ RUN      ] ManualExecutor.clockStartsAt0
[       OK ] ManualExecutor.clockStartsAt0 (0 ms)
[ RUN      ] ManualExecutor.scheduleAbs
[       OK ] ManualExecutor.scheduleAbs (0 ms)
[ RUN      ] ManualExecutor.advanceTo
[       OK ] ManualExecutor.advanceTo (0 ms)
[ RUN      ] ManualExecutor.advanceBack
[       OK ] ManualExecutor.advanceBack (0 ms)
[ RUN      ] ManualExecutor.advanceNeg
[       OK ] ManualExecutor.advanceNeg (0 ms)
[ RUN      ] ManualExecutor.waitForDoesNotDeadlock
[       OK ] ManualExecutor.waitForDoesNotDeadlock (0 ms)
[ RUN      ] ManualExecutor.getViaDoesNotDeadlock
[       OK ] ManualExecutor.getViaDoesNotDeadlock (0 ms)
[ RUN      ] ManualExecutor.clear
[       OK ] ManualExecutor.clear (0 ms)
[----------] 10 tests from ManualExecutor (0 ms total)

[----------] 7 tests from Executor
[ RUN      ] Executor.InlineExecutor
[       OK ] Executor.InlineExecutor (0 ms)
[ RUN      ] Executor.QueuedImmediateExecutor
[       OK ] Executor.QueuedImmediateExecutor (0 ms)
[ RUN      ] Executor.Runnable
[       OK ] Executor.Runnable (0 ms)
[ RUN      ] Executor.RunnablePtr
[       OK ] Executor.RunnablePtr (0 ms)
[ RUN      ] Executor.ThrowableThen
[       OK ] Executor.ThrowableThen (0 ms)
[ RUN      ] Executor.CrappyExecutor
[       OK ] Executor.CrappyExecutor (0 ms)
[ RUN      ] Executor.DoNothingExecutor
[       OK ] Executor.DoNothingExecutor (0 ms)
[----------] 7 tests from Executor (1 ms total)

[----------] 8 tests from FSM
[ RUN      ] FSM.example
[       OK ] FSM.example (0 ms)
[ RUN      ] FSM.magicMacrosExample
[       OK ] FSM.magicMacrosExample (0 ms)
[ RUN      ] FSM.ctor
[       OK ] FSM.ctor (0 ms)
[ RUN      ] FSM.update
[       OK ] FSM.update (0 ms)
[ RUN      ] FSM.badUpdate
[       OK ] FSM.badUpdate (0 ms)
[ RUN      ] FSM.actionOnUpdate
[       OK ] FSM.actionOnUpdate (0 ms)
[ RUN      ] FSM.noActionOnBadUpdate
[       OK ] FSM.noActionOnBadUpdate (0 ms)
[ RUN      ] FSM.stateTransitionAfterAction
[       OK ] FSM.stateTransitionAfterAction (0 ms)
[----------] 8 tests from FSM (0 ms total)

[----------] 3 tests from Filter
[ RUN      ] Filter.alwaysTrye
[       OK ] Filter.alwaysTrye (0 ms)
[ RUN      ] Filter.alwaysFalse
[       OK ] Filter.alwaysFalse (0 ms)
[ RUN      ] Filter.moveOnlyValue
[       OK ] Filter.moveOnlyValue (0 ms)
[----------] 3 tests from Filter (0 ms total)

[----------] 37 tests from Future
[ RUN      ] Future.futureDefaultCtor
[       OK ] Future.futureDefaultCtor (0 ms)
[ RUN      ] Future.futureToUnit
[       OK ] Future.futureToUnit (0 ms)
[ RUN      ] Future.voidFutureToUnit
[       OK ] Future.voidFutureToUnit (0 ms)
[ RUN      ] Future.unitFutureToUnitIdentity
[       OK ] Future.unitFutureToUnitIdentity (0 ms)
[ RUN      ] Future.toUnitWhileInProgress
[       OK ] Future.toUnitWhileInProgress (0 ms)
[ RUN      ] Future.makeFutureWithUnit
[       OK ] Future.makeFutureWithUnit (0 ms)
[ RUN      ] Future.onError
[       OK ] Future.onError (0 ms)
[ RUN      ] Future.special
[       OK ] Future.special (0 ms)
[ RUN      ] Future.then
[       OK ] Future.then (0 ms)
[ RUN      ] Future.thenTry
[       OK ] Future.thenTry (0 ms)
[ RUN      ] Future.thenValue
[       OK ] Future.thenValue (0 ms)
[ RUN      ] Future.thenValueFuture
[       OK ] Future.thenValueFuture (0 ms)
[ RUN      ] Future.thenFunction
[       OK ] Future.thenFunction (0 ms)
[ RUN      ] Future.thenFunctionFuture
[       OK ] Future.thenFunctionFuture (0 ms)
[ RUN      ] Future.thenStdFunction
[       OK ] Future.thenStdFunction (0 ms)
[ RUN      ] Future.thenBind
[       OK ] Future.thenBind (0 ms)
[ RUN      ] Future.thenBindTry
[       OK ] Future.thenBindTry (0 ms)
[ RUN      ] Future.value
[       OK ] Future.value (0 ms)
[ RUN      ] Future.isReady
[       OK ] Future.isReady (0 ms)
[ RUN      ] Future.futureNotReady
[       OK ] Future.futureNotReady (0 ms)
[ RUN      ] Future.hasException
[       OK ] Future.hasException (0 ms)
[ RUN      ] Future.hasValue
[       OK ] Future.hasValue (0 ms)
[ RUN      ] Future.makeFuture
[       OK ] Future.makeFuture (0 ms)
[ RUN      ] Future.finish
[       OK ] Future.finish (0 ms)
[ RUN      ] Future.finishBigLambda
[       OK ] Future.finishBigLambda (0 ms)
[ RUN      ] Future.unwrap
[       OK ] Future.unwrap (0 ms)
[ RUN      ] Future.throwCaughtInImmediateThen
[       OK ] Future.throwCaughtInImmediateThen (0 ms)
[ RUN      ] Future.throwIfFailed
[       OK ] Future.throwIfFailed (0 ms)
[ RUN      ] Future.getFutureAfterSetValue
[       OK ] Future.getFutureAfterSetValue (0 ms)
[ RUN      ] Future.getFutureAfterSetException
[       OK ] Future.getFutureAfterSetException (0 ms)
[ RUN      ] Future.detachRace
[       OK ] Future.detachRace (0 ms)
[ RUN      ] Future.CircularDependencySharedPtrSelfReset
[       OK ] Future.CircularDependencySharedPtrSelfReset (0 ms)
[ RUN      ] Future.Constructor
[       OK ] Future.Constructor (0 ms)
[ RUN      ] Future.ImplicitConstructor
[       OK ] Future.ImplicitConstructor (0 ms)
[ RUN      ] Future.thenDynamic
[       OK ] Future.thenDynamic (1 ms)
[ RUN      ] Future.RequestContext
**\* Aborted at 1477622255 (Unix time, try 'date -d @1477622255') ***
**\* Signal 11 (SIGSEGV) (0x20) received by PID 1302 (pthread TID 0x2ae4580a1a80) (linux TID 1302) (maybe from PID 32, UID 0) (code: address not mapped to object), stack trace: ***
    @ 00002ae45a5c92dd folly::symbolizer::(anonymous namespace)::signalHandler(int, siginfo_t_, void_)
                       /home/test/code/folly/folly/experimental/symbolizer/SignalHandler.cpp:458
    @ 00002ae45913832f (unknown)
    @ 000000000044357a folly::detail::Core<int>::doCallback()
                       /home/test/code/folly/folly/test/../../folly/futures/detail/Core.h:380
                       -> /home/test/code/folly/folly/test/../futures/test/CollectTest.cpp
    @ 00000000004439ec folly::detail::Core<int>::maybeCallback()
                       /home/test/code/folly/folly/test/../../folly/futures/detail/Core.h:357
                       -> /home/test/code/folly/folly/test/../futures/test/CollectTest.cpp
    @ 0000000000443b11 folly::detail::Core<int>::setResult(folly::Try<int>&&)
                       /home/test/code/folly/folly/test/../../folly/futures/detail/Core.h:204
                       -> /home/test/code/folly/folly/test/../futures/test/CollectTest.cpp
    @ 0000000000483dfe void folly::Promise<int>::setValue<int>(int&&) [clone .isra.1233]
                       /home/test/code/folly/folly/test/../../folly/futures/Promise-inl.h:117
                       -> /home/test/code/folly/folly/test/../futures/test/FutureTest.cpp
    @ 0000000000490e12 Future_RequestContext_Test::TestBody()
                       /home/test/code/folly/folly/test/../futures/test/FutureTest.cpp:851
    @ 00000000005b11a2 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test_, void (testing::Test::_)(), char const*)
                       /home/test/code/folly/folly/test/gtest-1.7.0/src/gtest.cc:2078
                       -> /home/test/code/folly/folly/test/gtest-1.7.0/src/gtest-all.cc
    @ 00000000005a4426 testing::Test::Run()
                       /home/test/code/folly/folly/test/gtest-1.7.0/src/gtest.cc:2151
                       -> /home/test/code/folly/folly/test/gtest-1.7.0/src/gtest-all.cc
    @ 00000000005a44cd testing::TestInfo::Run()
                       /home/test/code/folly/folly/test/gtest-1.7.0/src/gtest.cc:2326
                       -> /home/test/code/folly/folly/test/gtest-1.7.0/src/gtest-all.cc
    @ 00000000005a45d4 testing::TestCase::Run()
                       /home/test/code/folly/folly/test/gtest-1.7.0/src/gtest.cc:2444
                       -> /home/test/code/folly/folly/test/gtest-1.7.0/src/gtest-all.cc
    @ 00000000005a4887 testing::internal::UnitTestImpl::RunAllTests()
                       /home/test/code/folly/folly/test/gtest-1.7.0/src/gtest.cc:4315
                       -> /home/test/code/folly/folly/test/gtest-1.7.0/src/gtest-all.cc
    @ 00000000005a4b33 testing::UnitTest::Run()
                       /home/test/code/folly/folly/test/gtest-1.7.0/src/gtest.cc:2078
                       -> /home/test/code/folly/folly/test/gtest-1.7.0/src/gtest-all.cc
    @ 0000000000421976 main
                       /home/test/code/folly/folly/test/gtest-1.7.0/include/gtest/gtest.h:2288
                       -> /home/test/code/folly/folly/test/common/TestMain.cpp
    @ 00002ae45a213f44 __libc_start_main
    @ 00000000004219d6 (unknown)
    @ ffffffffffffffff (not found)

**Comment by Orvid** [comment]
This should have been fixed by https://github.com/facebook/folly/commit/5c3799297109076c31ee801f00312cfaa0bbc605.
