### ISSUE TITLE
StringPiece::find fails with "Function qfind_first_byte_of_sse42 only works with SSE42!"

### ISSUE THREAD

**Issue by tudor** [facebook/folly#509]
This happens because we build folly/detail/RangeSse42.cpp without -msse4.2 (or appropriate -march=... flags).

Compiling RangeSse42.cpp with -msse4.2 is always appropriate, even when the target architecture doesn't support SSE4.2, as we check at runtime that SSE4.2 is supported before calling the SSE4.2-specific functions.

**Comment by tudor** [comment]
This is on Ubuntu 16.04, gcc-5.4.0 (default), where the default gcc target doesn't include SSE4.2:
`gcc -Q --help=target | grep march` returns `x86-64`.

**Comment by Orvid** [comment]
I thought I already resolved this by having the SSE 4.2 version forward to the non-SSE 4.2 version when we compiled without SSE 4.2 support...

**Comment by tudor** [comment]
I think I hadn't rebased when I encountered the problem, so I missed your fix. This is better, though -- as folly checks for SSE4.2 at runtime, it's safe to always compile RangeSse42.cpp with SSE4.2 support, even when you're targeting a lower-end architecture, so this is suitable for prebuilt binaries / packages.

**Comment by Orvid** [comment]
Agreed, it's just that this method of resolving the issue doesn't help HHVM or WDT, as both use their own CMake scripts to build rather than the makefile here. :P
