### ISSUE TITLE
Add "libgtest-dev" as a dependency

### ISSUE THREAD

**Issue by vjon** [facebook/folly#511]
I think it would be a nice usability improvement if Google Test was setup as a Git submodule for this repository, as opposed to the current method of unzipping the source to folly/test. It would also have the side benefit of aligning the project structure with some other Facebook projects (e.g. osquery also depends on Google Test v1.7.0, and tracks it as a submodule).

If there's interest in this potential enhancement, I can whip up a commit for review.

**Comment by Orvid** [comment]
I'm not sure it would be worthwhile for Folly. The vast majority of distros that Folly supports already have gtest/gmock packages, so I'm not sure what would be gained by building against an in-tree version.

**Comment by vjon** [comment]
Hmm, in that case, perhaps this is just a documentation error? The Readme still refers to unzipping Google Test directly into folly/test/, and makes no mention of installing it via package manager.

**Comment by vjon** [comment]
Upon further review, and based on the input from @Orvid, it seems like the preferred option would be for `automake` to copy the Google Test source code from the distro package (i.e. `libgtest-dev` on Ubuntu), instead of requiring the user to manually extract the source into `./folly/test/gtest-1.*`

**Comment by Orvid** [comment]
It works that way, but isn't required. It should be fully compilable with `libgtest-dev` installed normally. If that isn't currently the case, then we should make that the case.

**Comment by vjon** [comment]
I am trying to build on Ubuntu 16.04, and the build fails upon running `make check`. The exact procedure was:

`autoreconf -ivf`
`./configure --enable-follytestmain`
`make`
`make check`

And the tail end of the output for `make check` is:

`make[3]: Entering directory '/home/vjon/Code/Projects/folly/folly/test'`
`make[3]: *** No rule to make target 'gtest-1.7.0/src/gtest-all.cc', needed by 'gtest-1.7.0/src/libfollytestmain_la-gtest-all.lo'.  Stop.`
`make[3]: Leaving directory '/home/vjon/Code/Projects/folly/folly/test'`
`Makefile:2550: recipe for target 'check-am' failed`
`make[2]: *** [check-am] Error 2`
`make[2]: Leaving directory '/home/vjon/Code/Projects/folly/folly/test'`
`Makefile:1854: recipe for target 'check-recursive' failed`
`make[1]: *** [check-recursive] Error 1`
`make[1]: Leaving directory '/home/vjon/Code/Projects/folly/folly/test'`
`Makefile:1728: recipe for target 'check-recursive' failed`
`make: *** [check-recursive] Error 1`

This is with all the listed dependencies + libgtest-dev installed.

**Comment by Orvid** [comment]
Support for the autotools build has been removed in favor of CMake, so I'm closing out this issue.

The CMake build expects google test to either be installed system wide, or have their paths passed in to the build.
