### ISSUE TITLE
folly::detail::AccessSpreader<std::atomic>::getcpuFunc Not Found 

### ISSUE THREAD

**Issue by helloleef** [facebook/folly#516]
link libfolly.a , g++6.2 ,  Error info is  

folly/detail/CacheLocality.h:256: undefined reference to `folly::detail::AccessSpreader<std::atomic>::getcpuFunc`

**Comment by jack17529** [comment]
Can I work on this one?

**Comment by Orvid** [comment]
That function no longer lives in `detail/CacheLocality.h`, it's been moved to `concurrency/CacheLocality.h`. If you can still reproduce the issue then feel free to fix it.

**Comment by jack17529** [comment]
@Orvid , this may be a silly question , but may I please know what does this line do -
https://github.com/facebook/folly/blob/master/folly/concurrency/CacheLocality.h#L96
I only have coded introductory templates.

**Comment by Orvid** [comment]
It declares `Atom` as a template template parameter:
http://en.cppreference.com/w/cpp/language/template_parameters#Template_template_parameter

**Comment by jack17529** [comment]
@Orvid can you please explain the meaning behind doing - https://github.com/facebook/folly/blob/master/folly/concurrency/CacheLocality.h#L385
this ?

**Comment by Orvid** [comment]
It's popping a value off of the free-list that had been previously pushed to at:
https://github.com/facebook/folly/blob/master/folly/concurrency/CacheLocality.h#L407
by storing the previous value in the first 8-bytes of the allocation.

**Comment by jack17529** [comment]
@Orvid the vcpkg installed old repositories in my system and is now not updating them , I have opened issue on vcpkg repository for this .
