### ISSUE TITLE
ZSTD_maxCLevel was not declared during compilation

### ISSUE THREAD

**Issue by fdesmedt** [facebook/folly#519]
I'm trying to install fblualib on an Ubuntu 16.04 (g++ 5.4.1) which has an install script to install all dependencies first, including folly. I get however an error during the compilation of folly: ‘ZSTD_maxCLevel’ was not declared in this scope.

Someone experienced the same issue?

Best regards

**Comment by Orvid** [comment]
This should be fixed by https://github.com/facebook/folly/commit/4432fc2457d2bdeea3e910a6dade8560e283f959, as the auto-conf script was only checking if a version of zstd was available rather than if it was new enough for Folly to be able to make use of it.
