### ISSUE TITLE
Can't compile folly on Ubuntu 16.04, error with double_conversion head file

### ISSUE THREAD

**Issue by stanislashzc** [facebook/folly#521]
After I configure folly and run make, it comes with this issue:
/bin/bash ./libtool  --tag=CXX   --mode=link g++  -std=gnu++1y -g -O2 -lboost_context -lboost_program_options -lboost_thread -lboost_filesystem -lboost_system -lboost_regex -lpthread -lboost_chrono  -lssl -lcrypto  -o generate_fingerprint_tables build/GenerateFingerprintTables.o libfollybase.la -llzma -lz -lsnappy -llz4 -liberty -ljemalloc -levent -ldouble-conversion -lglog -lgflags 
libtool: link: g++ -std=gnu++1y -g -O2 -o generate_fingerprint_tables build/GenerateFingerprintTables.o  ./.libs/libfollybase.a -lboost_context -lboost_program_options -lboost_thread -lboost_filesystem -lboost_system -lboost_regex -lpthread -lboost_chrono -lssl -lcrypto -llzma -lz -lsnappy -llz4 -liberty -ljemalloc -levent -ldouble-conversion -lglog -lgflags
./.libs/libfollybase.a(Conv.o): In function `double_conversion::StringToDoubleConverter::StringToDouble(char const*, int, int*) const':
/usr/local/include/double-conversion/double-conversion.h:506: undefined reference to `double_conversion::StringToDoubleConverter::StringToIeee(char const*, int, int*, bool) const'
/usr/local/include/double-conversion/double-conversion.h:506: undefined reference to `double_conversion::StringToDoubleConverter::StringToIeee(char const*, int, int*, bool) const'
collect2: error: ld returned 1 exit status
Makefile:1456: recipe for target 'generate_fingerprint_tables' failed
make[2]: *** [generate_fingerprint_tables] Error 1
make[2]: Leaving directory '/home/padl/data_1/software/folly-2016.11.21.00/folly'
Makefile:1736: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/padl/data_1/software/folly-2016.11.21.00/folly'
Makefile:1063: recipe for target 'all' failed
make: *** [all] Error 2

why it says undefined reference to `double_conversion::StringToDoubleConverter::StringToIeee(char const*, int, int*, bool) const'?
gcc version is 5.4.0 for Ubutun 16.04.

**Comment by Orvid** [comment]
double-conversion is getting linked in, so this sounds like an issue with your build environment rather than an issue with Folly.
