### ISSUE TITLE
Undefined reference to member functions in folly::symbolizer

### ISSUE THREAD

**Issue by Laser-Cat** [facebook/folly#522]
I got the following errors while linking the folly library.
/usr/local/lib/libfolly.so: undefined reference to `folly::symbolizer::installFatalSignalHandler()'
/usr/local/lib/libfolly.so: undefined reference to `folly::symbolizer::installFatalSignalCallbacks()'
By commenting those lines in Init.cpp the problems disappers
 #if !defined(__APPLE__) && !defined(_WIN32)
 #define USE_FOLLY_SYMBOLIZER 1
 #endif
Is this caused by googletest package or a BUG?

P.S. I am using Manjaro.

**Comment by cerceris** [comment]
Just faced the same issue. 
The reason is that the headers were put into Makefile.am, but the respective .cpp files were not.

**Comment by Orvid** [comment]
I've reverted the commit in question: https://github.com/facebook/folly/commit/6d58adc5225a4662faf5f6343069dec626fdc84d

**Comment by maichm** [comment]
I had solved this problem by replacing
`set(FOLLY_USE_SYMBOLIZER OFF)`
to 
`set(FOLLY_USE_SYMBOLIZER ON)`
in .file `CMake/folly-deps.cmake`
