### ISSUE TITLE
Debian 8.6 build failing - LZ4_compress

### ISSUE THREAD

**Issue by Ice32** [facebook/folly#524]
I'm running Debian 8.6 64 bit with g++ 4.9.2. I was trying to install Proxygen and required libraries, but the build seems to fail on some folly files. The same error happens when I download folly separately and then run `make `.

Here's the error:
![screenshot - 11282016 - 10 41 28 pm](https://cloud.githubusercontent.com/assets/10289395/20687245/0975c71e-b5bc-11e6-85ad-cef78daa7e5a.png)

**Comment by aslanie** [comment]
I received the same error, and I'm running it on Ubuntu14.04

**Comment by Orvid** [comment]
This should be fixed by https://github.com/facebook/folly/commit/b82fb4f77c83c14dbb34a1b5189f67018bba7a65. We were using an API only provided by a newer version of LZ4.
