### ISSUE TITLE
JSON serialization does not handle emoji?

### ISSUE THREAD

**Issue by yunjing** [facebook/folly#526]
`folly::json::serialize` failed with error `folly::decodeUtf8 encoding length maxed out` with given a `dynamic` object with emoji string "\xf0\x9f\x91\xB8".

I am no expert on unicode, but the [code](https://github.com/facebook/folly/blob/master/folly/json.cpp#L80) seems to be ignoring the 4th byte. Is this a bug or am i doing anything wrong?

**Comment by Orvid** [comment]
JSON only supports the escaped form of characters `\u0000` to `\uFFFF`, and (further upstream in the folly json encoding) we actually treat the return of that as being a `char16_t`. However, it's worth noting that characters above `\uFFFF` are still allowed in strings according to the spec, they just can't be escaped. I have no idea what should be done in this case.

**Comment by yunjing** [comment]
I guess I still don't fully understand the issue here. According to the [comment](https://github.com/facebook/folly/blob/master/folly/json.cpp#L45), my input "\xf0\x9f\x91\xB8" is a valid sequence. Then, why is it causing exception? In addition, the [code](https://github.com/facebook/folly/blob/master/folly/json.cpp#L80) here does not touch the 4th byte, which also contradicts the comment.

I naively changed the code from `i !=3` to `i != 4` and the function did return the right code point `128516`. Do you mind explaining why doing so is wrong?

**Comment by Orvid** [comment]
The issue is that, although it does get decoded correctly, it won't be encoded correctly in the escaped JSON string; the code [here](https://github.com/facebook/folly/blob/master/folly/json.cpp#L729) expects the maximum decoded value to be `65565`, because that's the maximum value that the JSON spec allows escaping like that is `65565`. The value you're trying to encode is too large to be escaped properly in the JSON format.

**Comment by ptf** [comment]
@Orvid you can encode chars above \uFFFF with a surrogate pair..

**Comment by yunjing** [comment]
@Orvid Thanks for the explanation. I am also wondering if it is reasonable to add the support of surrogate pair, as @ptf suggested, as an extension to the current implementation in folly.

**Comment by Orvid** [comment]
Support for 4-byte unicode characters via surrogate pairs was added in https://github.com/facebook/folly/commit/07a29570c3d9b4bf560c08d337fb7d76e961eb76#diff-9ac69ce2e36be451678f1be30c4b7548.
