### ISSUE TITLE
moveToFbString throws segfault sometimes

### ISSUE THREAD

**Issue by abhiguru** [facebook/folly#527]
Happens occasionally 

PC: @     0x7fdb4994fc9c folly::IOBuf::moveToFbString()
*** SIGSEGV (@0x30) received by PID 13575 (TID 0x7fdb3e07e700) from PID 48; stack trace: ***
    @     0x7fdb495f2670 (unknown)
    @     0x7fdb4994fc9c folly::IOBuf::moveToFbString()
    @     0x55aaa74a22cb CurlService::CurlClient::onEOM()
    @     0x55aaa74e39de proxygen::HTTPTransaction::processIngressEOM()
    @     0x55aaa74e3e3d proxygen::HTTPTransaction::onIngressEOM()
    @     0x55aaa74d2b4a proxygen::HTTPSession::onMessageComplete()
    @     0x55aaa751b597 proxygen::HTTP1xCodec::onMessageComplete()
    @     0x55aaa751b77a proxygen::HTTP1xCodec::onMessageCompleteCB()
    @     0x55aaa7509088 proxygen::http_parser_execute()
    @     0x55aaa7519830 proxygen::HTTP1xCodec::onIngress()
    @     0x55aaa74c9fae proxygen::HTTPSession::processReadData()
    @     0x55aaa74cc6e7 proxygen::HTTPSession::readDataAvailable()
    @     0x7fdb499726ae folly::AsyncSocket::handleRead()
    @     0x7fdb499819fc folly::AsyncSSLSocket::handleRead()
    @     0x7fdb4996d06a folly::AsyncSocket::ioReady()
    @     0x7fdb45d59a0c event_base_loop
    @     0x7fdb49984bd0 folly::EventBase::loopBody()
    @     0x7fdb499868b6 folly::EventBase::loopForever()
    @     0x55aaa74388fe VideoProcessor::initSegmentListener()
    @     0x55aaa7438629 VideoProcessor::VideoProcessor()
    @     0x55aaa74234d6 _ZZ4mainENKUlN3vcu12CurlResponseEE0_clES0_
    @     0x55aaa742451a _ZZZN5folly6FutureIN3vcu12CurlResponseEE18thenImplementationIRZ4mainEUlS2_E0_NS_6detail14callableResultIS2_S6_EELb0EJOS2_EEENSt9enable_ifIXntsrNT0_13ReturnsFutureE5valueENSC_6ReturnEE4typeEOT_NS7_9argResultIXT1_ESH_JDpT2_EEEENUlONS_3TryIS2_EEE_clESP_ENKUlvE_clEv
    @     0x55aaa742563b _ZN5folly11makeTryWithIZZNS_6FutureIN3vcu12CurlResponseEE18thenImplementationIRZ4mainEUlS3_E0_NS_6detail14callableResultIS3_S7_EELb0EJOS3_EEENSt9enable_ifIXntsrNT0_13ReturnsFutureE5valueENSD_6ReturnEE4typeEOT_NS8_9argResultIXT1_ESI_JDpT2_EEEENUlONS_3TryIS3_EEE_clESQ_EUlvE_EENSC_IXntsrSt7is_sameINSt9result_ofIFSI_vEE4typeEvE5valueENSO_ISX_EEE4typeESJ_
    @     0x55aaa7424d02 _ZN5folly7PromiseIN3vcu12CurlResponseEE7setWithIZZNS_6FutureIS2_E18thenImplementationIRZ4mainEUlS2_E0_NS_6detail14callableResultIS2_S9_EELb0EJOS2_EEENSt9enable_ifIXntsrNT0_13ReturnsFutureE5valueENSF_6ReturnEE4typeEOT_NSA_9argResultIXT1_ESK_JDpT2_EEEENUlONS_3TryIS2_EEE_clESS_EUlvE_EEvSL_
    @     0x55aaa7424634 _ZZN5folly6FutureIN3vcu12CurlResponseEE18thenImplementationIRZ4mainEUlS2_E0_NS_6detail14callableResultIS2_S6_EELb0EJOS2_EEENSt9enable_ifIXntsrNT0_13ReturnsFutureE5valueENSC_6ReturnEE4typeEOT_NS7_9argResultIXT1_ESH_JDpT2_EEEENUlONS_3TryIS2_EEE_clESP_
    @     0x55aaa7426773 _ZN5folly6detail8function14FunctionTraitsIFvONS_3TryIN3vcu12CurlResponseEEEEE9callSmallIZNS_6FutureIS5_E18thenImplementationIRZ4mainEUlS5_E0_NS0_14callableResultIS5_SF_EELb0EJOS5_EEENSt9enable_ifIXntsrNT0_13ReturnsFutureE5valueENSK_6ReturnEE4typeEOT_NS0_9argResultIXT1_ESP_JDpT2_EEEEUlS7_E_EEvRNS1_4DataES7_
    @     0x55aaa7466f20 folly::detail::function::FunctionTraits<>::operator()()
    @     0x55aaa7462cc0 _ZZN5folly6detail4CoreIN3vcu12CurlResponseEE10doCallbackEvENUlvE_clEv
    @     0x55aaa74700a4 _ZN5folly6detail8function14FunctionTraitsIFvvEE9callSmallIZNS0_4CoreIN3vcu12CurlResponseEE10doCallbackEvEUlvE_EEvRNS1_4DataE
    @     0x55aaa755c8bb folly::detail::function::FunctionTraits<>::operator()()
    @     0x55aaa755f841 wangle::ThreadPoolExecutor::runTask()
    @     0x55aaa75545b3 wangle::CPUThreadPoolExecutor::threadRun()

**Comment by afrind** [comment]
All of these crashes in slightly different places all suggest a memory related problem.  Can you reproduce using our sample code or small test progream and/or run your binary with ASAN enabled?

**Comment by abhiguru** [comment]
Have yet been unable to reproc with ASAN build will reopen if it occurs
