### ISSUE TITLE
sigsegv  folly::IOBufQueue::append() occasionally 

### ISSUE THREAD

**Issue by abhiguru** [facebook/folly#528]
Happens occsionally 

*** Aborted at 1481231432 (unix time) try "date -d @1481231432" if you are using GNU date ***
PC: @     0x7ff0a43b39d1 (unknown)
*** SIGSEGV (@0x7ff0846795c8) received by PID 14895 (TID 0x7ff09ac7e700) from PID 18446744071635965384; stack trace: ***
    @     0x7ff0a628a670 (unknown)
    @     0x7ff0a43b39d1 (unknown)
    @     0x7ff0a65e9fcd folly::IOBufQueue::append()
    @     0x56463663e6a9 proxygen::HTTP1xCodec::generateHeader()
    @     0x56463665e3a6 proxygen::HTTPChecks::generateHeader()
    @     0x5646365efbba proxygen::HTTPSession::sendHeaders()
    @     0x5646365ffea5 proxygen::HTTPTransaction::sendHeadersWithOptionalEOM()
    @     0x5646365c2721 CurlService::CurlClient::connectSuccess()
    @     0x5646365d9433 proxygen::HTTPConnector::connectSuccess()
    @     0x7ff0a66108d5 (anonymous namespace)::AsyncSSLSocketConnector::handshakeSuc()
    @     0x7ff0a6616557 folly::AsyncSSLSocket::handleConnect()
    @     0x7ff0a6619a2f folly::AsyncSSLSocket::handleRead()
    @     0x7ff0a660506a folly::AsyncSocket::ioReady()
    @     0x7ff0a29f1a0c event_base_loop
    @     0x7ff0a661cbd0 folly::EventBase::loopBody()
    @     0x7ff0a661e8b6 folly::EventBase::loopForever()
    @     0x5646365598fe VideoProcessor::initSegmentListener()
    @     0x564636559629 VideoProcessor::VideoProcessor()
    @     0x5646365444d6 _ZZ4mainENKUlN3vcu12CurlResponseEE0_clES0_
    @     0x56463654551a _ZZZN5folly6FutureIN3vcu12CurlResponseEE18thenImplementationIRZ4mainEUlS2_E0_NS_6detail14callableResultIS2_S6_EELb0EJOS2_EEENSt9enable_ifIXntsrNT0_13ReturnsFutureE5valueENSC_6ReturnEE4typeEOT_NS7_9argResultIXT1_ESH_JDpT2_EEEENUlONS_3TryIS2_EEE_clESP_ENKUlvE_clEv
    @     0x56463654663b _ZN5folly11makeTryWithIZZNS_6FutureIN3vcu12CurlResponseEE18thenImplementationIRZ4mainEUlS3_E0_NS_6detail14callableResultIS3_S7_EELb0EJOS3_EEENSt9enable_ifIXntsrNT0_13ReturnsFutureE5valueENSD_6ReturnEE4typeEOT_NS8_9argResultIXT1_ESI_JDpT2_EEEENUlONS_3TryIS3_EEE_clESQ_EUlvE_EENSC_IXntsrSt7is_sameINSt9result_ofIFSI_vEE4typeEvE5valueENSO_ISX_EEE4typeESJ_
    @     0x564636545d02 _ZN5folly7PromiseIN3vcu12CurlResponseEE7setWithIZZNS_6FutureIS2_E18thenImplementationIRZ4mainEUlS2_E0_NS_6detail14callableResultIS2_S9_EELb0EJOS2_EEENSt9enable_ifIXntsrNT0_13ReturnsFutureE5valueENSF_6ReturnEE4typeEOT_NSA_9argResultIXT1_ESK_JDpT2_EEEENUlONS_3TryIS2_EEE_clESS_EUlvE_EEvSL_
    @     0x564636545634 _ZZN5folly6FutureIN3vcu12CurlResponseEE18thenImplementationIRZ4mainEUlS2_E0_NS_6detail14callableResultIS2_S6_EELb0EJOS2_EEENSt9enable_ifIXntsrNT0_13ReturnsFutureE5valueENSC_6ReturnEE4typeEOT_NS7_9argResultIXT1_ESH_JDpT2_EEEENUlONS_3TryIS2_EEE_clESP_
    @     0x564636547773 _ZN5folly6detail8function14FunctionTraitsIFvONS_3TryIN3vcu12CurlResponseEEEEE9callSmallIZNS_6FutureIS5_E18thenImplementationIRZ4mainEUlS5_E0_NS0_14callableResultIS5_SF_EELb0EJOS5_EEENSt9enable_ifIXntsrNT0_13ReturnsFutureE5valueENSK_6ReturnEE4typeEOT_NS0_9argResultIXT1_ESP_JDpT2_EEEEUlS7_E_EEvRNS1_4DataES7_
    @     0x564636587e94 folly::detail::function::FunctionTraits<>::operator()()
    @     0x564636583c34 _ZZN5folly6detail4CoreIN3vcu12CurlResponseEE10doCallbackEvENUlvE_clEv
    @     0x564636591018 _ZN5folly6detail8function14FunctionTraitsIFvvEE9callSmallIZNS0_4CoreIN3vcu12CurlResponseEE10doCallbackEvEUlvE_EEvRNS1_4DataE
    @     0x56463667d82b folly::detail::function::FunctionTraits<>::operator()()
    @     0x5646366807b1 wangle::ThreadPoolExecutor::runTask()
    @     0x564636675523 wangle::CPUThreadPoolExecutor::threadRun()
    @     0x56463668eeab _ZSt13__invoke_implIvRKMN6wangle18ThreadPoolExecutorEFvSt10shared_ptrINS1_6ThreadEEERPS1_JRS4_EET_St21__invoke_memfun_derefOT0_OT1_DpOT2_
    @     0x56463668e48a _ZSt8__invokeIRKMN6wangle18ThreadPoolExecutorEFvSt10shared_ptrINS1_6ThreadEEEJRPS1_RS4_EENSt9result_ofIFOT_DpOT0_EE4typeESE_SH_

**Comment by afrind** [comment]
Is it possible for you to run using ASAN?  The problem is unlikely to be in IOBufQueue:append(), but rather some problem with the underlying memory being already freed or otherwise corrupt.  Running with a higher verbosity may also help turn up additional debug details.

**Comment by abhiguru** [comment]
Have been unable to reproduce with ASAN build will reopen if it occurs
