### ISSUE TITLE
support CMakeLists.txt

### ISSUE THREAD

**Issue by cyongxue** [facebook/folly#532]
when support CMakeLists.txt for make

**Comment by Orvid** [comment]
Currently I plan to support building Folly with CMake only on Windows with MSVC, due primarily to the fact that I'm using features of versions of CMake that are significantly newer than what is easily available (in the main packaging repos)

**Comment by tamaskenez** [comment]
it's very easy to build the latest cmake on any platform so this shouldn't be an issue
