### ISSUE TITLE
failed in configure, saying google-gflags library is not installed.

### ISSUE THREAD

**Issue by oranger34** [facebook/folly#535]
checking for main in -lgflags... no
configure: error: Please install google-gflags library

what shall I do to change the default path of gflags?

brew list gflags
/usr/local/Cellar/gflags/2.2.0/bin/gflags_completions.sh
/usr/local/Cellar/gflags/2.2.0/include/gflags/ (4 files)
/usr/local/Cellar/gflags/2.2.0/lib/libgflags.2.2.0.dylib
/usr/local/Cellar/gflags/2.2.0/lib/libgflags_nothreads.2.2.0.dylib
/usr/local/Cellar/gflags/2.2.0/lib/cmake/ (4 files)
/usr/local/Cellar/gflags/2.2.0/lib/pkgconfig/gflags.pc
/usr/local/Cellar/gflags/2.2.0/lib/ (4 other files)

**Comment by Orvid** [comment]
Support for the autotools build has been removed in favor of CMake, so I'm closing out this issue.
