### ISSUE TITLE
Small typo in folly/IPAddress.h

### ISSUE THREAD

**Issue by samsonwang** [facebook/folly#539]
File: folly/IPAddress.h
Line Number: 69
There shows: `// returns true iff the input string can be parsed as an ip-address` 
I think it maight be like this: `// returns true if the input string can be parsed as an ip-address` 
Typo: "iff" to "if".

**Comment by yfeldblum** [comment]
`iff` is intended and correct.

http://www.mathwords.com/i/if_and_only_if.htm

**Comment by spartucus** [comment]
@samsonwang [iff](https://en.wikipedia.org/wiki/If_and_only_if)
