### ISSUE TITLE
make failed, what not delared in this scope?

### ISSUE THREAD

**Issue by WXinlong** [facebook/folly#540]
Makefile:1380: recipe for target 'detail/CacheLocality.lo' failed      
 make[2]: *** [detail/CacheLocality.lo] Error 1                          
make[2]: Leaving directory '/home/Hutchinson/fblualib_src/folly/folly'  Makefile:1441: recipe for target 'all-recursive' failed                 
make[1]: *** [all-recursive] Error 1                                   
 make[1]: Leaving directory '/home/Hutchinson/fblualib_src/folly/folly'  Makefile:894: recipe for target 'all' failed                            
make: *** [all] Error 2                

Do u know how to fix it?

**Comment by Orvid** [comment]
We can't do anything as this doesn't tell us what the actual error is, which should be before this point in the log.

**Comment by WXinlong** [comment]
Oh sorry, the errors are listed below,
I guess it's make problem or what
------------------------------------------
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++0x -g -O2 -MT detail/CacheLocality.lo -MD -MP -MF detail/.deps/CacheLocality.Tpo -c detail/CacheLocality.cpp  -fPIC -DPIC -o detail/.libs/CacheLocality.o
In file included from ./../folly/FBString.h:59:0,
                 from ./../folly/Conv.h:27,
                 from detail/CacheLocality.cpp:23:
./../folly/Traits.h:152:38: error: template argument 1 is invalid
   struct IsRelocatable<  __VA_ARGS__ > : std::true_type {};
                                      ^
./../folly/Traits.h:218:3: note: in expansion of macro ‘FOLLY_ASSUME_RELOCATABLE’
   FOLLY_ASSUME_RELOCATABLE(__VA_ARGS__<T1, T2, T3>) }                   \
   ^
./../folly/Traits.h:452:1: note: in expansion of macro ‘FOLLY_ASSUME_FBVECTOR_COMPATIBLE_3’
 FOLLY_ASSUME_FBVECTOR_COMPATIBLE_3(std::basic_string);
 ^
./../folly/Traits.h:168:48: error: template argument 1 is invalid
   struct has_nothrow_constructor<  __VA_ARGS__ > : ::boost::true_type {};
                                                ^
./../folly/Traits.h:221:5: note: in expansion of macro ‘FOLLY_ASSUME_HAS_NOTHROW_CONSTRUCTOR’
     FOLLY_ASSUME_HAS_NOTHROW_CONSTRUCTOR(__VA_ARGS__<T1, T2, T3>) }
     ^
./../folly/Traits.h:452:1: note: in expansion of macro ‘FOLLY_ASSUME_FBVECTOR_COMPATIBLE_3’
 FOLLY_ASSUME_FBVECTOR_COMPATIBLE_3(std::basic_string);
 ^
In file included from ./../folly/Conv.h:27:0,
                 from detail/CacheLocality.cpp:23:
./../folly/FBString.h:912:3: error: reference to ‘basic_string’ is ambiguous
   std::basic_string<Char> backend_;
   ^
In file included from ./../folly/FBString.h:59:0,
                 from ./../folly/Conv.h:27,
                 from detail/CacheLocality.cpp:23:
./../folly/Traits.h:244:9: note: candidates are: template<class T, class R, class A> class std::basic_string
   class basic_string;
         ^
In file included from /usr/include/c++/5/string:39:0,
                 from /usr/include/c++/5/stdexcept:39,
                 from /usr/include/c++/5/array:38,
                 from /usr/include/c++/5/tuple:39,
                 from /usr/include/c++/5/functional:55,
                 from ./../folly/detail/CacheLocality.h:23,
                 from detail/CacheLocality.cpp:17:
/usr/include/c++/5/bits/stringfwd.h:71:11: note:                 template<class _CharT, class _Traits, class _Alloc> class std::__cxx11::basic_string
     class basic_string;
           ^
In file included from ./../folly/Conv.h:27:0,
                 from detail/CacheLocality.cpp:23:
./../folly/FBString.h: In copy constructor ‘folly::dummy_fbstring_core<Char>::dummy_fbstring_core(const folly::dummy_fbstring_core<Char>&)’:
./../folly/FBString.h:871:9: error: class ‘folly::dummy_fbstring_core<Char>’ does not have any field named ‘backend_’
       : backend_(another.backend_) {
         ^
./../folly/FBString.h: In constructor ‘folly::dummy_fbstring_core<Char>::dummy_fbstring_core(const Char*, size_t)’:
./../folly/FBString.h:874:9: error: class ‘folly::dummy_fbstring_core<Char>’ does not have any field named ‘backend_’
       : backend_(s, n) {
         ^
./../folly/FBString.h: In member function ‘void folly::dummy_fbstring_core<Char>::swap(folly::dummy_fbstring_core<Char>&)’:
./../folly/FBString.h:877:5: error: ‘backend_’ was not declared in this scope
     backend_.swap(rhs.backend_);
     ^
./../folly/FBString.h: In member function ‘const Char* folly::dummy_fbstring_core<Char>::data() const’:
./../folly/FBString.h:880:12: error: ‘backend_’ was not declared in this scope
     return backend_.data();
            ^
./../folly/FBString.h: In member function ‘Char* folly::dummy_fbstring_core<Char>::mutable_data()’:
./../folly/FBString.h:884:14: error: ‘backend_’ was not declared in this scope
     return &*backend_.begin();
              ^
./../folly/FBString.h: In member function ‘void folly::dummy_fbstring_core<Char>::shrink(size_t)’:
./../folly/FBString.h:888:5: error: ‘backend_’ was not declared in this scope
     backend_.resize(size() - delta);
     ^
./../folly/FBString.h: In member function ‘Char* folly::dummy_fbstring_core<Char>::expand_noinit(size_t)’:
./../folly/FBString.h:892:5: error: ‘backend_’ was not declared in this scope
     backend_.resize(size() + delta);
     ^
./../folly/FBString.h: In member function ‘void folly::dummy_fbstring_core<Char>::push_back(Char)’:
./../folly/FBString.h:896:5: error: ‘backend_’ was not declared in this scope
     backend_.push_back(c);
     ^
./../folly/FBString.h: In member function ‘size_t folly::dummy_fbstring_core<Char>::size() const’:
./../folly/FBString.h:899:12: error: ‘backend_’ was not declared in this scope
     return backend_.size();
            ^
./../folly/FBString.h: In member function ‘size_t folly::dummy_fbstring_core<Char>::capacity() const’:
./../folly/FBString.h:902:12: error: ‘backend_’ was not declared in this scope
     return backend_.capacity();
            ^
./../folly/FBString.h: In member function ‘void folly::dummy_fbstring_core<Char>::reserve(size_t)’:
./../folly/FBString.h:908:5: error: ‘backend_’ was not declared in this scope
     backend_.reserve(minCapacity);

**Comment by danielunderwood** [comment]
I'm having this same issue installing from the [thpp build script](https://github.com/facebook/thpp/blob/master/thpp/build_fbthrift_folly.sh).

**Comment by Orvid** [comment]
@danielunderwood I would file a bug against them directly and have them update https://github.com/facebook/thpp/blob/master/thpp/build_fbthrift_folly.sh#L32 to point to the latest hash rather than a > 1.5 year old hash.

**Comment by danielunderwood** [comment]
@Orvid pointing to the most recent tag `v2016.12.19.00` seemed to have fixed the problem that I was running into. Maybe this issue has been fixed sometime since whatever version the others in this issue are using as well?

**Comment by ypruan** [comment]
@WXinlong , hello! 
I have run into the same problem with you, and did you solve this problem? 
If so, can you leave a answer here? Thank your !

**Comment by WXinlong** [comment]
@ypruan  Sorry, I didn't fix it.
