### ISSUE TITLE
[Bug] ProducerConsumerQueue: crash on (empty) popFront()

### ISSUE THREAD

**Issue by breznak** [facebook/folly#552]
The crash occurs on `popFront()` even thoug I checked that `assert(!isEmpty())` before calling popFront. There are parallel reads/writes/removes to the queue. 

The crash output:
```
merQueue.h:127: void folly::ProducerConsumerQueue<XX>::popFront() [T = XX]: Assertion `currentRead != writeIndex_.load(std::memory_order_acquire)' failed.
```
(XX is a simple struct)

Steps to reproduce: 
A similar, simplified program:
```
q = ProducerConsumerQueue(1000);

//thread 1
while(true) {
  q.write(1);
  sleep(random_time);
}

//thread 2
while(!q.isEmpty()) {
  q.popFront();
  this_thread.yield();
}
```

Why I use something (ugly) as thread 2-cleaner is the lack of "clear()" method, see #551

**Comment by suspend0** [comment]
```
#include <atomic>
#include <thread>
#include <folly/ProducerConsumerQueue.h>
TEST(A, B) {
  std::atomic<bool> running{true};
  folly::ProducerConsumerQueue<int> q(1000);

  auto producer = [&] {
    while (running.load()) {
      q.write(1);
    }
    std::cout << "producer exit\n";
  };
  auto consumer = [&] {
    while (!q.isEmpty()) {
      q.popFront();
      std::this_thread::sleep_for(std::chrono::nanoseconds(1));
    }
    std::cout << "consumer exit\n";
  };

  std::thread t1(producer);
  std::thread t2(consumer);

  std::this_thread::sleep_for(std::chrono::seconds(20));
  running = false;

  t1.join();
  t2.join();
}
```

This code does not exhibit any issues.

Are you sure you're only using `ProducerConsumerQueue` with a single producer and single consumer thread?  Only one thread calling write and one thread calling isEmpty/pop is supported.

It's thread-safe but only under somewhat restrictive scenarios.

**Comment by breznak** [comment]
Thank you very much for the quick test case @suspend0 ! :+1: 

(I had to change the lambdas to be able to compile w/o pthread) But I don't replicate a crash on this either. 
I'm trying to get a closer example to my program. 
Yes, there's one (detached) thread that does ...ok, maybe at some point I've invalidated the concept that one thread only reads, other only writes...will check!
