### ISSUE TITLE
About compile option "-O2"

### ISSUE THREAD

**Issue by QunxingHu** [facebook/folly#556]
I wrote an simple example to compare the performance between fbstring and std::string, the results show that when i cmopile the program **without compile option "-O2", the performance of fbstring is not good as std::string**,  but when i **use "-O2" option, the performance of fbstring is almost twice faster than std::string**. Does it mean the "-O2" option is necessary for fbstring?

**Comment by yfeldblum** [comment]
If performance is a concern, you typically want to enable compiler optimizations. When using fbstring, but also in general.

Various parts of folly, including fbstring, are written with the assumption that compiler optimizations will be enabled.
