### ISSUE TITLE
folly 2017.03.06.00 clockid_t typedef redefinition causes build failure on macOS 10.11 with Xcode 8

### ISSUE THREAD

**Issue by ilovezfs** [facebook/folly#557]
Build log: https://bot.brew.sh/job/Homebrew%20Core/17816/version=el_capitan/console
(https://gist.github.com/ilovezfs/0456185fdeed2287585dca0c7be211d7#file-gistfile1-txt-L1936-L1949)
```
/bin/sh ./libtool  --tag=CXX   --mode=compile clang++ -DHAVE_CONFIG_H   -I./.. -pthread -I/usr/local/include -I/usr/local/Cellar/openssl/1.0.2k/include   -std=gnu++1y -g -O2 -c -o ClockGettimeWrappers.lo ClockGettimeWrappers.cpp
libtool: compile:  clang++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/local/include -I/usr/local/Cellar/openssl/1.0.2k/include -std=gnu++1y -g -O2 -c ClockGettimeWrappers.cpp  -fno-common -DPIC -o .libs/ClockGettimeWrappers.o
In file included from ClockGettimeWrappers.cpp:17:
In file included from ./../folly/ClockGettimeWrappers.h:19:
./../folly/portability/Time.h:32:17: error: typedef redefinition with different types ('uint8_t' (aka 'unsigned char') vs 'enum clockid_t')
typedef uint8_t clockid_t;
                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/time.h:171:3: note: previous definition is here
} clockid_t;
  ^
1 error generated.
make[2]: *** [ClockGettimeWrappers.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

This specifically affects macOS 10.11 when building with Xcode 8. The same bug has been fixed already on Sierra but was never addressed for El Capitan. (See https://github.com/facebook/folly/issues/484)

Therefore, I am re-reporting here.

In Homebrew, we've been working around it since Xcode 8 was released with the following hack:
```
      if MacOS.version == "10.11" && MacOS::Xcode.installed? && MacOS::Xcode.version >= "8.0"
        inreplace "portability/Time.h", "typedef uint8_t clockid_t;", ""
      end
```
Since an upstream fix did not make it into folly 2017.03.06.00, I will continue to use the hack for now.

**Comment by Orvid** [comment]
As long as I've not broken something else, https://github.com/facebook/folly/commit/01919b98fd78769d8e73dc2c0f959743393e886e
Should fix this. (I had the change up internally for quite a while but had forgotten about it)

**Comment by ilovezfs** [comment]
@Orvid Yes this is fixed though there are at least two other issues keeping a new version from shipping for Homebrew:
https://github.com/facebook/folly/issues/576
https://github.com/facebook/folly/issues/577
