### ISSUE TITLE
folly::IOBuf as input for folly::parseJson()

### ISSUE THREAD

**Issue by Memnarch** [facebook/folly#561]
Hi,
I just started using Proxygen and Folly. Currently i want to use a Folly::IOBuf as input for folly::parseJson.
First i used (as naiv as i am) the method described in the HTTPArchive-Test of Proxygen to get the characters.

[HTTPArchive.cpp](https://github.com/facebook/proxygen/blob/b9fa66b948f3be9cad9860b2dd339178883b352c/proxygen/lib/http/codec/compress/test/HTTPArchive.cpp)

However it seems the buffer is not zeroterminated(which is not a real surprise), i ended up getting some additional memory, sometimes. Which causes the parseJson to fail.
So i changed my code to use moveToFbString on the buffer first and put this fbstring into the parseJson. Which now works.

Can someone confirm that the previous version was wrong, and the new one isn't?
Just in case someone asks:
In Proxygene i receive a Body which contains json and need to read it.

**Comment by yfeldblum** [comment]
You should simply call `parseJson` with a `StringPiece` gotten from the `IOBuf`.

If the `IOBuf` is actually chained, it will have to be coalesced first before the `StringPiece` can be gotten from it.

```
std::unique_ptr<folly::IOBuf> inputMaybeChained = //...
auto const inputAsRange = folly::StringPiece(inputMaybeChained->coalesce());
auto inputAsDynamic = folly::parseJson(inputAsRange);
```

**Comment by Memnarch** [comment]
Thank you
