### ISSUE TITLE
failed under CentOS6 due to gflags invalid

### ISSUE THREAD

**Issue by markhu** [facebook/folly#564]
Unsure if this is a CentOS6 issue, or a gflags issue:
```
folly (master) $ ./configure
...
checking for main in -lgflags... yes
checking for gflags viability... no
configure: error: "gflags invalid, see config.log for details"
```

Does `folly` need a particular version of `gflags` ?  I grabbed the latest from https://github.com/gflags/gflags which was version 2.2.0 at the time. Also tried going back to 2.0 and 1.7 to no avail.

**Comment by bharath-g** [comment]
Yes I had the same issue. If you have root try yum installing 

```
$ yum list installed | grep gflags
gflags.x86_64                    2.1.1-6.el7                         @epel
gflags-devel.x86_64              2.1.1-6.el7                         @epel
```

If you don't have ROOT you could still try installing locally using yum. It helped in my case.

**Comment by markhu** [comment]
Unfortunately, the `gflags` version avail in my corporate repo mirror is `gflags-1.3-7` circa 2013.

Thanks for the tip on commenting out the check in the `configure` script. I tried that and was able to get a makefile. (After installing `libevent-devel`.)

**Comment by Orvid** [comment]
Support for building Folly with autotools has been removed in favor of CMake, so I'm closing this.
