### ISSUE TITLE
folly build error io/Compression.cpp

### ISSUE THREAD

**Issue by rongliang666** [facebook/folly#569]
io/Compression.cpp:1604:8:   required from here
/usr/include/c++/4.8.2/bits/stl_algo.h:214:23: error: no match for call to '(folly::io::{anonymous}::AutomaticCodec::canUncompress(const folly::IOBuf*, uint64_t) const::__lambda18) (const std::unique_ptr<folly::io::Codec>&)'
    if (__pred(*__first))
                     ^
when i run make command to build folly, the error like this, my gcc ver is 4.8.2. how can i solve this error， thankyou

**Comment by terrelln** [comment]
Its caused by the generic lambdas on lines 1602, 1609, 1634, 1639, and 1644. They will be changed to take a `std::unique_ptr<Codec> const&` instead.
