### ISSUE TITLE
Bits.cpp:48: Error: invalid instruction suffix for `popcnt'

### ISSUE THREAD

**Issue by castleshi** [facebook/folly#571]
Hi all! I got error when I run "make" under folly/folly, and dont know how to solve it!

castle@bogon:~/work/install/folly/folly$ make
make  all-recursive
make[1]: Entering directory '/home/castle/work/install/folly/folly'
Making all in .
make[2]: Entering directory '/home/castle/work/install/folly/folly'
depbase=`echo Bits.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I./.. -pthread -I/usr/include  -I/opt/local/include  -std=gnu++1y -g -O2 -MT Bits.lo -MD -MP -MF $depbase.Tpo -c -o Bits.lo Bits.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -I/opt/local/include -std=gnu++1y -g -O2 -MT Bits.lo -MD -MP -MF .deps/Bits.Tpo -c Bits.cpp  -fPIC -DPIC -o .libs/Bits.o
Bits.cpp: Assembler messages:
Bits.cpp:48: Error: invalid instruction suffix for `popcnt'
Makefile:1706: recipe for target 'Bits.lo' failed
make[2]: *** [Bits.lo] Error 1
make[2]: Leaving directory '/home/castle/work/install/folly/folly'
Makefile:1798: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/castle/work/install/folly/folly'
Makefile:1089: recipe for target 'all' failed
make: *** [all] Error 2

any hints?
P.S. 
gcc version 5.4.0
Ubuntu 16.04.2 LTS  i686

**Comment by yfeldblum** [comment]
Closing because this is too old.
