### ISSUE TITLE
using private boost.context API?

### ISSUE THREAD

**Issue by olk** [facebook/folly#572]
Hi,
I'm wondering why you still use the private fcontext-API from boost.context.
You should consider to switch to one of the public APIs, like: callcc()/continuation or execution_context<>. The benfit is that the public APIs remain stable while the fcontext-API might change if necessary. Addtionally, the public APIs prevent the user for resuming an invalid/terminated or already running context + stack management.

**Comment by yfeldblum** [comment]
This is probably a question for @andriigrynenko.

**Comment by yfeldblum** [comment]
The reason is that folly has an alternative higher-level layer and would otherwise not rely on boost for this, but relies on the boost-context library for the lowest-level details - especially the details that vary by platform.
