### ISSUE TITLE
autoreconf error

### ISSUE THREAD

**Issue by CodeMasterYi** [facebook/folly#574]
MacOS 10.12.4
using port install
dependencies are installed
cd folly/folly
autoreconf ***    

then :
m4/fb_check_pkg_config.m4:8: FB_CHECK_PKG_CONFIG is expanded from...
configure.ac:145: the top level
configure.ac:172: warning: PKG_PROG_PKG_CONFIG is m4_require'd but not m4_defun'd
m4/fb_check_pkg_config.m4:8: FB_CHECK_PKG_CONFIG is expanded from...
configure.ac:172: the top level
configure:17179: error: possibly undefined macro: AC_MSG_NOTICE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /opt/local/bin/autoconf failed with exit status: 1

**Comment by set-daemon** [comment]
I encountered the same problem in centos6.5 after i'd updated the autoconf version to 2.6.9, and can not solve it for a long time, 
so i do this work in another machine(also with autoconf version 2.6.9), and it works magically. 
maybe the environment of the previous machine is confused by my update operations?  very strange problem.

**Comment by fanyeren** [comment]
same problem on centos7

i have manually installed  autoconf & automaker to /usr/local

**Comment by fanyeren** [comment]
fixed this by installing pkg-config to /usr/local

**Comment by dstahlke** [comment]
Fixed by running "autoreconf -ivf -I /path/to/pkg-config/share/aclocal"
