### ISSUE TITLE
 SEGV folly::AsyncTimeout::libeventCallback

### ISSUE THREAD

**Issue by abhiguru** [facebook/folly#582]
==4304==ERROR: AddressSanitizer: SEGV on unknown address 0x7f613d00001f (pc 0x7f61178fec05 bp 0x000000000000 sp 0x7ffc0c629fa0 T0)
    #0 0x7f61178fec04 in folly::AsyncTimeout::libeventCallback(int, short, void*) io/async/AsyncTimeout.cpp:160
    #1 0x7f610b17241f in event_base_loop (/usr/lib/x86_64-linux-gnu/libevent-2.0.so.5+0xd41f)
    #2 0x7f611792f4ff in folly::EventBase::loopBody(int) io/async/EventBase.cpp:313
    #3 0x7f61179312c5 in folly::EventBase::loopForever() io/async/EventBase.cpp:443
    #4 0x55af2e28f588 in main /home/abhinav/ws/videoproc/main.cpp:220
    #5 0x7f6111f6c3f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)
    #6 0x55af2e1afce9 in _start (/home/abhinav/ws/videoproc/build/videoproc+0x2c5ce9)

**Comment by yfeldblum** [comment]
Closing this issue because it is too old, and because there is no local repro.
