### ISSUE TITLE
make fail  about OpenSSL

### ISSUE THREAD

**Issue by dsbaby** [facebook/folly#583]
The following error occurred during make. Please help. I am using master on Ubuntu 12.04.5. thanks~

u++1y -g -O2 -MT io/ShutdownSocketSet.lo -MD -MP -MF io/.deps/ShutdownSocketSet.Tpo -c io/ShutdownSocketSet.cpp -o io/ShutdownSocketSet.o >/dev/null 2>&1
depbase=`echo io/async/AsyncPipe.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
        /bin/bash ./libtool --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I./.. -pthread -I/usr/include   -I/opt/local/include  -std=gnu++1y -g -O2 -MT io/async/AsyncPipe.lo -MD -MP -MF $depbase.Tpo -c -o io/async/AsyncPipe.lo io/async/AsyncPipe.cpp &&\
        mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -I/opt/local/include -std=gnu++1y -g -O2 -MT io/async/AsyncPipe.lo -MD -MP -MF io/async/.deps/AsyncPipe.Tpo -c io/async/AsyncPipe.cpp  -fPIC -DPIC -o io/async/.libs/AsyncPipe.o
In file included from /usr/include/openssl/ssl.h:1365:0,
                 from ./../folly/portability/OpenSSL.h:36,
                 from ./../folly/io/async/ssl/OpenSSLPtrTypes.h:22,
                 from ./../folly/io/async/AsyncTransport.h:25,
                 from ./../folly/io/async/AsyncPipe.h:18,
                 from io/async/AsyncPipe.cpp:16:
./../folly/portability/OpenSSL.h:100:29: error: expected unqualified-id before 'const'
 int TLS1_get_client_version(const SSL*);
                             ^
./../folly/portability/OpenSSL.h:100:29: error: expected ')' before 'const'
./../folly/portability/OpenSSL.h:100:29: error: expected ')' before 'const'
make[2]: *** [io/async/AsyncPipe.lo] error 1

**Comment by louwers** [comment]
Possibly related #573

**Comment by dsbaby** [comment]
according to  #573，
solution： Downgrade to OpenSSL 1.0.X.

but my OpenSSL  is  already 1.0.X  

root@my-virtual-machine:/home/third/double-conversion# openssl version
OpenSSL 1.0.1 14 Mar 2012

**Comment by Orvid** [comment]
Which version of GCC are you trying to build with? Folly only supports GCC 4.9+, and 12.04 doesn't have that by default.

**Comment by stjacob** [comment]
@dsbaby  same issue. Is that solved?

**Comment by newpoo** [comment]
Same here.

**Comment by helloleef** [comment]
fix file  portability/OpenSSL.h 
```
// BoringSSL doesn't have notion of versioning although it defines
// OPENSSL_VERSION_NUMBER to maintain compatibility. The following variables are
// intended to be specific to OpenSSL.
#if !defined(OPENSSL_IS_BORINGSSL)
/*
# define FOLLY_OPENSSL_IS_100                \
  (OPENSSL_VERSION_NUMBER >= 0x10000003L && \
   OPENSSL_VERSION_NUMBER < 0x1000105fL)
# define FOLLY_OPENSSL_IS_101                \
  (OPENSSL_VERSION_NUMBER >= 0x1000105fL && \
   OPENSSL_VERSION_NUMBER < 0x1000200fL)
# define FOLLY_OPENSSL_IS_102                \
  (OPENSSL_VERSION_NUMBER >= 0x1000200fL && \
   OPENSSL_VERSION_NUMBER < 0x10100000L)
*/

# define FOLLY_OPENSSL_IS_101 1
```

Comment out auto detect openssl version code 。 hack yourself openssl version

**Comment by shuzhang1989** [comment]
same here, what will be the ssl version recommended?

**Comment by IlldianX** [comment]
Looks like this issue is also related to Ubuntu 12.04? I can build without any issues on Ubuntu 14 but failed consistently on 12.

**Comment by yfeldblum** [comment]
Note that HHVM uses Folly extensively, and lists supported distributions, starting for Ubuntu from 16.04 LTS:

https://docs.hhvm.com/hhvm/installation/linux
https://docs.hhvm.com/hhvm/installation/building-from-source

Ubuntu 16.04 LTS ships with OpenSSL 1.0.2g.

It is possible that Folly may work with some older versions of Ubuntu and of OpenSSL beyond what HHVM supports, but it may not work on the particular older versions of Ubuntu and of OpenSSL that you are trying it on.

**Comment by yfeldblum** [comment]
Closing because of age, because folly no longer uses `make` as the build system, and because folly no longer supports Ubuntu 16.04 LTS or OpenSSL < 1.1.
