### ISSUE TITLE
warning

### ISSUE THREAD

**Issue by saleyn** [facebook/folly#59]
gcc version 4.8.2 20140206
OS: Linux nova 3.13.7-1-ARCH

When including the following header in my code
#define FBSTRING_CONSERVATIVE
#include <folly/AtomicHashMap.h>
I am getting a warning below. What's the proper way of getting rid of it aside from defining no-deprecated compilation option?

In file included from /usr/include/c++/4.8.2/ext/hash_set:60:0,
                 from /opt/env/prod/Folly/Current/include/folly/FBString.h:101,
                 from /opt/env/prod/Folly/Current/include/folly/Conv.h:27,
                 from /opt/env/prod/Folly/Current/include/folly/Exception.h:26,
                 from /opt/env/prod/Folly/Current/include/folly/detail/ThreadLocalDetail.h:30,
                 from /opt/env/prod/Folly/Current/include/folly/ThreadLocal.h:53,
                 from /opt/env/prod/Folly/Current/include/folly/ThreadCachedInt.h:31,
                 from /opt/env/prod/Folly/Current/include/folly/AtomicHashArray.h:41,
                 from /opt/env/prod/Folly/Current/include/folly/AtomicHashMap.h:93,
                 ...
/usr/include/c++/4.8.2/backward/backward_warning.h:32:2: warning: #warning This file includes at least one deprecated or antiquated header which may be removed without further notice at a future date. Please use a non-deprecated interface with equivalent functionality instead. For a listing of replacement headers and interfaces, consult the file backward_warning.h. To disable this warning use -Wno-deprecated. [-Wcpp]
 #warning \
  ^

**Comment by facebook-github-bot-5** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by facebook-github-bot-2** [comment]
Thank you for your patience. After 30 days with no updates from the core team, we're closing out the issue. If you're still experiencing the problem described, please reopen the issue - thanks!
