### ISSUE TITLE
gcc 4.8 support

### ISSUE THREAD

**Issue by llchan** [facebook/folly#590]
Has folly dropped gcc-4.8 support? I see some examples of e.g. `auto` lambda parameters, which I think aren't supported in gcc-4.8. Can someone confirm? Can we continue to support gcc-4.8?

**Comment by yfeldblum** [comment]
Yes, folly is dropping gcc-4.8 and C++11. This was announced for hhvm [here](http://hhvm.com/blog/2017/02/15/hhvm-3-18.html) and basically applies to folly as well, although folly does not really have its own announcements channel yet.

**Comment by llchan** [comment]
Okay. That's not great for people on less cutting edge OSes (like RHEL7), but I understand the motivation to keep the code clean.

Can we update the folly README then? It still claims to support 4.8+.
