### ISSUE TITLE
Install Blockstack from source code

### ISSUE THREAD

**Issue by qzhang90** [facebook/folly#595]
I am trying to install Blockstack from source code on Ubuntu 16.04. Does blockstack-core include all the four layers(blockchain, virtualchain, routing, and storage)? Is there any documents describing how to install it from the source code? (I assume that get_started.sh the right point to start, please correct me if I am wrong).

**Comment by Orvid** [comment]
You should be filing this against one of the Blockstack repos (https://github.com/blockstack), not here.
