### ISSUE TITLE
autoreconf: 'configure.ac' or 'configure.in' is require

### ISSUE THREAD

**Issue by ypruan** [facebook/folly#597]
Hello,
  My operating system is Ubuntu 14.04 LTS, and I followed the instruct to install all the dependency listed in the README.md, but when I execute `autoreconf -ivf`, it will return the following problem:
`autoreconf: 'configure.ac' or 'configure.in' is required`
how can i solve it ?

**Comment by hw1** [comment]
@ypruan Hi, How did you solve the problem?

**Comment by magick93** [comment]
How did you solve this?

**Comment by yfeldblum** [comment]
This command needs to be run from within the `folly` subdirectory.

**Comment by anson2416** [comment]
hi @ypruan , can you tell how to resolve it? I did not understand what is the "folly sub" which i already run the command under the cloned folder. thanks.

**Comment by yfeldblum** [comment]
Folly no longer has a make build; the build system is now cmake.
