### ISSUE TITLE
compiler error:  gflags invalid

### ISSUE THREAD

**Issue by xuxilei** [facebook/folly#598]
[root@localhost folly]# ./configure

checking for a BSD-compatible install... /usr/bin/install -c

checking whether build environment is sane... yes

checking for a thread-safe mkdir -p... /usr/bin/mkdir -p

checking for gawk... gawk

checking whether make sets $(MAKE)... yes

checking whether make supports nested variables... yes

checking build system type... x86_64-unknown-linux-gnu

checking host system type... x86_64-unknown-linux-gnu

checking how to print strings... printf

checking for style of include used by make... GNU

checking for gcc... gcc

checking whether the C compiler works... yes

checking for C compiler default output file name... a.out

checking for suffix of executables...

checking whether we are cross compiling... no

checking for suffix of object files... o

checking whether we are using the GNU C compiler... yes

checking whether gcc accepts -g... yes

checking for gcc option to accept ISO C89... none needed

checking dependency style of gcc... gcc3

checking for a sed that does not truncate output... /usr/bin/sed

checking for grep that handles long lines and -e... /usr/bin/grep

checking for egrep... /usr/bin/grep -E

checking for fgrep... /usr/bin/grep -F

checking for ld used by gcc... /usr/bin/ld

checking if the linker (/usr/bin/ld) is GNU ld... yes

checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B

checking the name lister (/usr/bin/nm -B) interface... BSD nm

checking whether ln -s works... yes

checking the maximum length of command line arguments... 1572864

checking whether the shell understands some XSI constructs... yes

checking whether the shell understands "+="... yes

checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop

checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop

checking for /usr/bin/ld option to reload object files... -r

checking for objdump... objdump

checking how to recognize dependent libraries... pass_all

checking for dlltool... no

checking how to associate runtime and link libraries... printf %s\n

checking for ar... ar

checking for archiver @FILE support... @

checking for strip... strip

checking for ranlib... ranlib

checking command to parse /usr/bin/nm -B output from gcc object... ok

checking for sysroot... no

checking for mt... no

checking if : is a manifest tool... no

checking how to run the C preprocessor... gcc -E

checking for ANSI C header files... yes

checking for sys/types.h... yes

checking for sys/stat.h... yes

checking for stdlib.h... yes

checking for string.h... yes

checking for memory.h... yes

checking for strings.h... yes

checking for inttypes.h... yes

checking for stdint.h... yes

checking for unistd.h... yes

checking for dlfcn.h... yes

checking for objdir... .libs

checking if gcc supports -fno-rtti -fno-exceptions... no

checking for gcc option to produce PIC... -fPIC -DPIC

checking if gcc PIC flag -fPIC -DPIC works... yes

checking if gcc static flag -static works... no

checking if gcc supports -c -o file.o... yes

checking if gcc supports -c -o file.o... (cached) yes

checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes

checking whether -lc should be explicitly linked in... no

checking dynamic linker characteristics... GNU/Linux ld.so

checking how to hardcode library paths into programs... immediate

checking whether stripping libraries is possible... yes

checking if libtool supports shared libraries... yes

checking whether to build shared libraries... yes

checking whether to build static libraries... yes

checking for g++... g++

checking whether we are using the GNU C++ compiler... yes

checking whether g++ accepts -g... yes

checking dependency style of g++... gcc3

checking how to run the C++ preprocessor... g++ -E

checking for ld used by g++... /usr/bin/ld -m elf_x86_64

checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes

checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes

checking for g++ option to produce PIC... -fPIC -DPIC

checking if g++ PIC flag -fPIC -DPIC works... yes

checking if g++ static flag -static works... no

checking if g++ supports -c -o file.o... yes

checking if g++ supports -c -o file.o... (cached) yes

checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes

checking dynamic linker characteristics... (cached) GNU/Linux ld.so

checking how to hardcode library paths into programs... immediate

checking for gcc... (cached) gcc

checking whether we are using the GNU C compiler... (cached) yes

checking whether gcc accepts -g... (cached) yes

checking for gcc option to accept ISO C89... (cached) none needed

checking dependency style of gcc... (cached) gcc3

checking if g++ supports C++1y features without additional flags... no

checking if g++ supports C++1y features with -std=c++1y... yes

checking if g++ supports C++1y features with -std=gnu++1y... yes

checking whether -Wshadow-local and -Wshadow-compatible-local are supported... no

checking for main in -lgflags... yes

checking for gflags viability... no

configure: error: "gflags invalid, see config.log for details"

**Comment by xuxilei** [comment]
continue on:
/usr/local/lib/libgflags.a(gflags.cc.o): In function `google::(anonymous namespace)::FlagRegistry::GlobalRegistry()':

gflags.cc:(.text+0xe96): undefined reference to `pthread_rwlock_wrlock'

gflags.cc:(.text+0xeae): undefined reference to `pthread_rwlock_unlock'

gflags.cc:(.text+0xf47): undefined reference to `pthread_rwlock_init'

**Comment by anhldbk** [comment]
Well, I suffered the same error

**Comment by anhldbk** [comment]
@xuxilei : there's a workaround [here](https://github.com/facebook/folly/issues/231#issuecomment-115847214)

**Comment by tdauth** [comment]
I have the same problem but only on TravisCI where it uses Ubuntu 14.04.5 LTS. Everything works fine on my local Fedora system (Fedora 25).
This is my .travis.yml file:
```
language: cpp
compiler: clang
os: linux
script:
  - bash ./build.sh
addons:
  apt:
    packages:
      - cmake
      - libgflags-dev
      - libgflags2
      - libgoogle-glog-dev
      - valgrind
      - clang
    sources:
      - kalakris-cmake
```

My build script downloads Folly from GitHub and builds it: https://github.com/tdauth/cpp-futures-promises

**Comment by xzzh999** [comment]
i have the same error in centos 7.2, just rebuild gflags and glogs from the source code, and 
export LD_LIBRARY_PATH="/usr/local/lib" 
can solve this problem.

**Comment by NBA2018** [comment]
@xzzh999 I have the same error in centos7,but can't solve this problem with your method.can you help me?thanks.

**Comment by NBA2018** [comment]
@xuxilei How do you solve this problem in the end?

**Comment by jassfuchang** [comment]
i have the same problem, two kinds of errors found in config.log :
1. gflags.cc:(.text...): undefined reference to `pthread_...'
2. undefined reference to 'google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*) 

for problem 1 , an easy (ugly) solution is to replace "-lgflags" with "-lgflags -lpthread"  in folly/folly/configure

for problem 2 , DO UNINSTALL old version libgflags (also libglog), checkout from github and install from source

i was stucked on problem 2 because i reinstalled from source without apt-get remove, until i found two libgflags.a in different lib paths: /usr/lib/x86_64-linux-gnu and /usr/local/lib ; use "nm libgflags.a | grep FlagRegisterer | c++filt" to check and confirm the prior linked library is outdated.

refer to https://github.com/gflags/gflags/issues/203 commented by schuhschuh

**Comment by daniel-lucio** [comment]
> @xzzh999 I have the same error in centos7,but can't solve this problem with your method.can you help me?thanks.

check #929

**Comment by Orvid** [comment]
Support for building Folly with autotools has been removed in favor of CMake, so I'm closing this.
