### ISSUE TITLE
AtomicHashArray

### ISSUE THREAD

**Issue by saleyn** [facebook/folly#60]
Is there a reason why AtomicHashMap supports only stateless allocators?  It seems like an oversight, as It would be convenient to be able to support stateful allocation for containers stored in shared memory.

**Comment by facebook-github-bot-5** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by facebook-github-bot-2** [comment]
Thank you for your patience. After 30 days with no updates from the core team, we're closing out the issue. If you're still experiencing the problem described, please reopen the issue - thanks!
