### ISSUE TITLE
Warnings during installation in Ubuntu 16.04

### ISSUE THREAD

**Issue by jack17529** [facebook/folly#605]
libtool: warning: relinking 'libfollybenchmark.la'

libtool: warning: relinking 'libfollysymbolizer.la'

libtool: warning: relinking 'libfollyinit.la'

I think installation process is slow that's why, I am getting these.

**Comment by yfeldblum** [comment]
Closing this issue because it is too old, and because Ubuntu 16.04 is no longer a supported platform.
