### ISSUE TITLE
2017.06.12.00 build failure on macOS "No rule to make target 'all' in stats/test/"

### ISSUE THREAD

**Issue by ilovezfs** [facebook/folly#610]
CC @Orvid @wez 

```
Making all in io/test
make[2]: Nothing to be done for `all'.
Making all in experimental/io/test
make[2]: Nothing to be done for `all'.
Making all in stats/test
make[2]: *** No rule to make target `all'.  Stop.
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/2889/version=sierra/console
https://github.com/Homebrew/homebrew-core/pull/14509

I can work around it with
```
diff --git a/folly/Makefile.am b/folly/Makefile.am
index 435b93a..349ee1c 100644
--- a/folly/Makefile.am
+++ b/folly/Makefile.am
@@ -7,7 +7,7 @@ MAYBE_EXCEPTION_TRACER = experimental/exception_tracer
 endif
 
 SUBDIRS = . experimental $(MAYBE_INIT) test io/test experimental/io/test \
-	  stats/test $(MAYBE_EXCEPTION_TRACER)
+	  $(MAYBE_EXCEPTION_TRACER)
 
 ACLOCAL_AMFLAGS = -I m4
 
```

**Comment by theonajim** [comment]
I had the same failure on centos and ubuntu, I submitted a potential fix here: https://github.com/facebook/folly/pull/609

**Comment by wez** [comment]
@ilovezfs can you try this with the current master?  @theonajim's changes got pushed in https://github.com/facebook/folly/commit/972651e0572ac18d541fe4b243f5bf3a2d17acec

**Comment by ilovezfs** [comment]
@wez it looks like it works. @jcount added that commit as a patch to https://github.com/Homebrew/homebrew-core/pull/14509 and it's now :green_apple:

**Comment by ilovezfs** [comment]
All is well in 2017.06.19.00, so closing. Thanks!
