### ISSUE TITLE
autoreconf -ivf error

### ISSUE THREAD

**Issue by Candy710** [facebook/folly#613]
I follow the steps and occured this error,how can solve it?thank you very much.

#

1. linuxidc@www:~/folly/folly$ autoreconf -ivf
2. autoreconf: Entering directory `.'
3. autoreconf: configure.ac: not using Gettext
4. autoreconf: running: aclocal --force -I m4
5. autoreconf: configure.ac: tracing
6. autoreconf: running: libtoolize --copy --force
7. libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 
8. libtoolize: copying file `build-aux/ltmain.sh'
9. libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
10. libtoolize: copying file `m4/libtool.m4'
11. libtoolize: copying file `m4/ltoptions.m4'
12. libtoolize: copying file `m4/ltsugar.m4'
13. libtoolize: copying file `m4/ltversion.m4'
14. libtoolize: copying file `m4/lt~obsolete.m4'
15. autoreconf: running: /usr/bin/autoconf --force
16. autoreconf: running: /usr/bin/autoheader --force
17. autoreconf: running: automake --add-missing --copy --force-missing
18. stats/test/Makefile.am:6: warning: variable 'libgtest_la_SOURCES' is defined but no program or
19. stats/test/Makefile.am:6: library has 'libgtest_la' as canonical name (possible typo)
20. test/Makefile.am:99: warning: variable 'thread_id_test_SOURCES' is defined but no program or
21. test/Makefile.am:99: library has 'thread_id_test' as canonical name (possible typo)
22. test/Makefile.am:100: warning: variable 'thread_id_test_LDADD' is defined but no program or
23. test/Makefile.am:100: library has 'thread_id_test' as canonical name (possible typo)
24. autoreconf: Leaving directory `.'

**Comment by Candy710** [comment]
linuxidc@www:~/folly/folly$ autoreconf -ivf
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `build-aux'.
libtoolize: copying file `build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
stats/test/Makefile.am:6: warning: variable 'libgtest_la_SOURCES' is defined but no program or
stats/test/Makefile.am:6: library has 'libgtest_la' as canonical name (possible typo)
test/Makefile.am:99: warning: variable 'thread_id_test_SOURCES' is defined but no program or
test/Makefile.am:99: library has 'thread_id_test' as canonical name (possible typo)
test/Makefile.am:100: warning: variable 'thread_id_test_LDADD' is defined but no program or
test/Makefile.am:100: library has 'thread_id_test' as canonical name (possible typo)
autoreconf: Leaving directory `.'

**Comment by set-daemon** [comment]
i tried the folly-2017.07.31.00 version on centos6.5, "autoreconf -ivf" executed failed as following errors:
autoreconf: 'configure.ac' or 'configure.in' is required
thanks!

**Comment by yfeldblum** [comment]
@Candy710 - My first guess is that you are missing a required package? Check the readme / sample build scripts for the list of all required packages on your platform.

@set-daemon - `autoreconf -ivf` and all other build commands are expected to be run from within the `folly` subdirectory, not from the root of the repo, as described in the readme / sample build scripts.

**Comment by set-daemon** [comment]
thanks @yfeldblum, my problem has been solved by running from withing the folly subdirectory.

**Comment by yidazhi** [comment]
autoreconf: `configure.ac' or `configure.in' is required   thanks
![image](https://user-images.githubusercontent.com/35521643/45806217-12021000-bcf3-11e8-8a03-9a1ce7b1e1b1.png)

**Comment by Orvid** [comment]
@yidazhi The autotools based build system has been removed from Folly in favor of CMake, so you'll need to build Folly with CMake rather than autotools.
