### ISSUE TITLE
Wrong exception message for a failed future

### ISSUE THREAD

**Issue by tdauth** [facebook/folly#616]
I've created a custom combinator:
```

namespace folly
{

template<typename T>
Future<T> fallbackTo(Future<T> &&first, Future<T> &&second)
{
	return first.onError([second=std::move(second)] (std::exception &e) mutable
		{
			second.wait();

			if (second.hasValue())
			{
				return std::move(second);
			}

			auto f = makeFuture<T>(exception_wrapper(e));
			f.wait(); // TEST the message

			std::cout << "Message: " << e.what() << std::endl;
			std::cout << "Exception 0: " << f.getTry().exception().what() << std::endl; // TODO Wrong message
			std::cout << "Exception 1: " << f.getTry().exception().getCopied()->what() << std::endl; // TODO Wrong message

			return f;
		}
	); // Uses setWith() of a promise with the result of the function
}

}
```

The first Message: prints the correct exception message of the passed exception but as soon as I create a future from it with the required exception wrapper, the message is changed to something else. The copy does also have the wrong message:
```
Message: Failure 0!
Exception 0: St9exception: std::exception
Exception 1: std::exception
```

Why does the message get lost? Is this intentional and part of the purpose of the exception wrapper?

**Comment by yfeldblum** [comment]
This is a disallowed form of the `exception_wrapper` ctor: the runtime type of the passed reference is not the same as the compile-time type.

Note that `exception_wrapper` was recently rewritten (19e3e9fe724a363e342e92a5b08378900d6ab539), and the new implementation asserts against this disallowed form.
