### ISSUE TITLE
<limits> file not found

### ISSUE THREAD

**Issue by david50407** [facebook/folly#617]
When building with react-native for iOS, this came out:

```
In file included from /Users/Davy/TheApp/node_modules/react-native-fcm/ios/RNFIRMessaging.m:3:
In file included from /Users/Davy/Library/Developer/Xcode/DerivedData/Skyyer-ceqqaakmbxtyowfbqocnsbwovjre/Build/Products/Debug-iphonesimulator/include/React/RCTConvert.h:19:
In file included from /Users/Davy/Library/Developer/Xcode/DerivedData/Skyyer-ceqqaakmbxtyowfbqocnsbwovjre/Build/Products/Debug-iphonesimulator/include/yoga/Yoga.h:13:
../../../ios/Pods/Folly/folly/math.h:26:10: fatal error: 'limits' file not found
#include <limits>
         ^
1 error generated.
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1
```

![2017-06-21 16 32 20](https://user-images.githubusercontent.com/841969/27374657-383a7ade-569f-11e7-9b00-57edd04728e4.png)

**Comment by Orvid** [comment]
`limits` is a standard C++ header. If it's failing to be found, then it sounds like there's a configuration issue in the environment you're building with. The upstream repo (react-native in this case) would have a better grasp on the situation, so I would recommend filing an issue upstream with them.

**Comment by PatNeedham** [comment]
@Orvid do you have any ideas what kind of configuration issue(s) could be causing this?

**Comment by Orvid** [comment]
If the `limits` header doesn't exist, it would mean that your missing the C++ standard library in your list of includes.

**Comment by oferRounds** [comment]
Hey, have you found any solution to this? Facing the same issue after upgrading to RN 0.60+

**Comment by cwtob** [comment]
@oferRounds - Have you found a solution yet? I am running into this while upgrading to RN 0.62.2.

**Comment by oferRounds** [comment]
No.. the only solution I found was to use the library which caused the issue via Cocoa pods, and not as subproject

**Comment by oferRounds** [comment]
@cwtob please update if you find something

**Comment by ghadeeraqraa1992** [comment]
same issue , any update ?

**Comment by rpotato** [comment]
Note that clang was compiling an obj-c source file:

> In file included from /Users/Davy/TheApp/node_modules/react-native-fcm/ios/RNFIRMessaging.m:3:

and then clang was parsing and search header files till reaching  Yoga.h

> In file included from /Users/Davy/Library/Developer/Xcode/DerivedData/Skyyer-ceqqaakmbxtyowfbqocnsbwovjre/Build/Products/Debug-iphonesimulator/include/React/RCTConvert.h:19:
> In file included from /Users/Davy/Library/Developer/Xcode/DerivedData/Skyyer-ceqqaakmbxtyowfbqocnsbwovjre/Build/Products/Debug-iphonesimulator/include/yoga/Yoga.h:13:

at line Yoga.h:13 it is 

> #include <math.h>

it **intends** to include C/Obj-C system header file "**math.h**"

But due to some reasons clang found "**Math.h**" of Folly in project's shared header path(s), instead of system header file "**math.h**"

Note that Folly is C++ lib and its header files are for C++ code including. To include "limits" header the C++ convenient is **without** ".h" file ext. So when compiling obj-c source code clang will complain this unexpected include directive

> ../../../ios/Pods/Folly/folly/math.h:26:10: fatal error: 'limits' file not found
> #include <**limits**>


other cases of similar issue.
https://github.com/facebook/react-native/issues/21482
https://github.com/react-native-google-signin/google-signin/issues/316
https://github.com/facebook/react-native/issues/14326

one condition of this issue is header files from folly pollute the user header file space
https://github.com/facebook/react-native/issues/14326

another condition is case-insensitive file system, which makes clang considers "Math.h" as "math.h", as the following warning indicates:

> In file included from /Users/siva/Workspace/demo-mobile/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTConvert.h:19:
> /Users/siva/Workspace/demo-mobile/ios/build/Build/Products/Debug-iphonesimulator/include/yoga/Yoga.h:13:10: warning: non-portable path to file '<Math.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
> #include <math.h>
> ^~~~~~~~

But the root cause should be project header search path configuration. Why did clang not find the expected system header file "**math.h**"?

**Comment by sjchou** [comment]
try modify RNFIRMessaging.m to RNFIRMessaging.mm

**Comment by souradeepmajumdar05** [comment]
what is the exact solution for this limits not found issue

**Comment by weraaaaz** [comment]
Did anyone find any solution for this?

**Comment by assiaBhewa** [comment]
### Hello everyone,

I've been really stuck with an issue on my iOS project for several days and I can't seem to resolve it. I would greatly appreciate it if someone could take a look and give me a hand!

### App Context

**Key Features:**

Shopify Orders: The app processes orders from Shopify.
Video Uploads and QR Codes: Each order allows uploading a video and generates a QR code.
QR Code Downloads: Users can download these QR codes.
Platforms:

Android: Everything is smooth on Google Play.
iOS: This is where it gets tricky, I can't get through the build for the App Store.

**Versions and Tools:**

React Native: 0.74.1
Firebase: For authentication, storage, etc.
Xcode: Version 15.4
CocoaPods: Version 1.15.2
Languages: Objective-C++ and C++
iOS Build Problems:
I'm facing some tricky compilation errors related to C++ in my Objective-C++ code.

**Encountered Errors:**

Issue with FLT_MAX/FLT_MIN:

Initial error where the compiler could not find FLT_MAX and FLT_MIN. I bypassed this by adding <float.h>, but then...
Error 'limits' file not found:

Here’s what I get now:

```
'limits' file not found
In file included from <built-in>:1:
/Users/.../React-utils-prefix.pch:3:10: fatal error: 'limits' file not found
#include <limits>
```
Despite setting the C++ standard library to libc++ and thoroughly cleaning the build, this error remains.

**
<img width="1440" alt="pbReact2" src="https://github.com/facebook/folly/assets/78208485/a90670c3-8542-476c-854a-8ee7cae0a5f8">
<img width="1440" alt="pbReact1" src="https://github.com/facebook/folly/assets/78208485/3a5e3fbc-8588-4dd0-8f12-130698dfd24e">**
