### ISSUE TITLE
problem with constexpr declarations in folly/experimental/logging/LogLevel.h

### ISSUE THREAD

**Issue by jlinoff** [facebook/folly#620]
I believe that constexpr declarations for functions: `operator+()` and `isLogLevelFatal()` in `folly/experimental/logging/LogLevel.h` are not valid constexpr expressions which could cause problems for C++-14 compliant compilers.

My concern is that `operator+()` modifies a reference (lhs) and `isLogLevelFatal()` has multiple returns.

I am fairly sure that they could be refactored as follows to fix the problem but I wanted to make sure that the developers agree before changing anything.

### operator+() - _change constexpr to const_
```
inline const LogLevel operator+(LogLevel level, uint32_t value) {
  auto newValue = static_cast<uint32_t>(level) + value;
  // Cap the result at LogLevel::MAX_LEVEL
  if (newValue > static_cast<uint32_t>(LogLevel::MAX_LEVEL)) {
    return LogLevel::MAX_LEVEL;
  }
  return static_cast<LogLevel>(newValue);
}
```

### isLogLevelFatal() - _refactor_
```
inline constexpr bool isLogLevelFatal(LogLevel level) {
  return (folly::kIsDebug) ? level >= LogLevel::DFATAL : level >= LogLevel::FATAL;
}
```

**Comment by Orvid** [comment]
As far as I can tell, both of these are legal in C++14 due to extended constexpr support.

**Comment by remyabel** [comment]
> My concern is that operator+() modifies a reference (lhs) and isLogLevelFatal() has multiple returns.

C++14 introduced the [relaxed constexpr rules](https://isocpp.org/files/papers/N3652.html). If your C++14-enabled compiler doesn't support them, then it's a compiler bug.

**Comment by jlinoff** [comment]
It looks like my concern was based on a misunderstanding about the relaxed constexpr rules in C++14. Thank you both for the explanation and the reference.
