### ISSUE TITLE
error: body of constexpr function 'constexpr bool folly::isLogLevelFatal(folly::LogLevel)' not a return-statement

### ISSUE THREAD

**Issue by XinnuoXu** [facebook/folly#624]
Here is the compiling log:
@jlinoff @Orvid @remyabel

`Making all in logging
make[3]: Entering directory `/home/xxu/torch/folly/folly/experimental/logging'
make[4]: Entering directory `/home/xxu/torch/folly/folly'
make[4]: Leaving directory `/home/xxu/torch/folly/folly'
make[4]: Entering directory `/home/xxu/torch/folly/folly'
make[4]: Leaving directory `/home/xxu/torch/folly/folly'
Making all in .
make[4]: Entering directory `/home/xxu/torch/folly/folly/experimental/logging'
make[5]: Entering directory `/home/xxu/torch/folly/folly'
make[5]: Leaving directory `/home/xxu/torch/folly/folly'
make[5]: Entering directory `/home/xxu/torch/folly/folly'
make[5]: Leaving directory `/home/xxu/torch/folly/folly'
depbase=`echo AsyncFileWriter.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ../../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I../../.. -pthread -I/usr/include   -I/home/xxu/.local/include  -std=gnu++1y -g -O2 -MT AsyncFileWriter.lo -MD -MP -MF $depbase.Tpo -c -o AsyncFileWriter.lo AsyncFileWriter.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I../../.. -pthread -I/usr/include -I/home/xxu/.local/include -std=gnu++1y -g -O2 -MT AsyncFileWriter.lo -MD -MP -MF .deps/AsyncFileWriter.Tpo -c AsyncFileWriter.cpp  -fPIC -DPIC -o .libs/AsyncFileWriter.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I../../.. -pthread -I/usr/include -I/home/xxu/.local/include -std=gnu++1y -g -O2 -MT AsyncFileWriter.lo -MD -MP -MF .deps/AsyncFileWriter.Tpo -c AsyncFileWriter.cpp -o AsyncFileWriter.o >/dev/null 2>&1
depbase=`echo GlogStyleFormatter.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ../../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I../../.. -pthread -I/usr/include   -I/home/xxu/.local/include  -std=gnu++1y -g -O2 -MT GlogStyleFormatter.lo -MD -MP -MF $depbase.Tpo -c -o GlogStyleFormatter.lo GlogStyleFormatter.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I../../.. -pthread -I/usr/include -I/home/xxu/.local/include -std=gnu++1y -g -O2 -MT GlogStyleFormatter.lo -MD -MP -MF .deps/GlogStyleFormatter.Tpo -c GlogStyleFormatter.cpp  -fPIC -DPIC -o .libs/GlogStyleFormatter.o
In file included from GlogStyleFormatter.cpp:19:0:
../../../folly/experimental/logging/LogLevel.h: In function 'constexpr folly::LogLevel folly::operator+(folly::LogLevel, uint32_t)':
../../../folly/experimental/logging/LogLevel.h:93:1: error: body of constexpr function 'constexpr folly::LogLevel folly::operator+(folly::LogLevel, uint32_t)' not a return-statement
 }
 ^
../../../folly/experimental/logging/LogLevel.h: In function 'constexpr bool folly::isLogLevelFatal(folly::LogLevel)':
../../../folly/experimental/logging/LogLevel.h:130:1: error: body of constexpr function 'constexpr bool folly::isLogLevelFatal(folly::LogLevel)' not a return-statement
 }
 ^
make[4]: *** [GlogStyleFormatter.lo] Error 1
make[4]: Leaving directory `/home/xxu/torch/folly/folly/experimental/logging'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/home/xxu/torch/folly/folly/experimental/logging'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/xxu/torch/folly/folly/experimental'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/xxu/torch/folly/folly'
make: *** [all] Error 2`

**Comment by Orvid** [comment]
Which version of GCC are you trying to compile with? Folly requires at least GCC 4.9.

**Comment by remyabel** [comment]
@XinnuoXu Why did you ping me? I have nothing to do with folly.

**Comment by XinnuoXu** [comment]
@Orvid gcc (GCC) 4.9.4. Is that ok?

**Comment by XinnuoXu** [comment]
Sorry @remyabel I saw you leave a message on a related issue #620

**Comment by remyabel** [comment]
This [minimal test case](https://godbolt.org/g/mnwQZg) shows GCC 4.9.4 does not support multiple returns in a constexpr function.

**Comment by Orvid** [comment]
:( Yeah, I just discovered that as well. I was under the impression that 4.9 did support it, but apparently not.

**Comment by XinnuoXu** [comment]
I've tried version GCC 5.4.0 and GCC 6.3.0. They can compile this constexpr function. But they also get stuck on other part of 'experimental/logging' : (

@Orvid @remyabel Do you know exactly which version of GCC can compile the whole module successfully?

**Comment by Orvid** [comment]
4.9 not being able to compile it is a bug, and I'll work on getting it fixed.

**Comment by XinnuoXu** [comment]
@Orvid Many thanks! : )

**Comment by jlinoff** [comment]
@Orvid Many thanks as well!

**Comment by Orvid** [comment]
This should be fixed now.
