### ISSUE TITLE
atomic_shared_ptr reference count limit overflow?

### ISSUE THREAD

**Issue by noahdesu** [facebook/folly#628]
I'm trying to understand the reference count limits for atomic_shared_ptr, and in a simple test it seems like the limits are small. Although perhaps I am misunderstanding the results or not using atomic_shared_ptr correctly.

In the snippet below we build N atomic_shared_ptr's referring to the same base shared_ptr object, and for each new pointer we output the use count for the base pointer. After ~200K references the base overflows:

```c++
int main(int argc, char **argv)
{
  std::shared_ptr<int> sp(new int(0));

  int count = 0;
  while (true) {
    auto asp = new folly::atomic_shared_ptr<int>(sp);
    std::cout << ++count << "   " << sp.use_count() << std::endl;
  }
}
```

Each new shared pointer bumps the count by a big chunk:

```bash
1   8193
2   16385
3   24577
4   32769
5   40961
```

and finally

```
262143   2147475457
262144   -2147483647
262145   -2147475455
```

In contrast, when just allocating a large number of shared_ptrs the reference count increases 1 at a time. Although 240K references may be sufficient for some apps, I can imagine a pathological case in an application where that might occur, so I'm hoping i'm either using the API incorrectly or misunderstanding this trace.

**Comment by djwatson** [comment]
This is correct, and we should probably add a check for it.  Unfortunately I can't think of a permanent solution without modifying the underlying std::shared_ptr implementation (as Anthony Williams' atomic_shared_ptr did).

You could try modifying the EXTERNAL_OFFSET to be a smaller value - this will trade off how many threads can access the atomic_shared_ptr in a lock-free manner, but allow more total atomic_shared_ptrs against a single shared_ptr.

**Comment by noahdesu** [comment]
Thanks for the note. An overflow check, even if is a fatal error, would be nice.

**Comment by djwatson** [comment]
Sorry for the late fix, but a CHECK has been added
