### ISSUE TITLE
recommended usage for using address sanitizer with folly

### ISSUE THREAD

**Issue by sanjosh** [facebook/folly#629]
How do you recommend one use the address sanitizer with folly **fibers** ?  There is no documented option in "configure.ac" to turn it on.  

The functions being enabled here https://github.com/facebook/folly/blob/master/folly/fibers/FiberManager.cpp#L36-L45 are only available in g++ version 7.

If I try to compile folly with g++ version 7 (ubuntu 16.04), I get the following errors

> /usr/local/include/folly/futures/Future-inl.h:236:6: error: prototype for ‘decltype (((folly::Future<T>*)this)->folly::Future<T>::then(forward<Arg>(arg), (forward<Args>)(folly::Future::then::args)...)) folly::Future<T>::then(Executor*, Arg&&, Args&& ...)’ does not match any in class ‘folly::Future<T>’
>  auto Future<T>::then(Executor* x, Arg&& arg, Args&&... args)
> 
>  usr/local/include/folly/futures/Future-inl.h:1133:6: error: prototype for ‘decltype (((folly::Future<T>*)this)->folly::Future<T>::then(forward<Callback>(fn))) folly::Future<T>::thenMulti(Callback&&)’ does not match any in class ‘folly::Future<T>’
>   auto Future<T>::thenMulti(Callback&& fn)

**Comment by Orvid** [comment]
The GCC 7 issues should already be resolved on master via https://github.com/facebook/folly/commit/b0ec99828f0c782a38947513c5e0c242984e269e.

**Comment by sanjosh** [comment]
worked!  thanks, closing issue.
