### ISSUE TITLE
0.22.0 is the latest release according to GitHub API

### ISSUE THREAD

**Issue by ilovezfs** [facebook/folly#631]
https://github.com/facebook/folly/releases/latest points to https://github.com/facebook/folly/releases/tag/v0.22.0. It would be helpful to delete that explicit release to avoid confusing the Homebrew livecheck system, which checks whether the newest tag is actually the current release according to the GitHub API, but `curl https://api.github.com/repos/facebook/folly/releases/latest` currently prints incorrect information, so the newest tag never matches the current release, which is frozen at 0.22.0.

**Comment by Orvid** [comment]
I removed the release for that ancient tag, there should now be no tags that are explicitly marked as releases.

We would be publishing the tags as releases, but the last time we looked (admittedly > 3 months ago) there wasn't a way to do that with the APIs available :( Hopefully the lack of any releases at all is good enough for livecheck to fall back to the latest tag instead.

**Comment by ilovezfs** [comment]
@Orvid that is possible with the API now, I believe. But yes, having no releases will work for our purposes! Thank you for deleting the ancient release. :)

**Comment by ilovezfs** [comment]
@Orvid https://developer.github.com/v3/repos/releases/#create-a-release
