### ISSUE TITLE
Windows Universal support?

### ISSUE THREAD

**Issue by JunielKatarn** [facebook/folly#638]
Is folly supported in Windows Universal (aka UWP, Windows Store)?
Does anyone know of a successful build, and how to make it happen?

Please note, while folly has been ported to [VCPKG](https://github.com/Microsoft/vcpkg), it fails to build in UWP due to one of its dependencies.

**Comment by Orvid** [comment]
Folly is not currently supported under UWP, and we have no current plans to support it. As a side question, what dependencies don't work in UWP?
