### ISSUE TITLE
Updated build instructions for 16.04.1-Ubuntu missing

### ISSUE THREAD

**Issue by hw1** [facebook/folly#644]
I tried to build the folly library on my VirtualBox 16.04.1-Ubuntu. Runing autoreconf -ivf led to the error:
autoreconf: 'configure.ac' or 'configure.in' is required. Then, I tried cmake folly from a build directory. That failed with the message, "CMake Error at CMakeLists.txt:24 (message): This build script only supports building '' Folly on 64-bit Windows with Visual Studio 2015 or Visual Studio 2017." Are there updated instructions for linux 16.04.1?

**Comment by yfeldblum** [comment]
Which directory did you run `autoreconf -ivf` from?

**Comment by hw1** [comment]
@yfeldblum Thanks for your reply. I had done aureconf fro the topmost directory (named folly in which CMakeLists.txt resides. That was wrong: my mistake. It  should have been the folly subdirectory from which the command had to be invoked.
