### ISSUE TITLE
Unable to build folly on Linux

### ISSUE THREAD

**Issue by suryakiran** [facebook/folly#647]
Trying to build folly (v2017.07.31) on Ubuntu 16.10, gcc-7.1.0. Getting fatal error 
This build script only supports building '' Folly on 64-bit Windows with Visual Studio 2015 or Visual Studio 2017

**Comment by Orvid** [comment]
The CMake build system only supports Windows at the moment, for every other OS, use the autoconf build system instead.

I'll update the error message there to make this more clear.
