### ISSUE TITLE
correcting version of glog expected by folly

### ISSUE THREAD

**Issue by ahundt** [facebook/folly#648]
I'm trying to coordinate the correction of an inconsistency between three tools, folly, glog, and homebrew, so please bear with me.

folly appears to expect a dynamic library for glog named:

```
  /usr/local/opt/glog/lib/libglog.0.dylib
```

However, this does not appear to be the correct filename for various versions and methods of installing of glog, depending on how it was compiled. This inconsistency between glog and folly causes the homebrew install of folly to fail. I'd like to resolve this inconsistency so all the utilities work together correctly. Thanks for your consideration! :-)

Equivalent issues on the other projects:
https://github.com/google/glog/issues/196
https://github.com/Homebrew/homebrew-core/pull/14379

**Comment by ahundt** [comment]
```
        Testing folly
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20170801-62951-7aurkv.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/folly.rb --verbose
==> /usr/bin/clang++ -std=c++11 test.cc -I/usr/local/Cellar/folly/2017.07.31.00/include -L/usr/local/Cellar/folly/2017.07.31.00/lib -lfolly -o test
==> ./test
dyld: Library not loaded: /usr/local/opt/glog/lib/libglog.0.dylib
  Referenced from: /usr/local/opt/folly/lib/libfolly.57.dylib
  Reason: Incompatible library version: libfolly.57.dylib requires version 1.0.0 or later, but libglog.0.dylib provides version 0.3.5
Error: folly: failed
Failed executing: ./test 
/usr/local/Homebrew/Library/Homebrew/formula.rb:1804:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1742:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1742:in `system'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/folly.rb:64:in `block in <class:Folly>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1639:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:834:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1638:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1632:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:27:in `<main>'

```

**Comment by ahundt** [comment]
@Orvid is there any chance you could give this a look, it seems you're involved in some of the cmake code.

**Comment by Orvid** [comment]
I'm not actually very familiar with the homebrew setup :(

**Comment by ahundt** [comment]
@Orvid Sorry for the confusing post, I think the main question is related to folly and glog, no homebrew required. Essentially, can folly be updated to find a glog installation when it has been built and installed via cmake?

I believe the library name folly looks for doesn't work right when it is a cmake based install of glog.

**Comment by emmenlau** [comment]
If glog was built with cmake, could folly detect it from the cmake configuration first, instead of a find-script? This would probably be a lot more robust.
Currently I can not build folly against a standard glog that was built from source with cmake.
