### ISSUE TITLE
AtomicSharedPtr cannot be used with clang (libc++)

### ISSUE THREAD

**Issue by leolchat** [facebook/folly#651]
The file folly/concurrency/detail/AtomicSharedPtr-detail.h uses some internals of libstdc++ like the templated `std::__shared_count` or `std::_Sp_counted_base` which are not available elsewhere.

**Comment by amin-jabri** [comment]
I encountered the same problem on MacOS. it seems that std::_Sp_counted_base and _S_atomic are not available in libc++.

**Comment by amin-jabri** [comment]
I encountered the same problem on MacOS. it seems that std::_Sp_counted_base and _S_atomic are not available in libc++.

**Comment by djwatson** [comment]
folly/concurrency/detail/AtomicSharedPtr-detail.h would need an implementation for libc++.  If someone wants to provide one, I would be happy to merge it.
