### ISSUE TITLE
the file GlobalThreadPoolList.cpp is not compiled in Makefile

### ISSUE THREAD

**Issue by detective7th** [facebook/folly#660]
hey, I follow the instruction in READ.md about how to compile this folly and success, but I failed to compile wangle. the output indicate that gcc can not find reference about ThreadPoolListHook::XXXX. so I use the objdump checkout the libfolly.so, I found no symbol about the missing reference. Then I checkout the Makefile file in folly which generated by ./configure, I found no file about GlobalThreadPoolList.* . so I think the files GlobalThreadPoolList.* is not be compiled for some reason.

**Comment by geleji** [comment]
And it is not installed my make install either, causing wangle builds to break (for example).

**Comment by yfeldblum** [comment]
Should be fixed in cccde53ecdbfd7b9b328775eb3c814f95b1bb93a.
