### ISSUE TITLE
What is maximum number of getDouble?

### ISSUE THREAD

**Issue by raitucarp** [facebook/folly#663]
Hi, I come here from react-native, It seems that react native use getDouble in ReadableNativeArray.java, and ReadableNativeArray.cpp, that file uses folly to parse dynamic type.

My question: what is the maximum value of double type in dynamic? Because I encountering this error: 
https://github.com/facebook/react-native/issues/15568

**Comment by suspend0** [comment]
Well, the following works, so I expect that folly::dynamic supports the full range of values of double.

```
#include <assert.h>
#include <folly/dynamic.h>
int main() {
  double d = std::numeric_limits<double>::max();
  folly::dynamic v(d);
  assert(d == v.getDouble());
  return 0;
}
```

**Comment by raitucarp** [comment]
Ok, thank you for your confirmation. So, I can close this issue, and should focus to investigate bugs related with this in react-native.
