### ISSUE TITLE
ubuntu 17.04 make error

### ISSUE THREAD

**Issue by bilosikia** [facebook/folly#665]
i have installed all the packages.how can i deal with this?
detail/Crc32cDetail.cpp: In function ‘uint64_t folly::crc32_detail::CombineCRC(long unsigned int, uint64_t, uint64_t, uint64_t, const uint64_t*)’:
detail/Crc32cDetail.cpp:153:31: error: ‘_mm_cvtsi128_si64’ was not declared in this scope
   crc0 = _mm_cvtsi128_si64(res);
                               ^
detail/Crc32cDetail.cpp:155:34: error: ‘_mm_crc32_u64’ was not declared in this scope
   crc2 = _mm_crc32_u64(crc2, crc0);
                                  ^
detail/Crc32cDetail.cpp: In function ‘void folly::crc32_detail::triplet_loop(long unsigned int, uint64_t&, const unsigned char*&, long unsigned int)’:
detail/Crc32cDetail.cpp:48:52: error: ‘_mm_crc32_u64’ was not declared in this scope
   crc##0 = _mm_crc32_u64(crc##0, *(buf##0 + offset)); \
                                                    ^
detail/Crc32cDetail.cpp:201:9: note: in expansion of macro ‘CRCtriplet’
         CRCtriplet(crc, next, -128);

**Comment by yfeldblum** [comment]
Closing this issue because it is too old.
