### ISSUE TITLE
Fatal signal 6 (SIGABRT)

### ISSUE THREAD

**Issue by D-PorcoRosso** [facebook/folly#667]
Hi:

I wrote my jni library and integrated prebuild OpenSSL 1.0.2j to verify files signature correctness.

And I exploded my jni library (as an aar file) into application project which used react-native, and run application, the native crash happened.

Crash log as following text, do you have any idea about this crash?

A/ReactNativeJNI: Check failed: 0 
                                                                      
--------- beginning of crash
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 13774 (FinalizerDaemon)
                                                            
                                                            [ 08-29 16:23:49.846   571:  571 W/         ]
                                                            debuggerd: handling request: pid=13763 uid=10288 gid=10288 tid=13774
08-29 16:23:50.000 14901-14901/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-29 16:23:50.000 14901-14901/? A/DEBUG: Build fingerprint: 'google/sailfish/sailfish:7.1.2/NJH47F/4146041:user/release-keys'
08-29 16:23:50.000 14901-14901/? A/DEBUG: Revision: '0'
08-29 16:23:50.001 14901-14901/? A/DEBUG: ABI: 'arm'
08-29 16:23:50.001 14901-14901/? A/DEBUG: pid: 13763, tid: 13774, name: FinalizerDaemon  >>> com.xxxxxxxxx.xxxxxxxxx <<<
08-29 16:23:50.001 14901-14901/? A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
08-29 16:23:50.039 14901-14901/? A/DEBUG: Abort message: 'Check failed: 0 '
08-29 16:23:50.039 14901-14901/? A/DEBUG:     r0 00000000  r1 000035ce  r2 00000006  r3 00000008
08-29 16:23:50.039 14901-14901/? A/DEBUG:     r4 eb31f978  r5 00000006  r6 eb31f920  r7 0000010c
08-29 16:23:50.039 14901-14901/? A/DEBUG:     r8 d1840e18  r9 d183e17e  sl 59a52495  fp d184ff7c
08-29 16:23:50.039 14901-14901/? A/DEBUG:     ip 0000000b  sp eb31f250  lr edfa05c7  pc edfa2e30  cpsr 600f0010
08-29 16:23:50.061 14901-14901/? A/DEBUG: backtrace:
08-29 16:23:50.062 14901-14901/? A/DEBUG:     #00 pc 00049e30  /system/lib/libc.so (tgkill+12)
08-29 16:23:50.062 14901-14901/? A/DEBUG:     #01 pc 000475c3  /system/lib/libc.so (pthread_kill+34)
08-29 16:23:50.062 14901-14901/? A/DEBUG:     #02 pc 0001d635  /system/lib/libc.so (raise+10)
08-29 16:23:50.062 14901-14901/? A/DEBUG:     #03 pc 00019181  /system/lib/libc.so (__libc_android_abort+34)
08-29 16:23:50.063 14901-14901/? A/DEBUG:     #04 pc 00017048  /system/lib/libc.so (abort+4)
08-29 16:23:50.064 14901-14901/? A/DEBUG:     #05 pc 0000864b  /data/app/com.xxxxxxxxx.xxxxxxxxx-1/lib/arm/libglog.so
08-29 16:23:50.064 14901-14901/? A/DEBUG:     #06 pc 00009a63  /data/app/com.xxxxxxxxx.xxxxxxxxx-1/lib/arm/libglog.so (_ZN6google10LogMessage4FailEv+10)
08-29 16:23:50.064 14901-14901/? A/DEBUG:     #07 pc 0000bd47  /data/app/com.xxxxxxxxx.xxxxxxxxx-1/lib/arm/libglog.so (_ZN6google10LogMessage9SendToLogEv+246)
08-29 16:23:50.064 14901-14901/? A/DEBUG:     #08 pc 00009897  /data/app/com.xxxxxxxxx.xxxxxxxxx-1/lib/arm/libglog.so (_ZN6google10LogMessage5FlushEv+102)
08-29 16:23:50.064 14901-14901/? A/DEBUG:     #09 pc 0000bf7f  /data/app/com.xxxxxxxxx.xxxxxxxxx-1/lib/arm/libglog.so (_ZN6google15LogMessageFatalD2Ev+2)
08-29 16:23:50.065 14901-14901/? A/DEBUG:     #10 pc 000108dd  /data/app/com.xxxxxxxxx.xxxxxxxxx-1/lib/arm/libfolly_json.so (_ZN5folly7dynamic7destroyEv+88)
08-29 16:23:50.065 14901-14901/? A/DEBUG:     #11 pc 00010863  /data/app/com.xxxxxxxxx.xxxxxxxxx-1/lib/arm/libfolly_json.so (_ZNSt12_Destroy_auxILb0EE9__destroyIPN5folly7dynamicEEEvT_S5_+16)
08-29 16:23:50.065 14901-14901/? A/DEBUG:     #12 pc 00010873  /data/app/com.xxxxxxxxx.xxxxxxxxx-1/lib/arm/libfolly_json.so (_ZNSt6vectorIN5folly7dynamicESaIS1_EED2Ev+8)
08-29 16:23:50.065 14901-14901/? A/DEBUG:     #13 pc 000108a3  /data/app/com.xxxxxxxxx.xxxxxxxxx-1/lib/arm/libfolly_json.so (_ZN5folly7dynamic7destroyEv+30)
08-29 16:23:50.065 14901-14901/? A/DEBUG:     #14 pc 0003256f  /data/app/com.xxxxxxxxx.xxxxxxxxx-1/lib/arm/libreactnativejnifb.so
08-29 16:23:50.065 14901-14901/? A/DEBUG:     #15 pc 00032907  /data/app/com.xxxxxxxxx.xxxxxxxxx-1/lib/arm/libreactnativejnifb.so
08-29 16:23:50.065 14901-14901/? A/DEBUG:     #16 pc 0001df6b  /data/app/com.xxxxxxxxx.xxxxxxxxx-1/lib/arm/libreactnativejnifb.so (_ZNSt14_Function_baseD2Ev+12)
08-29 16:23:50.065 14901-14901/? A/DEBUG:     #17 pc 00032981  /data/app/com.xxxxxxxxx.xxxxxxxxx-1/lib/arm/libreactnativejnifb.so
08-29 16:23:50.065 14901-14901/? A/DEBUG:     #18 pc 00032a99  /data/app/com.xxxxxxxxx.xxxxxxxxx-1/lib/arm/libreactnativejnifb.so
08-29 16:23:50.065 14901-14901/? A/DEBUG:     #19 pc 0001df6b  /data/app/com.xxxxxxxxx.xxxxxxxxx-1/lib/arm/libreactnativejnifb.so (_ZNSt14_Function_baseD2Ev+12)
08-29 16:23:50.065 14901-14901/? A/DEBUG:     #20 pc 0001e009  /data/app/com.xxxxxxxxx.xxxxxxxxx-1/lib/arm/libreactnativejnifb.so
08-29 16:23:50.065 14901-14901/? A/DEBUG:     #21 pc 0001df6b  /data/app/com.xxxxxxxxx.xxxxxxxxx-1/lib/arm/libreactnativejnifb.so (_ZNSt14_Function_baseD2Ev+12)
08-29 16:23:50.065 14901-14901/? A/DEBUG:     #22 pc 0001df7f  /data/app/com.xxxxxxxxx.xxxxxxxxx-1/lib/arm/libreactnativejnifb.so
08-29 16:23:50.065 14901-14901/? A/DEBUG:     #23 pc 0001df9d  /data/app/com.xxxxxxxxx.xxxxxxxxx-1/lib/arm/libreactnativejnifb.so
08-29 16:23:50.065 14901-14901/? A/DEBUG:     #24 pc 0000afed  /data/app/com.xxxxxxxxx.xxxxxxxxx-1/lib/arm/libfb.so (_ZN8facebook3jni6detail10HybridData16setNativePointerESt10unique_ptrINS1_15BaseHybridClassESt14default_deleteIS4_EE+112)
08-29 16:23:50.065 14901-14901/? A/DEBUG:     #25 pc 0000b05b  /data/app/com.xxxxxxxxx.xxxxxxxxx-1/lib/arm/libfb.so
08-29 16:23:50.065 14901-14901/? A/DEBUG:     #26 pc 00a9a657  /data/app/com.xxxxxxxxx.xxxxxxxxx-1/oat/arm/base.odex (offset 0xa30000)

**Comment by yfeldblum** [comment]
Closing this issue because it is too old.
