### ISSUE TITLE
Change default build system to CMake

### ISSUE THREAD

**Issue by navidR** [facebook/folly#669]
Considering how it is easy to build applications and libraries using CMake, I created this issue to track this problem of "when CMake will be available for *nix (and all other) platforms?"

Right now CMake support is only available on Windows platform.

Let me give you an instance, I am building a complex Android application. Most of the networking and file system (while being multi threaded) logic is in NDK and I am using 8,9 different library. Compiling those libraries with Autotools is just like hell (therefore it is totally okay to call it Autohell). But just look at this link and see how it is easy to compile C++ project for NDK : 
https://developer.android.com/ndk/guides/standalone_toolchain.html

If you are not familiar with programming in NDK, I have to say compiling and setting up toolchain and required stuff is way complicated than your actual project (figure of speech), while with CMake and CMake support from Google, it is just adding two or three flags and then compiling your library to whatever arch and API level you are targeting. Folly and Wangle are very useful libraries. The only barrier for me to migrate our company C++/NDK to Folly is Autotools (consider how difficult it is to set up continuous integration for NDK and Autotools).

**Comment by Orvid** [comment]
Right now the biggest reason we haven't switched everything over to CMake is that nobody has taken the time to do so. The CMake build currently exists purely to make it sane to work on Folly from Windows.

**Comment by q96456** [comment]
I hope CMakeList.txt can support on MAC OS.Thanks.

**Comment by navidR** [comment]
@Orvid do you guys accept PR? I can work on it in my spare time.

**Comment by Orvid** [comment]
@navidR Yes, we do.

**Comment by JoeLoser** [comment]
Is there anyone actively working on this (internal at FB or external contributors)?

**Comment by yfeldblum** [comment]
This is done.
