### ISSUE TITLE
folly v2017.09.11.00 does not pick up libunwind reference

### ISSUE THREAD

**Issue by smellyfis** [facebook/folly#671]
I am using Gentoo and am trying to build an updated folly ebuild (installation stuff) and autotools did not put in the -lunwind for the linker and I got several unrecognized symbols related. when I added "-lunwind" to every libfolly*_LDFLAGS I was able to link properly. I do not generally use autotools so I don't know where it is needed to be placed to pick up that flag dynamically, but i see there is something checking for it in configure.ac.

**Comment by yfeldblum** [comment]
Closing this issue because it is too old, and because folly now uses cmake.
