### ISSUE TITLE
folly link error

### ISSUE THREAD

**Issue by z3ppj1g5aw** [facebook/folly#673]
Hi,
Folly installed correctly but whenever I try to link folly (for example, while installing fbthrift), I'm getting the following error

/usr/local/lib/libfolly.so: undefined reference to `unw_backtrace'
/usr/local/lib/libfolly.so: undefined reference to `_ULx86_64_step'
/usr/local/lib/libfolly.so: undefined reference to `_ULx86_64_get_reg'
/usr/local/lib/libfolly.so: undefined reference to `_Ux86_64_getcontext'
/usr/local/lib/libfolly.so: undefined reference to `_ULx86_64_init_local'
/usr/local/lib/libfolly.so: undefined reference to `_ULx86_64_is_signal_frame'
collect2: error: ld returned 1 exit status

What is the reason for this? 

Thanks

**Comment by bluealert** [comment]
You can build folly and install it to the correct directory on the same computer by yourself, and then the error may be solved.

**Comment by guoxiao** [comment]
@bluealert In the process of building `folly` it also fails with the same message.
```
libtool: link: g++ -std=gnu++1y -Wall -Wextra -O2 -g -o .libs/logging_example main.o  ./.libs/libfollylogging_example.a /home/xxx/code/facebook/folly/folly/experimental/logging/.libs/libfollylogging.so /home/xxx/code/facebook/folly/folly/.libs/libfolly.so -lboost_context -lboost_program_options -lboost_thread -lboost_filesystem -lboost_system -lboost_regex -lpthread -lboost_chrono -lssl -lcrypto -lbz2 -lzstd -llzma -lz -lsnappy -llz4 -liberty -ldl -levent -ldouble-conversion -lglog -lgflags
/home/xxx/code/facebook/folly/folly/.libs/libfolly.so: undefined reference to `unw_backtrace'
/home/xxx/code/facebook/folly/folly/.libs/libfolly.so: undefined reference to `_ULx86_64_step'
/home/xxx/code/facebook/folly/folly/.libs/libfolly.so: undefined reference to `_ULx86_64_get_reg'
/home/xxx/code/facebook/folly/folly/.libs/libfolly.so: undefined reference to `_Ux86_64_getcontext'
/home/xxx/code/facebook/folly/folly/.libs/libfolly.so: undefined reference to `_ULx86_64_init_local'
/home/xxx/code/facebook/folly/folly/.libs/libfolly.so: undefined reference to `_ULx86_64_is_signal_frame'
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:421: logging_example] Error 1
make[4]: Leaving directory '/home/xxx/code/facebook/folly/folly/experimental/logging/example'
```

**Comment by jhhudso** [comment]
Passing LIBS=-lunwind to configure like this
LIBS=-lunwind ./configure
before you compile will make it work.

**Comment by JasonOldWoo** [comment]
@jrahman thx a lot!
