### ISSUE TITLE
native_handle() passed where get_id() is expected

### ISSUE THREAD

**Issue by capsocrates** [facebook/folly#674]
https://github.com/facebook/folly/blob/af4a335238f0ccefdf8a8e6a2689d3a1d44b584a/folly/executors/NamedThreadFactory.h#L38

I don't know if this compiles in *nix builds, but it doesn't compile on MSVC. `setThreadName` expects a `std::thread::id` as the first arg, but this line is passing a `std::thread::native_handle_type` instead.

Obvious fix is to change the call from `get_native_handle()` to `get_id()`. I have that change locally and can commit it if that's okay.

**Comment by Orvid** [comment]
Fixed by aa62e6f3ba01d7332f92ffe91694a43577234d62. `get_id()` would have fixed it, but it wouldn't have gotten it working on OSX, which is why I went the way I did in that commit.
