### ISSUE TITLE
Forking a future

### ISSUE THREAD

**Issue by leolchat** [facebook/folly#675]
As part of some API, I find myself willing to return a future and also internally be able to do something when it is done.

Obvious solution if I own the promise is to start upfront with a sharedpromise.

But using another library which returns future and I am stuck and needs to 'fork' the future before returning it.

Is there a recommended way?
I came up with two options (see [gist](https://gist.github.com/leolchat/d1014c8a03c6c10bd3a875db6ab68a0b) ) one requiring copy of a Try and one not requiring it. Any comments ?

**Comment by yfeldblum** [comment]
You can use `folly::splitFuture` for this case. It is based on `folly::SharedPromise` but takes care of constructing it from an input `folly::Future` and handling the lifetime correctly.

Closing, because this answers the question as asked. Thanks for asking!

**Comment by leolchat** [comment]
I missed that helper file (since it is not mentioned in the README.md, thank you for pointing it out!

I am still interested in feedbacks for the forkFuture I wrote which does not rely on sharedPromise and thus do not use a mutex.

**Comment by yfeldblum** [comment]
Sure, you can use your technique too, if it works better for your case.

**Comment by leolchat** [comment]
Thank you.
