### ISSUE TITLE
asm command does not compile in MSVC

### ISSUE THREAD

**Issue by capsocrates** [facebook/folly#679]
This code
[`    asm volatile("" ::"m"(ptr) : "memory");`](https://github.com/facebook/folly/blob/94b8816bbdca38914030842554cc955caee59063/folly/Malloc.h#L193)
Introduced in [this commit](https://github.com/facebook/folly/commit/610c11630a3cbccdc2be0a91b5a6c2f934af3f55) does not compile in MSVC.

**Comment by KindDragon** [comment]
This issue already fixed in master
