### ISSUE TITLE
Error with 'libfollybenchmark.la' during make

### ISSUE THREAD

**Issue by samdasnake** [facebook/folly#684]
I am receiving the following error when I run `make install` to install folly.  I am running Ubuntu 16.04.  Here are the error messages I receive.
`/usr/bin/ld: /usr/local/lib/libdouble-conversion.a(double-conversion.cc.o): relocation R_X86_64_32 against '.bss' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libdouble-conversion.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
libtool:   **_error: error: relink 'libfollybenchmark.la' with the above command before installing it_**
Makefile:1316: recipe for target 'install-libLTLIBRARIES' failed
make[2]: *** [install-libLTLIBRARIES] Error 1`

I have tried to install folly directly as well as with the fblualib install_all.sh script.  In both cases I received this same error message.  Does anyone know how I can resolve this issue?  Thanks!

**Comment by Crista23** [comment]
I get the same error. Did you find any solution?

**Comment by JoeLoser** [comment]
Did you install `double conversion` library using `apt-get`? If so, do you know if it compiles the library's sources using `-fPIC` for position independent code? I recommend repeating the exact commands that `apt-get` spews out for installing the lib and passing `VERBOSE=1` to its invocation of `make` to see all of the compiler and linker flags.

If `apt-get` doesn't pass `-fPIC` through when building the lib, I would recommend building the library from source with `-fPIC` and then retrying to build Folly.
