### ISSUE TITLE
Folly compilation error....

### ISSUE THREAD

**Issue by msiraj83** [facebook/folly#685]
Hi..
I want to install facebook/folly on my system. My system specification is 
OS = Ubuntu-14.04 LTS
Processor = GPU based
Compiler = gcc-4.9 (I have gcc-4.8 by default but I configure with gcc-4.9 using ./configure CC=path to gcc-4.9)

In have install all the dependencies and configure successfully. But when i run the make command than it give error attached
![folly_error](https://user-images.githubusercontent.com/8863047/31340440-504cb41a-ad30-11e7-9bfd-b33949ce2d45.png)

Can any body help me in this regards please

**Comment by Orvid** [comment]
It looks like you're building using GCC 4.9, but you're still building with the standard library that comes with GCC 4.8, which is why you're seeing the issues.

**Comment by msiraj83** [comment]
@Orvid thanks for your conformation...  yes you are right.... I solve the issue.. by installing the latest version of GCC i.e. gcc-5 and and run the configure command with CC=/usr/bin/gcc-5 and CXX=/usr/bin/g++-5. 
After that its build and install successfully...

**Comment by msiraj83** [comment]
@Orvid thanks for your conformation...  yes you are right.... I solve the issue.. by installing the latest version of GCC i.e. gcc-5 and and run the configure command with CC=/usr/bin/gcc-5 and CXX=/usr/bin/g++-5. 
After that its build and install successfully...
