### ISSUE TITLE
dyld: Library not loaded: libboost_context.dylib

### ISSUE THREAD

**Issue by guodongxiaren** [facebook/folly#687]
./generate_fingerprint_tables
dyld: Library not loaded: libboost_context.dylib
  Referenced from: /Users/jelly/Documents/Source/folly/folly/./generate_fingerprint_tables
  Reason: image not found
make[2]: *** [FingerprintTables.cpp] Trace/BPT trap: 5
make[1]: *** [all-recursive] Error 1

**Comment by yfeldblum** [comment]
Closing this issue because it is too old, and because the fingerprint-tables generation is gone.
