### ISSUE TITLE
Undefined reference

### ISSUE THREAD

**Issue by kelu27** [facebook/folly#690]
I'm building folly for mcrouter on ubuntu:16.04:
Here is my error with your last commit https://github.com/facebook/folly/commit/69d97159209c5a77fdf7805155738604233d0b8a:

`folly/folly/.libs/libfolly.so: undefined reference to folly::AsyncSocketException::getMessage(folly::AsyncSocketException::AsyncSocketExceptionType, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'`

**Comment by maichm** [comment]
+1

**Comment by yfeldblum** [comment]
Closing this issue because it is too old. In addition, if it is specific to Ubuntu 16.04, folly no longer targets that platform.
