### ISSUE TITLE
win ProducerConsumerQueue

### ISSUE THREAD

**Issue by yangxingpping** [facebook/folly#698]
Installing from vcpkg. Compiling failed when I am try to run ProducerConsumerQueue,with error C2327,C2065. folly::ProducerConsumerQueue<int>::writeIndex is not type name, nor enum.
writeIndex_ is not declared. It seems like vc++ does not support assign array size with sizeof(writeIndex_).

**Comment by Orvid** [comment]
Which version of MSVC? There are known limitations to which parts of Folly are supported under 2015 update 3.

**Comment by yangxingpping** [comment]
I'm sorry, vs2017 x64 with /std:c++14.
