### ISSUE TITLE
folly configure checking whether the Boost::Context library is available... no

### ISSUE THREAD

**Issue by tlanwairen123** [facebook/folly#699]
i try build the folly. there have an error for configure for checking whether the Boost::Context library is available... no
I have install boost and boost_context，how can i Solve the problem

**Comment by JoeLoser** [comment]
Mind sharing some more info? For starters:

1. Which OS are you using?
2. How are you building Folly? E.g. which build script are you using if any?
3. Did you specify to use static or shared libraries for Boost? Do you have both installed?

**Comment by JoeLoser** [comment]
@tlanwairen123 is this still an issue even with the latest CMake improvements to support other OSes other than just Windows?
