### ISSUE TITLE
Compression namespace

### ISSUE THREAD

**Issue by RcRonco** [facebook/folly#700]
Hi,
When compression moved from ```io``` to its own folder the namespace still stayed ```folly::io```, which is quite confusing.
Maybe it should be in its own namespace or in the ```folly``` namespace, or even return the ```compression``` into ```io``` folder.

In compression [Utils.h](https://github.com/facebook/folly/blob/master/folly/compression/Utils.h#L30) the namespace ```folly::io::compression``` exists, refactoring the namespaces of the compression folder will make it more consistent, I don`t mind to do it.

**Comment by Orvid** [comment]
I believe the plan is to shift the namespace as well, we're just doing all of the physical moves first, then we'll be renaming a few things to make them more consistent (this included), and finally post a write-up of everything that moved and where it went :)
