### ISSUE TITLE
Errors were encountered while processing:

### ISSUE THREAD

**Issue by phyorch** [facebook/folly#701]
>     g++ \
>     automake \
>     autoconf \
>     autoconf-archive \
>     libtool \
>     libboost-all-dev \
>     libevent-dev \
>     libdouble-conversion-dev \
>     libgoogle-glog-dev \
>     libgflags-dev \
>     liblz4-dev \
>     liblzma-dev \
>     libsnappy-dev \
>     make \
>     zlib1g-dev \
>     binutils-dev \
>     libjemalloc-dev \
>     libssl-dev \
>     pkg-config
[sudo] password for phyorch: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
autoconf is already the newest version (2.69-9).
automake is already the newest version (1:1.15-4ubuntu1).
g++ is already the newest version (4:5.3.1-1ubuntu1).
libdouble-conversion-dev is already the newest version (2.0.1-3ubuntu2).
liblz4-dev is already the newest version (0.0~r131-2ubuntu2).
liblzma-dev is already the newest version (5.1.1alpha+20120614-2ubuntu2).
libsnappy-dev is already the newest version (1.1.3-2).
libtool is already the newest version (2.4.6-0.1).
make is already the newest version (4.1-6).
pkg-config is already the newest version (0.29.1-0ubuntu1).
autoconf-archive is already the newest version (20150925-1).
libboost-all-dev is already the newest version (1.58.0.1ubuntu1).
libgflags-dev is already the newest version (2.1.2-3).
libgoogle-glog-dev is already the newest version (0.3.4-0.1).
libjemalloc-dev is already the newest version (3.6.0-9ubuntu1).
binutils-dev is already the newest version (2.26.1-1ubuntu1~16.04.5).
libevent-dev is already the newest version (2.0.21-stable-2ubuntu0.16.04.1).
libssl-dev is already the newest version (1.0.2g-1ubuntu4.8).
zlib1g-dev is already the newest version (1:1.2.8.dfsg-2ubuntu4.1).
The following packages were automatically installed and are no longer required:
  linux-headers-4.10.0-28 linux-headers-4.10.0-28-generic linux-headers-4.10.0-33
  linux-headers-4.10.0-33-generic linux-headers-4.10.0-35 linux-headers-4.10.0-35-generic
  linux-image-4.10.0-28-generic linux-image-4.10.0-33-generic linux-image-4.10.0-35-generic
  linux-image-extra-4.10.0-28-generic linux-image-extra-4.10.0-33-generic
  linux-image-extra-4.10.0-35-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 26 not upgraded.
5 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up linux-firmware (1.157.13) ...
update-initramfs: Generating /boot/initrd.img-4.10.0-37-generic

gzip: stdout: No space left on device
E: mkinitramfs failure cpio 141 gzip 1
update-initramfs: failed for /boot/initrd.img-4.10.0-37-generic with 1.
dpkg: error processing package linux-firmware (--configure):
 subprocess installed post-installation script returned error exit status 1
Setting up linux-image-4.10.0-38-generic (4.10.0-38.42~16.04.1) ...
Running depmod.
update-initramfs: deferring update (hook will be called later)
The link /initrd.img is a dangling linkto /boot/initrd.img-4.10.0-38-generic
vmlinuz(/boot/vmlinuz-4.10.0-38-generic
) points to /boot/vmlinuz-4.10.0-38-generic
 (/boot/vmlinuz-4.10.0-38-generic) -- doing nothing at /var/lib/dpkg/info/linux-image-4.10.0-38-generic.postinst line 491.
Examining /etc/kernel/postinst.d.
run-parts: executing /etc/kernel/postinst.d/apt-auto-removal 4.10.0-38-generic /boot/vmlinuz-4.10.0-38-generic
run-parts: executing /etc/kernel/postinst.d/initramfs-tools 4.10.0-38-generic /boot/vmlinuz-4.10.0-38-generic
update-initramfs: Generating /boot/initrd.img-4.10.0-38-generic

gzip: stdout: No space left on device
E: mkinitramfs failure cpio 141 gzip 1
update-initramfs: failed for /boot/initrd.img-4.10.0-38-generic with 1.
run-parts: /etc/kernel/postinst.d/initramfs-tools exited with return code 1
Failed to process /etc/kernel/postinst.d at /var/lib/dpkg/info/linux-image-4.10.0-38-generic.postinst line 1052.
dpkg: error processing package linux-image-4.10.0-38-generic (--configure):
 subprocess installed post-installation script returned error exit status 2
No apport report written because the error message indicates its a followup error from a previous failure.
                                                                                                          No apport report written because MaxReports is reached already
                                                             dpkg: dependency problems prevent configuration of linux-image-extra-4.10.0-38-generic:
 linux-image-extra-4.10.0-38-generic depends on linux-image-4.10.0-38-generic; however:
  Package linux-image-4.10.0-38-generic is not configured yet.

dpkg: error processing package linux-image-extra-4.10.0-38-generic (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of linux-image-generic-hwe-16.04:
 linux-image-generic-hwe-16.04 depends on linux-image-4.10.0-38-generic; however:
  Package linux-image-4.10.0-38-generic is not configured yet.
 linux-image-generic-hwe-16.04 depends on linux-image-extra-4.10.0-38-generic; however:
  Package linux-image-extra-4.10.0-38-generic is not configured yet.
 linux-image-generic-hwe-16.04 depends on linux-firmware; however:
  Package linux-firmware is not configured yet.

dpkg: error processing package linux-image-generic-hwe-16.04 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problNo apport report written because MaxReports is reached already
                                                                                    ems prevent configuration of linux-generic-hwe-16.04:
 linux-generic-hwe-16.04 depends on linux-image-generic-hwe-16.04 (= 4.10.0.38.40); however:
  Package linux-image-generic-hwe-16.04 is not configured yet.

dpkg: error processing package linux-generic-hwe-16.04 (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 linux-firmware
 linux-image-4.10.0-38-generic
 linux-image-extra-4.10.0-38-generic
 linux-image-generic-hwe-16.04
 linux-generic-hwe-16.04

**Comment by DariuszOstolski** [comment]
gzip: stdout: No space left on device

**Comment by Orvid** [comment]
You ran out of disk space.
