### ISSUE TITLE
CMakeLists tests cmake-bitness, not OS

### ISSUE THREAD

**Issue by kfsone** [facebook/folly#706]
[edit: That should read 'compiler-bitness, not OS'; you are reporting a non-64bit OS when, infact, it's simply the non-64bit generator]

    if (NOT CMAKE_SIZEOF_VOID_P EQUAL 8)

Repro:

1. Install "Windows win64-x64 Installer" from https://cmake.org/download/
2. git clone folly
3. Run "Cmake-gui" and point it at the folly clone,
4. Click configure

`C:\Users\oliver>wmic os get osarchitecture
OSArchitecture
64-bit
`

`Selecting Windows SDK version 10.0.16299.0 to target Windows 10.0.17025.
The CXX compiler identification is MSVC 19.12.25805.1
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/Preview/Professional/VC/Tools/MSVC/14.12.25805/bin/Hostx86/x86/cl.exe
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/Preview/Professional/VC/Tools/MSVC/14.12.25805/bin/Hostx86/x86/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
CMake Error at CMakeLists.txt:29 (message):
  Folly requires a 64bit OS`

**Comment by Orvid** [comment]
I need to reword the error text slightly, but the check itself is correct: Folly cannot be compiled as 32-bit code on Windows due largely to core design decisions that I made while creating the socket portability layer. Beyond that, the vast majority of Folly is entirely untested on any 32-bit platform.

**Comment by kfsone** [comment]
Not looking to run it under 32-bit, the message simply mislead me enough, and evoked experiences I had in the past with CMAKE_SIZEOF_VOID_P being wrong because I was running 32-bit cmake, that I didn't realize I hadn't specified the 64-bit generator, which ultimately is what the error was *trying* to tell me :)
