### ISSUE TITLE
PackedSyncPtr, DiscriminatedPtr, ...: 5-level paging and 56-bit addressing in Linux kernel 4.14+

### ISSUE THREAD

**Issue by ido** [facebook/folly#712]
Please disregard this issue if you have already discussed this internally and are addressing it for a future release of folly.

Symptoms from this issue may include possible corruption of the 8 LSB out of the `uint16_t` used by the `PackedSyncPtr, DiscriminatedPtr,` and any types in folly which rely on them (or other pointer types in folly which rely on x86 using only the 48 LSBs of the pointer for virtual addressing).  (I'm not certain, but `AtomicHashMap` and certain variant types might also be at risk.)  This is only relevant to upcoming x86 hardaware with Linux kernels 4.14+ when 56 bit addressing is requested by the user (see below), which is not the default.

Some newer hardware (new/upcoming x86 CPUs) and kernels are transitioning from using 47-bits to 56-bits for userspace virtual addresses with the introduction of 5-level paging, along with 52-bit physical addresses (needs verification).  This changes the arithmetic in `PackedSyncPtr` and other pointer types in `folly` which make use of the 16 most significant bits in pointers to store other data (such as 1-bit lock state + user data in `PackedSyncPtr`, underlying type identity as in `DiscriminatedPtr`, etc.)  When 56-bit addressing is in use, these types would be restricted to `uint8_t` instead of `uint16_t` worth of metadata they can pack into the pointer.

This will limit `DiscriminatedPtr` to 255 type identities (+ empty sentinel value) instead of `2^16-1`, and `PackedSyncPtr` to 7 bits of user metadata (+ 1 bit for synchronization/locking).

On Linux kernel versions 4.14+, if the user requests address space above `2^47` in the hint address provided to `mmap()`, then the kernel may allocate 56-bit userspace virtual addresses and use 5-level paging.  This may corrupt the user data these `folly` pointer types rely on, and will cause improper pointer address storage and dereferencing (since most of these types mask the top 16 bits of the pointer with zeroes before dereferencing or converting them to native pointer types).

More information about 56-bit addressing and 5-level page tables can be found here:
- https://lwn.net/Articles/717293/ (LWN article explaining 5-level page tables)
- https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=b1b6f83ac938d176742c85757960dec2cf10e468 (Git merge of 5-level page tables from Ingo Molnar's mm tree)
- https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=77ef56e4f0fbb350d93289aa025c7d605af012d4 (Git commit containing documentation and kernel config parameter for 5-level paging CONFIG_X86_5LEVEL=y)

Apologies in advance for not submitting a pull request: many other types in `folly` depend on these pointer types, so I did not want to spend the time to code up the change and test the downstream impact before further discussion.  At a minimum, perhaps it would be wise to have a template parameter which affects the `static_assert`s and limits MSB usage to 8 bits (e.g. a `bool` or if we are forward-thinking a `size_t` indicating whether or not 56-bit addressing is in use or how many MSBs are available to use, respectively).

NB: I think 5-level paging will have deeper effects on the calculus of various low latency/high throughput logging techniques on x86 hardware as well, but that is beyond the scope of this issue.

**Comment by djwatson** [comment]
Yes our internal plan is to change these interfaces to only use uint8_t, I don't think there is anything that depends on them being uint16_t.

**Comment by ido** [comment]
Great, should be a simple change then.  Closing since I'm assuming you have an internal issue tracker for this.
