### ISSUE TITLE
[Question] Keeping C++11 support vs migrating to C++14

### ISSUE THREAD

**Issue by JoeLoser** [facebook/folly#726]
I am interested to learn the reasoning behind Folly continuing to keep support for C++11 as the minimum rather than bumping it up to C++14.  I assume it is due to internal libraries or applications, but would like a confirmation. It seems we already require Boost with C++14 support, but only require a C++11-compliant compiler per the top level `README.md` "folly requires gcc 4.9+ and a version of boost compiled with C++14 support".

Is there any timeline or motivation(s) in requiring C++14 support?

**Comment by Orvid** [comment]
Folly has required C++14 support for most of the last year. If the readme says otherwise, that needs to be fixed.

**Comment by yfeldblum** [comment]
Thanks for the question.

The baseline language version Folly requires is currently C++14. Folly is not compatible with C++11.

Concerning gcc support: Much of Folly code continues to work with gcc 4.9, using C++11 and the subset of C++14 that is implemented in that compiler, for internal reasons. However, Folly may at any time drop compatibility with gcc 4.9 and may only be compatible with gcc 5+, and then will be able to use all of C++14. There is not a public timeline for when compatibility with gcc 4.9 will be dropped, other than to say that the baseline language version is currently C++14.
