### ISSUE TITLE
One little goto 🦖

### ISSUE THREAD

**Issue by mkudrnac** [facebook/folly#732]
https://github.com/facebook/folly/blob/e7f26d60480810d6c2b724130e35761d75af33fc/folly/String.cpp#L47

![main-qimg-ed4254c72d3c84c43bef0d32b7ff4172](https://user-images.githubusercontent.com/12230741/34783624-5d2f7bfa-f62c-11e7-9691-5afb55ce78c3.png)

**Comment by yfeldblum** [comment]
Welcome to Jurassic Park: facebook/fbthrift@e3d5183bedd57a71c0b4dd4955d04f49153de826.
