### ISSUE TITLE
folly/folly/experimental/logging/example/main.cpp

### ISSUE THREAD

**Issue by TomGarden** [facebook/folly#735]
#  log moudle don't work
Resently I want use folly's logging moudle.
But it don't work well.
Compile no problem。
## compile cmd
sources path : https://github.com/facebook/folly/blob/master/folly/experimental/logging/example/main.cpp
```
$ g++ main.c lib.cpp -std=c++14 -o testMain -lfollylogging -lfolly -ldouble-conversion -lglog -lgflags
```

I don't find any log from function `XLOG()`

**Comment by TomGarden** [comment]
## I fix my error
### error operate
```
$ g++ main.c lib.cpp -std=c++14 -o testMain -lfollylogging -lfolly -ldouble-conversion -lglog -lgflags
$ ./testMain
```
### right operate
```

$ g++ main.c lib.cpp -std=c++14 -o testMain -lfollylogging -lfolly -ldouble-conversion -lglog -lgflags
$ ./testMain -logging="INFO"
$ ./testMain -logging="DBG2"
```
### about
I need read and understand the sources
every line

**Comment by JoeLoser** [comment]
@djwatson mind closing this issue as the user fixed his own error?
