### ISSUE TITLE
Poly does not work with noexcept methods

### ISSUE THREAD

**Issue by maikel** [facebook/folly#737]
The `folly/Poly.md` document does not mention `noexcept` at all. Consider this example

```
#include <folly/Poly.h>
#include <iostream>

struct IDrawable {
  template <typename Base> struct Interface : Base {
    void draw(std::ostream& out) const /* noexcept */ {
      folly::poly_call<0>(*this, out);
    }
  };

  template <typename T> using Members = folly::PolyMembers<&T::draw>;
};

struct Circle {
  void draw(std::ostream& out) const /* noexcept */ { out << "Cirlce.\n"; }
};

using Drawable = folly::Poly<IDrawable>;

int main() {
  Drawable obj = Circle{};
  obj.draw(std::cout);
}
```

Uncommenting any `noexcept` breaks on my machine (using clang from 2017-11-25 and folly from 2017-12-25)

I attached the error message for uncommenting `Circle::draw`'s  `noexcept` specifier.

[error.log](https://github.com/facebook/folly/files/1639659/error.log)

**Comment by cstratopoulos** [comment]
Seems highly unlikely that you're still wondering about this since it's been well over a year, but for anyone else who might stumble on this, the fix is relatively simple:
https://github.com/cstratopoulos/folly/commit/306965b7255e581074a3b0c8a3bcacfc438e0c7b

**Comment by maikel** [comment]
Thank you, this is still helpful. I might reconsider this library in the future.
