### ISSUE TITLE
cmake module for gflags on fc27

### ISSUE THREAD

**Issue by dotnwat** [facebook/folly#753]
on fedora 27 folly cmake build doesn't find the installed version of `gflags-devel` because the install cmake module doesn't create a target called `gflags`, but rather `gflags-shared`.

```diff
diff --git a/CMake/folly-deps.cmake b/CMake/folly-deps.cmake
index 0e687b98..70346531 100755
--- a/CMake/folly-deps.cmake
+++ b/CMake/folly-deps.cmake
@@ -26,7 +26,7 @@ find_package(gflags CONFIG QUIET)
 if (gflags_FOUND)
   message(STATUS "Found gflags from package config")
   set(FOLLY_HAVE_LIBGFLAGS ON)
-  set(FOLLY_SHINY_DEPENDENCIES ${FOLLY_SHINY_DEPENDENCIES} gflags)
+  set(FOLLY_SHINY_DEPENDENCIES ${FOLLY_SHINY_DEPENDENCIES} gflags-shared)
   list(APPEND CMAKE_REQUIRED_LIBRARIES ${GFLAGS_LIBRARIES})
   list(APPEND CMAKE_REQUIRED_INCLUDES ${GFLAGS_INCLUDE_DIR})
 else()
```

**Comment by JoeLoser** [comment]
Perhaps it would make more sense to have a CMake `option` on a per-third-party-lib basis (where appropriate, e.g. not for header-only libs), which would tell the associated `FIND_LIBRARY` call to look for static or dynamic libs?

**Comment by kornrunner** [comment]
I believe this is now sorted via #789 ?

**Comment by yfeldblum** [comment]
Closing this issue because it is too old.
