### ISSUE TITLE
Bits.h in MSVC

### ISSUE THREAD

**Issue by ichenq** [facebook/folly#76]
It seems the effort to port Bits.h to MSVC have a little bit problem:
__builtin_ffs(x) won't return 0 when x is not 0, but _BitScanForward(index, mask) can load index to zero when mask's LSB is 1.

I make this:
`````````````````````cpp
#ifdef _MSC_VER
    unsigned long index;
    return (_BitScanForward(&index, x) ? index + 1 : 0);
#else
    return __builtin_ffs(x);
#endif
````````````````````

**Comment by facebook-github-bot-5** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by facebook-github-bot-2** [comment]
Thank you for your patience. After 30 days with no updates from the core team, we're closing out the issue. If you're still experiencing the problem described, please reopen the issue - thanks!
