### ISSUE TITLE
Requirement of atomic to be trivial is not standard-compliant

### ISSUE THREAD

**Issue by Swiftkill** [facebook/folly#771]
https://github.com/facebook/folly/blob/8635022f0c4005dc218dd74cdee768126c954763/folly/experimental/hazptr/hazptr-impl.h#L316-L318

This is not legal anymore because atomics aren't trivial by standard. g++\clang still bear  that as  defect though.
Relevant defect:
http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#1734

**Comment by yfeldblum** [comment]
Somewhat fixed in a47a5531edcb95a27f987e810272ba94a9b51162.
