### ISSUE TITLE
[Feature Request] Automake build script

### ISSUE THREAD

**Issue by ecarew** [facebook/folly#777]
Since this is essentially meant to be compiled on a modern Linux flavor, like Ubuntu 16.04, it sure would be nice to have an Automake style compile script. The cmake script might be cool for dependencies, but debugging it when it breaks is definitely less user friendly. For an example, see results from my 16.04 cmake run.

**Comment by suspend0** [comment]
There is folly/folly/Makefile.am and folly/folly/configure.ac (one directory below folly/CMakeLists.txt)

are these what you are looking for?

**Comment by yfeldblum** [comment]
I think we want to minimize the number of build systems involved. Given that folly and multiple other projects are using cmake, I think we want to keep it limited to that.
