### ISSUE TITLE
Compile failed!

### ISSUE THREAD

**Issue by wumuzi520** [facebook/folly#787]
folly/portability/Time.cpp:276:2: 错误：#error No clock_gettime(3) compatibility wrapper available for this platform

centos 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Moonant** [comment]
I have same error, what 's the solution?

**Comment by daniel-lucio** [comment]
For CentOS, check #929

**Comment by yanke1311** [comment]
> folly/portability/Time.cpp:276:2: 错误：#error No clock_gettime(3) compatibility wrapper available for this platform
> 
> centos 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

I faced the same error, if you have had the solution?
