### ISSUE TITLE
[CMake] FindDwarf.cmake assumes a certain directory structure for finding dwarf.h

### ISSUE THREAD

**Issue by JoeLoser** [facebook/folly#788]
It seems `FindDwarf.cmake` assumes it will find `dwarf.h` in a subdirectory from `libdwarf`. Is there a particular reason why this is the case, or can it just search for `dwarf.h` and it need not necessarily be in the subdirectory of `libdwarf`? The reason I ask is that, if you install `dwarfutils` via Homebrew, your directory structure will look something like:

```
├── [Feb 24 18:15]  INSTALL_RECEIPT.json
├── [Jan 29 17:01]  NEWS
├── [Feb 24 18:15]  README
├── [Jan 29 17:01]  README.md
├── [Jan 29 17:01]  bin
│   └── [Jan 29 17:01]  dwarfdump
├── [Jan 29 17:01]  include
│   ├── [Jan 29 17:01]  dwarf.h
│   └── [Jan 29 17:01]  libdwarf.h
├── [Jan 29 17:01]  lib
│   └── [Jan 29 17:01]  libdwarf.a
└── [Jan 29 17:01]  share
    └── [Jan 29 17:01]  man
        └── [Jan 29 17:01]  man1
            └── [Jan 29 17:01]  dwarfdump.1
```

So, in this case, it is just in the `include` directory. I noticed `FindLibiberty.cmake` was written with a similar intent in mind. Moreover, `folly-deps.cmake` has this forced subdirectory as well, whereas I believe it does not need to.

Any insights @simpkins that I might be missing or harm in changing them to not impose a subdirectory?

**Comment by yfeldblum** [comment]
I don't see the harm in making this build step a little more generic, if possible. Want to submit a change?

**Comment by JoeLoser** [comment]
Yep, will do it tonight
