### ISSUE TITLE
c++: error: unrecognized command line option '-std=gnu++14'

### ISSUE THREAD

**Issue by ineslyl** [facebook/folly#797]
Hello, i got those problems when i run this line :  "make -j $(nproc)" . The version of GCC is 4.8.4.

c++: error: unrecognized command line option '-std=gnu++14'
make[2]: *** [CMakeFiles/folly_base.dir/folly/Executor.cpp.o] Error 1
make[2]: *** [CMakeFiles/folly_base.dir/folly/Expected.cpp.o] Error 1
make[2]: *** [CMakeFiles/folly_base.dir/folly/File.cpp.o] Error 1
ake[2]: *** [CMakeFiles/folly_base.dir/folly/Format.cpp.o] Error 1
make[2]: *** [CMakeFiles/folly_base.dir/folly/FormatArg.cpp.o] Error 1
......

**Comment by yfeldblum** [comment]
Since Folly uses modern language and library features, GCC 4.8 is no longer supported.

GCC 4.9 currently works, but only as long as select internal projects require.

Best to use GCC 5+.

**Comment by ineslyl** [comment]
@yfeldblum thx i'm going to try to update gcc.
