### ISSUE TITLE
Trouble on Ubuntu 16.04

### ISSUE THREAD

**Issue by EmpireofKings** [facebook/folly#816]
Hello all , i am currently experiencing an error while trying to install folly on ubuntu 16.04. I have downloaded all of the dependencies. I

``/bin/sh ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I./.. -pthread -I/usr/include    -std=gnu++1y -g -O2 -MT String.lo -MD -MP -MF $depbase.Tpo -c -o String.lo String.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++1y -g -O2 -MT String.lo -MD -MP -MF .deps/String.Tpo -c String.cpp  -fPIC -DPIC -o .libs/String.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++1y -g -O2 -MT String.lo -MD -MP -MF .deps/String.Tpo -c String.cpp -o String.o >/dev/null 2>&1
depbase=`echo Unicode.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I./.. -pthread -I/usr/include    -std=gnu++1y -g -O2 -MT Unicode.lo -MD -MP -MF $depbase.Tpo -c -o Unicode.lo Unicode.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++1y -g -O2 -MT Unicode.lo -MD -MP -MF .deps/Unicode.Tpo -c Unicode.cpp  -fPIC -DPIC -o .libs/Unicode.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++1y -g -O2 -MT Unicode.lo -MD -MP -MF .deps/Unicode.Tpo -c Unicode.cpp -o Unicode.o >/dev/null 2>&1
/bin/sh ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I./.. -pthread -I/usr/include   -msse4.2 -std=gnu++1y -g -O2 -MT detail/libfollybasesse42_la-RangeSse42.lo -MD -MP -MF detail/.deps/libfollybasesse42_la-RangeSse42.Tpo -c -o detail/libfollybasesse42_la-RangeSse42.lo `test -f 'detail/RangeSse42.cpp' || echo './'`detail/RangeSse42.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -msse4.2 -std=gnu++1y -g -O2 -MT detail/libfollybasesse42_la-RangeSse42.lo -MD -MP -MF detail/.deps/libfollybasesse42_la-RangeSse42.Tpo -c detail/RangeSse42.cpp  -fPIC -DPIC -o detail/.libs/libfollybasesse42_la-RangeSse42.o
g++: error: unrecognized command line option ‘-msse4.2’
Makefile:1714: recipe for target 'detail/libfollybasesse42_la-RangeSse42.lo' failed
make[2]: *** [detail/libfollybasesse42_la-RangeSse42.lo] Error 1
make[2]: Leaving directory '/media/nvidia/Astro/lucida/tools/fbthrift/thrift/build/deps/folly/folly'
Makefile:1798: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/media/nvidia/Astro/lucida/tools/fbthrift/thrift/build/deps/folly/folly'
Makefile:1089: recipe for target 'all' failed
make: *** [all] Error 2
``

**Comment by jack17529** [comment]
@EmpireofKings  don't worry we will do something.

**Comment by Orvid** [comment]
What architecture and version of GCC are you trying to use?

**Comment by EmpireofKings** [comment]
Hello friends,
I am using a Nvidia Jetson Tx2, the jetson uses an ARM64 cpu and it was this that was the cause of the error. To solve the error I had to delete the `libfollybasesse42_la_CXXFLAGS = -msse4.2` flag from the makefile and from the instructions.h .

**Comment by yfeldblum** [comment]
Closing this issue because it is too old, and because Ubuntu 16.04 is no longer a target platform.
