### ISSUE TITLE
Singleton requested before registrationComplete() call

### ISSUE THREAD

**Issue by alexliyu7352** [facebook/folly#822]
F0418 05:40:30.485599 18975 Singleton.cpp:149] Singleton 18MyExpensiveService/N12_GLOBAL__N_110PrivateTagE requested before registrationComplete() call.
This usually means that either main() never called folly::init, or singleton was requested before main() (which is not allowed).
*** Check failure stack trace: ***

the test code is 
a.h
class MyExpensiveService {
//   ....
public:
    //   // Caution - may return a null ptr during startup and shutdown.
       static std::shared_ptr<MyExpensiveService> getInstance();
};
a.cpp
 namespace { struct PrivateTag {}; }
  static folly::Singleton<MyExpensiveService, PrivateTag> the_singleton;
  std::shared_ptr<MyExpensiveService> MyExpensiveService::getInstance() {
   return the_singleton.try_get();
 }

int main()
{
auto instance = MyExpensiveService::getInstance();
}

**Comment by yfeldblum** [comment]
The error message explains what is wrong with the example.

**Comment by alexliyu7352** [comment]
But how to use this?could you give me a right one?

**Comment by yfeldblum** [comment]
"This usually means that either main() never called folly::init"
