### ISSUE TITLE
complile "proxygen"(master version) get DSO error

### ISSUE THREAD

**Issue by loveleon** [facebook/folly#825]
compile environment information: ubuntu16.04 64bit gcc-5.4 
when i run proxygen deps.sh to compile proxygen.
i got an error:
libtool: link: ranlib .libs/libqcram.a
libtool: link: rm -fr .libs/libqcram.lax
libtool: link: ( cd ".libs" && rm -f "libqcram.la" && ln -s "../libqcram.la" "libqcram.la" )
/bin/bash ../../libtool  --tag=CXX   --mode=link g++ -std=gnu++14  -pthread -DLIBMC_FBTRACE_DISABLE  -Wno-missing-field-initializers -Wno-deprecated -O3 -g -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -g -O2   -o CompressionSimulator codec/compress/test/HTTPArchive.o codec/compress/experimental/simulator/Main.o codec/compress/experimental/simulator/CompressionSimulator.o libqpack.la libqcram.la libproxygenhttp.la ../services/libproxygenservices.la -liberty -lwangle -lfolly -lz -lssl -lcrypto -levent -lgflags -lglog  -L/usr/lib64 -lpthread -pthread -lfolly -lglog -ldouble-conversion -lboost_system -lboost_thread
libtool: link: g++ -std=gnu++14 -pthread -DLIBMC_FBTRACE_DISABLE -Wno-missing-field-initializers -Wno-deprecated -O3 -g -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -g -O2 -o CompressionSimulator codec/compress/test/HTTPArchive.o codec/compress/experimental/simulator/Main.o codec/compress/experimental/simulator/CompressionSimulator.o -pthread  ./.libs/libqpack.a -L/usr/lib64 ./.libs/libqcram.a ./.libs/libproxygenhttp.a ../services/.libs/libproxygenservices.a -liberty -lwangle -lz -lssl -lcrypto -levent -lgflags -lpthread -lfolly -lglog -ldouble-conversion -lboost_system -lboost_thread -pthread
/usr/bin/ld: //usr/local/lib/libfolly.a(CacheLocality.cpp.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:916: recipe for target 'CompressionSimulator' failed
make[5]: *** [CompressionSimulator] Error 1
make[5]: Leaving directory '/home/cxh/CLionProjects/proxygen/proxygen/lib/http'
Makefile:1144: recipe for target 'all-recursive' failed
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory '/home/cxh/CLionProjects/proxygen/proxygen/lib/http'
Makefile:661: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/home/cxh/CLionProjects/proxygen/proxygen/lib/http'
Makefile:512: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/cxh/CLionProjects/proxygen/proxygen/lib'
Makefile:418: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/cxh/CLionProjects/proxygen/proxygen'
Makefile:350: recipe for target 'all' failed
make: *** [all] Error 2

i decide to add -ldl LDFLAGS in somewhere CMakeLists.txt to deal with the issues.
But i couldn't known how to add it .
So everyone can help me,give some ideas,thanks very much.

**Comment by loveleon** [comment]
@nguyenxuantuong could you give me some help.TKS

**Comment by Orvid** [comment]
This is an issue with Proxygen not passing the appropriate libraries to link against, not Folly. Please file a bug against them instead. 
https://github.com/facebook/proxygen
