### ISSUE TITLE
It seems the performance of AsyncSocket is less than libevent or boost::asio?

### ISSUE THREAD

**Issue by alexliyu7352** [facebook/folly#828]
In my other issues https://github.com/facebook/wangle/issues/129
I found the performance less than other async IO LIb.so, I think it is the issues of wangle.
But I did some test that only use the folly asyncsocket and eventbase, it still less than other lib.
so, why? and what should I do to Improve performance?
In my mind, folly AsyncSocket will better than other lib, because It has lockfree queue and zerocopy IObuf,
but why in the fact benchmark it seems bad?

**Comment by diptanu** [comment]
@alexliyu7352 Can you provide some details about your benchmark, how to reproduce it, numbers, etc?
