### ISSUE TITLE
Vtable emitted in every translation unit for {Exception, ExceptionWrapper, Optional, Expected, and Conv} 

### ISSUE THREAD

**Issue by JoeLoser** [facebook/folly#834]
Compiling with `clang++` with `-Weverything` leads to a warning worth bringing up: `-Wweak-vtables`. I recommend reading this [StackOverflow post](https://stackoverflow.com/questions/23746941/what-is-the-meaning-of-clangs-wweak-vtables?noredirect=1&lq=1) for an overview of the warning and why to care.

Essentially, without at least one out-of-line virtual method in a class, the compiler will copy the vtable for every TU which includes the header in which that class is defined in, leading to bigger object files, longer link times, and possible perf left on the table.

In [LLVM's coding standards](https://llvm.org/docs/CodingStandards.html#provide-a-virtual-method-anchor-for-classes-in-headers), they recommend as part of their best practices to always pin the class vtable to a given object file.  I'll give an example solution below.

**Problem Example**
```c++
class FOLLY_EXPORT OptionalEmptyException : public std::runtime_error {
 public:
  OptionalEmptyException()
      : std::runtime_error("Empty Optional cannot be unwrapped") {}
};
```

**Proposed Solution**
```c++
// Expected.h
class FOLLY_EXPORT BadExpectedAccess : public std::logic_error {
 public:
  BadExpectedAccess() : std::logic_error("bad Expected access") {}
  virtual void anchor();
};

// in Expected.cpp
void BadExpectedAccess::anchor()  {}
```

Is this worth fixing? One tricky part is how some header-only pieces such as `Optional` would not be header-only then, which I suspect is worrisome.

**Comment by yfeldblum** [comment]
What is the effect size in practice?

**Comment by urnathan** [comment]
The multiple vtables are all comdat -- i.e. all-but-one are removed at the static link step.
You're also not saving [much] compile time -- the compiler has to figure out the vtable layout whether it emits the vtable or not.
