### ISSUE TITLE
Build fail using ubuntu 14.04

### ISSUE THREAD

**Issue by yuneeclianghu** [facebook/folly#839]
folly/folly/executors/ThreadPoolExecutor.cpp:31:13: error: expected constructor, destructor, or type conversion before '(' token
 DEFINE_int64(
           ^
folly/folly/executors/ThreadPoolExecutor.cpp: In constructor 'folly::ThreadPoolExecutor::ThreadPoolExecutor(size_t, size_t, std::shared_ptr<folly::ThreadFactory>, bool)':
folly/folly/executors/ThreadPoolExecutor.cpp:43:22: error: 'FLAGS_threadtimeout_ms' was not declared in this scope
       threadTimeout_(FLAGS_threadtimeout_ms) {
                      ^
folly/folly/executors/CPUThreadPoolExecutor.cpp:20:12: error: expected constructor, destructor, or type conversion before '(' token
 DEFINE_bool(
            ^
folly/folly/executors/CPUThreadPoolExecutor.cpp: In constructor 'folly::CPUThreadPoolExecutor::CPUThreadPoolExecutor(size_t, std::unique_ptr<folly::BlockingQueue<folly::CPUThreadPoolExecutor::CPUTask> >, std::shared_ptr<folly::ThreadFactory>)':
folly/folly/executors/CPUThreadPoolExecutor.cpp:35:11: error: 'FLAGS_dynamic_cputhreadpoolexecutor' was not declared in this scope
           FLAGS_dynamic_cputhreadpoolexecutor ? 0 : numThreads,
           ^
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[  3%] Building CXX object CMakeFiles/folly_base.dir/folly/synchronization/ParkingLot.cpp.o
[  3%] Building CXX object CMakeFiles/folly_base.dir/folly/synchronization/AsymmetricMemoryBarrier.cpp.o
At global scope:
cc1plus: error: unrecognized command line option '-Wno-inconsistent-missing-override' [-Werror]

**Comment by sillyousu** [comment]
I have the same problem on `Centos 7` + `GCC 7.x` tool chain.
I work around this by including`gflags` head file to `ThreadPoolExecutor.h`.
```
diff --git a/folly/executors/ThreadPoolExecutor.h b/folly/executors/ThreadPoolExecutor.h
index 1c32ebf..6437ec8 100644
--- a/folly/executors/ThreadPoolExecutor.h
+++ b/folly/executors/ThreadPoolExecutor.h
@@ -28,6 +28,7 @@
 #include <queue>

 #include <glog/logging.h>
+#include <gflags/gflags.h>

 namespace folly {
```

**Comment by sillyousu** [comment]
@djwatson add dynamic_cputhreadpoolexecutor flag in https://github.com/facebook/folly/commit/68a6b5b55b177ae5d9c60a65f9e79f3eb57d10af#diff-51c662965fede0aafdf676a9abe63da4R20 . Do you have any idea?

**Comment by djwatson** [comment]
Right, usually missing gflag include

**Comment by sillyousu** [comment]
Now `gflag` head file  is provided by `glog`  obliquely.
But not all `glog` is compiled with `gflag` feature.

@djwatson ,  I think we should include `gflag` explicitly. thoughs?

**Comment by daniel-lucio** [comment]
For CentOS, check #929
