### ISSUE TITLE
Seems like a BUG in folly::synchronization::ParkingLot::Bucket

### ISSUE THREAD

**Issue by SimonCqk** [facebook/folly#841]
Hey team,
I'm reading some code segaments while I may find a bug in `folly::synchronization::ParkingLot::Bucket`.
Inside the struct `Bucket`, there maintains a var named `count_` which means size of Bucket, I guess, and in the last of  `::erase()`:

> https://github.com/facebook/folly/blob/master/folly/synchronization/ParkingLot.h#L122

`count_.fetch_sub(1)` is done, but in `::push_back()`:

> https://github.com/facebook/folly/blob/master/folly/synchronization/ParkingLot.h#L87

there is no corresponding op like `count_.fetch_add(1)`, which really confused me.

**Comment by yfeldblum** [comment]
The `fetch_add` is in `park_until`.
