### ISSUE TITLE
folly future/promise

### ISSUE THREAD

**Issue by kreuzerkrieg** [facebook/folly#844]
Hi,
Quick question. I saw that folly implements `then` continuation on `folly::Expected`, but I cant find anything like `when_all`/`when_any`. Is there something similar in folly library?
Sincerely,
E

**Comment by suspend0** [comment]
Does `collectAll(....).then(x)` meet your use case?  The collectAll/collectAny versions that take iterator pairs return futures.  You can find them defined in `folly/futures/helpers.h`

**Comment by kreuzerkrieg** [comment]
Yay! Sounds like just what the doctor ordered. Thanks!

**Comment by yfeldblum** [comment]
We do not currently have combinators for `Expected` the way we do for `Future`.
