### ISSUE TITLE
build failed on vs2017  15.7.1 

### ISSUE THREAD

**Issue by wangniancai** [facebook/folly#845]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2244	'folly::futures::detail::FutureBase<T>::FutureBase': unable to match function definition to an existing declaration (compiling source file C:\Workspace\vcpkg\buildtrees\folly\src\8.04.23.00-6f3066549d\folly\experimental\observer\detail\ObserverManager.cpp)	folly_base	c:\workspace\vcpkg\buildtrees\folly\src\8.04.23.00-6f3066549d\folly\futures\future-inl.h	160	

same version work well on vs 2015 update3

**Comment by Orvid** [comment]
This is being tracked upstream as an MSVC bug: https://developercommunity.visualstudio.com/content/problem/246602/157-fails-with-folly.html

I have a diff up internally to work around the issue for now, which will hopefully land in the next few days.

**Comment by Orvid** [comment]
https://github.com/facebook/folly/commit/8521e599c7bf974c77bfc52ab1190eb5f8e540e3 has landed that should work around this issue.

**Comment by wangniancai** [comment]
Future-inl.h(322): error C2903: 'get': symbol is neither a class template nor a function template 
workaroud still have some errors
