### ISSUE TITLE
getting error while configuring folly

### ISSUE THREAD

**Issue by krustagi** [facebook/folly#847]
Hi,

I am running below command to configure folly on linux based environment. 
cmake configure .

**_I am getting below error:
CMake Error at CMakeLists.txt:6 (apply_folly_compile_options_to_target):
  Unknown CMake command "apply_folly_compile_options_to_target"._**

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.6)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/home/krastogi/git/folly/folly/CMakeFiles/CMakeOutput.log".

Please help me in resolving this error.

**Comment by Orvid** [comment]
This is the result of running CMake from `folly/`. Run CMake in the root of the repo instead.

**Comment by krustagi** [comment]
Tried same but same issue.

**Comment by sungwonida** [comment]
> This is the result of running CMake from `folly/`. Run CMake in the root of the repo instead.

That was my case. The issue has been solved. Thanks!
