### ISSUE TITLE
how to use fbstring without changing application code

### ISSUE THREAD

**Issue by wankai** [facebook/folly#853]
hi, I want to use fbstring to improve performance of our services.
because we have thousands of services, so I don't want to change code.

Could any one teach me the right way to accomplish this task ? 
thx

**Comment by ly82882592** [comment]
hi,wankai
have solve this issue , I can`t find this head file "basic_fbstring_malloc.h"
Could yout teach me ?

**Comment by wankai** [comment]
@ly82882592 finally，I use gcc7.3 instead, which has SSO string.

**Comment by yfeldblum** [comment]
libstdc++ as far back as (IIRC) gcc 5.1 has SSO strings. Upgrading to that version or higher of the standard library is probably the right approach for most applications that want SSO strings.

Aside from that, `basic_fbstring_malloc.h` has to be created from `folly/Malloc.h` when used to replace the std lib `<string>` header. There might be more requirements like this.

**Comment by wankai** [comment]
@yfeldblum 
I try hard to replace std::string with fbstring, but failed finally.
It would be very appreciate if  you could write a guide about how to do this.
I find many people encounter this problem, and no body find way out.
