### ISSUE TITLE
unable to install folly on ubuntu 16.04 LTS : undefined reference to folly::initLoggingOrDie(folly::Range<char const*>)' 

### ISSUE THREAD

**Issue by Basha-90** [facebook/folly#855]
I am trying to install  `fblualib`  and it dependencies using `install_all.sh` script from https://github.com/facebookarchive/fblualib/blob/master/INSTALL.md  but I encounter the following problem

`[ 34%] Linking CXX static library lib/libwangle.a`
`[ 34%] Built target wangle`
`Scanning dependencies of target gtest`
`[ 36%] Creating directories for 'gtest'`
`[ 37%] Performing download step (git clone) for 'gtest'`
`-- gtest download command succeeded.  See also /tmp/fblualib-build.0JrC4C/wangle/wangle/gtest/src/gtest-stamp/gtest-download-*.log`
`[ 38%] No patch step for 'gtest'`
`[ 39%] Performing update step for 'gtest'
-- gtest update command succeeded.  See also /tmp/fblualib-build.0JrC4C/wangle/wangle/gtest/src/gtest-stamp/gtest-update-*.log`
`[ 40%] Performing configure step for 'gtest'
-- gtest configure command succeeded.  See also /tmp/fblualib-build.0JrC4C/wangle/wangle/gtest/src/gtest-stamp/gtest-configure-*.log`
`[ 41%] Performing build step for 'gtest'
-- gtest build command succeeded.  See also /tmp/fblualib-build.0JrC4C/wangle/wangle/gtest/src/gtest-stamp/gtest-build-*.log`
`[ 43%] No install step for 'gtest'`
`[ 44%] Completed 'gtest'`
`[ 44%] Built target gtest`
`Scanning dependencies of target ObservingHandlerTest`
`[ 45%] Building CXX object CMakeFiles/ObservingHandlerTest.dir/channel/broadcast/test/ObservingHandlerTest.cpp.o`
`[ 46%] Building CXX object CMakeFiles/ObservingHandlerTest.dir/test/TestMain.cpp.o`
`[ 47%] Linking CXX executable bin/ObservingHandlerTest`

` `
`/usr/local/lib/libfolly.so: undefined reference to folly::initLoggingOrDie(folly::Range<char const*>)'`
`collect2: error: ld returned 1 exit status`
`CMakeFiles/ObservingHandlerTest.dir/build.make:140: recipe for target 'bin/ObservingHandlerTest' failed`
`make[2]: *** [bin/ObservingHandlerTest] Error 1`
`CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/ObservingHandlerTest.dir/all' failed`
`make[1]: *** [CMakeFiles/ObservingHandlerTest.dir/all] Error 2`
`Makefile:138: recipe for target 'all' failed`
`make: *** [all] Error 2`

**Comment by kwkwvenusgod** [comment]
Same error and same ubuntu version.

**Comment by wilfredcho** [comment]
same error. any solution yet?

**Comment by 4in2peace** [comment]
One workaround solution: 
install folly manually and comment out the folly installation in this install_all.sh

**Comment by maichm** [comment]
+1

**Comment by danobi** [comment]
I have a fix here:  #872

**Comment by danobi** [comment]
f1e13ac24f3ca43 closes this issue.
