### ISSUE TITLE
support a header only subset of folly

### ISSUE THREAD

**Issue by delaitre** [facebook/folly#856]
Hi,

I would really like to use part of folly which seems to be header only (e.g. `folly::Function`) but I can't becaue the build system requires all the dependencies to be installed in order for cmake configure to work.

Would it be possible to have a `FOLLY_HEADER_ONLY` CMake variable or similar that would just provide a `folly` CMake target setup to use folly as a header only lib? That would skip the dependency searching and would not build anything.

**Comment by yfeldblum** [comment]
There is no subset of folly which is promised to be header-only. Anything which currently happens to be header-only can start to involve source files at any time.

I know that header-only libraries have certain advantages, but they also have disadvantages. In the case of folly and for Meta's usage, the disadvantages outweigh.
