### ISSUE TITLE
gcc version dependency and release mapping ( gcc version 4.85)

### ISSUE THREAD

**Issue by goldstar111** [facebook/folly#858]
Is there a place where you show which version of folly depends on which version of gcc? I had one before and I git pulled and it does not work anymore. Thx!.

**Comment by goldstar111** [comment]
Anyway by trial and error I just found out that the last release version of folly that compiles with gcc version 4.8.5 is **v2017.03.27.00** . At some point someone should provide some mapping.

**Comment by yfeldblum** [comment]
Current Folly works with gcc >= 5.
