### ISSUE TITLE
Build failure on OS X Mavericks due to '-finput-charset=UTF-8'

### ISSUE THREAD

**Issue by ryandesign** [facebook/folly#865]
Building folly 2018.05.28.00 fails on OS X Mavericks (10.9):

    clang: error: unknown argument: '-finput-charset=UTF-8'

The version of clang is 600.0.57, as provided by Xcode 6.2, which is the last version of Xcode that is compatible with Mavericks.

**Comment by Orvid** [comment]
We don't support building Folly on anything earlier than OSX 10.11 and don't actively test anything prior to OSX 10.13 or XCode 9.4.

**Comment by xmnlab** [comment]
thanks!
