### ISSUE TITLE
unable to install folly ubuntu 

### ISSUE THREAD

**Issue by csinfo** [facebook/folly#868]
just run make

[ 92%] Built target folly_base
[ 92%] Linking CXX executable GenerateFingerprintTables
CMakeFiles/folly_base.dir/folly/compression/Zstd.cpp.o: In function `folly::io::zstd::(anonymous namespace)::ZSTDStreamCodec::resetCCtx()':
/root/folly/folly/compression/Zstd.cpp:163: undefined reference to `ZSTD_CCtx_setParametersUsingCCtxParams'
CMakeFiles/folly_base.dir/folly/compression/Zstd.cpp.o: In function `folly::io::zstd::(anonymous namespace)::ZSTDStreamCodec::resetDCtx()':
/root/folly/folly/compression/Zstd.cpp:203: undefined reference to `ZSTD_DCtx_reset'
/root/folly/folly/compression/Zstd.cpp:205: undefined reference to `ZSTD_DCtx_setMaxWindowSize'
CMakeFiles/folly_base.dir/folly/compression/Zstd.cpp.o: In function `folly::io::zstd::(anonymous namespace)::ZSTDStreamCodec::doUncompressStream(folly::Range<unsigned char const*>&, folly::Range<unsigned char*>&, folly::io::StreamCodec::FlushOp)':
/root/folly/folly/compression/Zstd.cpp:225: undefined reference to `ZSTD_decompress_generic'
CMakeFiles/folly_base.dir/folly/compression/Zstd.cpp.o: In function `folly::io::zstd::Options::Options(int)':
/root/folly/folly/compression/Zstd.cpp:231: undefined reference to `ZSTD_createCCtxParams'
/root/folly/folly/compression/Zstd.cpp:236: undefined reference to `ZSTD_CCtxParams_init'
CMakeFiles/folly_base.dir/folly/compression/Zstd.cpp.o: In function `folly::io::zstd::Options::set(ZSTD_cParameter, unsigned int)':
/root/folly/folly/compression/Zstd.cpp:244: undefined reference to `ZSTD_CCtxParam_setParameter'
CMakeFiles/folly_base.dir/folly/compression/Zstd.cpp.o: In function `folly::io::zstd::Options::freeCCtxParams(ZSTD_CCtx_params_s*)':
/root/folly/folly/compression/Zstd.cpp:248: undefined reference to `ZSTD_freeCCtxParams'
collect2: error: ld returned 1 exit status
CMakeFiles/GenerateFingerprintTables.dir/build.make:516: recipe for target 'GenerateFingerprintTables' failed
make[2]: *** [GenerateFingerprintTables] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/GenerateFingerprintTables.dir/all' failed
make[1]: *** [CMakeFiles/GenerateFingerprintTables.dir/all] Error 2
Makefile:129: recipe for target 'all' failed

**Comment by chriddi** [comment]
I solved this by installing libzstd-dev and using a release version from https://github.com/facebook/folly/releases
Maybe it helps...

**Comment by yfeldblum** [comment]
@terrelln

**Comment by terrelln** [comment]
@csinfo it looks like the build found a version of the zstd headers >= `zstd-1.3.2` (since `Zstd.cpp` built), but ended up linking against an older version of zstd.

As @chriddi suggested, `libzstd-dev` is `zstd-1.3.3`, so it should work.
