### ISSUE TITLE
pkg-config not installed in cmake build

### ISSUE THREAD

**Issue by danobi** [facebook/folly#876]
The autotools build generates and installs a (mostly) correct pkg-config file.
The cmake build does not. This blocks removing autotools as currently
planned, as non-cmake projects would be unable to (easily) link against libfolly.

**Comment by yfeldblum** [comment]
Does c2e51a8e28f7c2ca7c6fb686c5ddf10ccd976871 fix this?

**Comment by danobi** [comment]
Seems like it should. Closing issue for now.
