### ISSUE TITLE
Traits.h marks std::list as trivially relocatable, but in fact it is not

### ISSUE THREAD

**Issue by Quuxplusone** [facebook/folly#889]
Hi folks,

https://github.com/facebook/folly/blob/8fb5c15272a0dcdc/folly/Traits.h#L712 should be removed, as `std::list<T>` is never trivially relocatable on libstdc++ nor libc++. (The last heap-allocated element of the list holds a pointer into the list object itself; `memcpy`ing the list will break this pointer.)

Oh, and similarly, https://github.com/facebook/folly/blob/8fb5c15272a0dcdc/folly/Traits.h#L716 is wrong for at least libc++; I'm not sure about libstdc++.

Also, hi, this is Arthur O'Dwyer. I've got a WG21 proposal to standardize the Folly/EASTL/BSL notion of "trivially relocatable" into C++2a. I have wording and an implementation and everything. I am looking for coauthors, particularly coauthors who have been involved with the prior art in Folly. If you'd like to contribute and/or lend your support to [P1144 Object relocation in terms of move plus destroy](https://quuxplusone.github.io/blog/2018/07/18/announcing-trivially-relocatable/), please shoot me an email!

**Comment by Quuxplusone** [comment]
(See also: #35, #316, #498.)

**Comment by nbronson** [comment]
Hi Quuxplusone,

Can you give us more information about how you reached your conclusion for std::list? The heap allocated nodes form a circular list; there is no pointer back to the list object itself. When the list has one element, for example, it points to itself. This is true in both libstdc++ and libc++.

I don't know about std::function.

Thanks,
  Nathan

**Comment by Quuxplusone** [comment]
Hi Nathan,

Right, the "circular" part of "circular list" is what causes the trouble.

Contrast these two diagrams from [P0773R0](http://open-std.org/JTC1/SC22/WG21/docs/papers/2017/p0773r0.html#B):

![](https://quuxplusone.github.io/draft/fancy-pointers.list.png)
![](https://quuxplusone.github.io/draft/fancy-pointers.fwdlist.png)

The trick with `std::list` (and `std::map` and `std::set`, which were dealt with in #35) is that the heap-allocated nodes contain both forward ("next") and backward ("prev") pointers. The "prev" pointer of the first node, and the "next" pointer of the last node, both point to the node that is stored within the stack-allocated object itself. Quoting from P1144R0 draft revision 10:

> `std::list` needs somewhere to store its "past-the-end" node, commonly referred to as the "sentinel node," whose `prev` pointer points to the `list`’s last node. If the sentinel node is allocated on the heap, then `std::list` can be trivially relocatable; but if the sentinel node is placed within the `list` object itself (as happens on libc++ and libstdc++), then relocating the `list` object requires fixing up the `list`’s last node’s `next` pointer so that it points to the new sentinel node inside the destination `list` object. This fixup of an arbitrary heap object cannot be simulated by `memcpy`.


You can verify for yourself the memcpyability of `std::forward_list` and `std::vector`, and the non-memcpyability of `std::list` and `std::set`, [like this](https://wandbox.org/permlink/BiEEVcoND9uR4rWJ):

```
template<class Ctr>
void examine()
{
    Ctr a {1, 2, 3};
    alignas(Ctr) char buffer[sizeof(Ctr)];
    Ctr& b = *(Ctr*)buffer;
    
    memcpy(&b, &a, sizeof (Ctr));
    
    printf("Printing the elements of b:\n");
    for (auto&& elt : b) {
        printf("  %d\n", elt);
    }
}
```

**Comment by nbronson** [comment]
Thanks for the clarification, I was mistaken.

**Comment by Quuxplusone** [comment]
@nbronson: I've got a relatively exhaustive list of "what's trivially relocatable and what's not" for libc++, here: https://github.com/Quuxplusone/libcxx/blob/trivially-relocatable/test/libcxx/type_traits/is_trivially_relocatable.pass.cpp

[(Godbolt)](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAKxAEZSAbAQwDtRkBSAJgCFufSAZ1QBXYskwgA5NwDMeFsgYisAag6yAwqwCeG7BwAMAQTkKlKzOq1NixJntkGTZxcrUbtRALZ5OTo1MueTdLa00AI0JBTAJ9QNcLDy1kBGJUFlR4l2DzdytPNBZ8AjwMgH0AN1s8JgiGTGygkKSCrSwARxFGgJyW/PCAMxIAd1t0coY8QTje5rywz0GRRVKMpgYmxIGlkQIxHud50OTNBUJaqYAvTGJJ6dmj7cWtMsEt3JO2s4JbpiJiB9%2Bi9NFMZkCFqcGKhkBtDglPq1wt4mAAHCFfZGYbwkRxPRE7LTebG48rETDCMQSDFIzzePaYAAeNMJmlQqLWLA2LJBXUw3R5p3sxVQ3kF33sa3F4XJwCZ0s8MUeCOBp0ECFsmAm9N%2BzLmzzVBCYyAA1gqtDNiApgObNJbrVU8JgRrbBDoZtjyrd0oD9QSQQQ0pgmOhbftUQ0wzpUZgFFg9fjVd8CNHMOUCPZoraViQsOTtWjs5liHmteUldnSlMU7bqlbWMq%2BpDvpVMMgAVsTJaRO3VAAVdQAdh4/YgAEoNCO%2BxAijN%2B9wAGwT2QjgB%2B0%2BXI44g4AIpPAt3exwAKx8U8ZvCVS4MHRkzDQ2FG%2BqNY971%2BqABKQ5HH/Hk8/M4ZHOH6Lpuqirr%2BYHbnuK4HhmPYEKoADKACy36qJUqB4OgqgPia5Yavmf4rhhWE4SseEEZq6DEWuqG0UOMF8C4Xbwb2ADS36BKoPH9qoszMcYvGqBEqCoAwqjsn8HayDBO6ASwc7saBqizgJ3G8aJ4mSTGkokJ4qgKUpKlqfuLi7mZxi/N4Eb/D0mj6Koh6ITM6AgCAGrqp4ylOOhgh4Dc6Y6dJJDjkZiHKVwS6qUBAmMZZcH/H4MWKYhWkSX2VpXhsxgsDo1h7k2gxYIMqjlAAMgAkjwmgAAq1eUfYfpVABqlXGOV5UAJrlB%2B2DlQA8poxh9sYPDldg5TGAAcl1Gk8fBPSCXI94xPNqiDBsa2wX0mDFHggwJKxSXIClc7pao02oAQO6YBEIjAAVKoHWVVU1fV5Q7tgPAAKoAOIVdgLX9dYBiyaoXDrZtDDbctwSrY0JjCYtCXw/th0scYMwneUTCCDExAEBArnudM6ZZdet7kg%2B/x1JGWggU47nVMomCkOoXCQ5zm6JaUyC4/jtxE2AYAkyAZMXtlDA3neNNPvTmh9vozMbN07PcFzXA88dfMCwTRNixLFMbDL1MwrTz6eH2ABUysgCzasc5r2tY0aut4/rxMEG54uCOTl6U7L5vy/ZYvkoMtx7RI5QjPYqK6Vb8RM/bqts07Gsu9j7uC4TXs%2B0bAcm1T97B3Tofe6TLAXBsAW3Pc4JaErATJw7acaxnllZ34etC3npN%2B5Lgdm4%2BZeKhXIAm8H%2BmN0n2Aq6z6ucx3O2uzjHu94bA/G9Lxdy6PFrj6i3jEO5qLiToOLEKiCDd5Pj7T4rs/z477fc53bu3znBvjwXUumyXI9LYHx9iVJgIgGAEHKFgBovxE7NzninBe6c34ry7vzdeudN7%2Bz/rvUuQC7Tj08ggMePt7RsCfogl%2BS8UGCTQT3TBP8t6Fx3kHQBCsxYNHxnAsGCDW6L2du/NeX8%2B6%2B2wUPABFt2Hj04e8LQmFsIUL4cgrWgjs6eywYPIurDJHlx9isPAfJygcl9I/eBz827UJUagj%2B6DhEaO3v/Pe%2BCxbqmokYjM3C7ZKNflY2hNj6Hf3zkwnB2iQ4kPciMYM%2BFjGeJbqnfhy8/FCPUYwsRWjh46PCSAVETA8AmI/KQRmPDzEJJobzT%2BnsRb2OYY4vBUifY5LyZ4ApTdimUIsQI6xySN6pM0SwjJYTgHuXDArApYzFHxOUZnfxGDhai16Q43BbDdHDJEBGeyLTCkTKQT46Z3SGFBLSf0iRgyCE%2BzrLUFgsxNBjK2WY9ppTfHlNsZU%2BZhy%2Bm1OWVki5DZmmkD7Hctp3jLF7LUT095izQn7zOe5dknJuQM22VQzpSSwW5yqQsmpSzMlDJAHCsoXJNgz3ucClFzyAkiN/uIpx9T3K6C8anJ64NMrMNyjoR5oKKngv7kcz5OKYUgBpvTXhkzdmqK5QcnlHzsWnLFkyCQHICXuN9CKnZILxUvN7hiiFWKoXOPHvKzAiqMgMrVWSnWEq5nVJCQM6Fcq7AkHKI%2BTAwBcSmuRYk8lszKXBOpXUlZIBvSOrQFgd1HTPUWs1ZK0R0q9W0sDQ6u4RQSgErDRyjVFLrV%2Bq%2Bbi70/hVUerKZGzNmKbUnLtePFMMZyhxnlHEs1EbV5osCVKyFtr9U%2B1sPYRwNz2bHiReGotTbLUQG1a23V7b41docFbPtA701dObT63lMqK0gMwHyWJBbB1POLd6rN6Ty0dvcsMYgYwSz12ua0tNUyM3erHTGttR741givfO29i6R0PqpYemlAaUToi0Oxf576xWfqjVa0t2b%2BVi3pBAvAAHvIgZJaK9V4GKXft9b%2B/1WS4OlArEB0DaHUVfreeOstf6skEc0D5IFqHzXDog8u2Nk6A05hLJHAsgGaPIbo6zJlO5LrXVuvdYAC6SNMYPccyjuL2Olm1OA0oiGgO8bDQJoTN07oPXE16uxUHsM5oFXJzj5Q8PTFiN5Ad6mrqadEzpvdemdUUZw7J4s8nywWcIyh/jGg5IaZE9pj9EmS1Oeg7K8erZ2wP2vfW7o1nhNabE0F3TKTQsGZg%2BPbGpot0lOSw51L5GwtrvcnyAUxK%2BOFt3YxkLhX0vhYaVaEghBbylfsjF7d8XbOBbA8F/d%2BnpMuYFUfE%2BIBOhldMRVndnLJP9b5fV0%2Bx8T2jHGJenLDy8vVfvWRx9E7n0BuG%2B5V9a3SWNroVtqTc3ivZMWyAZTPH2u5Z6ylrV22f0DcM2LA7t3FMIcLCph762nv5Zexd1dx7rsjbM9R2jN6gebeEZhldcb9s3eh0RhjZ3HO1fexlhpN3jP5lM39%2B7VnfO%2Bf84l%2Bz8OCs7ecx9w%2B%2BO3MmbM3d4DAPW6dYC0luHmOadvcu%2BDr7BOyxQ88zR0nslyc2a51T3n3LadFcF4z3MJm0febi2T8G0vKcbbl9G/nYP41fcizJCbanNeCe13Z3XMyscK7q1d6dPaCmqH7cnQgIUVWPeI89/XWGcfzYnnYGdjc53u9%2BHpL3gOffA790j1jWSxttbth7yPsOY/U/lwb5HWTT3nomEd8rpMI//Gntu2Xtu%2Bf%2B4Fy%2Bh43Di%2Be/N5LrXCXrc88r1n6vhv/3E7ZynkvMly82/2S2%2B3Aerss977xhvafYtTbvXb7PCfcWi%2BubRmfpeo8naHXr0fS%2B9tUbF%2Bv8WA%2By/e4xx3uPLGD%2BuZV4T1n0%2BT%2BN7nxXkfzGn0yaM0z%2B/P2H%2BtI34Pufqdpfnvl3jnrfhxj/vBmrggqnpvunhfm/qDuAV/nfmWDAQAWftHogUusgcvqgZASLlPv/oKubAwDWqflvvRsAUgbNt3lksLgpvBn/nbEKhQc/kPu3rQWluPuDowaZj9hgaQbCOQXAYAdgTQbgXQSgWLPwUIWwWIVgdvlVrvu/rtp/mLCbtFv3hweYpzjrlwVITwTXgGuSK2MQDEOwbPmcFcrbOrvPuhn1sYfQbihEMaPhAoPrFYfAbiknp4AoMqPYa/kYdjiYbnukFcjWopELN4abhwnXq8FcrPAgZISOngTfgKp4TEYoSYpoW2KbgEckXPvoW3hnqoekRoYwhmMGN4LEQ/EUikTviAaOq9mAfgZvNUUwLUTkcdtQU0dwaES4QKqgJaDUXUfkujqkTNs4TIePCMZ0d0ZQb0Q2v0SEWPmEbiqkLYOTLkgQLIpoFsSqo0Soc0RUYNmHC6kyDsVmCkIRJMasWkdIe0ePLKHWpwWUacU8RkWLMgCiAQKkE3n5lbt1sRjxAAPRgkiRthgIxCqCECqAiAxCCAYT5EkBwlXK3CEo3i%2B6gHx7fGZZ/EAnFEW4U6lEorgmQkRDQmIlWDwk0nIlaHEDokR5Yl6Cx64nX6VGkIXjkLEnN6W6t4gk4GPEzHPHclWhsCYFUE%2Bb8mklClTE1brFDFiwjBkI2h8lAmCnc4fEDFKmzE%2Byqk8mgBP6z4dYknAnanCnTGDH6kLYja/H/BElmmykWniYUlQmwg0lwmIT0kolRZMkBGYlFw4lqF06452nuSCCEnEIalS5alumqAQkekwm0k%2BlIl%2BkAjMlBk7whlnH0544jZqmAlxldaWkKlOE2likRkgBqlSnFkt6lnBEimVn4kFkRJFmxkNky7D5rH75cnVmGkSnGk9GdkCmNk9nNl6lVniwYnAD2DkFqS/KJEEDswAAskMQRE51pU5rZlc8YHmfIig9k9AXApAsgpAq59xJxupfZ5xLxSUWQWg9AEMV502ipt5%2BZ7kqQERqAkZ7o1kTqeE7k6AYgD5LAxxb5FZO5/ZKAaQGQv5NZ/5noSgMIJowyCGaYZ8hRL%2BW575bRu5NZCxZ8si7xVpeFeJMFUQexYu65r5C%2BVeFFd5PsVF1G65hgdFjhi%2B%2BFMF%2BihieEuGDICYEF9FnejFn5NZhEZY/FWgqEHFvWXFYl4ZIAgY5IIYwlnFDFnJTFwyQYIYpMoYOFhhk5H5SlqI6Qvg20ZuhlOpvZ3F2l2S5l5micUUcluZXxMFZlooTlciZErl7JoZiu8ayw%2Bw5IyxlWkFClWl4lwVBwzlC4flmeV%2BH%2B9lMVoVPlCim5Rl25JlgerihOqVyemVNlxldl4leVZYBVcVCV5R7l9l5VEwlV6VBlk2TZTGiOUVSlywqwqaTVxELVQW7pRQRonhqgWFGJAZVyqATk94GMiVkGopBFOSpoTAcoEwRoggZojcEAfYy4/VPWg1GQw1iko1WE41zJU1MQDAs1qh7VyV4lS1JoK1ZY61m1j8UU21u16lI4iZkJQ1uSx1Y1Ee5101V1IZt16h9lD1T1a1eMr18iNEO1clB1Vy/1yJgNtwwNl1s1YNrRtpE8Pgfg/hSRRVZF52qS05pevg/MgwzA6ppF5ZCOuN05yaFwFQPyQC9NDxbVTNBFLNnIVQNQZcuMeUX1ONWC05lEwAIg4wAluo1VzRiO05OobxQBXNGGPNMFMQ6BG6X1UgY4jA0gx4UgpALA0ghgxtv5UgDkvA/ATkog4gBQwQtAxtBAZtet%2BtaFq5AAnAAHQLgAAc/tC4sgsgUUx4C4XAXthgC4x4BtUgq5xtptUg5tpAltxtggIAhgpArtydetpAcAsASAaANkeADQZAFAgEJdZdKAzAbARitAtAq5q5pAgwpdEeGdEAEQbtpAUQXIxAOg0gztpAxdxIVyA0LAN43dWAKIbADQg9xt%2BA5I7Yl4FI3dTIbYDI895AGJDAW9F43gbt%2Bttd7A/A/AjAeAEQGdkA%2Bt%2BKQE0gAAtANLIKoPfa5L5pwDbbwFwEwC/a5FMBEL5v/R/XwLwOnfbRIHQEfYbYnd3ZbYyEHffQuKuapMfYZEyLpBhSjRJLVA3U3WOIZLgIQGiXIM%2BWyFXRjSQ/g9bSAzwC7YfR7SAMeIYD7bIA3bIAuAuIOLIKubIIOIYF7bHbvfHcbQfbQIYFnUnSnWnUIJndnfQ3HVwDA7nandIHQ7nWOPreYf5BkCAKuUAA%3D%3D)

I'd like to talk more via email and see if we can combine efforts. I'm coming around to the idea that the *primary* benefit of [putting `is_trivially_relocatable` into the C++ Standard](https://quuxplusone.github.io/blog/2018/07/18/announcing-trivially-relocatable/) would be that library vendors are in a better position to judge the relocatability of their types than forcing that burden onto end-users like Folly, and I'm looking for evidence (anecdotal like #35, #316, #498, #889; or perhaps more-than-anecdotal if possible!) to support that general line of attack.

**Comment by yfeldblum** [comment]
I would love to see some common way for library authors to mark their own types as trivially-relocatable. And to see encouragement for types to be trivially-relocatable, and library optimizations for types which are trivially-relocatable.

Q: "trivially" modifies "relocatable" - what does it mean for a type to be relocatable but not trivially-relocatable? (Does a type being relocatable just mean it has both a destructor and a move-or-copy-constructor?)

**Comment by nbronson** [comment]
Could making relocation a first-class entity help with another problem we have, which is how to relocate a std::pair<const A,B> without copying the A (and without relying on a UB const_cast)?

**Comment by Quuxplusone** [comment]
> Q: "trivially" modifies "relocatable" - what does it mean for a type to be relocatable but not trivially-relocatable? (Does a type being relocatable just mean it has both a destructor and a move-or-copy-constructor?)

Yes, that's how my paper defines it. The operation in general is "relocation"; a type that supports relocation is "relocatable"; and if relocation is tantamount to memcpy then it's "trivially relocatable." (And yes that's a bit different from how Folly calls it, but I think it is more consistent with the other C++11 type traits.)

> Could making relocation a first-class entity help with another problem we have, which is how to relocate a `std::pair<const A,B>` without copying the `A` (and without relying on a UB const_cast)?

No, not as my paper defines it (because I don't really define it as a first-class entity). I'm not sure that we *ought* to be able to "relocate out of" `const`-qualified objects... I discuss this briefly in my blog post [here](https://quuxplusone.github.io/blog/2018/07/06/thoughts-on-sanely-move-assignable/#notice-that-if-is_trivially_swap) in the context of `swap`: `swap` can be implemented in terms of relocate, instead of assignment. Does that mean we should be able to swap unassignable objects? I think not.  Stealing-the-guts-out-of a `const` object, even as part of a relocate operation, seems *kind* of analogous, at least.
