### ISSUE TITLE
Traits.h produces error from FOLLY_ASSUME_FBVECTOR_COMPATIBLE_*

### ISSUE THREAD

**Issue by mtanski** [facebook/folly#89]
It seams like if another library is included before folly/Traits.h (which gets included from all over folly) that has any kind of use of boost::has_nothrow_constructor on basic types (std::shared_ptr, boost::shared_ptr, others) the folly FOLLY_ASSUME_FBVECTOR_COMPATIBLE_* macros end up producing errors.

**More detail**:
It seams like if there is a use templated use of a std::shared_ptr or that depends on not fully defined type (see bellow with External) then folly will blow up. In my case I have an external library that uses std::shared_ptr<SomeType> and it hides SomeType due to the [PIMPL idiom](http://en.wikipedia.org/wiki/Opaque_pointer).

Reduced test case:
```c++
#include <string>
#include <memory>

// Some other header would do this

#include <boost/type_traits.hpp>

struct External;

template <typename T>
class Check : public  boost::has_nothrow_constructor<T>
{ };

static_assert(Check<std::shared_ptr<External>>::value, "txt");

// Then we include folly

#include <folly/Traits.h>

int main(int argc, char* argv[])
{
    return 0;
}
```

Compilation error
```
In file included from test2.cpp:18:0:
/usr/local/include/folly/Traits.h:448:1: error: partial specialization of ‘boost::has_nothrow_constructor<std::shared_ptr<_Tp1> >’ after instantiation of ‘boost::has_nothrow_constructor<std::shared_ptr<External> >’ [-fpermissive]
 FOLLY_ASSUME_FBVECTOR_COMPATIBLE_1(std::shared_ptr);
 ^
```

**EDIT**: There was another unrelated issue in this ticket. I fixed it... but the original problem still remains.

**Comment by facebook-github-bot-5** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by facebook-github-bot-2** [comment]
Thank you for your patience. After 30 days with no updates from the core team, we're closing out the issue. If you're still experiencing the problem described, please reopen the issue - thanks!

**Comment by decibelbrown** [comment]
I have seen what appears to be the same issue when importing solely `#include <folly/futures/Future.h>` and `#include <boost/signals2.hpp>` while using `std::shared_ptr`s. I can attempt to provide another test case if that would be required to reopen this issue.

**Comment by mtanski** [comment]
Still seeing this issue.
