### ISSUE TITLE
Travis CI jobs failing -- Boost 1.55 does not have SpreadSort

### ISSUE THREAD

**Issue by JoeLoser** [facebook/folly#890]
The Travis CI builds are using an older version of Boost (1.55) which does not seem to have SpreadSort (https://api.travis-ci.org/v3/job/409420176/log.txt). It appears SpreadSort came in Boost 1.58 (https://www.boost.org/doc/libs/1_58_0/libs/sort/doc/html/sort/sort_hpp.html#sort.sort_hpp.header_spreadsort).

@djwatson any reason to stick with Boost 1.55 for the CI builds, or should we conditionally define to use spreadsort or regular `std::sort` based on Boost version?

**Comment by JoeLoser** [comment]
Reverted in 82fb08d, so closing the issue.

**Comment by djwatson** [comment]
Internal discussion was that we would be moving to boost 1.58, and CI would drop 14.04 ubuntu.
