### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Roman-Koshelev** [facebook/folly#905]
kosh@kosh:~/work/folly/_build5$ cmake .. 
- Boost version: 1.65.1
- Found the following Boost libraries:
-   context
-   chrono
-   date_time
-   filesystem
-   program_options
-   regex
-   system
-   thread
-   atomic
- Found double-conversion: /usr/lib/x86_64-linux-gnu/libdouble-conversion.so
- Found libevent: /usr/lib/x86_64-linux-gnu/libevent.so
- Found LZ4: /usr/lib/x86_64-linux-gnu/liblz4.so
- Found Zstd: /usr/lib/x86_64-linux-gnu/libzstd.so
- Setting FOLLY_USE_SYMBOLIZER: ON
- Configuring done
- Generating done
- Build files have been written to: /home/kosh/work/folly/_build5
kosh@kosh:~/work/folly/_build5$ make -j3
[  0%] Building CXX object CMakeFiles/folly_base.dir/folly/experimental/symbolizer/ElfCache.cpp.o
[  0%] Building CXX object CMakeFiles/folly_base.dir/folly/experimental/symbolizer/Dwarf.cpp.o
[  0%] Building CXX object CMakeFiles/folly_base.dir/folly/experimental/symbolizer/Elf.cpp.o
/home/kosh/work/folly/folly/experimental/symbolizer/Dwarf.cpp:24:10: fatal error: dwarf.h: Нет такого файла или каталога
 #include <dwarf.h> // @manual
          ^~~~~~~~~
compilation terminated.
CMakeFiles/folly_base.dir/build.make:1934: recipe for target 'CMakeFiles/folly_base.dir/folly/experimental/symbolizer/Dwarf.cpp.o' failed
make[2]: *** [CMakeFiles/folly_base.dir/folly/experimental/symbolizer/Dwarf.cpp.o] Error 1
make[2]: *** Ожидание завершения заданий…
CMakeFiles/Makefile2:3148: recipe for target 'CMakeFiles/folly_base.dir/all' failed
make[1]: *** [CMakeFiles/folly_base.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by JoeLoser** [comment]
What does CMake's configure step report as `LIBDWARF_INCLUDE_DIR`? Does it find it? I suspect your `dwarf.h` is actually in `libdwarf` subdirectory.

**Comment by Roman-Koshelev** [comment]
kosh@kosh:~/work/folly$ grep -r LIBDWARF_INCLUDE_DIR
_build5/CMakeCache.txt:LIBDWARF_INCLUDE_DIR:PATH=/usr/include
_build5/CMakeCache.txt://ADVANCED property for variable: LIBDWARF_INCLUDE_DIR
_build5/CMakeCache.txt:LIBDWARF_INCLUDE_DIR-ADVANCED:INTERNAL=1
CMake/folly-deps.cmake:list(APPEND FOLLY_INCLUDE_DIRECTORIES ${LIBDWARF_INCLUDE_DIRS})
CMake/FindLibDwarf.cmake:find_path(LIBDWARF_INCLUDE_DIR NAMES libdwarf/dwarf.h)
CMake/FindLibDwarf.cmake:mark_as_advanced(LIBDWARF_INCLUDE_DIR)
CMake/FindLibDwarf.cmake:  REQUIRED_VARS LIBDWARF_LIBRARY LIBDWARF_INCLUDE_DIR)
CMake/FindLibDwarf.cmake:  set(LIBDWARF_INCLUDE_DIRS ${LIBDWARF_INCLUDE_DIR})

kosh@kosh:~/work/folly$ sudo find / -name dwarf.h
/usr/src/linux-headers-4.15.0-23/arch/arc/include/asm/dwarf.h
/usr/src/linux-headers-4.15.0-23/arch/parisc/include/asm/dwarf.h
/usr/src/linux-headers-4.15.0-23/arch/sh/include/asm/dwarf.h
/usr/src/linux-headers-4.15.0-29/arch/arc/include/asm/dwarf.h
/usr/src/linux-headers-4.15.0-29/arch/parisc/include/asm/dwarf.h
/usr/src/linux-headers-4.15.0-29/arch/sh/include/asm/dwarf.h
/usr/include/libdwarf/dwarf.h

**Comment by Roman-Koshelev** [comment]
"I suspect your dwarf.h is actually in libdwarf subdirectory. ". You're right

**Comment by JoeLoser** [comment]
One short-term workaround may be to just set `LIBDWARF_INCLUDE_DIR` at CMake configure time by passing `-DLIBDWARF_INCLUDE_DIR=/usr/include/libdwarf`.

I think my recent commit (https://github.com/facebook/folly/commit/e66fb34c91bdc721c844326c02f1e9fe649eb0cf#diff-60d4eaa0cfbc3df1105fc034f11b08b4L21) broke the behavior in the include. In the PR (https://github.com/facebook/folly/pull/790), I actually did not modify `folly/experimental/symbolizer/Dwarf.cpp`, but I think @andrewjcg who pulled the PR internally may have changed those lines.

**Comment by JoeLoser** [comment]
@Roman-Koshelev I think a more proper fix is to have the `FindLibDwarf.cmake` script to know about certain OS/package-manager specific PATHs in addition to commonly user-installed package places like `opt`.

For example, something like this would be more robust:

```
find_path (LIBDWARF_INCLUDE_DIR
  NAMES
    libdwarf.h dwarf.h
  PATHS
    /usr/include
    /usr/include/libdwarf
    /usr/local/include
    /usr/local/include/libdwarf
    /opt/local/include
)
```

I can try to land a PR with this tomorrow if I get some time.

**Comment by simpkins** [comment]
I've got a patch in progress to search for both dwarf.h or libdwarf/dwarf.h
I'm changing the code to just invoke `find_path()` again with `libdwarf/dwarf.h` if it doesn't find `dwarf.h`, so that it still honors everything in CMAKE_PREFIX_PATH and CMAKE_INCLUDE_PATH.

**Comment by JoeLoser** [comment]
@simpkins thanks for the fix -- your approach is cleaner and simpler than the one I proposed above. I didn't realize my original change would accidentally break Debian-based systems who did have it in a subdirectory. Sorry about that.
