### ISSUE TITLE
Folly build failed with MSVC on windows

### ISSUE THREAD

**Issue by QuellaZhang** [facebook/folly#913]
Folly build failed with MSVC on windows, could you help have a look? Noted that this issue only found when compiles with unreleased vctoolset, that next release of MSVC will have this behavior.

**Environment**
VCPKG(latest revision from github) + Visual Studio 15.7.2

**Repro steps:**

1. open X64 native tools command prompt for VS2017
2. git clone https://github.com/Microsoft/vcpkg D:\VCPKG\src
3. cd d:\vcpkg\src
4. devenv /upgrade .\toolsrc\vcpkg.sln
5. set _CL_=/D_SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING
6. msbuild /p:Configuration=Release /p:Platform=x86 /p:WindowsTargetPlatformVersion=10.0.17134.0 toolsrc\vcpkg.sln /t:Rebuild
7. set _CL_=
8. set path=%cd%\toolsrc\Release;%path%
9. set _Build_ERROR_X64=0
10. vcpkg install folly:x64-windows --head

**Failure Info:**
D:\Folly\vcpkg\src\buildtrees\folly\src\head\folly-master\folly/FBString.h(1846): error C2039: 'logic_error': is not a member of 'std'
D:\Folly\vcpkg\src\buildtrees\folly\src\head\folly-master\folly/FBString.h(2867): note: see declaration of 'std'
D:\Folly\vcpkg\src\buildtrees\folly\src\head\folly-master\folly/FBString.h(1844): note: while compiling class template member function 'unsigned __int64 folly::basic_fbstring<char,std::char_traits<char>,std::allocator<char>,folly::fbstring_core<E>>::traitsLength(const char *)'
        with
        [
            E=char
        ]
D:\Folly\vcpkg\src\buildtrees\folly\src\head\folly-master\folly/FBString.h(1162): note: see reference to function template instantiation 'unsigned __int64 
folly::basic_fbstring<char,std::char_traits<char>,std::allocator<char>,folly::fbstring_core<E>>::traitsLength(const char *)' being compiled
        with
        [
            E=char
        ]
D:\Folly\vcpkg\src\buildtrees\folly\src\head\folly-master\folly/FBString.h(2869): note: see reference to class template instantiation 'folly::basic_fbstring<char,std::char_traits<char>,std::allocator<char>,folly::fbstring_core<E>>' being compiled
        with
        [
            E=char
        ]
D:\Folly\vcpkg\src\buildtrees\folly\src\head\folly-master\folly/FBString.h(1846): error C2065: 'logic_error': undeclared identifier
D:\Folly\vcpkg\src\buildtrees\folly\src\head\folly-master\folly/FBString.h(1846): error C2672: 'throw_exception': no matching overloaded function found
D:\Folly\vcpkg\src\buildtrees\folly\src\head\folly-master\folly/FBString.h(1847): error C2974: 'folly::throw_exception': invalid template argument for 'Ex', type expected
D:\Folly\vcpkg\src\buildtrees\folly\src\head\folly-master\folly/lang/Exception.h(78): note: see declaration of 'folly::throw_exception'

**Comment by Orvid** [comment]
@yfeldblum It looks like we're reliant on an implicit include in fbstring. I'll put up a diff.

**Comment by QuellaZhang** [comment]
Thanks for your investigation!

**Comment by QuellaZhang** [comment]
Thanks for your investigation!
  @@@We use VS2017 version 15.7.2, not VS2015
Wating for your fix : )

**Comment by QuellaZhang** [comment]
Thanks for your investigation!
@yfeldblum Sorry for the confusion. We use VS2017 version 15.7.2, not VS2015
@Orvid Wating for your fix :  )
