### ISSUE TITLE
fbstring replace std::string can`t find ”basic_fbstring_malloc.h“ 

### ISSUE THREAD

**Issue by ly82882592** [facebook/folly#924]
I has try replace std::string , but I can`t find this head file ”basic_fbstring_malloc.h“   . pleace help me how slove this problem.

**Comment by yfeldblum** [comment]
Would upgrading to a version of the standard library with SSO strings, like the one that ships with GCC 5.1 or higher, be an alternative approach?

**Comment by wankai** [comment]
@yuinm have you solved this problem ?

**Comment by yuinm** [comment]
no , But i`m using gcc 5.2 .
