### ISSUE TITLE
`logging/CustomLogFormatter.cpp` is missing from `folly/Makefile.am`

### ISSUE THREAD

**Issue by lembacon** [facebook/folly#925]
`logging/CustomLogFormatter.cpp` is missing from `folly/Makefile.am`, when building with autotools, it will result `dyld: Symbol not found: __ZTVN5folly18CustomLogFormatterE`.

**Comment by Orvid** [comment]
As a heads up, we're in the process of removing the autotools build in favor of the CMake build, so the homebrew recipe will need to be updated to build with CMake at some point.

I'll put up a diff to get the autotools build working again for now though. :)

**Comment by Orvid** [comment]
I've just pushed v2018.09.03.01 which should contain the fix for the autotools build.
