### ISSUE TITLE
Folly RPM for CentOS 7 and CentOS 6

### ISSUE THREAD

**Issue by daniel-lucio** [facebook/folly#929]
Because more than one was looking for it

https://inside-out.xyz/technology/folly-facebook-open-source-library-rpm-for-centos-6-and-7.html

More Facebook RPM's coming soon

**Comment by Orvid** [comment]
In general, packaging Folly as an RPM is useless, as we make no guarantees of binary compatibility, so upgrading it independently of anything that depends on it will break things.

Also, please do not go commenting on every issue created in the last 5 years, it isn't helpful and just spams people.

**Comment by daniel-lucio** [comment]
It is good to know this project management is poor. There is something that is called Major. Marjos are used to prevent any problem from libraries that are not binary compatible between releases.

My RPM use majors to make sure that today's release won't conflict with the next in 1 year. I will just keep incrementing the major each time I publish an update. Those who use my RPM will not have problems when updating.
