### ISSUE TITLE
error: sizeof (int*) / sizeof (int)’ does not compute the number of array elements [-Werror=sizeof-pointer-div]

### ISSUE THREAD

**Issue by furkanusta** [facebook/folly#933]
Hi, I am using g++ (GCC) 8.1.1 20180712 (Red Hat 8.1.1-5) on Fedora 28 using CMake and I am getting:

> ../folly/small_vector.h:420:36: error: division ‘sizeof (int*) / sizeof (int)’ does not compute the number of array elements [-Werror=sizeof-pointer-div]
       constexpr_max(sizeof(Value*) / sizeof(Value), RequestedMaxInline)};

I did a quick check on the code but it looks like it is not using the division for array size but instead to calculate the optimal capacity for union storage.

If it is actually an error on GCC's side I might report it to them, in the meantime I've removed the -Werror from the flag-list.

There is also couple more warnings from gcc: 
> declaration of ‘RWSpinLockType’ shadows a previous local [-Wshadow=compatible-local]

and

> void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘class std::unique_ptr<int, > std::default_delete<int> >’ with no trivial copy-assignment [-Wclass-memaccess]

Should I open up new issues for those as well or just change the title to 'GCC8.1 warnings' and put the details for the others in here as well?

**Comment by yfeldblum** [comment]
The first two items in this issue have been fixed. The last one is too vague for me to tell.
