### ISSUE TITLE
EventBase.cpp:211] Check failed: evbTid == curTid This logic must be executed in the event base thread. Event base thread name: "IO Thread0", current thread name: "IO Thread0"

### ISSUE THREAD

**Issue by nguyenngodinh** [facebook/folly#934]
I get this issue when the handler try to write to the channel. 
[backtrace.log](https://github.com/facebook/folly/files/2399462/backtrace.log)

**Comment by nguyenngodinh** [comment]
@yfeldblum  please! help me! I try out to search the issue, but find nothing. 
I also get difficult to find the document so I can get deeper understand about the lib.

**Comment by nguyenngodinh** [comment]
@yfeldblum I have found the issuse! The reason is i have set wrong sequence of EventBaseHandler and AsyncSocketHandler when setup wangle pipeline Factory.

**Comment by blackrose28** [comment]
Care to clarify? I'm encountering this as well, not yet find any solution.

**Comment by HsiehYuho** [comment]
How about wrap the `eventBase` by `runInEventBaseThread`? 
For example:
```
 eb_.getEventBase()->runInEventBaseThread(
      [this, delay] {
        eb_.getEventBase()->runAfterDelay(
            [this] {
             someFunc();
            },
            delay.count());
      });
```

Not sure it helps or not :)
