### ISSUE TITLE
make error on centos7.4

### ISSUE THREAD

**Issue by junstor** [facebook/folly#936]
[  1%] Building CXX object CMakeFiles/folly_base.dir/folly/dynamic.cpp.o
In file included from /root/soft/folly/folly/container/F14Map.h:38:0,
                 from /root/soft/folly/folly/dynamic.h:67,
                 from /root/soft/folly/folly/dynamic.cpp:19:
/root/soft/folly/folly/container/detail/F14Policy.h: In instantiation of ‘folly::f14::detail::ObjectHolder<Tag, T, true>::ObjectHolder(Args&& ...) [with Args = {folly::detail::DynamicHasher}; char Tag = 'H'; T = folly::detail::DynamicHasher]’:
/root/soft/folly/folly/container/detail/F14Policy.h:218:43:   required from ‘folly::f14::detail::BasePolicy<KeyType, MappedTypeOrVoid, HasherOrVoid, KeyEqualOrVoid, AllocOrVoid, ItemType>::BasePolicy(folly::f14::detail::BasePolicy<KeyType, MappedTypeOrVoid, HasherOrVoid, KeyEqualOrVoid, AllocOrVoid, ItemType>&&) [with KeyType = folly::dynamic; MappedTypeOrVoid = folly::dynamic; HasherOrVoid = folly::detail::DynamicHasher; KeyEqualOrVoid = folly::detail::DynamicKeyEqual; AllocOrVoid = void; ItemType = std::pair<const folly::dynamic, folly::dynamic>*]’
/root/soft/folly/folly/container/detail/F14Policy.h:734:7:   required from ‘folly::f14::detail::F14Table<Policy>::F14Table(folly::f14::detail::F14Table<Policy>&&) [with Policy = folly::f14::detail::NodeContainerPolicy<folly::dynamic, folly::dynamic, folly::detail::DynamicHasher, folly::detail::DynamicKeyEqual, void>]’
/root/soft/folly/folly/container/F14Map.h:291:3:   required from here
/root/soft/folly/folly/container/detail/F14Policy.h:74:63: error: too many initializers for ‘folly::detail::DynamicHasher’
   ObjectHolder(Args&&... args) : T{std::forward<Args>(args)...} {}
                                                               ^
/root/soft/folly/folly/container/detail/F14Policy.h: In instantiation of ‘folly::f14::detail::ObjectHolder<Tag, T, true>::ObjectHolder(Args&& ...) [with Args = {folly::detail::DynamicKeyEqual}; char Tag = 'E'; T = folly::detail::DynamicKeyEqual]’:
/root/soft/folly/folly/container/detail/F14Policy.h:218:43:   required from ‘folly::f14::detail::BasePolicy<KeyType, MappedTypeOrVoid, HasherOrVoid, KeyEqualOrVoid, AllocOrVoid, ItemType>::BasePolicy(folly::f14::detail::BasePolicy<KeyType, MappedTypeOrVoid, HasherOrVoid, KeyEqualOrVoid, AllocOrVoid, ItemType>&&) [with KeyType = folly::dynamic; MappedTypeOrVoid = folly::dynamic; HasherOrVoid = folly::detail::DynamicHasher; KeyEqualOrVoid = folly::detail::DynamicKeyEqual; AllocOrVoid = void; ItemType = std::pair<const folly::dynamic, folly::dynamic>*]’
/root/soft/folly/folly/container/detail/F14Policy.h:734:7:   required from ‘folly::f14::detail::F14Table<Policy>::F14Table(folly::f14::detail::F14Table<Policy>&&) [with Policy = folly::f14::detail::NodeContainerPolicy<folly::dynamic, folly::dynamic, folly::detail::DynamicHasher, folly::detail::DynamicKeyEqual, void>]’
/root/soft/folly/folly/container/F14Map.h:291:3:   required from here
/root/soft/folly/folly/container/detail/F14Policy.h:74:63: error: too many initializers for ‘folly::detail::DynamicKeyEqual’
/root/soft/folly/folly/container/detail/F14Policy.h: In instantiation of ‘folly::f14::detail::ObjectHolder<Tag, T, true>::ObjectHolder(Args&& ...) [with Args = {const folly::detail::DynamicHasher&}; char Tag = 'H'; T = folly::detail::DynamicHasher]’:
/root/soft/folly/folly/container/detail/F14Policy.h:208:76:   required from ‘folly::f14::detail::BasePolicy<KeyType, MappedTypeOrVoid, HasherOrVoid, KeyEqualOrVoid, AllocOrVoid, ItemType>::BasePolicy(const folly::f14::detail::BasePolicy<KeyType, MappedTypeOrVoid, HasherOrVoid, KeyEqualOrVoid, AllocOrVoid, ItemType>&) [with KeyType = folly::dynamic; MappedTypeOrVoid = folly::dynamic; HasherOrVoid = folly::detail::DynamicHasher; KeyEqualOrVoid = folly::detail::DynamicKeyEqual; AllocOrVoid = void; ItemType = std::pair<const folly::dynamic, folly::dynamic>*]’
/root/soft/folly/folly/container/detail/F14Policy.h:734:7:   required from ‘folly::f14::detail::F14Table<Policy>::F14Table(const folly::f14::detail::F14Table<Policy>&) [with Policy = folly::f14::detail::NodeContainerPolicy<folly::dynamic, folly::dynamic, folly::detail::DynamicHasher, folly::detail::DynamicKeyEqual, void>]’
/root/soft/folly/folly/container/F14Map.h:286:3:   required from here
/root/soft/folly/folly/container/detail/F14Policy.h:74:63: error: too many initializers for ‘folly::detail::DynamicHasher’
/root/soft/folly/folly/container/detail/F14Policy.h: In instantiation of ‘folly::f14::detail::ObjectHolder<Tag, T, true>::ObjectHolder(Args&& ...) [with Args = {const folly::detail::DynamicKeyEqual&}; char Tag = 'E'; T = folly::detail::DynamicKeyEqual]’:
/root/soft/folly/folly/container/detail/F14Policy.h:208:76:   required from ‘folly::f14::detail::BasePolicy<KeyType, MappedTypeOrVoid, HasherOrVoid, KeyEqualOrVoid, AllocOrVoid, ItemType>::BasePolicy(const folly::f14::detail::BasePolicy<KeyType, MappedTypeOrVoid, HasherOrVoid, KeyEqualOrVoid, AllocOrVoid, ItemType>&) [with KeyType = folly::dynamic; MappedTypeOrVoid = folly::dynamic; HasherOrVoid = folly::detail::DynamicHasher; KeyEqualOrVoid = folly::detail::DynamicKeyEqual; AllocOrVoid = void; ItemType = std::pair<const folly::dynamic, folly::dynamic>*]’
/root/soft/folly/folly/container/detail/F14Policy.h:734:7:   required from ‘folly::f14::detail::F14Table<Policy>::F14Table(const folly::f14::detail::F14Table<Policy>&) [with Policy = folly::f14::detail::NodeContainerPolicy<folly::dynamic, folly::dynamic, folly::detail::DynamicHasher, folly::detail::DynamicKeyEqual, void>]’
/root/soft/folly/folly/container/F14Map.h:286:3:   required from here
/root/soft/folly/folly/container/detail/F14Policy.h:74:63: error: too many initializers for ‘folly::detail::DynamicKeyEqual’
make[2]: *** [CMakeFiles/folly_base.dir/folly/dynamic.cpp.o] Error 1
make[1]: *** [CMakeFiles/folly_base.dir/all] Error 2
make: *** [all] Error 2

**Comment by yfeldblum** [comment]
Thanks for the report and thanks for the solution.

Folly (currently) is a C++14 library and supports gcc >= 5.
