### ISSUE TITLE
`CMAKE_INCLUDE_PATH` and `CMAKE_LIBRARY_PATH` are ignored.

### ISSUE THREAD

**Issue by deech** [facebook/folly#937]
I'm self-compiling some of the dependencies (eg. `OpenSSL`) and invoking `cmake` with `cmake -DCMAKE_INCLUDE_DIR= ...` but I notice that `cmake` is still picking up the system version. Looking at the generated `Cmake` file it as though each dependency has it's own variable.

**Comment by calebmarchent** [comment]
Hi Deech,

The search order for CMake is documented in the following article. https://cmake.org/cmake/help/v3.10/command/find_package.html#command:find_package

One option you might consider is using the CMAKE_PREFIX_PATH; conversely you may also want to pass the location using -isystem CFLAGS or CXXFLAGS.
