### ISSUE TITLE
Debian Package for Folly(-dev)?

### ISSUE THREAD

**Issue by calebmarchent** [facebook/folly#938]
Has anyone tried packaging Folly for Debian/Ubuntu? If not, does anyone mind if I have a go?

I am looking at creating a Debian package for [LogDevice](https://github.com/facebookincubator/LogDevice), which builds against Folly and would like to have folly as a package and use it as build dependency for my [LogDevice](https://github.com/facebookincubator/LogDevice) Debian package.

**Comment by Orvid** [comment]
In general, we tend to not package Folly separately, due to the way we do development internally. Usually it's better to compile and link Folly in statically for any packages.

**Comment by calebmarchent** [comment]
Ok; will try that in first instance and see how it goes. Closing for now.
