### ISSUE TITLE
Moving a scopeguard means trouble?

### ISSUE THREAD

**Issue by Amaroker** [facebook/folly#940]
There's a problem in ScopeGuard.h:

  ```
ScopeGuardForNewException(ScopeGuardForNewException&& other) = default;

  ~ScopeGuardForNewException() noexcept(ExecuteOnException) {
    if (ExecuteOnException == (exceptionCounter_ < uncaught_exceptions())) {
      if (ExecuteOnException) {
        ScopeGuardImplBase::runAndWarnAboutToCrashOnException(function_);
      } else {
        function_();
      }
    }
  }
```
The move constructor is defaulted and will leave "other.function_" in a "valid but unspecified state". I don't know about other compilers, but Visual Studio will set it to an empty state.

Later, when the other object is destroyed, the destructor calls function_ and since it's in an empty state, it will throw std::bad_function_call.

I don't think that's acceptable. If a ScopeGuardForNewException object is moved-from, wouldn't it be much better to ensure that the function is not called in the destructor?

**Comment by yfeldblum** [comment]
Thanks for opening the issue.

It looks like this is safe if RVO copy elision can be assumed, but you are right that this is not semantically safe pre-C++17 since it is only safe to rely on RVO copy elision since C++17.

**Comment by Amaroker** [comment]
This library is supposed to work with C++14:

> Folly (acronymed loosely after Facebook Open Source Library) is a library of C++14 components
