### ISSUE TITLE
std::atomic<std::thread::id> SingletonHolder::creating_thread_ is uninitialized

### ISSUE THREAD

**Issue by cieplik** [facebook/folly#941]
`creating_thread_` member variable is uninitialized when read for the first time in `SingletonHolder<T>::createInstance()`:

https://github.com/facebook/folly/blob/f43ce6d6866b7b994b3019df561109afae050ebc/folly/Singleton-inl.h#L202-L203

**Comment by yfeldblum** [comment]
This should have been addressed in e45b48c765188d15008d7cd91f9da9437faebe8a.
