### ISSUE TITLE
Folly failed with cmake error “This build script only supports building Folly on 64-bit Windows with Visual Studio 2015 or Visual Studio 2017. MSVC version '1920' 

### ISSUE THREAD

**Issue by QuellaZhang** [facebook/folly#949]
Hi All,

I try to build Folly with VS2017, it failed with cmake error “This build script only supports building Folly on 64-bit Windows with Visual Studio 2015 or Visual Studio 2017. MSVC version '1920' is not supported.”, we use Folly to test VS compiler, this is because our VS compiler version is updated, this issue found with unreleased vctoolset and the next release VS will have this behavior, could someone help to look at this?

Folly source code "D:\Folly\src\CMakeLists.txt":
```
  if (MSVC_VERSION GREATER_EQUAL 1910 AND MSVC_VERSION LESS 1920)
    set(MSVC_IS_2015 OFF)
    set(MSVC_IS_2017 ON)
  elseif(MSVC_VERSION EQUAL 1900)
    set(MSVC_IS_2015 ON)
    set(MSVC_IS_2017 OFF)
  else()
    message(
       FATAL_ERROR
       "This build script only supports building Folly on 64-bit Windows with "
       "Visual Studio 2015 or Visual Studio 2017. "
       "MSVC version '${MSVC_VERSION}' is not supported."
    )
  endif()
```

**Comment by Orvid** [comment]
For a quick-fix, adjusting
```
if (MSVC_VERSION GREATER_EQUAL 1910 AND MSVC_VERSION LESS 1920)
```
to:
```
if (MSVC_VERSION GREATER_EQUAL 1910 AND MSVC_VERSION LESS_EQUAL 1920)
```

Right now the only thing the MSVC version guards do is decide whether to pass the `/permissive-` and enable a few additional warnings :)

I'll put up a diff internally to make this same change as well :)
