### ISSUE TITLE
FBVector growth factor

### ISSUE THREAD

**Issue by pawanjay176** [facebook/folly#954]
In the [](https://github.com/facebook/folly/blob/master/folly/docs/FBVector.md) page, it says choosing different growth factors allows memory reuse after k number of reallocations. 
> For instance, choosing 1.5 as the factor allows memory reuse after 4 reallocations; 1.45 allows memory reuse after 3 reallocations; and 1.3 allows reuse after only 2 reallocations.

Can someone expand on how we are getting the number of reallocations for the different growth factors?

**Comment by yfeldblum** [comment]
From the sequence given just previously: find the exponent of the first element in the sequence which is not larger than the sum of the previous elements in the sequence.

**Comment by pawanjay176** [comment]
But how can we guarantee that the previously deallocated chunks are contiguous? If they aren't contiguous, how can we reuse them?

**Comment by yfeldblum** [comment]
The basic case being discussed is a sequence of push-back calls in a tight loop, so a simple allocator might simply reallocate at the end of the previous allocation each time a reallocation is needed, unless there is free space where an old but subsequently deallocated allocation was. There is no guarantee that an allocator will do this, or that there are no intervening allocations that disrupt this pattern.
