### ISSUE TITLE
Can not build Folly on Mac OS

### ISSUE THREAD

**Issue by uilianries** [facebook/folly#961]
Hi!

I'm trying to package Folly project for [Conan.io](https://github.com/conan-io/conan). However, I need to build Folly using a large variation of settings, including OS (linux, mac, windows), build type (debug, release), compiler (gcc, clang, mingw, msvc, apple-clang) and arch (x86, x86_64).

Unfortunately, I'm not able to build Folly with apple-clang on OSX.

All builds could be resumed by the follow error:

```
[  4%] Building CXX object source_subfolder/CMakeFiles/folly_base.dir/folly/Fingerprint.cpp.o
/Users/travis/.conan/data/folly/2018.11.05.00/bincrafters/testing/build/b4a26302e12b71362a60dcb24c5b9058b86d697b/source_subfolder/folly/Fingerprint.cpp:107:36: error: constexpr variable 'poly_table_63' must be initialized by a constant expression
FOLLY_STORAGE_CONSTEXPR auto const poly_table_63 = make_poly_table<63>();
```

As I running Conan to build Folly, it calls cmake but it does not change any compiler flag. All Folly dependencies were solve by Conan, including:

* OpenSSL/1.0.2o
* boost/1.67.0
* bzip2/1.0.6
* double-conversion/3.1.1
* gflags/2.2.1
* glog/0.3.5
* libevent/2.1.8
* lz4/1.8.3
* zlib/1.2.11
* zstd/1.3.5

- Could Folly be built by apple-clang? If yes, how?
- Is there some limitation about building as static or shared library?

#### Steps to reproduce
Here I'm expressing generic steps using CMake, it might result on same Conan error:

    wget https://github.com/facebook/folly/archive/v2018.11.05.00.tar.gz
    tar zxf v2018.11.05.00
    cd folly-2018.11.05.00
    mkdir build
    cmake ..
    cmake --build . 

But if you are interested to reproduce Conan steps:

    git clone https://github.com/bincrafters/conan-folly.git
    cd conan-folly
    conan create . bincrafters/testing

Conan create will download Folly source code, all dependencies pre-build and build Folly.

#### Environment
Folly version: 2018.11.05.00
OS: OSX
Compiler: apple-clang
Version: 9.0, 9.1
Arch: x86_64
Boost: 1.67.0

#### Logs
* Apple Clang 9.0 + x86_64 + Release + Share library:
https://travis-ci.org/bincrafters/conan-folly/jobs/452155640#L4153
* Apple Clang 9.0 + x86_64 + Release + Static library:
https://travis-ci.org/bincrafters/conan-folly/jobs/452155642#L4153
* Apple Clang 9.0 + x86_64 + Debug + Share library:
https://travis-ci.org/bincrafters/conan-folly/jobs/452155641#L4155
* Apple Clang 9.0 + x86_64 + Debug + Static library:
https://travis-ci.org/bincrafters/conan-folly/jobs/452155643#L4154

* Apple Clang 9.1 + x86_64 + Release + Share library:
https://travis-ci.org/bincrafters/conan-folly/jobs/452155644#L2705
* Apple Clang 9.1 + x86_64 + Debug + Share library:
https://travis-ci.org/bincrafters/conan-folly/jobs/452155645#L2706
* Apple Clang 9.1 + x86_64 + Release + Static library:
https://travis-ci.org/bincrafters/conan-folly/jobs/452155646#L2705
* Apple Clang 9.1 + x86_64 + Debug + Static library:
https://travis-ci.org/bincrafters/conan-folly/jobs/452155647#L2706

**Comment by uilianries** [comment]
If I understood, Folly requires C++1z, but xcode9 should be able to build.

**Comment by Orvid** [comment]
To clarify, is this just XCode 9.0 & 9.1? Is 9.2 and above fine?

**Comment by Orvid** [comment]
In theory, https://github.com/facebook/folly/commit/613f048bfb95c2a992d9446b5cc22a6a26214c39 should hopefully fix this, but I haven't tested anything other than that it doesn't break existing builds yet, as I don't currently have a 9.0/9.1 environment handy. If the commit above doesn't fix it, I'll get a 9.0/9.1 environment setup so I can actually test the fix :)

**Comment by uilianries** [comment]
Hi! Thanks for you help! I'll check with xcode soon. I just need to update my Boost package before to try this.

**Comment by uilianries** [comment]
Worked!

https://travis-ci.org/bincrafters/conan-folly/builds/454190994

Thanks for your support! :smile:
