### ISSUE TITLE
libunwind dependency

### ISSUE THREAD

**Issue by cypherpu** [facebook/folly#964]
libunwind should be added as a cmake dependency.

/home/igor/git/facebook/folly/folly/experimental/symbolizer/StackTrace.cpp:20:10: fatal error: libunwind.h: No such file or directory
 #include <libunwind.h>

**Comment by eventhelix** [comment]
Got the same problem when compiling folly on Ubuntu 18.04.
The following package install fixed the issue:
`sudo apt-get install libunwind-dev`

**Comment by peterd3270** [comment]
In ubuntu 14  the following worked:

`sudo apt-get install libunwind8-dev`
