### ISSUE TITLE
 folly/test/FBVectorTestUtil.h file not found while running in Xcode

### ISSUE THREAD

**Issue by Mr-nightskycoder** [facebook/folly#970]

**Comment by Orvid** [comment]
How are you invoking cmake when you're seeing this error?

**Comment by Ba777** [comment]
I just cloned the folly folder in my desktop and then created a C++ project and added "Header search paths" before building the project. But no luck. 

Could you please provide me instruction to invoke cmake? Sorry if it is very basic question.

**Comment by Ba777** [comment]
I use Apple CLang default compiler to compile the program.
