### ISSUE TITLE
clang:-1: linker command failed with exit code 1 (use -v to see invocation) error while running ConvTest.cpp in XCode

### ISSUE THREAD

**Issue by Mr-nightskycoder** [facebook/folly#971]
<img width="263" alt="screen shot 2018-11-19 at 7 31 59 pm" src="https://user-images.githubusercontent.com/12070068/48741524-d243a000-ec31-11e8-95f8-2dc6fe3c8a6c.png">

Please help.

**Comment by Orvid** [comment]
We need the actual error message from the linker before we can do anything about it. `exit code -1` doesn't actually tell us anything.

**Comment by Ba777** [comment]
Ld /Users/balachandhar/Library/Developer/Xcode/DerivedData/ConvTest-hcpdyrlgnwkrjyazlbbksjvlperz/Build/Products/Debug/ConvTest normal x86_64 (in target: ConvTest)

    cd /Users/balachandhar/Documents/ConvTest

    export MACOSX_DEPLOYMENT_TARGET=10.13

    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -L/Users/balachandhar/Library/Developer/Xcode/DerivedData/ConvTest-hcpdyrlgnwkrjyazlbbksjvlperz/Build/Products/Debug -L/usr/local/lib/ -L/usr/local/Cellar/folly/2018.09.24.00_2/lib/ -L/usr/local/Cellar/boost/1.67.0_1/lib/ -F/Users/balachandhar/Library/Developer/Xcode/DerivedData/ConvTest-hcpdyrlgnwkrjyazlbbksjvlperz/Build/Products/Debug -filelist /Users/balachandhar/Library/Developer/Xcode/DerivedData/ConvTest-hcpdyrlgnwkrjyazlbbksjvlperz/Build/Intermediates.noindex/ConvTest.build/Debug/ConvTest.build/Objects-normal/x86_64/ConvTest.LinkFileList -mmacosx-version-min=10.13 -Xlinker -object_path_lto -Xlinker /Users/balachandhar/Library/Developer/Xcode/DerivedData/ConvTest-hcpdyrlgnwkrjyazlbbksjvlperz/Build/Intermediates.noindex/ConvTest.build/Debug/ConvTest.build/Objects-normal/x86_64/ConvTest_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -stdlib=libc++ /usr/local/lib/gtest.a /usr/local/lib/gtest_main.a -Xlinker -dependency_info -Xlinker /Users/balachandhar/Library/Developer/Xcode/DerivedData/ConvTest-hcpdyrlgnwkrjyazlbbksjvlperz/Build/Intermediates.noindex/ConvTest.build/Debug/ConvTest.build/Objects-normal/x86_64/ConvTest_dependency_info.dat -o /Users/balachandhar/Library/Developer/Xcode/DerivedData/ConvTest-hcpdyrlgnwkrjyazlbbksjvlperz/Build/Products/Debug/ConvTest



Undefined symbols for architecture x86_64:

  "folly::cold_detail::ColdClass::ColdClass()", referenced from:

      folly::Unexpected<folly::ConversionCode>::Unexpected(folly::ConversionCode&&) in main.o

      folly::Unexpected<folly::ConversionCode>::Unexpected(folly::ConversionCode const&) in main.o

  "folly::makeConversionError(folly::ConversionCode, folly::Range<char const*>)", referenced from:

      std::__1::enable_if<detail::IsArithToArith<unsigned char, long long>::value, unsigned char>::type folly::to<unsigned char, long long>(long long const&)::'lambda'(folly::ConversionCode)::operator()(folly::ConversionCode) const in main.o

      std::__1::enable_if<detail::IsArithToArith<signed char, long long>::value, signed char>::type folly::to<signed char, long long>(long long const&)::'lambda'(folly::ConversionCode)::operator()(folly::ConversionCode) const in main.o

      std::__1::enable_if<detail::IsArithToArith<double, float>::value, double>::type folly::to<double, float>(float const&)::'lambda'(folly::ConversionCode)::operator()(folly::ConversionCode) const in main.o

      std::__1::enable_if<detail::IsArithToArith<float, double>::value, float>::type folly::to<float, double>(double const&)::'lambda'(folly::ConversionCode)::operator()(folly::ConversionCode) const in main.o

      std::__1::enable_if<!(std::is_same<folly::Range<char const*>, unsigned char>::value), unsigned char>::type folly::to<unsigned char>(folly::Range<char const*>)::'lambda'(folly::ConversionCode)::operator()(folly::ConversionCode) const in main.o

      std::__1::enable_if<!(std::is_same<folly::Range<char const*>, unsigned char>::value), unsigned char>::type folly::to<unsigned char>(folly::Range<char const*>)::'lambda0'(folly::ConversionCode)::operator()(folly::ConversionCode) const in main.o

      std::__1::enable_if<!(std::is_same<folly::Range<char const*>, signed char>::value), signed char>::type folly::to<signed char>(folly::Range<char const*>)::'lambda'(folly::ConversionCode)::operator()(folly::ConversionCode) const in main.o

      ...

  "folly::detail::str_to_bool(folly::Range<char const*>*)", referenced from:

      std::__1::enable_if<std::is_same<bool, bool>::value, folly::Expected<bool, folly::ConversionCode> >::type folly::detail::convertTo<bool>(folly::Range<char const*>*) in main.o

  "folly::Expected<double, folly::ConversionCode> folly::detail::str_to_floating<double>(folly::Range<char const*>*)", referenced from:

      std::__1::enable_if<std::is_floating_point<double>::value, folly::Expected<double, folly::ConversionCode> >::type folly::detail::convertTo<double>(folly::Range<char const*>*) in main.o

  "folly::Expected<float, folly::ConversionCode> folly::detail::str_to_floating<float>(folly::Range<char const*>*)", referenced from:

      std::__1::enable_if<std::is_floating_point<float>::value, folly::Expected<float, folly::ConversionCode> >::type folly::detail::convertTo<float>(folly::Range<char const*>*) in main.o

  "folly::Expected<signed char, folly::ConversionCode> folly::detail::str_to_integral<signed char>(folly::Range<char const*>*)", referenced from:

      std::__1::enable_if<(std::is_integral<signed char>::value) && (!(std::is_same<signed char, bool>::value)), folly::Expected<signed char, folly::ConversionCode> >::type folly::detail::convertTo<signed char>(folly::Range<char const*>*) in main.o

  "folly::Expected<unsigned char, folly::ConversionCode> folly::detail::str_to_integral<unsigned char>(folly::Range<char const*>*)", referenced from:

      std::__1::enable_if<(std::is_integral<unsigned char>::value) && (!(std::is_same<unsigned char, bool>::value)), folly::Expected<unsigned char, folly::ConversionCode> >::type folly::detail::convertTo<unsigned char>(folly::Range<char const*>*) in main.o

  "folly::Expected<int, folly::ConversionCode> folly::detail::str_to_integral<int>(folly::Range<char const*>*)", referenced from:

      std::__1::enable_if<(std::is_integral<int>::value) && (!(std::is_same<int, bool>::value)), folly::Expected<int, folly::ConversionCode> >::type folly::detail::convertTo<int>(folly::Range<char const*>*) in main.o

  "folly::Expected<unsigned int, folly::ConversionCode> folly::detail::str_to_integral<unsigned int>(folly::Range<char const*>*)", referenced from:

      std::__1::enable_if<(std::is_integral<unsigned int>::value) && (!(std::is_same<unsigned int, bool>::value)), folly::Expected<unsigned int, folly::ConversionCode> >::type folly::detail::convertTo<unsigned int>(folly::Range<char const*>*) in main.o

  "folly::Expected<short, folly::ConversionCode> folly::detail::str_to_integral<short>(folly::Range<char const*>*)", referenced from:

      std::__1::enable_if<(std::is_integral<short>::value) && (!(std::is_same<short, bool>::value)), folly::Expected<short, folly::ConversionCode> >::type folly::detail::convertTo<short>(folly::Range<char const*>*) in main.o

  "folly::Expected<unsigned short, folly::ConversionCode> folly::detail::str_to_integral<unsigned short>(folly::Range<char const*>*)", referenced from:

      std::__1::enable_if<(std::is_integral<unsigned short>::value) && (!(std::is_same<unsigned short, bool>::value)), folly::Expected<unsigned short, folly::ConversionCode> >::type folly::detail::convertTo<unsigned short>(folly::Range<char const*>*) in main.o

  "folly::Expected<long long, folly::ConversionCode> folly::detail::str_to_integral<long long>(folly::Range<char const*>*)", referenced from:

      std::__1::enable_if<(std::is_integral<long long>::value) && (!(std::is_same<long long, bool>::value)), folly::Expected<long long, folly::ConversionCode> >::type folly::detail::convertTo<long long>(folly::Range<char const*>*) in main.o

  "folly::Expected<unsigned long long, folly::ConversionCode> folly::detail::str_to_integral<unsigned long long>(folly::Range<char const*>*)", referenced from:

      std::__1::enable_if<(std::is_integral<unsigned long long>::value) && (!(std::is_same<unsigned long long, bool>::value)), folly::Expected<unsigned long long, folly::ConversionCode> >::type folly::detail::convertTo<unsigned long long>(folly::Range<char const*>*) in main.o

  "folly::Expected<signed char, folly::ConversionCode> folly::detail::digits_to<signed char>(char const*, char const*)", referenced from:

      std::__1::enable_if<(std::is_integral<signed char>::value) && (!(std::is_same<signed char, bool>::value)), folly::Expected<signed char, folly::ConversionCode> >::type folly::tryTo<signed char>(char const*, char const*) in main.o

  "folly::Expected<unsigned char, folly::ConversionCode> folly::detail::digits_to<unsigned char>(char const*, char const*)", referenced from:

      std::__1::enable_if<(std::is_integral<unsigned char>::value) && (!(std::is_same<unsigned char, bool>::value)), folly::Expected<unsigned char, folly::ConversionCode> >::type folly::tryTo<unsigned char>(char const*, char const*) in main.o

  "folly::Expected<int, folly::ConversionCode> folly::detail::digits_to<int>(char const*, char const*)", referenced from:

      std::__1::enable_if<(std::is_integral<int>::value) && (!(std::is_same<int, bool>::value)), folly::Expected<int, folly::ConversionCode> >::type folly::tryTo<int>(char const*, char const*) in main.o

  "folly::Expected<unsigned int, folly::ConversionCode> folly::detail::digits_to<unsigned int>(char const*, char const*)", referenced from:

      std::__1::enable_if<(std::is_integral<unsigned int>::value) && (!(std::is_same<unsigned int, bool>::value)), folly::Expected<unsigned int, folly::ConversionCode> >::type folly::tryTo<unsigned int>(char const*, char const*) in main.o

  "folly::Expected<unsigned short, folly::ConversionCode> folly::detail::digits_to<unsigned short>(char const*, char const*)", referenced from:

      std::__1::enable_if<(std::is_integral<unsigned short>::value) && (!(std::is_same<unsigned short, bool>::value)), folly::Expected<unsigned short, folly::ConversionCode> >::type folly::tryTo<unsigned short>(char const*, char const*) in main.o

  "folly::demangle(char const*)", referenced from:

      folly::demangle(std::type_info const&) in main.o

  "google::LogMessage::stream()", referenced from:

      Conv_DoubleToInt_Test::TestBody() in main.o

      Conv_EnumToInt_Test::TestBody() in main.o

      Conv_IntToEnum_Test::TestBody() in main.o

      Conv_UnsignedEnum_Test::TestBody() in main.o

      std::__1::enable_if<(std::is_floating_point<float>::value) && (IsSomeString<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::value), void>::type folly::toAppend<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, float>(float, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, double_conversion::DoubleToStringConverter::DtoaMode, unsigned int) in main.o

      std::__1::enable_if<(std::is_floating_point<double>::value) && (IsSomeString<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::value), void>::type folly::toAppend<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, double>(double, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, double_conversion::DoubleToStringConverter::DtoaMode, unsigned int) in main.o

      std::__1::enable_if<(std::is_floating_point<double>::value) && (IsSomeString<folly::basic_fbstring<char, std::__1::char_traits<char>, std::__1::allocator<char>, folly::fbstring_core<char> > >::value), void>::type folly::toAppend<folly::basic_fbstring<char, std::__1::char_traits<char>, std::__1::allocator<char>, folly::fbstring_core<char> >, double>(double, folly::basic_fbstring<char, std::__1::char_traits<char>, std::__1::allocator<char>, folly::fbstring_core<char> >*, double_conversion::DoubleToStringConverter::DtoaMode, unsigned int) in main.o

      ...

  "google::LogMessage::LogMessage(char const*, int, int)", referenced from:

      Conv_DoubleToInt_Test::TestBody() in main.o

      Conv_EnumToInt_Test::TestBody() in main.o

      Conv_IntToEnum_Test::TestBody() in main.o

      Conv_UnsignedEnum_Test::TestBody() in main.o

  "google::LogMessage::~LogMessage()", referenced from:

      Conv_DoubleToInt_Test::TestBody() in main.o

      Conv_EnumToInt_Test::TestBody() in main.o

      Conv_IntToEnum_Test::TestBody() in main.o

      Conv_UnsignedEnum_Test::TestBody() in main.o

  "google::LogMessageFatal::LogMessageFatal(char const*, int)", referenced from:

      std::__1::enable_if<(std::is_floating_point<float>::value) && (IsSomeString<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::value), void>::type folly::toAppend<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, float>(float, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, double_conversion::DoubleToStringConverter::DtoaMode, unsigned int) in main.o

      std::__1::enable_if<(std::is_floating_point<double>::value) && (IsSomeString<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::value), void>::type folly::toAppend<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, double>(double, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, double_conversion::DoubleToStringConverter::DtoaMode, unsigned int) in main.o

      std::__1::enable_if<(std::is_floating_point<double>::value) && (IsSomeString<folly::basic_fbstring<char, std::__1::char_traits<char>, std::__1::allocator<char>, folly::fbstring_core<char> > >::value), void>::type folly::toAppend<folly::basic_fbstring<char, std::__1::char_traits<char>, std::__1::allocator<char>, folly::fbstring_core<char> >, double>(double, folly::basic_fbstring<char, std::__1::char_traits<char>, std::__1::allocator<char>, folly::fbstring_core<char> >*, double_conversion::DoubleToStringConverter::DtoaMode, unsigned int) in main.o

  "google::LogMessageFatal::~LogMessageFatal()", referenced from:

      std::__1::enable_if<(std::is_floating_point<float>::value) && (IsSomeString<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::value), void>::type folly::toAppend<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, float>(float, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, double_conversion::DoubleToStringConverter::DtoaMode, unsigned int) in main.o

      std::__1::enable_if<(std::is_floating_point<double>::value) && (IsSomeString<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::value), void>::type folly::toAppend<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, double>(double, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, double_conversion::DoubleToStringConverter::DtoaMode, unsigned int) in main.o

      std::__1::enable_if<(std::is_floating_point<double>::value) && (IsSomeString<folly::basic_fbstring<char, std::__1::char_traits<char>, std::__1::allocator<char>, folly::fbstring_core<char> > >::value), void>::type folly::toAppend<folly::basic_fbstring<char, std::__1::char_traits<char>, std::__1::allocator<char>, folly::fbstring_core<char> >, double>(double, folly::basic_fbstring<char, std::__1::char_traits<char>, std::__1::allocator<char>, folly::fbstring_core<char> >*, double_conversion::DoubleToStringConverter::DtoaMode, unsigned int) in main.o

  "double_conversion::DoubleToStringConverter::ToPrecision(double, int, double_conversion::StringBuilder*) const", referenced from:

      std::__1::enable_if<(std::is_floating_point<float>::value) && (IsSomeString<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::value), void>::type folly::toAppend<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, float>(float, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, double_conversion::DoubleToStringConverter::DtoaMode, unsigned int) in main.o

      std::__1::enable_if<(std::is_floating_point<double>::value) && (IsSomeString<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::value), void>::type folly::toAppend<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, double>(double, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, double_conversion::DoubleToStringConverter::DtoaMode, unsigned int) in main.o

      std::__1::enable_if<(std::is_floating_point<double>::value) && (IsSomeString<folly::basic_fbstring<char, std::__1::char_traits<char>, std::__1::allocator<char>, folly::fbstring_core<char> > >::value), void>::type folly::toAppend<folly::basic_fbstring<char, std::__1::char_traits<char>, std::__1::allocator<char>, folly::fbstring_core<char> >, double>(double, folly::basic_fbstring<char, std::__1::char_traits<char>, std::__1::allocator<char>, folly::fbstring_core<char> >*, double_conversion::DoubleToStringConverter::DtoaMode, unsigned int) in main.o

  "double_conversion::DoubleToStringConverter::ToShortestIeeeNumber(double, double_conversion::StringBuilder*, double_conversion::DoubleToStringConverter::DtoaMode) const", referenced from:

      double_conversion::DoubleToStringConverter::ToShortest(double, double_conversion::StringBuilder*) const in main.o

      double_conversion::DoubleToStringConverter::ToShortestSingle(float, double_conversion::StringBuilder*) const in main.o

  "double_conversion::DoubleToStringConverter::ToFixed(double, int, double_conversion::StringBuilder*) const", referenced from:

      std::__1::enable_if<(std::is_floating_point<float>::value) && (IsSomeString<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::value), void>::type folly::toAppend<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, float>(float, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, double_conversion::DoubleToStringConverter::DtoaMode, unsigned int) in main.o

      std::__1::enable_if<(std::is_floating_point<double>::value) && (IsSomeString<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::value), void>::type folly::toAppend<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, double>(double, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, double_conversion::DoubleToStringConverter::DtoaMode, unsigned int) in main.o

      std::__1::enable_if<(std::is_floating_point<double>::value) && (IsSomeString<folly::basic_fbstring<char, std::__1::char_traits<char>, std::__1::allocator<char>, folly::fbstring_core<char> > >::value), void>::type folly::toAppend<folly::basic_fbstring<char, std::__1::char_traits<char>, std::__1::allocator<char>, folly::fbstring_core<char> >, double>(double, folly::basic_fbstring<char, std::__1::char_traits<char>, std::__1::allocator<char>, folly::fbstring_core<char> >*, double_conversion::DoubleToStringConverter::DtoaMode, unsigned int) in main.o

  "_dallocx", referenced from:

      folly::usingJEMalloc()::'lambda'()::operator()() const in main.o

  "_mallctl", referenced from:

      folly::usingJEMalloc()::'lambda'()::operator()() const in main.o

  "_mallctlbymib", referenced from:

      folly::usingJEMalloc()::'lambda'()::operator()() const in main.o

  "_mallctlnametomib", referenced from:

      folly::usingJEMalloc()::'lambda'()::operator()() const in main.o

  "_mallocx", referenced from:

      folly::usingJEMalloc()::'lambda'()::operator()() const in main.o

  "_nallocx", referenced from:

      folly::goodMallocSize(unsigned long) in main.o

      folly::usingJEMalloc()::'lambda'()::operator()() const in main.o

  "_rallocx", referenced from:

      folly::usingJEMalloc()::'lambda'()::operator()() const in main.o

  "_sallocx", referenced from:

      folly::usingJEMalloc()::'lambda'()::operator()() const in main.o

  "_sdallocx", referenced from:

      folly::usingJEMalloc()::'lambda'()::operator()() const in main.o

  "_xallocx", referenced from:

      folly::usingJEMalloc()::'lambda'()::operator()() const in main.o

ld: symbol(s) not found for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by lostpupil** [comment]
Any progress yet?
