### ISSUE TITLE
Question about FBVector's computePushBackCapacity

### ISSUE THREAD

**Issue by leventov** [facebook/folly#973]
https://github.com/facebook/folly/blob/4c2915820febea2ca104666608906476e0be6bf9/folly/FBVector.h#L1212-L1223

Why doesn't it try to fit medium-sized allocations into jemalloc's size classes, that are powers of two plus quarters of that power of two. Then the transitions could be
2<sup>n</sup> -> 2<sup>n</sup> + 2<sup>n - 1</sup>
2<sup>n</sup> + 2<sup>n - 2</sup> -> 2<sup>n</sup> + 3 * 2<sup>n - 2</sup>
2<sup>n</sup> + 2<sup>n - 1</sup> -> 2<sup>n + 1</sup> ; or 2<sup>n + 1</sup> + 2<sup>n - 1</sup>
2<sup>n</sup> + 3 * 2<sup>n - 2</sup> -> 2<sup>n + 1</sup> + 2<sup>n - 1</sup>; or 2<sup>n + 1</sup> + 2<sup>n</sup>

However, to avoid integral divisions in computePushBackCapacity() if `sizeof(T)` is not a power of two, this approach would likely require to store the number of allocated bytes instead of the capacity expressed in the number of stored elements, and therefore significant refactoring of the FBVector's code.

**Comment by yfeldblum** [comment]
I don't know the answer.
