### ISSUE TITLE
Folly can fail to link with code compiled with c++14

### ISSUE THREAD

**Issue by jmccl** [facebook/folly#975]
Folly can fail to link with code compiled with std=c++14 if the compiler in use faithfully implements c++17. This is because c++17 treats const static variables as inline, whereas previously inline variables weren’t a thing.

More specifically, if proxygen is compiled with gcc 8.x (debian buster, arch etc.) it fails with the following error:

> /usr/bin/ld: HTTPSessionAcceptorTest.o: in function `HTTPSessionAcceptorTestBase::HTTPSessionAcceptorTestBase()':
> /usr/local/include/folly/String-inl.h:462: undefined reference to `folly::ssl::SSLServerOptions::kCipherList'
> 

Note that proxygen is compiled with c++14.

More minimally, this code fails as shown below:

```
#include <folly/io/async/SSLOptions.h>
#include <iostream>

int main(int argc, char * argv[])
{
    std::cout << "There are " << folly::ssl::SSLServerOptions::kCipherList.size() << " options.\n";
}
```

> \# g++ --version
> g++ (Debian 8.2.0-9) 8.2.0
> Copyright (C) 2018 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> \# g++ -std=c++14 main.cpp -lfolly 
> /usr/bin/ld: /tmp/cci8Yb37.o: in function `main':
> main.cpp:(.text+0x29): undefined reference to `folly::ssl::SSLServerOptions::kCipherList'

If compiled with -std=c++17 it succeeds. If the whole thing (folly included) is compiled with gcc 6.x, it succeeds.

The problem is that as folly is compiled with gnu++1z (c++17) on gcc8, it emits no symbol for kCipherList. I had initially thought that was the problem, but the gcc folks explained what was going on.

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=87947

Per the suggestion in that bug, the following patch fixes things.

```
@@ -73,7 +73,7 @@ struct SSLServerOptions {
   /**
    * The list of ciphers recommended for server use.
    */
-  static constexpr auto kCipherList = folly::make_array(
+  static constexpr __attribute__((used)) auto kCipherList = folly::make_array(
       "ECDHE-ECDSA-AES128-GCM-SHA256",
       "ECDHE-ECDSA-AES256-GCM-SHA384",
       "ECDHE-ECDSA-AES128-SHA"
```

That may well not be your preferred course however. 

I you wish, I’ll submit a PR.

**Comment by digitalist** [comment]
got this error too

**Comment by bcopeland** [comment]
This code was changed recently in commit d6d6412f4ada06cf61c1d1275e91a7fb1562bdfe, which I think will fix this issue.

**Comment by jmccl** [comment]
Yes, thanks. This seems to be fixed.
