### ISSUE TITLE
Bad AtomicHashMap performance with specific key value

### ISSUE THREAD

**Issue by hypheng** [facebook/folly#978]
I encountered an extremely bad performance using AtomicHashMap. I suspect the hash value of the key is not good. So I write a micro benchmark to reproduce.
```C++
#include <folly/AtomicHashMap.h>
#include <folly/Benchmark.h>
#include <folly/container/Foreach.h>
#include <functional>
#include <unordered_map>
using namespace std;
using namespace folly;
const size_t kMapSize = 100 * 1000;
BENCHMARK(unordered_map_test, n) {
  FOR_EACH_RANGE (i, 0, n) {
    std::unordered_map<size_t, size_t> map(kMapSize);
    FOR_EACH_RANGE (j, 0, kMapSize) {
      map.insert({j + kMapSize, j});
    }
    FOR_EACH_RANGE (j, 0, kMapSize) {
      map.find(j + kMapSize);
    }
  }
}
BENCHMARK(AtomicHashMap_test, n) {
  FOR_EACH_RANGE (i, 0, n) {
    folly::AtomicHashMap<size_t, size_t> map(kMapSize);
    FOR_EACH_RANGE (j, 0, kMapSize) {
      map.insert({j + kMapSize, j});
    }
    FOR_EACH_RANGE (j, 0, kMapSize) {
      map.find(j + kMapSize);
    }
  }
}
int main() {
  runBenchmarks();
}
````

> ==================================================================
hashmap_bench.cpp                               relative  time/iter  iters/s
==================================================================
unordered_map_test                                          41.31ms    24.21
AtomicHashMap_test                                            1.93s  517.03m
==================================================================

**Comment by hypheng** [comment]
Interestingly when kMapSize = 1000 * 1000, the performance is good.
But this is too tricky. It will prevent me from using this tool because the result is unstable.

**Comment by Orvid** [comment]
@nbronson
