### ISSUE TITLE
Fail to use folly future in http similar case

### ISSUE THREAD

**Issue by kapcino** [facebook/folly#982]
I use folly::future within Proxygen and it works well, but failed in one similar case.

I create a new thread to receive specific protocol message using a select base library. When data is received, callback is called and then pull data from db. 

The case is very like HTTPServer. So I use the same Future and then style, but find that the then function never called.

Is there something I missed to called for this case? Something called in Proxygen framework and need manual setup?

Thanks.

```c++
// used for pull data from db
Future<std::string> getData(const std::string& msg);

// receive message, and process message in callback
void callback(const std::string& msg) {
   getData(msg)  // method is called, backend message send, but no receive
       .then([&](std::string& ret) {
           cout << "ret: " << ret;  // <<<<- never called
});

cout << "future done";       // <<<< called
}

// tried this, but also failed
auto pool = std::make_shared<CPUThreadPoolExecutor>(2, std::make_shared<NamedThreadFactory>("cpu"));
setCPUExecutor(pool);

void callback(const std::string& msg) {
   getData(msg).then(getCPUExecutor().get(), [&](std::string& ret) {
   cout << "ret: " << ret;
});

// and also tried to use SemiFuture which seems new in readme
void callback(const std::string& msg) {
   getData(msg).semi().defer([&](std::string& ret) {
   cout << "ret: " << ret;      // <<<<- never called
});

```

**Comment by yfeldblum** [comment]
My first guess is that the future returned by `getData` is never completed with a value - i.e. the associated promise is never fulfilled with a value - and that's why the continuation passed to `.then` is never called.

**Comment by kapcino** [comment]
Thanks for you response @yfeldblum. The problem is that the same function works well in proxy gen’s onEOM callback. 

So I am wondering something done in the proxygen framework is missing.

**Comment by yfeldblum** [comment]
It seems like it would depend on what `getData` does internally.

**Comment by kapcino** [comment]
The `getData` uses hiredis async lib to get data from redis server, and wrap in Future.

Pseudo code like this:

``` c++
// hiredis context from current event base
redisAsyncContext* ctx() {
  auto eb = folly::EventBaseManager::get()->getExistingEventBase();
  auto c = redisAsyncConnect(_host, _port);
  redisLibeventAttach(c, eb->getLibeventBase());
  return c;
}

// redis callback
static void redis_string_callback(redisAsyncContext* c, void* r, void* privdata) {
  auto p = (folly::Promise<string>*)privdata;
  redisReply* reply = static_cast<redisReply*>(r);
  string out = reply->str;
  p->setValue(out);
  }
}

Future<std::string> getData(const std::string& msg) {
auto p = new folly::Promise<string>();
auto f = p->getFuture();
auto c = ctx();
redisAsyncCommandArgv(c, redis_string_callback, p, /*size, etc..*/);
return f;
}

```

**Comment by kapcino** [comment]
The Libevent adapter version use `event_base_dispatch(base)` to drive the loop.
