### ISSUE TITLE
Fail to build folly from source with -fPIC as shared object

### ISSUE THREAD

**Issue by posutsai** [facebook/folly#983]
I try to build folly from source with `-fPIC` flag. Refer to [this commit](https://github.com/facebook/folly/commit/cdb9225b6b1ee4feb3adf8bbe0c75b6ea8463c21). I turn the `BUILD_SHARED_LIBS` option in CMakeLists.txt on. However, linker meets the error and builds unsuccessfully.
Following is the error when I run `make`.
```
[ 99%] Built target folly_base
Scanning dependencies of target folly
[ 99%] Linking CXX shared library libfolly.so
/usr/bin/ld: CMakeFiles/folly_base.dir/folly/Uri.cpp.o: relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
CMakeFiles/folly_base.dir/folly/Uri.cpp.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
CMakeFiles/folly.dir/build.make:508: recipe for target 'libfolly.so' failed
make[2]: *** [libfolly.so] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/folly.dir/all' failed
make[1]: *** [CMakeFiles/folly.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```
Is there still something I haven't done to build shared object?

**Comment by posutsai** [comment]
Should I reinstall any required dependencies with -fPIC flag?
Such as libboost-all-dev, libevent-dev, libdouble-conversion-dev .... etc

**Comment by tabokie** [comment]
@posutsai Mind sharing how you solved this issue (or not)? I encountered a very similiar problem lately. Thanks a lot~

**Comment by futurely** [comment]
`cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON ..`

https://github.com/facebook/folly/pull/833
