### ISSUE TITLE
Error-prone folly::dynamic interface

### ISSUE THREAD

**Issue by kremius** [facebook/folly#985]
`folly::dynamic` has a range-based constructor:
```cpp
template <class Iterator>
explicit dynamic(Iterator first, Iterator last);
```
The constructor basically forwards the range to `std::vector<dynamic>` with help of a vector range constructor
```cpp
template< class InputIt >
vector( InputIt first, InputIt last,
        const Allocator& alloc = Allocator() );
```
Probably it's convenient for certain use cases, but imagine that you need to create a simple json , so something like this will be done in C++ code
```cpp
folly::dynamic data = folly::dynamic::object("key", "value");
```
But imagine that you have missed the `object` function call, and instead you wrote (I actually did it)
```cpp
folly::dynamic data = folly::dynamic("key", "value");
```
Surprisingly, it will compile, but it does something very broken and probably not wanted. Because both `"key"` and  `"value"` are actually pointers compiler interprets this like a call to a range constructor, as if we tried to pass an array of chars to function. Because `char` is convertible to `folly::dynamic` (as `INT64` I suppose) this perfectly works and tries to create an array of ints. Depending on how compiler will place string literals in memory a lot of things can happen, I will give two examples:
1. Array of some length with random numbers from -128 to 127 will be created (if `"key" <= "value"`)
2. `std::bad_alloc` will be thrown when array grows too much (if `"key" > "value"` the range is basically indefinite, so out-of-memory occurs. Segmentation fault can happen too I assume).

Is there any some real use-case where you want to call the range constructor of `folly::dynamic` on a pair of two char pointers? I think, it's possible to `enable_if` the constructor in order to prevent such errors, but maybe I'm missing something.

**Comment by ljluestc** [comment]
```

#include <type_traits>
#include <iterator>

namespace folly {

class dynamic {
public:
    // Other members and constructors...

    // Updated range-based constructor
    template <class Iterator,
              typename std::enable_if<!std::is_pointer<Iterator>::value ||
                                      !std::is_same<typename std::remove_cv<typename std::remove_pointer<Iterator>::type>::type, char>::value,
                                      int>::type = 0>
    explicit dynamic(Iterator first, Iterator last) {
        // Implementation...
    }

    // Other members and methods...
};

} // namespace folly
```
