### ISSUE TITLE
unable to link C++ std::atomic code

### ISSUE THREAD

**Issue by zhangchurong** [facebook/folly#986]
I met a problem when I am building the folly,here is my code 
`cd $dir/folly
mkdir _build && cd _build
cmake ..
make -j $(nproc)
sudo make install
sudo ldconfig # reload the lib paths after freshly installed folly. fbthrift needs it.`
when it runs to cmake ..
error occured
`-- Performing Test FOLLY_CPP_ATOMIC_BUILTIN
-- Performing Test FOLLY_CPP_ATOMIC_BUILTIN - Failed
-- Performing Test FOLLY_CPP_ATOMIC_WITH_LIBATOMIC
-- Performing Test FOLLY_CPP_ATOMIC_WITH_LIBATOMIC - Failed
CMake Error at CMake/folly-deps.cmake:170 (message):
  unable to link C++ std::atomic code: you may need to install GNU libatomic
Call Stack (most recent call first):
  CMakeLists.txt:86 (include)
`
I tried adding the add_definitions(-std=c++11) to the cmakelists, but it did no work 
my CXX compiler identification is GNU 4.8.4

**Comment by yfeldblum** [comment]
> I tried adding the add_definitions(-std=c++11) to the cmakelists

Folly is a C++14 library.

> my CXX compiler identification is GNU 4.8.4

Folly supports GCC versions only >= 5.
