### ISSUE TITLE
Folly/exception. h file not found 

### ISSUE THREAD

**Issue by princekumarwm** [facebook/folly#991]
Package.json file 👍 

{
  "version": "0.0.5",
  "scripts": {
    "start": "react-native start",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "setup": "npm install",
    "clean-build": "rm -rf build && mkdir -pv build/android && mkdir -pv build/ios",
    "build-android": "react-native bundle --platform android --dev false --entry-file index.js --bundle-output build/android/index.android.bundle --assets-dest build/android/",
    "build-ios": "react-native bundle --platform ios --dev false --entry-file index.js --bundle-output build/ios/index.ios.bundle --assets-dest build/ios/",
    "build-app": "npm run clean-build && npm run build-android && npm run build-ios",
    "compress-build": "cd ./build && zip -r9 samsmx_cms_reactnative.zip *"
  },
  "dependencies": {
    "@babel/runtime": "^7.2.0",
    "react": "16.7.0",
    "react-native": "^0.57.8",
    "react-native-gesture-handler": "^1.0.12",
    "react-native-material-ripple": "^0.8.0",
    "react-navigation": "^3.0.9"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0"
  },
  "private": true
}

We have written one module in react and trying to integrate in the existing swift app. 

My podfile: 

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
#  pod 'UbuduSDK',’~> 1.22.0’
#pod 'Polyline'
#pod 'FBNotifications'
#pod 'FacebookCore',’~> 0.3.3’
#pod 'FacebookLogin'
#pod 'FacebookShare'

def change_lines_in_file(file_path, &change)
  print "Fixing #{file_path}...\n"
  
  contents = []
  
  file = File.open(file_path, 'r')
  file.each_line do | line |
    contents << line
  end
  file.close
  
  File.open(file_path, 'w') do |f|
    f.puts(change.call(contents))
  end
end

post_install do |installer|
  # https://github.com/facebook/yoga/issues/711#issuecomment-381098373
  change_lines_in_file('./Pods/Target Support Files/yoga/yoga-umbrella.h') do |lines|
    lines.reject do | line |
      [
      '#import "Utils.h"',
      '#import "YGLayout.h"',
      '#import "YGNode.h"',
      '#import "YGNodePrint.h"',
      '#import "YGStyle.h"',
      '#import "Yoga-internal.h"',
      ].include?(line.strip)
    end
  end
  
  # https://github.com/facebook/yoga/issues/711#issuecomment-374605785
  change_lines_in_file('../samsmx_cms_reactnative/node_modules/react-native/React/Base/Surface/SurfaceHostingView/RCTSurfaceSizeMeasureMode.h') do |lines|
    
    unless lines[27].include?("#ifdef __cplusplus")
      lines.insert(27, "#ifdef __cplusplus")
      lines.insert(34, "#endif")
    end
    lines
  end
  
  # https://github.com/facebook/react-native/issues/13198
  change_lines_in_file('../samsmx_cms_reactnative/node_modules/react-native/React/Base/Surface/SurfaceHostingView/RCTSurfaceSizeMeasureMode.h') do |lines|
    lines.map { |line| line.include?("#import <RCTAnimation/RCTValueAnimatedNode.h>") ? '#import "RCTValueAnimatedNode.h"' : line }
  end
  
  # https://github.com/facebook/react-native/issues/16039
  
  change_lines_in_file('../samsmx_cms_reactnative/node_modules/react-native/React/Base/Surface/SurfaceHostingView/RCTSurfaceSizeMeasureMode.h') do |lines|
    lines.map { |line| line.include?("#import <fishhook/fishhook.h>") ? '#import "fishhook.h"' : line }
  end
end

use_frameworks!

target 'SAMS' do
  pod 'React', :path => '../samsmx_cms_reactnative/node_modules/react-native', :subspecs => [
  'Core',
  'RCTImage',
  'RCTNetwork',
  'RCTText',
  'RCTWebSocket',
  'DevSupport',
  'CxxBridge',
  'RCTLinkingIOS'
  ]
  
  pod 'yoga', :path => '../samsmx_cms_reactnative/node_modules/react-native/ReactCommon/yoga'
#  pod 'native-navigation', :path => '../samsmx_cms_reactnative/node_modules/native-navigation'
  pod 'Folly', :path => '../samsmx_cms_reactnative/node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'GoogleTagManager’,’~> 3.15.0’
  pod 'AFNetworking'
  pod 'AFNetworkActivityLogger', git: 'https://github.com/AFNetworking/AFNetworkActivityLogger.git'
  pod 'iCarousel'
  pod 'UICollectionViewLeftAlignedLayout'
  pod 'CardIO'
  pod 'FMDB'
  pod 'HTMLReader'
  pod 'SWTableViewCell'
  pod 'DHSmartScreenshot'
  pod 'ImageEffects'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'FBNotifications'
  pod 'FacebookCore', :git => 'https://github.com/facebook/facebook-sdk-swift', :branch => 'master'
  pod 'FacebookLogin'
  pod 'RxCocoa'
  pod 'RxSwift'
  pod 'Moya/RxSwift'
  pod 'ModelMapper'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'Firebase/InAppMessagingDisplay'
  pod 'GooglePlaces'
  pod 'Crashlytics'
  
end

target 'SAMSTests' do
  inherit! :search_paths
  # Pods for testing
end

target 'SAMSDev' do
     pod 'React', :path => '../samsmx_cms_reactnative/node_modules/react-native', :subspecs => [
      'Core',
      'RCTImage',
      'RCTNetwork',
      'RCTText',
      'RCTWebSocket',
      'DevSupport',
      'CxxBridge',
      'RCTLinkingIOS'
      ]
      pod 'yoga', :path => '../samsmx_cms_reactnative/node_modules/react-native/ReactCommon/yoga'
#      pod 'native-navigation', :path => '../samsmx_cms_reactnative/node_modules/native-navigation'
      pod 'Folly', :path => '../samsmx_cms_reactnative/node_modules/react-native/third-party-podspecs/Folly.podspec'
      pod 'GoogleTagManager’,’~> 3.15.0’
      pod 'AFNetworking'
      pod 'AFNetworkActivityLogger', git: 'https://github.com/AFNetworking/AFNetworkActivityLogger.git'
      pod 'iCarousel'
      pod 'UICollectionViewLeftAlignedLayout'
      pod 'CardIO'
      pod 'FMDB'
      pod 'HTMLReader'
      pod 'SWTableViewCell'
      pod 'DHSmartScreenshot'
      pod 'ImageEffects'
      pod 'Fabric'
      pod 'Crashlytics'
      pod 'FBNotifications'
      pod 'FacebookCore', :git => 'https://github.com/facebook/facebook-sdk-swift', :branch => 'master'
      pod 'FacebookLogin'
      pod 'RxCocoa'
      pod 'RxSwift'
      pod 'Moya/RxSwift'
      pod 'ModelMapper'
      pod 'Firebase/Core'
      pod 'Firebase/Database'
      pod 'Firebase/Messaging'
      pod 'Firebase/InAppMessagingDisplay'
      pod 'GooglePlaces'
      pod 'Crashlytics'
end

Tried deleting derived data, clearing npm module, nothing works.

**Comment by ljluestc** [comment]
```

platform :ios, '10.0'

target 'YourTargetName' do
  # Pods for YourTargetName
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  # ... other pods ...

  target 'YourTargetTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SAMSDev' do
    pod 'React', :path => '../samsmx_cms_reactnative/node_modules/react-native', :subspecs => [
      'Core',
      # ... other subspecs ...
    ]
    pod 'yoga', :path => '../samsmx_cms_reactnative/node_modules/react-native/ReactCommon/yoga'
    # ... other pods ...
  end
end
```
